Shopify/cli

.changeset/shy-singers-peel.md
packages/app/src/cli/services/deploy.ts

The `Next steps in Shopify Partners` section can show when there are no next steps to take.
A small validation on the next steps post deployment before outputting them.
Run `deploy` on an app with `web` and a function extension.

Check before showing "Next steps in Shopify Partners"

---

.github/workflows/shopify-cli.yml

Fixing a little oopsie on the CI matrix. We should run on all supported OSes, not just Ubuntu.
Chooses the CI OS from the CI matrix.
CI

Choose OS from matrix, don't always use ubuntu

---

packages/app/package.json
packages/cli-hydrogen/package.json
packages/cli-main/package.json

It would be good to have some better content on the npm pages for our public-facing modules (`cli`, `app`, `hydrogen-cli`).
Adds 3 things:
1. `homepage` reference to repo
2. `bugs` reference to GitHub Issues page
3. Copies README from the main project into each package so it appears in all 3 ([symlinks don't work](https://github.com/npm/npm/issues/3310))
Just gotta merge it!

Npm related improvements

---

.github/workflows/shopify-cli.yml

Windows CI is currently failing, even though there are no new breaking changes. Disabling while we investigate and fix.
TEMPORARILY removes Windows from the CI matrix.
CI

Disable Windows CI for now

---

.github/workflows/shopify-cli.yml

We use the fixture app a lot for local testing and debugging, and therefore it's important that it's in a good state so that the CLI can interact with it.
I'm extending our GitHub Actions workflow to build the app through the CLI. If the app breaks with any changes, the job will fail and surface the underlying errors.
CI should pass

Build the fixture app on CI

---

packages/create-hydrogen/src/services/init.ts

This PR fixes various issues parsing Git URLs without a branch or sub directory. A command such as the one below would fail with various errors stemming from the `git` and `pathe` modules. After this PR, this should run successfully. Unfortunately, no tests yet exist for this service (nor do good debug logs), but these are in the works. For now, I'd like to get this fix in.
```
yarn create @shopify/hydrogen --template someUser/someRepo
```
To test these changes, checkout this branch, and run the following and it should succeed.
```
dev create-hydrogen --template calltheguys/hello-3hydrogen --path ../  
```

Fix 3P repo downloads in create-hydrogen

---

.gitattributes
.github/workflows/shopify-cli.yml
packages/app/package.json
packages/app/rollup.config.js
packages/cli-hydrogen/package.json
packages/cli-hydrogen/rollup.config.js
packages/cli-kit/package.json
packages/cli-kit/src/dependency.test.ts
packages/cli-main/package.json
packages/cli-main/rollup.config.js
packages/cli-testing/package.json
packages/create-app/package.json
packages/create-app/src/utils/template/npm.test.ts
packages/create-app/src/utils/template/npm.ts
packages/create-hydrogen/package.json
packages/features/package.json
packages/features/steps/app.steps.ts
packages/features/steps/create-app.steps.ts
packages/features/steps/hydrogen.steps.ts
packages/features/steps/theme.steps.ts
packages/theme/package.json
packages/theme/rollup.config.js

Windows CI is broken, this should fix it.
1 actual issue (small, output-related) was found.
Makes sure we're working with properly formatted paths in all cases, both in code and in tests. Once they're passed through any `path` method this happens automatically, but sometimes we need to `path.normalize` explicitly.
CI

Windows fixes

---

packages/cli-kit/package.json

Move ansi-colors to devDependencies

---

.changeset/perfect-maps-clean.md
packages/cli-kit/assets/auth-error.html
packages/cli-kit/assets/empty-url.html
packages/cli-kit/assets/missing-code.html
packages/cli-kit/assets/missing-state.html
packages/cli-kit/assets/style.css
packages/cli-kit/assets/success.html

Fixes #44 
Balancing the HTML tags involved, as well as re-styling the CSS to reflect the proper layout.
Run the auth flow by using the `shopify app dev` command.

Fix HTML+CSS styling issues

---

packages/features/steps/app.steps.ts
packages/features/steps/create-app.steps.ts

Followup to https://github.com/Shopify/cli/pull/105
Apparently dependency installation during extension creation is also slow on Windows/Mac.
Extends the timeout for these as well. 5 minutes should generally cover it.
CI

Give more time for creating apps and extensions in tests

---

.github/workflows/shopify-cli.yml

Contributor PRs aren't building because it tries to check out their branch from our repo... where it doesn't exist.
Tells GitHub checkout action to use their repo instead.
CI

Checkout branch from forked repo

---

packages/app/src/cli/models/app/extensions.ts
packages/app/src/cli/services/deploy.ts

Fixes [internal issue](https://github.com/Shopify/checkout-web/issues/10858)
Simply adding `configuration_schema` to the attributes being sent to the backend for extensions of type `checkout_ui_extension`. The backend is already ready to parse and validate this attribute.
Follow the instructions presented [here](https://github.com/Shopify/checkout-web/issues/10858#issuecomment-1170045881)

Add configuration_schema attribute for checkout_ui_extension

---

.github/workflows/shopify-cli.yml
packages/features/cucumber.js
packages/features/steps/environment.steps.ts

Faster CI
We always build before running feature tests, which makes sense locally. But in CI, there's no need to build again, as we just built in an earlier step!
CI

Faster acceptance tests in CI

---

.github/workflows/shopify-cli.yml

Save money in CI!
In the rare case of PRs without code changes, we run an hour of CI (actually several times that when you take into account Windows x 2 and Mac x 10).
We add a quick check before running acceptance tests. If nx says there were changes, we'll run as usual. If nx says no changes, we move on to the next step.
[Before](https://github.com/Shopify/cli/actions/runs/2655166972/usage):
[After](https://github.com/Shopify/cli/actions/runs/2656405258/usage):
Note that we could also use a more complex strategy of skipping all CI on PRs without substantive changes. However, that would require adding an extra pre-step which takes a runner, loads the app, installs dependencies, and runs nx to check if anything is affected. This will make CI slower and cost computation time. Since 90%+ of …

Skip acceptance tests if no meaningful pr changes

---

packages/theme/package.json

No reason for the package to be private anymore. Also it's already on npm!
Sets `@shopify/theme` to non-private in `package.json`, allowing us to keep publishing versions.
shipit!

@shopify/theme no longer a private package

---

.changeset/stale-jeans-jam.md
packages/app/src/cli/services/build/extension.ts
packages/app/src/cli/services/dev/extension.ts
packages/app/src/cli/services/scaffold/extension.ts
packages/cli-kit/src/node/ruby.ts
packages/cli-kit/src/system.ts
packages/theme/package.json
packages/theme/src/cli/commands/theme/check.ts
packages/theme/src/cli/commands/theme/delete.ts
packages/theme/src/cli/commands/theme/dev.ts
packages/theme/src/cli/commands/theme/help-old.ts
packages/theme/src/cli/commands/theme/init.ts
packages/theme/src/cli/commands/theme/language-server.ts
packages/theme/src/cli/commands/theme/list.ts
packages/theme/src/cli/commands/theme/open.ts
packages/theme/src/cli/commands/theme/package.ts
packages/theme/src/cli/commands/theme/publish.ts
packages/theme/src/cli/commands/theme/pull.ts
packages/theme/src/cli/commands/theme/push.ts
packages/theme/src/cli/commands/theme/share.ts
packages/theme/src/cli/flags.ts
packages/theme/src/hooks/prerun.ts

Makes theme init work properly
• Update Ruby CLI to latest
• Fix: Await Ruby subprocess
• Add `--path` flag to init for better development flow
• Add `--verbose` flag to see more output from the Node CLI
Run `shopify theme init` locally, optionally with specifying name (positional arg), `--path`, and `-v/--verbose`

Theme improvements (mainly theme init)

---

.changeset/many-birds-fetch.md
packages/theme/src/cli/commands/theme-command.ts
packages/theme/src/cli/commands/theme/help-old.ts
packages/theme/src/cli/commands/theme/pull.ts
packages/theme/src/cli/commands/theme/push.ts

Tidies up loose ends around theme pull/push
* Adds a missing `-t` flag shortcut
* Adds subcommands to `theme help-old` for convenience (this was invaluable in finding what was missing from these commands!)
* Supports multiple `--only` or `--ignore` flags correctly in theme pull/push
`shopify theme push/pull -t whatever`

Theme push and pull

---

packages/cli-main/src/cli/commands/logs.ts

We're supposed to hide the flag for now, as it's not officially supported and is likely to be removed.
Switches the `hidden` property from false to true.
`shopify logs -h`

Correctly hide --last-command flag

---

.changeset/gentle-panthers-count.md
packages/app/src/cli/services/build/extension.ts
packages/app/src/cli/services/dev/select-store.test.ts
packages/app/src/cli/services/dev/select-store.ts

Fixes https://github.com/Shopify/shopify-cli-planning/issues/283
Fixes https://github.com/Shopify/shopify-cli-planning/issues/316
- A couple of minor copy changes
- Change error from Bug to Abort

Copy updates and error cleaning

---

packages/theme/package.json

It's time to share `@shopify/theme` with the world!
Modifies `package.json` to add a few important pieces (homepage, bugs URL, README) and get it published to npm.
Merge and deploy!

Publish @shopify/theme to npm

---

packages/theme/package.json

Copies a few things we specify in all the other `package.json` specifications.
Mainly, specifies supported Node versions and OSes.
N/A

Theme package.json improvements

---

packages/app/src/cli/models/app/extensions.ts
packages/app/src/cli/services/deploy.ts

Fixes [minor internal issue](https://github.com/Shopify/checkout-web/issues/12751)
Renaming the `configuration_schema` attribute optionally found in the `shopify.ui.extension.toml` file of Checkout UI Extensions to `settings`.
Follow instructions in [this internal companion PR](https://github.com/Shopify/shopify/pull/369339).

Rename configurationSchema to settings for Checkout Extensions

---

packages/ui-extensions-cli/src/build.ts
packages/ui-extensions-cli/src/cli.ts
packages/ui-extensions-server-kit/src/ExtensionServerClient/ExtensionServerClient.test.ts

Fixes extensions promises linting errors

Fix promise extensions linting problems

---

packages/ui-extensions-go-cli/create/templates/projects/checkout_ui_extension/shopify.ui.extension.toml.tpl

1:1 port from https://github.com/Shopify/shopify-cli-extensions/pull/381

Add settings example in checkout ui extension template

---

packages/cli-hydrogen/src/cli/services/deploy.ts

Closes https://github.com/Shopify/oxygen-platform/issues/463
This uses the existing functionality from `shopify hydrogen build` to build the specified Hydrogen project.

Add build functionality to `hydrogen shopify deploy`

---

packages/cli-kit/package.json
packages/cli-kit/src/git.test.ts
packages/cli-kit/src/git.ts
yarn.lock

https://github.com/Shopify/cli/pull/281 adds these changes to the correct branch

Adding basic unit test to `shopify hydrogen deploy`

---

.eslintrc.cjs
packages/app/src/cli/services/dev.ts
packages/cli-hydrogen/src/cli/commands/hydrogen/info.test.ts
packages/cli-kit/src/error.ts
packages/cli-kit/src/node/error-handler.ts
packages/cli-kit/src/node/ruby.ts
packages/cli-kit/src/output.ts
packages/ui-extensions-server-kit/src/testing/extensions.ts

Drops noisy `as` casts that we don't need.
Adds an ESLint rule to catch these.
Lint & tsc

Lint: Add rule @typescript-eslint/no-unnecessary-type-assertion

---

packages/cli-kit/src/analytics.ts
packages/cli-kit/src/node/base-command.ts
packages/cli-kit/src/node/error-handler.test.ts
packages/cli-kit/src/node/error-handler.ts

https://github.com/Shopify/shopify-cli-planning/issues/362
Captures metadata from installed plugins; uses the same environment data regular analytics uses
Shared an internal video of how this appears. Can be recreated by triggering an error.

Expand metadata sent to Bugsnag

---

docs/release.md

After merging the extensions binary inside CLI repo, the releasing process has changed so the news steps should be documented
- Updating the release wiki documentation

Updated CLI3 release process documentation

---

packages/cli-kit/package.json

Included a link to the repository on the NPM package (etc.) itself.
Adds `repository` and `bugs` properties to `package.json` of `@shopify/-cli-kit` package.

add repository and bugs to cli-kit package.json file

---

packages/create-app/src/utils/template/npm.ts

Builds on main are broken from merging a version bump until we release it. This shouldn't happen.
We resolve packages locally in acceptance testing so we can create an app using the local packages before they're pushed to npm. This was broken on CI because we introduced a new plugin but didn't update its local source.
CI

Resolve @shopify/plugin-ngrok locally

---

.changeset/shaggy-ties-stare.md
packages/theme/CHANGELOG.md

We want to include a last-minute change before releasing. This PR replaces https://github.com/Shopify/cli/pull/427 to avoid creating a new version.
Fixes the changelog

Fix changelog

---

packages/app/package.json
packages/cli-hydrogen/package.json
packages/cli-main/package.json
packages/create-app/package.json
packages/create-hydrogen/package.json
packages/theme/package.json
packages/ui-extensions-cli/package.json

In addition to https://github.com/Shopify/cli/pull/424.
Included a link to the repository on the NPM package (etc.) itself.
Adds repository and bugs properties to package.json of all packages.

add repository and bugs to published packages

---

.changeset/dry-yaks-train.md

Adds missing changeset for #449

Add changeset

---

.changeset/five-timers-tap.md
.changeset/manual-log-refactor.md
packages/app/src/cli/services/deploy/upload.test.ts

Fixes https://github.com/Shopify/shopify-cli-planning/issues/353
- All the test should pass

Fixed upload unit tests

---

.changeset/wet-apricots-sip.md
fixtures/app/extensions/web-pixel/shopify.ui.extension.toml
packages/app/src/cli/services/deploy.ts
packages/app/src/cli/validators/extensions/ui.ts
packages/app/templates/ui-extensions/projects/web_pixel/shopify.ui.extension.toml.liquid

https://github.com/Shopify/ce-customer-behaviour/issues/1461

[web-pixel-extension] renamed property configuration to settings

---

bin/spin

We use the script at `bin/spin` as a way to automatically set some environmental variables for internal use.
Per the script, this variables are only set if they don't have a value already, which doesn't make sense for the `SHOPIFY_SERVICE_ENV` variable, we always want it to be `spin` if you are executing this script.
There is a flow where running `dev up` will set your variable to `production` and the script won't update it anymore.
This was originally reported by @kim76 , thanks!
- Force `SHOPIFY_SERVICE_ENV=spin` on `bin/spin` script
- Remove unused variables from the script to avoid confusion (they don't do anything)
- execute `dev up`
- `bin/spin yarn shopify app dev --path fixtures/app` should connect to spin

Improve bin/spin script

---

packages/app/src/cli/constants.ts

We updated a lot of things in the retail packages, so we want the newly generated projects to use the most up to date dependencies.

Updated retail to 0.12.0

---

.vscode/launch.json
packages/app/src/cli/constants.test.ts
packages/app/src/cli/constants.ts
packages/app/src/cli/services/generate/extension.ts

Part of https://github.com/Shopify/script-service/issues/4796
- Introduces `delivery_customization` function extension
This PR will be merged after a `delivery_customization` sample function is released in order to generate an extension. 
The `delivery_customization` will appear when scaffolding an extension.
```sh
dev shopify app scaffold extension --path 
```

[Functions] Add delivery_customizations function extension

---

fixtures/app/package.json
package.json
packages/app/src/cli/constants.ts
packages/ui-extensions-go-cli/support/merge_config.rb
packages/ui-extensions-go-cli/testdata/extension.config.integration.yml
packages/ui-extensions-go-cli/testdata/extension.config.yml

We need to update the cli template for scaffolded extensions to use version `0.19.0`. This package was just released today.
Bumps up the version number.
Scaffold a new app with a Checkout UI extension and validate the version `0.19.0` is present in the package.json of the app.
N/A

updated checkout-ui-extensions to latest 0.19.0

---

.changeset/config.json

Dependabot changelogs just have a list of commits rather than a more descriptive list of changes.
Using the same configuration as other public repos at Shopify to source from GitHub.
Dependabot version bumps
N/A

Source changelogs from GitHub

---

docs/release.md

Wrong link in the release documentation
Fixes the link
Clicking the link

Fix release doc link

---

packages/app/src/cli/services/dev/extension/bundler.test.ts
packages/app/src/cli/services/dev/extension/bundler.ts

Adds tests around recent file watch & bundler additions for development extension server.
Tests that payload store extensions are updated for bundler and locale watcher when `setupBundlerAndFileWatcher` function is called.
This PR is just tests -- simply ensure they pass.

Bundler tests

---

packages/app/src/cli/constants.ts
packages/app/templates/ui-extensions/projects/pos_ui/src/index.liquid

This PR updates the version of the retail-ui-extensions library to be used in the template, to an up to date version that fixes a major issue with the React renderer. Additionally, it also updates the template and removes certain features that are not yet ready.
- updates retail dependency versions
- updates template
Nothing is live yet.

Updated POS liquid template and dependency version

---

packages/features/snapshots/commands.txt

We added a new snapshot test and a new command at the same time
`yarn test` passes

Add new command to snapshot test

---

fixtures/app/extensions/customer-accounts-ui/locales/en.default.json
fixtures/app/extensions/customer-accounts-ui/locales/fr.json
fixtures/app/extensions/customer-accounts-ui/shopify.ui.extension.toml
fixtures/app/extensions/customer-accounts-ui/src/index.jsx
fixtures/app/package.json
packages/app/src/cli/models/app/extensions.ts
packages/app/src/cli/services/deploy.ts
packages/app/src/cli/services/dev/extension/payload.ts
packages/app/src/cli/services/dev/extension/payload/models.ts
packages/app/src/cli/utilities/extensions/configuration.test.ts
packages/app/src/cli/utilities/extensions/configuration.ts
packages/ui-extensions-go-cli/api/api_test.go
packages/ui-extensions-go-cli/core/core.go
packages/ui-extensions-server-kit/src/testing/extensions.ts
packages/ui-extensions-server-kit/src/types.ts
yarn.lock

Serves `localization` for `customer-accounts-ui` extensions. We are currently working on adding advanced i18n support to our `customer-accounts-ui` extensions. To do so, we need a way to easily test our extensions while those are being developed and the most comfortable way is to deliver the localization information inside of our dev console.
This is part of https://github.com/Shopify/core-issues/issues/43741 and https://github.com/Shopify/core-issues/issues/43321
✅ Adds  a new `customer-accounts-ui` fixture (which includes an `locales` folder)
✅ Serves the `localization` to the dev-console when the CLI is started with `yarn shopify app dev`
✅ Adds a missing entry to the `packages/ui-extensions-go-cli/core/core.go` file, in order to correctly serve `categories`
1. Clone this repo with …

[Feature] Link localization to customer-accounts-extensions

---

.changeset/lazy-cobras-thank.md
packages/cli-kit/src/api/graphql/functions/app_function_set.ts

There are some unused fields in the `FunctionSet` mutation, some of which are deprecated. 
Related issue: https://github.com/Shopify/script-service/issues/4519
This PR removes the unused fields.
Deploy an app with a function.
N/A

Remove unused fields from FunctionSet mutation

---

README.md

Today:
After fix:
Fix broken link

Fix: readme broken link corrected for 'getting started'

---

packages/app/templates/ui-extensions/projects/checkout_ui/shopify.ui.extension.toml.liquid

Mirrors the configuration example in https://shopify.dev/apps/checkout/custom-banners/add-custom-banner to be consistent with the formatting of this setting.

Add parent settings field in default configuration for checkout extension

---

.vscode/extensions.json

Nx [has](https://nx.dev/core-features/integrate-with-editors) an extension for VSCode that provides a visual interface to interact with the project, for example to run actions.
I'm including it in the list of recommended extensions. VSCode will recommend contributors of the project to install it in their environment.

Recommend the Nx VSCode extension

---

package.json
packages/app/package.json
packages/app/src/cli/services/environment.test.ts
packages/app/src/cli/services/environment/id-manual-matching.test.ts
packages/app/src/cli/services/environment/id-manual-matching.ts
packages/app/src/cli/services/environment/id-matching.test.ts
packages/app/src/cli/services/environment/id-matching.ts
packages/app/src/cli/services/environment/identifiers-extensions.test.ts
packages/app/src/cli/services/environment/identifiers-extensions.ts
packages/app/src/cli/services/environment/identifiers-functions.test.ts
packages/app/src/cli/services/environment/identifiers-functions.ts
packages/app/src/cli/services/environment/identifiers.test.ts
packages/app/src/cli/services/environment/identifiers.ts
packages/app/src/cli/services/environment/prompts.ts
packages/cli-kit/src/api/graphql/all_app_extension_registrations.ts
yarn.lock

⚠️  This can't be merged until [this change](https://github.com/Shopify/partners/pull/42962) in Partners is merged and deployed ⚠️ 
This is the second PR of the ID-Matching refactor, adding support to ID-match functions along with extensions.
Fixes https://github.com/Shopify/shopify-cli-planning/issues/419
- Add id-matching logic specific for functions
- merge the ids from extensions and functions
- Rename some interfaces to better understand what they represent
- Add many more tests
- Create a project with different types of functions, deploy, delete IDs, deploy again, delete only some IDs, create new functions with duplicated types, deploy again, etc... just play with creating and deploying functions and removing the IDs from the `.env` file.
How do we know this change was effective? …

Functions ID-matching

---

.changeset/nine-beers-begin.md
.changeset/popular-monkeys-heal.md
fixtures/app/extensions/product-subscription/src/index.js
packages/app/src/cli/services/build/extension.ts
packages/app/src/cli/services/dev/extension.test.ts
packages/app/src/cli/services/dev/extension.ts
packages/app/src/cli/services/dev/extension/payload.ts
packages/app/src/cli/services/dev/extension/payload/models.ts
packages/cli-kit/src/constants.ts
packages/cli-kit/src/environment/local.ts
packages/ui-extensions-go-cli/core/core.go

After testing the new Node logic for building and deving extensions and fixing some bugs that emerged (), we are in a position to make it the default in the next release and give users the options to opt-back into the Go logic if they encounter issues.
I'm making the new Node logic the default and giving users the option to use the Go workflow by passing the environment variable `SHOPIFY_CLI_USE_GO_BINARY=1`. If no major issues arise, we'll remove the Go logic after two weeks.
You should be able to `build` and `dev` the fixture app.
This is a significant change so it's important that we feel confident across the board before merging it. If you are part of a team that maintains an extension type, please, tophat the new workflow and confirm that everything works as expected. Please, make …

Build and dev extensions by default using the new Node logic

---

fixtures/app/extensions/product-discount/input.graphql
packages/app/src/cli/services/environment/identifiers.test.ts
packages/app/src/cli/services/environment/identifiers.ts
packages/cli-kit/src/constants.ts
packages/cli-kit/src/environment/local.ts

We recently introduced automatic function matching to the CLI, this fixed a bunch of issues that partners had when working on teams and deploying functions. (or deploying from CI)
Just as a cautionary measure, we are putting this new feature behind an environment flag until functions team is confident partners are ready for this.
- Add new environment flag: `SHOPIFY_CLI_FUNCTION_MATCHING`
- Only execute the new function matching if `SHOPIFY_CLI_FUNCTION_MATCHING` is truthy
Try to deploy a function with and without `SHOPIFY_CLI_FUNCTION_MATCHING`
If you don't use the flag and deploy a function without an ID in the `.env` file, it will be duplicated.

Functions matching behind a flag

---

bin/package.js
packaging/src/shopify-cli.rb.liquid
packaging/src/shopify-cli@3.rb.liquid

Homebrew formula generation was broken, both the process and the output.
* Don't overwrite the original executable!
* Pass all variables through to the liquid partial, so [this](https://github.com/Shopify/homebrew-shopify/pull/436/files) doesn't happen again
* When opening a PR from CI, include the `shopify-cli` file too.
Some can be tested with `yarn package`. The rest will wait for the next deploy.

Homebrew formula fixes

---

packages/app/src/cli/services/generate/extension.test.ts
packages/app/src/cli/services/generate/extension.ts
packages/app/templates/ui-extensions/projects/checkout_ui/src/index.liquid
packages/app/templates/ui-extensions/projects/customer_accounts_ui/src/index.liquid
packages/app/templates/ui-extensions/projects/pos_ui/src/index.liquid
packages/app/templates/ui-extensions/projects/post_purchase_ui/src/index.liquid
packages/app/templates/ui-extensions/projects/subscription_ui/src/index.liquid

Until now all templates had only 2 versions: react or not-react, so our code was only able to handle those 2 cases.
With the changes in this PR all templates will receive the full flavor string (including javascript or typescript), allowing for more complex templates.
- Make all templates check the flavor with `contains` instead of `equals`
- Pass the full flavor to the liquid engine.
- I've already tried with all extensions but: Try to generate extensions with different flavors, react flavors should generate react extensions.

Use full flavor string in templates

---

packages/app/package.json
packages/app/src/cli/models/extensions/extension-points.ts
packages/app/src/cli/models/extensions/extensions.ts
packages/app/src/cli/models/extensions/functions.ts
packages/app/src/cli/models/extensions/schemas.ts
packages/cli-kit/src/api/graphql/extension_specifications.ts

As part of the extension refactor project, this PR introduces some new types/interfaces that will be used to replace the existing ones.
Fixes https://github.com/Shopify/shopify-cli-planning/issues/437
- Add a new folder where all the new types and classes will live
- Add interfaces for `ExtensionSpec`, `ExtensionPointSpec` and `FunctionSpec`
- Add classes `ExtensionInstance` and `FunctionInstance`
- Define all the basic schemas for extensions and functions (specific types can extend these)
- Export all these new files so that a plugin can access all definitions.
Most of the code has been taken from the proposed prototype, with some improvements/cleanups
Nothing to test yet, that will come in a future PR along with automated tests. …

Extensions refactor: add new types/classes

---

packages/app/src/cli/models/extensions/extensions.ts
packages/app/src/cli/models/extensions/functions.ts
packages/ui-extensions-dev-console/package.json
packages/ui-extensions-dev-console/project.json
packages/ui-extensions-dev-console/src/ActionSet/Action/Action.tsx
packages/ui-extensions-dev-console/src/ActionSet/ActionSet.test.tsx
packages/ui-extensions-dev-console/src/ActionSet/ActionSet.tsx
packages/ui-extensions-dev-console/src/App.tsx
packages/ui-extensions-dev-console/src/CheckBox/Checkbox.tsx
packages/ui-extensions-dev-console/src/DevConsole.tsx
packages/ui-extensions-dev-console/src/ExtensionRow/ExtensionRow.tsx
packages/ui-extensions-dev-console/src/QRCodeModal/QRCodeModal.test.tsx
packages/ui-extensions-dev-console/src/QRCodeModal/QRCodeModal.tsx
packages/ui-extensions-dev-console/src/hooks/useDevConsoleInternal.tsx
packages/ui-extensions-dev-console/src/hooks/usePolarisToast.tsx
packages/ui-extensions-dev-console/src/hooks/useToast.tsx
packages/ui-extensions-dev-console/src/main.tsx
packages/ui-extensions-dev-console/src/tests/DevConsole.test.tsx
packages/ui-extensions-dev-console/tests/MockAppProvider.tsx
packages/ui-extensions-dev-console/tests/MockI18nProvider.tsx
packages/ui-extensions-dev-console/tests/css-transform.js
packages/ui-extensions-dev-console/tests/mock-i18n.ts
packages/ui-extensions-dev-console/tests/mount.tsx
packages/ui-extensions-server-kit/project.json
packages/ui-extensions-server-kit/src/context/ExtensionServerProvider.test.tsx
packages/ui-extensions-server-kit/src/context/ExtensionServerProvider.tsx
packages/ui-extensions-server-kit/src/testing/MockExtensionServerProvider.tsx
packages/ui-extensions-test-utils/project.json
packages/ui-extensions-test-utils/src/render.tsx
packages/ui-extensions-test-utils/src/renderHook.tsx

Fixes Shopify/shopify-cli-planning#451
Ensures that `lint` commands in the `ui-extension-*` projects also check `TSX` files.
Run `lint`!

Linting for extension packages

---

.changeset/config.json
.changeset/silly-waves-sniff.md
packages/cli-kit/src/log.test.ts
packages/cli-kit/src/log.ts
packages/cli-kit/src/public/common/object.test.ts
packages/cli-kit/src/public/common/object.ts
packages/cli-kit/src/public/node/base-command.ts
packages/cli-kit/src/public/node/hooks/init.ts
packages/cli-main/package.json
packages/theme/package.json

Fixes https://github.com/Shopify/shopify-cli-planning/issues/447
- Removed the `init` hook that initiates the `logger` and moved that initiation to the `BaseCommand`. This way that process is run only once a command is executed instead of running it for each plugin that includes the `cli-kit`
- Added some logic to apply the log file truncation process only for the last 30MB (fixed) to truncate the file to a maximum of 5MB (fixed). Truncating huge files (5GB) takes now few seconds instead of several minutes
- Applied union strategy for array fields when using the method `deep merging` with two objects
- Old strategy: ```deepMerge({foo: ['bar']}, {foo: ['bar', 'none']}) ``` => ```{foo: ['bar', 'bar', 'none']}```
- New strategy:  ```deepMerge({foo: ['bar']}, {foo: ['bar', 'none']}) ``` => …

Polish log truncation

---

docs/cli/testing-strategy.md

- Fixed an outdated snippet in the testing strategy doc

Fixed snipset code in the testing strategy documentation

---

packages/app/src/cli/commands/app/generate/extension.ts
packages/app/src/cli/constants.ts
packages/app/src/cli/models/app/extensions.ts
packages/app/src/cli/models/extensions/extension-specifications/checkout_ui_extension.ts
packages/app/src/cli/models/extensions/extension-specifications/customer_accounts_ui_extension.ts
packages/app/src/cli/models/extensions/extension-specifications/pos_ui_extension.ts
packages/app/src/cli/models/extensions/extension-specifications/post_purchase_extension.ts
packages/app/src/cli/models/extensions/extension-specifications/product_subscription.ts
packages/app/src/cli/models/extensions/extension-specifications/theme_app_extension.ts
packages/app/src/cli/models/extensions/extension-specifications/web_pixel_extension.ts
packages/app/src/cli/models/extensions/extensions.ts
packages/app/src/cli/models/extensions/functions.ts
packages/app/src/cli/models/extensions/schemas.ts
packages/app/src/cli/services/deploy.ts
packages/app/src/cli/services/dev/extension/server/middlewares.ts
packages/app/src/cli/services/dev/output.ts
packages/app/src/cli/services/generate/extension.ts
packages/app/src/cli/services/info.ts
packages/app/src/cli/utilities/extensions/configuration.ts
packages/cli-kit/src/api/graphql/extension_specifications.ts

As part of the extension refactor project, this step is the last one before finally replacing everything with the new system.
Contributes to https://github.com/Shopify/shopify-cli-planning/issues/439
- Update `ExtensionInstance` to implement `UIExtension` and `ThemeExtension`
- Update `FunctionInstance` to implement `FunctionExtension`
- Update `UIExtension`, `ThemeExtension` and `FunctionExtension` to be generic
- Update all extension types enums to accept a generic string
- Update all methods that switched over an extension type to add a default option (because it can be any string now)
- Update the `ExtensionSpec` and `FunctionSpec` with some missing properties.
- Remove the new loader functions because we won't need them
⚠️ This PR doesn't replace any extension behaviour, everything …

Extensions refactor: Make new instances conform to old interfaces

---

packaging/src/shopify-cli.rb.liquid

Fixes broken Homebrew formulae 
* Use the correct reference to Homebrew Node
* Update the executable paths for the @3 formula which was broken
I've verified that the changes generate a formula that I've put into my local Tap and used to install the CLI successfully.

More Homebrew fixes

---

packages/cli-kit/src/public/node/ruby.ts

Update CLI2 dependency to latest version

Update CLI2 to version 2.32.0

---

packages/app/src/cli/models/extensions/extension-specifications/checkout_ui_extension.ts

Fixes https://github.com/Shopify/checkout-web/issues/16264
With https://github.com/Shopify/cli/pull/727 typings were introduced for `checkout_ui_extensions`. However the `settings` definition was incorrect. The type `string` is declared but we need an object for the upload to core: https://github.com/Shopify/shopify/blob/a16e132ccb97e6f90004e75732e18d7b461f7621/components/apps/app/services/apps/models/ui_extension/operations/merchant_settings_update.rb#L45-L48
Inexplicably, deploying from the app's extension folder somehow works around this, but this is a weird piece of tribal knowledge, and a bad developer experience in the wild, especially as our public docs [provide an example of the object](https://shopify.dev/api/checkout-extensions/checkout/configuration).
Typically, this will …

Correct the type definition for checkout_ui_extension:settings

---

yarn.lock

Yarn install touches the lockfile at the moment. Pushing an update to remove the noise.

Lockfile out of sync

---

packages/app/src/cli/constants.ts

https://github.com/Shopify/pos-next-react-native/issues/19313
The Extensibility team is looking to expose this command in order for select partners to develop POS UI extensions for early access.
This PR exposes the extension template `POS UI` to the public. This is safe to do so since CLI has pre-checks for any gating when they run the `generate` command and proceed with a extension template. Ex. A shop must have the correct beta flag enabled to develop / deploy a extension.

Remove POS UI from shopify private

---

.github/workflows/reviewers-reminder.yml

The @Shopify/checkout-ui-extensions-api-stewardship team should be automatically added as a reviewer when the CLI template files for Checkout UI extensions change.
Appends a new codeowners rule.

codeowners for checkout ui ext template

---

bin/save-coverage-file.js
packages/app/package.json
packages/app/project.json

Fixes https://github.com/Shopify/internal-cli-foundations/issues/481
Runs test:coverage for the app package

[CI] Include app in coverage stats

---

.changeset/ninety-dingos-taste.md
packages/app/src/cli/commands/app/generate/extension.ts
packages/app/src/cli/services/generate/extension.test.ts
packages/app/src/cli/services/generate/extension.ts

We introduced a bug that breaks generating function templates

Fix functions template type

---

fixtures/app/package.json
packages/app/src/cli/models/extensions/ui-specifications/checkout_ui_extension.ts
packages/app/src/cli/models/extensions/ui-specifications/ui_extension.ts
pnpm-lock.yaml

Update Checkout UI Extensions

---

.changeset/calm-moons-shout.md

Backfills a changeset I forgot to commit to https://github.com/Shopify/cli/pull/950

Add missing changeset for session refresh fix

---

packages/cli-kit/src/api/admin.ts
packaging/src/shopify-cli.rb.liquid

We are showing outdated information in a couple of places
Updates two unrelated copies:
- Sunset date for CLI 2
- Unauthorized error message for dev stores
Just changing text, so I think it's enough to check they are right

Update some copies

---

packages/app/src/cli/utilities/extensions/fetch-extension-specifications.test.ts
packages/app/src/cli/utilities/extensions/fetch-extension-specifications.ts

Post purchase extension has an invalid value for `surface` in the Specifications API
Fixes #0000 
Hardcode the surface value for post purchase extensions until it is fixed in the API

Fix post purchase extension surface

---

.changeset/shaggy-humans-tell.md

Add changeset for extension plugins

---

.changeset/slimy-starfishes-fly.md
packages/app/src/cli/models/app/app.ts
packages/app/src/cli/services/dev/urls.test.ts
packages/app/src/cli/services/dev/urls.ts

Sometimes an app needs to specify multiple custom auth callback paths, but the [`auth_callback_path` config value in `shopify.web.toml`](https://shopify.dev/apps/tools/cli/structure#shopify-web-toml) only accepts a single value.
Enables the code to handle `auth_callback_path` specified as a string or an array. The change is backwards compatible (still accepts a string).
In the [fixture app `shopify.web.toml`](https://github.com/Shopify/cli/blob/main/fixtures/app/web/shopify.web.toml), test setting `auth_callback_path` to a string and an array, and verify that the app builds.
```
type="backend"
auth_callback_path = "/custom/path1"
[commands]
dev = "npm run dev"
build = "pnpm run build"
```
```
type="backend"
auth_callback_path = ["/custom/path1", "/custom/path2"]
[commands]
dev = "npm run …
```

[Feature] Accept array for auth_callback_path config for multiple custom paths

---

package.json
packages/app/src/cli/utilities/app/http-reverse-proxy.ts
packages/cli-hydrogen/package.json
packages/cli-kit/package.json
packages/cli-kit/src/file.ts
pnpm-lock.yaml

We are improving the launch time of the CLI
I'm updating some dependencies to use the ESM version of them and changing some imports to be dynamic.
Tests should pass and you should be able to `build` and `dev` the fixture app.

Perf ws http proxy fs extra

---

packages/cli-kit/src/path.test.ts
packages/cli-kit/src/path.ts

We introduced a fix for this a few weeks ago, but there was a bug in the fix 🙃 
Fixes https://github.com/Shopify/cli/issues/1037
Ensure that we use `{dot: true}` int fastGlob
create a new app with pnpm and try to generate an extension

Fix loading specifications

---

.changeset/silver-schools-visit.md
packages/cli-kit/src/public/node/ruby.ts

Bumping `CLI2` that includes the new version of `theme-check` that supports section groups

Bump CLI2 to 2.34.0

---

packages/app/templates/ui-extensions/projects/ui_extension/src/AdminCheckoutEditorRenderSettings.liquid

Fix the template for the Admin extension point for the new `ui_extension` spec
Fix some errors in the template

Fix the the AdminCheckoutEditorRenderSettings extension point template

---

packages/app/src/cli/models/extensions/ui-specifications/pos_ui_extension.ts

A new retail `ui-extensions` was published, so updating the default version here. 
New version. 
Scaffold a new extension using the CLI. 

Default version bump

---

packages/cli-kit/src/private/node/ui/components/SelectInput.test.tsx

Fixes a test broken in a [recent PR](https://github.com/Shopify/cli/pull/1157).

Fix broken test

---

packages/app/templates/ui-extensions/projects/pos_ui/src/index.liquid

The template for POS UI Extensions was outdated. 
The template is now up to date and is better formatted. 
Scaffold a new POS UI Extension. 

Updated the default POS UI extension template

---

fixtures/app/extensions/customer-accounts-ui/shopify.ui.extension.toml
packages/app/templates/ui-extensions/projects/customer_accounts_ui/shopify.ui.extension.toml.liquid

Remove categories from customer accounts scaffolds

---

pnpm-lock.yaml

Fix Release workflow on main as it was referencing the private registry.

Remove references to npm registry

---

.github/dependabot.yml
.github/workflows/changelog-reminder.yml
packages/cli-kit/assets/cli-ruby/test/shopify-cli/commands/populate/product_test.rb

- Skipped detected `cli-ruby`
- Disabled `dependabot` for `cli-ruby` dependencies
-  Fixed `changeset` reminder

Skipped flaky test and disable dependabot for ruby dependencies

---

.changeset/grumpy-planes-accept.md
packages/cli-kit/src/public/node/ruby.test.ts
packages/cli-kit/src/public/node/ruby.ts

Fixes https://github.com/Shopify/cli/issues/1303
We were running the CLI on a different Ruby than the bundle install. This fixes the problem.
Needs a global install via Homebrew to test, I think.

Use correct bundler for Homebrew ruby version

---

.changeset/angry-terms-hunt.md
packages/app/src/cli/services/dev.ts

Fix dev console link not appearing

---

.changeset/eleven-balloons-tease.md
packages/app/package.json
pnpm-lock.yaml

The version of Javy that we use is broken on windows
Updates to latest version of javy

Update to latest javy

---

.changeset/silver-horses-think.md
packages/app/src/cli/constants.ts
packages/app/src/cli/models/extensions/function-specifications/cart_checkout_validation.ts

We are releasing the cart & checkout validation function.
Publishing the cart & checkout validation function template.
- generate an extension
```
pnpm shopify app generate extension --path ../your-app
```
- select "Function - Cart and Checkout Validation"
- give a name to your extension
- choose Rust
- `ls` into the extension folder to confirm the files have been generated

[Feature] Add cart & checkout validation function template

---

packages/cli-kit/assets/cli-ruby/lib/shopify_cli/messages/messages.rb
packages/cli-kit/assets/cli-ruby/test/fixtures/shopify_schema.json
packages/cli-kit/assets/cli-ruby/vendor/deps/smart_properties/lib/smart_properties/property.rb

Noticed there are small typos in the word 'occurred'
Correcting small typos

corrected typos 'occured' -> 'ocurred'

---

package.json
packages/cli-kit/assets/cli-ruby/Gemfile.lock

Sometimes you just want to run unit tests
Adds a `test:unit` and a `test:features` aliases

Add test aliases

---

package.json
packages/cli-kit/package.json
pnpm-lock.yaml

https://github.com/Shopify/cli/issues/1240
Updates liquidjs to 10.5.0
- Create a new app
- Generate an extension
- The liquid files should have been templated correctly

Update liquidjs dependency

---

packages/cli-kit/src/public/node/context/local.test.ts
packages/cli-kit/src/public/node/context/local.ts
packages/cli-kit/src/public/node/context/spin.ts

Reverts Shopify/cli#1272
It has been causing some regressions and this is the easiest way to fix things for now.

Revert "[Feature] Set firstPartyDev to true when env is Spin"

---

fixtures/app/package.json
pnpm-lock.yaml

Make fixtures app deployable

---

fixtures/app/package.json
packages/create-app/src/utils/template/npm.ts
pnpm-lock.yaml

Restore the old retail-ui dependency in fixtures app that was installed via the internal registry

Revert make fixtures app deployable

---

packages/cli-kit/src/public/node/ruby.ts

Fixes #1425 
`npm` packages up files as non-executable, and we're invoking the file with `bundle exec` which is resulting in an error because it's not an executable file.
Changes `bundle exec /path/to/shopify` to `bundle exec ruby /path/to/shopify` so we're invoking `ruby` not the file itself.
Making sure, of course, to invoke the correct ruby!
Before:
After:
Probably need to deploy to nightly to confirm the fix works.

Fix: Run `ruby` with shopify bin file as an argument

---

.changeset/clean-guests-poke.md
packages/cli-kit/src/public/node/ruby.ts

Duplicates https://github.com/Shopify/cli/pull/1429

Fix ruby cli executable

---

packages/app/package.json
pnpm-lock.yaml

Remove unused shopify-cli-extensions package

---

.changeset/clean-guests-poke.md
.github/workflows/shopify-cli.yml

Added a changeset for the ruby bin fix, and a small fix for stable branch workflows

Cherry-pick fixes to main

---

bin/package.js
packaging/3/src/shopify-cli.rb.liquid
packaging/3/src/shopify-cli@3.rb.liquid
packaging/nightly/src/shopify-cli-nightly.rb.liquid
packaging/pre/src/shopify-cli-pre.rb.liquid

Lets us test `nightly` and `pre` releases via Homebrew.
Adds new formulae for `shopify-cli-nightly` and `shopify-cli-pre`, and modifies the flow to accommodate them. Also auto-merges the created PRs so we only need to inspect the primary formula manually.
You can change cli-kit version to an existing nightly release, and verify the formula looks correct.
Once this is merged, we'll verify on the next nightly release that the formula actually works.

Pre and nightly brew formulae

---

.changeset/large-geese-drum.md

I forgot to add a changeset for this PR: https://github.com/Shopify/cli/pull/1433/files

Add changeset for ruby fix

---

shipit.nightly.yml

Followup to https://github.com/Shopify/cli/pull/1453. @alvaro-shopify pointed out I missed actually calling the `package` script from the nightly shipit stack.
Runs the package script (just as we do in `shipit.production.yml`).
Merge and deploy nightly!

Add package step to nightly so we'll update Homebrew

---

bin/package.js

Packaging was broken (see [here](https://shipit.shopify.io/shopify/cli/nightly/deploys/2037960) and [here](https://github.com/Shopify/homebrew-shopify/pull/507)).
References the right variable
Merge and deploy nightly!

Use correct variable

---

package.json
pnpm-lock.yaml

Release is broken because the eslint-plugin package doesn't exist on npm (which makes sense)
Force the project to use the local package as dependency

Link eslint-plugin-cli dependency to local package

---

packages/app/src/cli/models/extensions/ui-specifications/pos_ui_extension.ts

POS UI Extensions 0.43.0 is now available. 
Updated the default version. 
Scaffold a new POS UI Extension. 
No steps necessary. 

Bumped the POS UI Extensions version

---

.eslintrc.cjs
packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.test.tsx
packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.tsx
packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx
packages/cli-kit/src/private/node/ui/components/FullScreen.tsx
packages/cli-kit/src/private/node/ui/components/SelectInput.tsx
packages/cli-kit/src/private/node/ui/components/SelectPrompt.tsx
packages/cli-kit/src/private/node/ui/components/TextAnimation.tsx
packages/cli-kit/src/private/node/ui/components/TextPrompt.tsx

We had the react hooks eslint package installed but weren't using it so this PR adds it.

Add 'plugin:react-hooks/recommended' to eslint

---

packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.tsx
packages/cli-kit/src/private/node/ui/components/SelectInput.tsx
packages/cli-kit/src/private/node/ui/components/SelectPrompt.tsx
packages/cli-kit/src/public/node/output.ts
packages/cli-kit/src/public/node/ui.tsx

`pnpm refresh-documentation` was broken

Fix errors while running refresh-documentation script

---

.changeset/brown-carrots-cry.md
packages/cli-kit/src/private/node/api.ts
packages/cli-kit/src/private/node/api/graphql.ts

- When an API request returns an error the CLI is not generating debug log messages with neither the time execution nor the headers. This last point is quite important in case you want to trace the error request using this [tutorial](https://videobin.shopify.io/v/Nxz5l2) as we are not able to get the value of `x-request-id`
- The handling of the errors is done inside the method that executes the request, so the debug logging is run in one place
Run the `dev` command using a wrong `api-key` with the `--verbose` flag
`yarn shopify app dev --api-key 1234 --verbose``
you should see that the correct responses and the error response should show the execution time and the desired headers

Add log information when API requests return an error

---

packages/cli-kit/src/private/node/ui/components/Tasks.test.tsx

This will fix some tests flakyness.

Increase sleep for some Tasks tests

---

.changeset/soft-spiders-reflect.md
packages/app/src/cli/api/graphql/template_specifications.ts
packages/app/src/cli/constants.ts
packages/app/src/cli/services/generate/fetch-template-specifications.ts

The `templateSpecifications` partners API operation [has added a new `version` parameter ](https://github.com/Shopify/partners/pull/46472)to return different specifications content depending on its value 
IMPORTANT: This PR cannot be merged until the one from partners is shipped
- Add a constant to define manually the remote specification version supported by the CLI
- Send the version constant value as a parameter in the `fetchTemplateSpecifications` request 
- Create a partners spin instance from the branch `support_version_for_template_specifications`
```sh
spin up partners -c partners.branch=support_version_for_template_specifications
```
- Wait until the instance is up and running and run the CLI command 
```
SHOPIFY_SERVICE_ENV=spin SPIN_INSTANCE=$(spin show -o name) p shopify app …
```

Add remote template specification version param to the request

---

docs/cli/cross-os-compatibility.md

Windows and Ubuntu VM were a bit wrong
Fix them

Keep improving cross os instructions

---

packages/app/src/cli/models/extensions/ui-specifications/tax_calculation.ts
packages/app/templates/ui-extensions/projects/tax_calculation/shopify.ui.extension.toml.liquid

Relies on https://github.com/Shopify/shopify/pull/416992
Fixes #0000 

Add metafields to tax_calculation config

---

packages/app/src/cli/models/extensions/ui-specifications/pos_ui_extension.ts
packages/app/templates/ui-extensions/projects/pos_ui_extension/shopify.ui.extension.toml.liquid
packages/app/templates/ui-extensions/projects/pos_ui_extension/src/index.liquid

resolves https://github.com/Shopify/pos-next-react-native/issues/22707
New version of UI Extensions was released. 
Updates the default version and the liquid files for the new extension point names. 
Scaffold a new extension. 

Version bump and liquid update

---

package.json
packages/cli-kit/package.json
packages/cli/package.json
packages/plugin-cloudflare/package.json
packages/ui-extensions-dev-console/package.json
pnpm-lock.yaml

Close our backlog of version bumps. Limited to in-theory simple patch upgrades.
Merging dependabot branches into a holding branch.

Merge patch updates from dependabot

---

README.md

We just want to check if merging this PR will automatically create another one for the main branch.

Test for stable PRs

---

.changeset/wild-oranges-shop.md
packages/theme/oclif.manifest.json
packages/theme/src/cli/commands/theme/open.ts

Apply PR created by @jeffreyguenther https://github.com/Shopify/cli/pull/1035 (already reviewed/approved)

Fix description for `shopify theme open` flags

---

packages/app/src/cli/models/extensions/ui-specifications/pos_ui_extension.ts
packages/app/templates/ui-extensions/projects/pos_ui_extension/src/index.liquid

Fixes https://github.com/Shopify/pos-next-react-native/issues/23540

Updated POS UI Extensions template

---

.changeset/old-sheep-attack.md
packages/app/src/cli/services/deploy.test.ts
packages/app/src/cli/services/deploy.ts
packages/app/src/cli/services/deploy/bundle.ts

When you `deploy` an app that only contains functions this error is returned
- Run the extensions build logic in the app contains functions
- Run the deploy command with an app that contains only functions

Fix deploy app that contais only functions as extensions

---

.changeset/big-goats-share.md
packages/app/src/cli/services/generate/extension.ts
packages/cli-kit/src/public/node/node-package-manager.test.ts
packages/cli-kit/src/public/node/node-package-manager.ts

Install pos_ui_extension node dependencies as exact versions

---

.changeset/big-goats-share.md
packages/app/src/cli/services/generate/extension.ts
packages/cli-kit/src/public/node/node-package-manager.test.ts
packages/cli-kit/src/public/node/node-package-manager.ts

Force POS extension dependencies to be installed as exact versions instead of with a caret `^`

Install pos_ui_extension node dependencies as exact versions (main)

---

packages/app/oclif.manifest.json
packages/app/src/cli/api/graphql/create_deployment.ts
packages/app/src/cli/commands/app/deploy.ts
packages/app/src/cli/services/deploy.test.ts
packages/app/src/cli/services/deploy.ts
packages/app/src/cli/services/deploy/upload.test.ts
packages/app/src/cli/services/deploy/upload.ts

Removing label prompt and label flag from deploy command.

Remove label prompt

---

.npmrc

In a recent PR I addeed `vitest` and `vite` to pnpm's hoist pattern.
This indicates to pnpm which dependencies matching a pattern should be hoisted to the root modules directory.
I added vitest and vite so that the vscode extension would work BUT pnpm by default already hoists `*eslint*` and `*prettier*`, [[doc ref](https://pnpm.io/npmrc#public-hoist-pattern)]. So, by adding a custom pattern we were overriding the default without knowing it.
Add eslint and prettier to pnpm hoist pattern.

Add eslint and prettier to pnpm hoist pattern

---

packages/ui-extensions-dev-console/src/sections/Extensions/components/PostPurchaseRow/components/PostPurchaseModal/PostPurchaseModal.test.tsx

Fixes https://github.com/Shopify/cli/pull/1959 unit tests

Fix Update post purchase chrome extension url

---

.changeset/pre.json

Exit prerelease for version 3.46

---

packages/cli/package.json
pnpm-lock.yaml

Currently `demo generate-file` fails because `zod-to-json-schema` isn't a dep of`@shopify/cli`.
Upgrades from `devDependencies` to `dependencies`.
FYI it's a [94k npm package with 0 dependencies](https://www.npmjs.com/package/zod-to-json-schema).
I'd rather not have included it, but it doesn't seem like a huge amount of weight to add. For context, just installing `@shopify/cli` + deps via npm is 115M.
The real test will be on nightly, making sure `generate-demo` works as expected.

Include zod-to-json-schema in deps not devDeps for `demo generate-file`

---

.changeset/green-seals-sniff.md
packages/app/src/cli/services/function/build.test.ts
packages/app/src/cli/services/function/build.ts
pnpm-lock.yaml

We had some reports of the CLI silently crashing when running Javy, this PR should fix that.
Fixes #0000 
Run javy with stdout/stderr as `inherit`
- Having an app with a function, run deploy inside the vscode debugger terminal.

Patch javy process

---

packages/theme/src/cli/services/update/check.test.ts
packages/theme/src/cli/services/update/schemas/update_extension_schema_v1.ts

Fixes part of https://github.com/Shopify/shopify/issues/428094
This PR just introduces changes generated by the `cd packages/theme && p schema:generate` command. Also, this PR updates unit tests accordingly.
N/A
None.

Update `update_extension.json` schema following the latest design changes

---

.changeset/dull-houses-taste.md
packages/app/src/cli/services/dev.ts
packages/app/src/cli/services/dev/output.ts
packages/app/src/cli/utilities/app/http-reverse-proxy.ts
packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.test.tsx
packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx

Hotfix for https://github.com/Shopify/cli/pull/1985

Fix render dev

---

packages/app/src/cli/services/context/prompts.ts

Closes https://github.com/Shopify/app-deploys/issues/510
This PR updates the prompt that's being shown as part of the `app deploy` command to highlight the to-be-removed extensions. The title was renamed from `Missing locally` to `Removed` and the body was updated from `Extensions missing locally will be removed for users when you publish this deployment` to `Will be removed for users when this version is released.`
1. Create an app
2. Generate an extension
3. Enable the deployments beta flag
4. Run `app deploy` to release an app version
5. Delete the local extension code
6. Run the `app deploy` again
The prompt for deletion should match the mocks.
When releasing:
When creating an app version:
When beta flag is not enabled:

Update deploy prompt based on DX changes

---

packages/app/src/cli/models/extensions/specification.ts

Type-check is broken on main due to a missing return type in `build(...`
Add return type to `build`

Add missing return type to fix type-check

---

packages/cli-kit/src/public/node/api/business-platform.ts
packages/cli-kit/src/public/node/context/fqdn.test.ts
packages/cli-kit/src/public/node/context/fqdn.ts

As part of the effort to support the business-platform API, we need to provide a way to execute queries for it.
- Add a new helper ` businessPlatformRequest` to run queries in the business-platform API
- Add a new helper to obtain the API fqdn depending on the environment.

Add businessPlatformRequest and FQDN

---

.github/workflows/combine-prs.yml

Dependabot opens 50+ PRs each month with updates. Is really cumbersome to go through all of them, or manually create a PR to include all updates. And our PR list is just flooded with dependabot stuff.
Add a workflow to automatically create a branch with all dependabot updates (this workflow can only be triggered manually)

Add github workflow to combine dependabot PRs

---

packages/app/src/cli/services/deploy.ts

Revert "Add warning message to deploy"

---

.changeset/fair-rockets-flow.md
packages/app/src/cli/services/extensions/bundle.test.ts
packages/app/src/cli/services/extensions/bundle.ts

Replicated from https://github.com/Shopify/cli/pull/2160 to be included as a fix

Skip .DS_Store files in theme bundle creation

---

packages/cli-kit/src/private/node/session/exchange.ts

I noticed we have 1 identity request running serially that could be parallel, shaving a few hundred ms on authentication.
Runs the extra request in parallel. Non-blocking IO FTW.
Theme commands still work after logging out and logging in again.

Parallelize admin token request

---

.changeset/thin-islands-matter.md

We accidentally merged a major change to changesets
Change major to minor

Revert major changeset

---

packages/app/src/cli/services/deploy/mode.test.ts
packages/app/src/cli/services/deploy/mode.ts

Fixes https://github.com/Shopify/app-deploys/issues/578
- Move upcoming changes banner to be displayed only in case of `legacy` mode and `unified_app_deployment_opt_in` enabled
- Run `deploy` command with `unified_app_deployment` and `unified_app_deployment_opt_in` DISABLED. Upcoming changes banner should NOT be displayed
- Run `deploy` command with `unified_app_deployment` DISABLED and `unified_app_deployment_opt_in` ENABLED. Upcoming changes banner should be displayed
- Run `deploy` command with `unified_app_deployment` ENABLED and `unified_app_deployment_opt_in` DISABLED/ENABLED. Upcoming changes banner should NOT be displayed

Display upcoming changes banner in deploy only if opt in enabled

---

packages/app/src/cli/services/deploy.ts

✅ Got approval to get this released as part of 3.47.
Fixes: https://github.com/Shopify/app-deploys/issues/544
We want to notify users that changes are coming to deployments.

Deployment announcement banner

---

packages/cli-kit/src/private/node/ui/components/GitDiff.tsx

Escape @ in commments

---

.changeset/early-needles-cheer.md

Filling in the changeset for https://github.com/Shopify/cli/pull/2083 and the subsequent fixes in https://github.com/Shopify/cli/pull/2207 and https://github.com/Shopify/cli/pull/2216

Backfill changeset for unify-webs

---

docs/cli-kit/ui-kit/readme.md

Fixes https://github.com/Shopify/internal-cli-foundations/issues/677
The token system needed some more high level documentation explaining how to use it and why it exists.
I've added a section to the UI kit docs to do that.

Add documentation for the token system

---

.changeset/short-yaks-smile.md
packages/app/oclif.manifest.json
packages/app/src/cli/commands/app/dev.ts
packages/cli-kit/src/public/node/error.ts
packages/cli-kit/src/public/node/plugins/tunnel.ts
packages/plugin-cloudflare/src/tunnel.test.ts
packages/plugin-cloudflare/src/tunnel.ts

Cherrypicking commits from https://github.com/Shopify/cli/pull/2263 to create a patch release on 3.47 branch.

Improve Cloudflare errors (on stable/3.47)

---

packages/app/templates/ui-extensions/projects/pos_ui_extension/package.json.liquid

New POS UI extensions version was released. 
Update the base version. 
Scaffold an extension. 

CLI POS UI extensions default version update

---

.changeset/bright-seas-travel.md
packages/app/src/cli/services/deploy.ts

With all the recent changes we accidentally removed a custom output message for deployed functions.
This PR restores it.
- Show a different message after legacy deploy for function and non-function extensions.
- deploy a function with the legacy system, you should get a message that the function is live

Show the correct deploy summary when not using simplified deployments (stable)

---

packages/app/src/cli/services/context.test.ts
packages/app/src/cli/services/context.ts

This ensures that the `Dev store` is correctly populated in the reused values banner.

Ensure cachedAppInfo has correct dev store info

---

.changeset/pre.json

Exit from `pre` version one last time.

Exit from `pre`

---

packages/app/src/cli/api/graphql/clear_requested_scopes.ts
packages/app/src/cli/services/app/config/push.test.ts
packages/app/src/cli/services/app/config/push.ts

Adds clear mutation for scopes for the serverless install functionality.

add clear mutation

---

packages/app/src/cli/models/extensions/extension-instance.ts
packages/app/src/cli/services/dev/update-extension.ts

- In https://github.com/Shopify/cli/pull/2284, I forgot to update the context in `update-extension`. 
- This PR extracts the handle and removes it from the config altogether so the backend doesn't need to care about it being in the config hash.
- This PR extracts the handle and removes it from the config altogether so the backend doesn't need to care about it being in the config hash.
- Generate a new extension with `handle` in the TOML config.
- Deploy the extension normally. It should be successful

Extract handle from deployConfig

---

packages/app/src/cli/services/app/config/use.test.ts
packages/app/src/cli/services/context.test.ts

Fix bad merge in tests

---

packages/app/src/cli/services/app/config/link.ts
packages/app/src/cli/services/context.test.ts
packages/app/src/cli/services/context.ts

Revert "Reset behavior"

---

.changeset/sour-bulldogs-smile.md
packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb
packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/dev_server/proxy_test.rb

Backport https://github.com/Shopify/cli/pull/2285

[3.47] Fix image_url on data attributes

---

packages/cli-kit/assets/cli-ruby/test/shopify-cli/core/monorail_test.rb

Removes low value flaky test.
Delete test_log_event_handles_errors
CI does that

Removed flaky test test_log_event_handles_errors

---

packages/ui-extensions-dev-console/index.html

Incorrect favicon path causes a false 404 in user app code
Correct the path used
Open the dev console, confirm no errors in the network tab

Use the correct favicon in the dev console

---

packages/cli-kit/src/private/node/ui/components/TextPrompt.test.tsx
packages/cli-kit/src/private/node/ui/components/TextPrompt.tsx

Fixes https://github.com/Shopify/internal-cli-foundations/issues/664

Make TextPrompt preview footer wrap

---

packages/app/src/cli/prompts/dev.test.ts
packages/app/src/cli/prompts/dev.ts
packages/app/src/cli/services/app/config/link.ts
packages/app/src/cli/services/context.test.ts
packages/app/src/cli/services/context.ts
packages/app/src/cli/services/dev/select-app.test.ts
packages/app/src/cli/services/dev/select-app.ts
packages/app/src/cli/utilities/app/config/getTomls.ts

Show linked tomls when they are linked.

Show linked tomls

---

packages/app/src/cli/models/extensions/extension-instance.ts

With recent changes we broke the tax_calc extension again, this should fix it.
Eventually this special case won't be necessary!

Fix tax calculation build path

---

packages/app/oclif.manifest.json
packages/app/src/cli/commands/app/deploy.ts
packages/app/src/cli/commands/app/import-flow-legacy-extensions.ts
packages/app/src/cli/commands/app/release.ts
packages/app/src/cli/services/app/config/link.ts
packages/app/src/cli/services/context.test.ts
packages/app/src/cli/services/context.ts
packages/app/src/cli/services/deploy.test.ts
packages/app/src/cli/services/deploy.ts
packages/app/src/cli/services/deploy/mode.test.ts
packages/app/src/cli/services/import-flow-legacy-extensions.test.ts
packages/app/src/cli/services/import-flow-legacy-extensions.ts
packages/app/src/cli/services/release.test.ts
packages/app/src/cli/services/release.ts

Fixes https://github.com/Shopify/internal-cli-foundations/issues/687
- Links a configuration from `deploy` when it's not found
- Create a new app

Implement --reset for deploy

---

packages/app/src/cli/commands/app/build.ts
packages/app/src/cli/commands/app/deploy.ts
packages/app/src/cli/commands/app/dev.ts
packages/app/src/cli/commands/app/function/schema.ts
packages/app/src/cli/commands/app/generate/extension.ts
packages/app/src/cli/commands/app/release.ts
packages/app/src/cli/commands/app/update-url.ts
packages/app/src/cli/commands/app/versions/list.ts
packages/app/src/cli/metadata.ts
packages/app/src/cli/prompts/deprecation-warnings.ts
packages/app/src/cli/prompts/release.ts
packages/app/src/cli/services/context/prompts.ts
packages/app/src/cli/services/deploy/mode.ts
packages/app/src/cli/services/dev.ts
packages/cli-kit/src/public/node/metadata.ts
packages/cli-kit/src/public/node/monorail.ts

Adds analytics to simplified deployment features
A selection of additional metadata points - largely around prompt usage in deployment.
Run `deploy` and `release`, confirm that nothing is broken.

Analytics for simplified deployments

---

packages/app/src/cli/prompts/dev.test.ts
packages/app/src/cli/prompts/dev.ts

Update content to match new link feature

Update link prompt content

---

packages/app/src/cli/services/app/config/link.test.ts
packages/app/src/cli/services/app/config/link.ts
packages/app/src/cli/services/app/write-app-configuration-file.test.ts
packages/app/src/cli/services/app/write-app-configuration-file.ts
packages/app/src/cli/services/context.test.ts
packages/app/src/cli/services/context.ts
packages/app/src/cli/services/dev/urls.ts
packages/cli-kit/src/public/node/toml.ts

Adds lightweight support for comments when generating a new config file. 
run `shopify app config link` and confirm there are comments

insert comments after initial write

---

.changeset/healthy-eagles-fold.md
packages/app/src/cli/services/dev.ts
packages/app/src/cli/services/extensions/common.ts
packages/cli-kit/assets/cli-ruby/lib/project_types/extension/messages/messages.rb
packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/extension/dev_server.rb

Fixes https://github.com/Shopify/app-deploys/issues/618
- Display a message that warns the user to enable `dev preview` mode using the dashboard in case the app includes one or more `draftable` extension or a `theme app extension`
- In case app opts into `unified deployment` theme app extension instructions don't include the point regarding to enable `dev preview`
- Create a new app with a function extension and a theme app extension
- Run the `dev` command.
- Enable `app_unified_deployment` beta flag (either run `deploy` or from `partners internal dashboard`) and run `dev` again

Display dev preview warn message running dev command

---

.changeset/friendly-tigers-burn.md
packages/app/src/cli/api/graphql/app_deploy.ts
packages/app/src/cli/api/graphql/app_release.ts
packages/app/src/cli/api/graphql/app_version_by_tag.ts
packages/app/src/cli/api/graphql/app_versions_diff.ts
packages/app/src/cli/api/graphql/generate_signed_upload_url.ts
packages/app/src/cli/api/graphql/get_versions_list.ts
packages/app/src/cli/services/deploy.ts
packages/app/src/cli/services/deploy/upload.test.ts
packages/app/src/cli/services/deploy/upload.ts
packages/app/src/cli/services/release.test.ts
packages/app/src/cli/services/release.ts
packages/app/src/cli/services/release/version-diff.test.ts
packages/app/src/cli/services/release/version-diff.ts
packages/app/src/cli/services/versions-list.test.ts
packages/app/src/cli/services/versions-list.ts

Fixes https://github.com/Shopify/app-deploys/issues/535
Depends on [these changes](https://github.com/Shopify/partners/pull/48970) in Partners
This PR replaces "deployment" terminology with "app version" terminology. There are no changes to the CLI's behavior.
Should "deployment" be renamed to "app version" in [`examples.ts`](https://github.com/Shopify/cli/blob/6cea462885bd660ea20d97972f1005b0e98d241e/packages/cli-kit/bin/documentation/examples.ts#L177-L183) and [`ui.tsx`](https://github.com/Shopify/cli/blob/966b3cb127351162e65c042a993ddde7671d03b5/packages/cli-kit/src/public/node/ui.tsx#L140-L146)? Are there any other instances of deployment terminology I've missed?
**If https://github.com/Shopify/partners/pull/48970 hasn't merged yet, run the CLI against a spin instance with the …

Replace "deployment" terminology with "app version" terminology

---

packages/app/src/cli/models/extensions/specification.ts
packages/app/src/cli/models/extensions/specifications/checkout_post_purchase.ts
packages/app/src/cli/models/extensions/specifications/checkout_ui_extension.ts
packages/app/src/cli/models/extensions/specifications/customer_accounts_ui_extension.ts
packages/app/src/cli/models/extensions/specifications/function.ts
packages/app/src/cli/models/extensions/specifications/pos_ui_extension.ts
packages/app/src/cli/models/extensions/specifications/product_subscription.ts
packages/app/src/cli/models/extensions/specifications/tax_calculation.ts
packages/app/src/cli/models/extensions/specifications/theme.ts
packages/app/src/cli/models/extensions/specifications/ui_extension.ts
packages/app/src/cli/models/extensions/specifications/web_pixel_extension.ts
packages/app/src/cli/services/dev/extension/payload.test.ts
packages/app/src/cli/services/dev/extension/server/utilities.test.ts

We had it because historically we weren't fetching the remote specs, but now all surfaces values come from the remote spec so we shouldn't override this locally.
Fixes #0000 
Remove surface from local specifications

Remove surface from local specs

---

packages/app/src/cli/api/graphql/get_config.ts
packages/app/src/cli/prompts/config.test.ts
packages/app/src/cli/prompts/config.ts
packages/app/src/cli/services/app/config/push.test.ts
packages/app/src/cli/services/app/config/push.ts
packages/app/src/cli/services/app/write-app-configuration-file.ts
packages/app/src/cli/services/context.ts

1. Fixes issue where push shows a diff because the fields are sorted differently [screenshot](https://github.com/Shopify/cli/assets/446046/5824f18b-0a16-47dd-aad4-e5c117f9a2b1)
2. Adds current app/config file banner to `push`
3. Adds current config file name to `deploy`'s banner
- For issue number 1, I'm using `rewriteConfiguration` to make sure both sides of the comparison have fields in the same order
- For issue number 2 and 3, I extracted code from `showReusedDevValues` into `renderCurrentlyUsedConfigInfo` that can be used everywhere we need to show the currently used config banner.
1. link a config
2. change webhook api version and scopes
3. push it
You should see the correct diff and which file you're pushing
You should also see the current file when trying to `deploy`
How do we …

Fix push diff order and show app info on push

---

.changeset/thick-humans-film.md
packages/app/src/cli/services/dev/extension/utilities.test.ts
packages/app/src/cli/services/dev/extension/utilities.ts

Fixes https://shopify.slack.com/archives/C04DP0S28UR/p1689975995133039

Rename order-details to order-status for customer account extensions

---

packages/create-app/src/prompts/init.test.ts
packages/create-app/src/prompts/init.ts

Slight reword for init prompts
Run create-app

Tweak wording on init prompts

---

packages/app/src/cli/models/extensions/extension-instance.ts
packages/app/src/cli/models/extensions/specification.ts
packages/app/src/cli/models/extensions/specifications/checkout_post_purchase.ts
packages/app/src/cli/models/extensions/specifications/customer_accounts_ui_extension.ts
packages/app/src/cli/models/extensions/specifications/pos_ui_extension.ts
packages/app/src/cli/models/extensions/specifications/theme.ts
packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
packages/app/src/cli/models/extensions/specifications/ui_extension.ts
packages/app/src/cli/models/extensions/specifications/web_pixel_extension.ts
packages/app/src/cli/services/dev.ts
packages/app/src/cli/services/dev/output.test.ts
packages/app/src/cli/services/dev/output.ts

We used to show a previewMesage before the logs for each extension, but that's no longer the case and we had some dead code there.
- Remove unused code related to previewMessage.
- The feature is still there in case we want to use it in the future.

Remove previewMessage

---

packages/app/src/cli/models/extensions/specifications/function.ts

Bug: when deploy function extension of type `order-routing-location-rule`, getting the following error:
```
╭─ error ──────────────────────────────────────────────────────────────────────╮
│                                                                              │
│  Invalid extension type “order_routing_location_rule” in                     │
│  “extensions/closest-location-to-buyer/shopify.function.extension.toml”      │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
```
`order_routing_location_rule` is missing from the list of `additionalIdentifiers`.
Order Routing Extension is being public to selected partners for this summer edition early access. So we need to make …

Add order_routing_location_rule as a valid function extension identifier

---

RELEASE_NOTES/3.48.md

Adding the public facing changeset for 3.48.0.

Add 3.48 release notes

---

packages/cli-kit/package.json
packages/eslint-plugin-cli/package.json
packages/ui-extensions-dev-console/package.json
packages/ui-extensions-server-kit/package.json
packages/ui-extensions-test-utils/package.json
pnpm-lock.yaml

I noticed we were using multiple versions of typescript
Use the same version.

Use Typescript 5.0.4 everywhere

---

.github/workflows/checks.yml
packages/app/src/cli/models/app/app.test.ts
packages/app/src/cli/models/app/app.ts
packages/app/src/cli/services/dev/extension/payload.ts

With workspaces when looking for a dependency we need to start searching in the package folder first and then up to the root. For the ui-server payload we were looking directly in the app root.
Fixes https://github.com/Shopify/cli/issues/2227
- Clean up some unused code
- Start looking for extensions dependencies in the extension folder
- Apparently tests were completely broken for this feature, so this PR also fixes them

Look for extensions dependencies starting from the extension folder

---

.changeset/breezy-months-hope.md
.changeset/hungry-berries-rest.md
.changeset/light-fireants-share.md
.changeset/tasty-walls-mate.md
packages/cli-kit/src/public/node/node-package-manager.ts
packages/cli/src/cli/services/upgrade.test.ts
packages/cli/src/cli/services/upgrade.ts

Duplicate of [this PR](https://github.com/Shopify/cli/pull/2596) but for the stable branch
Also includes the changes from https://github.com/Shopify/cli/pull/2540 by @matteodepalo 

[3.48] Upgrade ensures that both CLI and APP are on latest

---

.changeset/five-pianos-mate.md
.changeset/light-fireants-share.md
.changeset/strong-beers-tickle.md
.changeset/tasty-walls-mate.md
packages/cli-kit/src/private/node/api.ts
packages/cli-kit/src/private/node/api/graphql.ts
packages/cli-kit/src/private/node/api/headers.ts
packages/cli-kit/src/private/node/api/urls.test.ts
packages/cli-kit/src/private/node/api/urls.ts
packages/cli-kit/src/public/node/http.ts
packages/create-app/src/commands/init.test.ts
packages/create-app/src/commands/init.ts
packages/create-app/src/prompts/init.ts

Backport these PRs to stable 3.48:
- https://github.com/Shopify/cli/pull/2549
- https://github.com/Shopify/cli/pull/2540
- https://github.com/Shopify/cli/pull/2535

Backport more fixes

---

packages/app/src/cli/api/graphql/get_urls.ts
packages/app/src/cli/services/dev/urls.ts

The graphql query for fetching URLs was wrong 🤦 
Fix it

Fix get urls graphql query

---

packages/app/src/cli/models/app/loader.test.ts

Skip config link test on windows

---

packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.test.tsx
packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx
packages/cli-kit/src/public/node/ui.tsx

Clearer separation of footer and logs in `dev`
Changes ConcurrentOutput styling
Run `dev` 

Add border and padding for dev footer

---

packages/app/src/cli/constants.ts
packages/app/src/cli/models/app/loader.ts
packages/app/src/cli/models/extensions/extension-instance.ts
packages/app/src/cli/models/extensions/specification.ts
packages/app/src/cli/models/extensions/specifications/checkout_post_purchase.ts
packages/app/src/cli/models/extensions/specifications/checkout_ui_extension.ts
packages/app/src/cli/models/extensions/specifications/customer_accounts_ui_extension.ts
packages/app/src/cli/models/extensions/specifications/flow_action.ts
packages/app/src/cli/models/extensions/specifications/flow_trigger.ts
packages/app/src/cli/models/extensions/specifications/function.ts
packages/app/src/cli/models/extensions/specifications/pos_ui_extension.ts
packages/app/src/cli/models/extensions/specifications/product_subscription.ts
packages/app/src/cli/models/extensions/specifications/tax_calculation.ts
packages/app/src/cli/models/extensions/specifications/theme.ts
packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
packages/app/src/cli/models/extensions/specifications/ui_extension.ts
packages/app/src/cli/models/extensions/specifications/web_pixel_extension.ts

With all the recent changes in extensions specs there are some duplicated configs that we don't need.
- Remove `graphQLType` from specs where it's identical to the identifier (default value)
- Remove `partnersWebIdentifier` from specs where it's identical to the identifier (default value)
- Remove `singleEntryPath` as a boolean config in the spec and treat it as a feature. Only extensions that support it, include it.
- Remove `shouldFetchCartUrl` in favor of the feature `cart_url`
- Remove unused hardcoded constants for extensions
- Remove `supportedFlavors` from extension specs since we moved that to the templates
Extensions continue working

Some clean up on local extensions specifications

---

dev.yml
package.json
packages/app/package.json
packages/cli-kit/package.json
packages/cli/package.json
packages/create-app/package.json
packages/plugin-cloudflare/package.json
packages/plugin-did-you-mean/package.json
packages/theme/package.json
pnpm-lock.yaml

Upgrade oclif core

---

.changeset/rotten-mirrors-march.md
packages/app/src/cli/api/graphql/development_preview.ts
packages/app/src/cli/api/graphql/find_app.ts
packages/app/src/cli/commands/app/dev.ts
packages/app/src/cli/models/organization.ts
packages/app/src/cli/services/context.ts
packages/app/src/cli/services/dev.ts
packages/app/src/cli/services/dev/extension.ts
packages/app/src/cli/services/dev/output.ts
packages/app/src/cli/services/extensions/common.ts
packages/app/src/cli/utilities/app/http-reverse-proxy.test.ts
packages/app/src/cli/utilities/app/http-reverse-proxy.ts
packages/cli-kit/src/private/node/tree-kill.ts
packages/cli-kit/src/private/node/ui.tsx
packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.test.tsx
packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx
packages/cli-kit/src/public/node/base-command.ts
packages/cli-kit/src/public/node/hooks/postrun.ts
packages/cli-kit/src/public/node/system.ts
packages/cli-kit/src/public/node/tree-kill.ts
packages/cli-kit/src/public/node/ui.tsx

Hotfix for https://github.com/Shopify/cli/pull/2595
Adds the ability to enable/disable developer preview on `shopify app dev`

Added back GQL for enabling developer preview, updated renderDev footer

---

.github/workflows/shopify-cli.yml

This reverts commit 3389dfe9ae6b38844a08e4cc952f857330a31e5f.
This change is being introduced otherwise the checkout fails when a PR is opened from a fork.
This reverts commit 3389dfe9ae6b38844a08e4cc952f857330a31e5f.
N/A.
None.
N/A
N/A

Revert "Remove actions/checkout branch and repo"

---

packages/app/src/cli/services/app/config/link.test.ts
packages/app/src/cli/services/app/config/link.ts

We were not validating remote scopes properly, an array is always `true` inside an `if` even if empty.
Fixes https://github.com/Shopify/app-management-internal/issues/20
Check if the array exists and if it's empty

Properly validate if there are remote scopes or not

---

.changeset/silver-colts-rule.md
packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb
packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/dev_server/proxy_test.rb

[3.48] Fix the issue with the loading of custom fonts

---

packages/app/src/cli/services/app/config/link.test.ts
packages/app/src/cli/services/app/config/link.ts

Revert "Properly validate if there are remote scopes or not"

---

.changeset/blue-years-cross.md
packages/cli-kit/src/private/node/api/graphql.ts

Fixes https://github.com/Shopify/develop-app-management/issues/167
Saying the request failed with status 200 isn't helpful, it's just confusing!
Only reports non-200 errors. We also took the opportunity to fix up some spacing issues.
Before:
After:
1. Introduce a deliberate breakage into GraphQL, e.g. an incorrectly named field (I changed a field name in `packages/app/src/cli/api/graphql/find_app.ts`)
2. Run a command that uses that query
3. Observe the resulting error

Don't report 200 errors

---

packages/app/src/cli/models/app/loader.ts

Fixes https://github.com/Shopify/develop-app-management/issues/41
Breaks down analytics logging, and uses it in the lightweight app config loading flow too.
Run `app config push --verbose` and note that data about config as code opt-in is shown.

Ensure that `loadAppConfiguration` logs data too

---

packages/app/src/cli/models/extensions/specifications/flow_template.ts

Related extension template PR: [#46](https://github.com/Shopify/extensions-templates/pull/46)
Related shopify PR: https://github.com/Shopify/shopify/pull/445833
The original structure of the extension template for flow templates that allowed for multiple flow templates per extension revealed unnecessary additional complexities in the implementation. The complexities show on the Flow side where we need to parse the flow templates and reconcile changes within an extension and make corresponding updates Flow side.
Restricting a to a single Flow template per extension makes deletion and future reviewing new and updated templates much easier.
I've also added a workflow_path field to give the extension author flexibility to name the .flow file since it's easy to forget which workflow file is …

Update Flow template spec and schema to be 1 template per ext

---

.changeset/perfect-points-agree.md
packages/app/src/cli/services/dev/ui/components/Dev.test.tsx
packages/app/src/cli/services/dev/ui/components/Dev.tsx
packages/cli-kit/src/private/node/ui/hooks/use-abort-signal.ts

Same as https://github.com/Shopify/cli/pull/2800 but for stable.

Dev component exit with exception stable

---

.changeset/nasty-numbers-vanish.md
packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb
packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/dev_server/proxy_test.rb

Backport https://github.com/Shopify/cli/pull/2711.

[3.49] Fix local font URLs

---

.changeset/famous-squids-camp.md
packages/app/package.json
packages/app/src/cli/constants.ts
packages/app/src/cli/services/dev.ts
packages/app/src/cli/services/dev/graphiql/server.ts
packages/app/src/cli/services/dev/graphiql/template.ts
packages/app/src/cli/services/dev/processes/graphiql.ts
packages/app/src/cli/services/dev/processes/setup-dev-processes.test.ts
packages/app/src/cli/services/dev/processes/setup-dev-processes.ts
packages/app/src/cli/services/dev/ui.test.tsx
packages/app/src/cli/services/dev/ui.tsx
packages/app/src/cli/services/dev/ui/components/Dev.test.tsx
packages/app/src/cli/services/dev/ui/components/Dev.tsx
packages/app/src/cli/services/dev/urls.test.ts
packages/app/src/cli/services/dev/urls.ts
packages/app/src/cli/services/dev2.ts
pnpm-lock.yaml

Made this during hackdays, let's ship it so everyone can benefit!
https://videobin.shopify.io/v/vN9gjR
Adds a `g` hotkey to `dev` to open GraphiQL in your browser, using the same credentials as your app.
Run `dev` in old/new modes, and press `g`
We should probably document this, right?

GraphiQL from dev

---

.changeset/modern-ears-draw.md
packages/cli-kit/src/public/node/node-package-manager.ts

Cherrypick changes from https://github.com/Shopify/cli/pull/2819

[stable] Fix upgrade with yarn and workspaces

---

bin/create-test-app.js

Testing with npm will help us catch bugs faster.

Always use npm in test app script

---

configurations/tsconfig.json
package.json
packages/cli-kit/package.json
packages/eslint-plugin-cli/package.json
packages/ui-extensions-dev-console/package.json
packages/ui-extensions-server-kit/package.json
packages/ui-extensions-test-utils/package.json
pnpm-lock.yaml

Upgrade TypeScript to 5.2.2

---

.changeset/friendly-nails-listen.md
packages/app/src/cli/commands/app/deploy.ts
packages/app/src/cli/commands/app/dev.ts

Replicates https://github.com/Shopify/cli/pull/2849 for stable

Read SHOPIFY_API_KEY as a way to specify --api-key

---

.changeset/light-pianos-perform.md
packages/plugin-cloudflare/src/tunnel.ts

Add this [fix](https://github.com/Shopify/cli/pull/2890) to the `stable` branch

Support new cloudfare error message to stable

---

.changeset/mighty-tips-love.md
packages/cli/README.md
packages/theme/oclif.manifest.json
packages/theme/package.json
packages/theme/src/cli/commands/theme/check.ts
packages/theme/src/cli/commands/theme/language-server.ts
packages/theme/src/cli/flags.ts
pnpm-lock.yaml

Fixes #1840
Introduces a `--dev-preview` flag for `shopify theme language-server`. This flag will run the language-server that uses the new [typescript implementation of theme-check](https://github.com/Shopify/theme-tools).
1. Within this repo/branch:
```bash
pnpm build
pnpm shopify:run theme init tophat-theme
SHOPIFY_FLAG_DEV_PREVIEW=1 code ./tophat-theme
(cd ./packages/cli-kit/bin && echo "$(pwd)/dev.js")
```
2. In the vscode instance that was opened by the previous command, open vscode settings with `cmd` + `,`
3. On the top right of the settings panel that opened, click the button with the hover label "Open Settings (JSON)"
4. Add this line to your VSCode settings: 
```json
"shopifyLiquid.shopifyCLIPath": "<YOUR_CLI_PATH>",
```
Note: please ensure the setting …

Dev Preview flag for theme language-server 

---

.changeset/funny-monkeys-joke.md
packages/app/src/cli/services/context.ts

Fixes https://github.com/Shopify/develop-app-management/issues/1476
- `p shopify app dev --path your-app` and select a valid store
- Update the store in shopify.app.toml to a wrong value
- `p shopify app dev --path your-app`

Fix store not found error message

---

packages/app/src/cli/services/deploy/bundle.ts

Cherrypick commits from https://github.com/Shopify/cli/pull/2911

[main] Fix concurrent function builds

---

.changeset/heavy-fishes-tan.md

When I created #2924, I forgot to add a changeset for the change. This PR adds that.

Add missing changeset for template flavors

---

.github/workflows/shopify-cli.yml

Install ruby on main acceptance tests

---

.github/workflows/shopify-cli.yml

CI wasn't running properly on PRs to stable. (See [here](https://github.com/Shopify/cli/actions/runs/6706782737), where everything was skipped.)
A PR to stable should be treated the same as a PR to main.
Checks if it's a pull to main OR a stable branch, not just main.
Gotta merge and find out!

Run main workflow on stable branches too

---

.changeset/long-snakes-lie.md
packages/cli-kit/src/public/node/base-command.ts
packages/cli-kit/src/public/node/cli.ts
packages/cli-kit/src/public/node/error-handler.test.ts
packages/cli-kit/src/public/node/error-handler.ts

Fixes https://github.com/Shopify/develop-app-management/issues/1522 
Confirms https://github.com/Shopify/develop-app-management/issues/1528
Confirms https://github.com/Shopify/develop-app-management/issues/1527
To test:
- Make an app 
- Add a checkout extension 
- Replace the code there with garbage 
- Run `pnpm shopify app build --verbose` 
- Confirm that CLI shows the syntax error, exits, skips sending the error to monorail (because we're in development).

Update base-command.ts to await error handling

---

packages/app/src/cli/services/function/build.ts
packages/cli-kit/src/public/node/git.ts
packages/cli-kit/src/public/node/node-package-manager.ts

Related to https://github.com/Shopify/develop-app-management/issues/1531
Wrapping a few steps from `generate extension` that are actually network time rather than active time.
Run `generate extension` and see that the active time is lower and the network time is higher with this branch.

Generate extension features that use the network incorrectly instrumented

---

.changeset/great-lemons-vanish.md
packages/cli-kit/src/public/node/cli.ts

Fix node link

---

.changeset/perfect-toes-listen.md
packages/app/oclif.manifest.json
packages/app/src/cli/commands/app/versions/list.ts
packages/app/src/cli/services/versions-list.test.ts
packages/app/src/cli/services/versions-list.ts
packages/cli/README.md
packages/theme/oclif.manifest.json
packages/theme/src/cli/commands/theme/list.ts
packages/theme/src/cli/services/list.test.ts
packages/theme/src/cli/services/list.ts

Having a `json` output option in some commands allows users to pipe that output or use it in a script. Making the CLI more composable and scriptable.
Fixes https://github.com/Shopify/cli/issues/3056
- Add `--json` to `app versions list`
- Add `--json` to `theme list`
Run `shopify theme list --json`
Run `npm exec shopify app versions list --json`
Update documentation to include this flags! Merge [this PR](https://github.com/Shopify/shopify-dev/pull/38870)

Add json output to versions list and theme list

---

.changeset/kind-stingrays-sparkle.md
packages/cli-kit/src/public/node/error.ts

We recently added some changes on error handling, but is causing Oclif to also print errors through its own handler.
Pass the error to oclif handler, but add a property to every error to skip printing it to console.

Fix duplicated errors

---

.github/workflows/shopify-cli.yml

https://github.com/Shopify/cli/pull/3085 didn't work, second try!
Approach taken from [here](https://github.com/Shopify/cambridge/blob/2c9358e0478b632d06318796309f3f7a50584d2a/.github/workflows/update-rbis.yml#L20).

Skip coverage report for dependabot PRs II

---

shipit.nightly.yml

The new approach failed as well. And pnpm is [working on it](https://github.com/pnpm/pnpm/issues/7336). Hopefully they fix it soon!
This reverts commit c12348b9e69818887c7bbdc5cee9a0a1585dde28.
shipit

Revert "Install pnpm via npm"

---

.changeset/healthy-chicken-beg.md
packages/app/src/cli/services/dev/graphiql/templates/graphiql.tsx

Polaris select boxes apparently require JS to work. Since we are just generating the initial HTML via Polaris, the select box contents were not being updated when the user chose a new value.
I think eventually we will need to rebuild this as a new package, but this is a good enough band-aid for now that lets us run with the lightweight solution.
Adds a line of JS to update the select box visible content when the value changes.
1. Run `dev`
2. Hit `g` to open GraphiQL
3. Confirm that changing the API version from the select dropdown updates the visible value.

Update select box contents when a new value is selected

---

packages/app/src/cli/services/dev/graphiql/templates/graphiql.tsx

We don't pass on custom headers, so we shouldn't show the editor which implies that they will be used.
Disables the Headers part of the interface.
Before:
After:
Open GraphiQL and confirm you can't edit the request headers anymore.

Disable custom headers editor in GraphiQL

---

.changeset/long-geese-clean.md
packages/app/src/cli/services/dev/graphiql/templates/graphiql.tsx

Further updates related to https://github.com/Shopify/cli/pull/3152#issuecomment-1834606516 with [new designs](https://www.figma.com/file/1UrPp4aUxgxSmBOZeJAUkC/GraphiQL?type=design&node-id=202%3A553&mode=design&t=FceZOzEHpNcST3ax-1)
* Aligns the colors (disconnected messaging is all red)
* Smaller icons in badges (the big ones, e.g. for links, were a bit gross)
* Changed the icon for the disconnected state
* Ensures the top bar titles and contents are all aligned nicely
* Shows `Disconnected` instead of `App uninstalled` when both are true (because the correct fix is restarting `dev`, not installing your app!)
Before:
After:
Run `dev` and open GraphiQL, then once GraphiQL is open kill `dev`.

Restyle top bar again

---

RELEASE_NOTES/3.51.md
RELEASE_NOTES/3.52.md

Add release notes for 3.52

---

packages/app/src/cli/services/dev/graphiql/templates/graphiql.tsx

See https://graphql.org/brand/
> Don't use “GraphQL” in a way that could imply partnership, sponsorship,
> or endorsement by the GraphQL project or GraphQL Foundation either
> directly or by omission.
Refers to
> the GraphiQL playground for the Shopify Admin API
instead of
> the Shopify GraphiQL Explorer
as the old text:
* implied we made GraphiQL (we didn't)
* used the term Explorer which is actually a GraphiQL plugin we don't include right now
Open GraphiQL. The default message should be different.

Update GraphiQL intro message to comply with GraphQL brand guidelines

---

.changeset/rich-carpets-prove.md

Fixes: https://github.com/Shopify/develop-app-foundations/issues/841
Move all the changes made in the [prototype](https://github.com/Shopify/cli/pull/3115) to a new branch that should be ready to be merged to `main`.
Cannot be merged before these PRs:
- Partners: [Versioned App Config](https://github.com/Shopify/partners/pull/51691)
- Shopify: [Versioned App Config](https://github.com/Shopify/shopify/pull/465581)
```[tasklist]
```

Versioned app config

---

.changeset/smooth-llamas-yell.md
packages/app/src/cli/api/graphql/get_config.ts
packages/app/src/cli/prompts/config.ts
packages/app/src/cli/services/app/select-app.ts

Right now the beta flag `versioned_app_config` is fetched using an strategy we would like to change
This `versioned_app_config` beta doesn't have any utility for the new CLI release
We don't want to include it in the query because in that case we will be tied to it in the future and won't be able to deprecate it in a clean way
The beta will be restored with the first pending PR for `verioned_app_config`
- Remove the beta from the query
- `deploy` and `link` command should work as expected

Remove versioned app beta flag

---

packages/app/src/cli/models/app/loader.test.ts
packages/app/src/cli/models/extensions/specifications/app_config_app_access.ts
packages/app/src/cli/services/info.test.ts

Right now `redirect_urls` config is a mandatory field as it's indicated in the [public doc](https://shopify.dev/docs/apps/tools/cli/configuration#auth). 
However every previous CLI versions have the `auth` section (that includes the `redirect_urls`) marked as `optional`. This means that users can remove it from the `toml` and the `config push` command is run successfully. However the server side doesn't remove the content of the property if it's receive as empty, so in case the user runs the `link` command the content will be restored in the `toml``
- Mark the `auth` section as mandatory in the `toml`
- Create a new `cli` app and run the `p shopify app config link --path /PATH/TO/YOUR/APP` command to link it to a new remote app.
- Enable `versioned_app_config` beta flag in the created …

Make auth section inside the config mandatory

---

.gitignore

It's annoying that the NX cache keeps popping up in git.
Ignore it!
Open the project in VS code, or run an NX command

Ignore NX cache

---

packages/app/src/cli/services/dev/ui.tsx
packages/app/src/cli/services/dev/ui/components/Dev.tsx

Get the word out about Edition to developers by meeting them where they are - in the console!
Adds a menu item to `app dev` to open Edition. Includes link tracking, and is timed to coincide with Edition start + 1 hour, and disappear 1 week later.
If we see a good response to this, maybe we'll build something even more fun next time 😉
Note this is Not Good Code™️ because the goal was to scrape something together that we are confident works, then revert and possibly rebuild later, depending on how the developer community responds.
```
$ IS_EDITION_WEEK=1 p shopify app dev --path  /path/to/your/app
```
And press `e` when the menu loads

Add link from app dev to promote Edition

---

packages/app/src/cli/services/app/config/push.ts
packages/app/src/cli/services/dev.ts

When running dev, we recommend the user runs a command in the case of a scope mismatch. We were telling them the wrong command.
Start to recommend `deploy`
Update app scopes and run dev against that app. Confirm the warning prompt is updated.

Recommend `deploy` instead of `push`

---

.changeset/four-walls-sort.md
packages/app/src/cli/services/app/config/link.ts

Move https://github.com/Shopify/cli/pull/3339 to stable

Move link uses scopes to create app

---

.changeset/kind-phones-punch.md
packages/cli-kit/assets/cli-ruby/bin/shopify

Back-porting https://github.com/Shopify/cli/pull/3369

[3.55] Fix the error message that started occurring since Ruby 3.3.0 [2]

---

packages/app/src/cli/models/app/app.test-data.ts
packages/app/src/cli/models/app/app.ts
packages/app/src/cli/models/app/loader.ts

- App constructor had 13 unnamed parameters, making it weird and complex to create a new App object.
- It was breaking our rule of max 3 parameters in functions and constructors
Fixes https://github.com/Shopify/develop-app-management/issues/1595
- Extract App constructor parameters to an object
Just that everything still works

Extract app constructor parameters to object

---

packages/theme/src/cli/services/pull.test.ts
packages/theme/src/cli/services/pull.ts
packages/theme/src/cli/utilities/asset-checksum.test.ts
packages/theme/src/cli/utilities/asset-checksum.ts

- Part of https://github.com/Shopify/develop-advanced-edits/issues/27
- I'm breaking this part out to make downstream PRs easier to review
- Extract this method from the pull service so that it can be re-used in the flow for `push`
- `pnpm test`

[Refactor] Extract rejectliquidChecksums from pull service to utility class

---

.vscode/launch.json

Trying to run the CLI with VSCode debugger attached results in this error:
This PR:
1. Adds ```"console" : "integratedTerminal"``` to all our shopify app commands so they will run in the terminal
2. Adds a new ```shopify app {cmd}``` option so you can debug different command options 
On each command run you need to enter in the command + app arguments
However, you can update the default argument in the launch.json file
- Check out this branch
- Run one of the `shopify app` commands
The VSCode debugger should run both the command and attach the debugger to our command process in the terminal. 

Update launch.json to launch debugger in integrated terminal and include option for generic app command

---

RELEASE_NOTES/3.56.md

Add release notes for 3.56.0

---

packages/app/templates/ui-extensions/projects/web_pixel_extension/shopify.extension.toml.liquid

Removes default examples until we are ready to launch in ~2 weeks.
Removes default examples until we are ready to launch in ~2 weeks.
NA
NA

remove default customer privacy settings

---

packages/app/src/cli/models/app/app.test-data.ts
packages/app/src/cli/prompts/dev.test.ts
packages/app/src/cli/prompts/dev.ts
packages/app/src/cli/services/app/fetch-app-from-config-or-select.ts
packages/app/src/cli/services/app/select-app.ts
packages/app/src/cli/services/context.test.ts
packages/app/src/cli/services/context.ts
packages/app/src/cli/services/dev.ts
packages/app/src/cli/services/dev/select-app.test.ts
packages/app/src/cli/services/dev/select-app.ts
packages/app/src/cli/services/generate.ts
packages/app/src/cli/services/info.test.ts
packages/app/src/cli/services/info.ts
packages/app/src/cli/services/webhook/find-app-info.ts
packages/app/src/cli/utilities/developer-platform-client.ts
packages/app/src/cli/utilities/developer-platform-client/partners-client.ts

Includes the skeleton work on Partners adapter (branch `partners-adapter`, as well as migrating `shopify app info` as the first command to fully use the new adapter.
Closes https://github.com/Shopify/develop-app-management/issues/1615
1. Includes the skeleton `DeveloperPlatformClient` adapter with just a couple of methods, and handling implications on testing etc.
2. Removes direct Partners references from `shopify app info` and its dependencies. This amounts to a fair bit of code, especially when including tests.
Make sure that `shopify app info` works as before. For good measure, we should try a few critical paths (`dev`, `deploy`, etc. especially with `--reset`) after each of these PRs.

Migrate app info to partners adapter

---

packages/app/src/cli/models/app/app.test-data.ts
packages/app/src/cli/prompts/dev.test.ts
packages/app/src/cli/prompts/dev.ts
packages/app/src/cli/services/app/fetch-app-from-config-or-select.test.ts
packages/app/src/cli/services/app/fetch-app-from-config-or-select.ts
packages/app/src/cli/services/app/write-app-configuration-file.test.ts
packages/app/src/cli/services/context.test.ts
packages/app/src/cli/services/context.ts
packages/app/src/cli/services/dev/urls.test.ts
packages/app/src/cli/services/generate.test.ts
packages/app/src/cli/services/generate.ts
packages/app/src/cli/utilities/developer-platform-client.ts
packages/app/src/cli/utilities/developer-platform-client/partners-client.ts

Increments on https://github.com/Shopify/develop-app-management/issues/1621 but mostly operates on dependencies that will also be useful for https://github.com/Shopify/develop-app-management/issues/1622
Continues the work of substituting a `DeveloperPlatformClient` object where a direct connection to Partners once was.
Make sure `dev` still works properly

Migrate dev to Partners adapter, part 1

---

packages/app/src/cli/utilities/developer-platform-client/partners-client.ts

Recent PR #3477 introduced a problem because the incorrect variable name was used.
Uses the correct variable name.
Deploying works again

Use correct GraphQL variable names

---

packages/app/package.json
packages/theme/package.json
pnpm-lock.yaml

Bumps Shopify/theme-tools packages.
Because we want the latest features.

Bump Shopify/theme-tools packages

---

packages/app/src/cli/api/graphql/get_versions_list.ts
packages/app/src/cli/models/app/app.test-data.ts
packages/app/src/cli/services/context.test.ts
packages/app/src/cli/services/context.ts
packages/app/src/cli/services/context/identifiers-extensions.test.ts
packages/app/src/cli/services/context/identifiers-extensions.ts
packages/app/src/cli/services/dev/create-extension.test.ts
packages/app/src/cli/services/dev/create-extension.ts
packages/app/src/cli/services/dev/fetch.test.ts
packages/app/src/cli/services/dev/fetch.ts
packages/app/src/cli/services/dev/processes/setup-dev-processes.test.ts
packages/app/src/cli/services/dev/processes/setup-dev-processes.ts
packages/app/src/cli/services/dev/processes/theme-app-extension.ts
packages/app/src/cli/services/dev/select-store.test.ts
packages/app/src/cli/services/dev/select-store.ts
packages/app/src/cli/services/dev/theme-extension-args.test.ts
packages/app/src/cli/services/dev/theme-extension-args.ts
packages/app/src/cli/services/generate.ts
packages/app/src/cli/services/versions-list.test.ts
packages/app/src/cli/services/versions-list.ts
packages/app/src/cli/utilities/developer-platform-client.ts
packages/app/src/cli/utilities/developer-platform-client/partners-client.ts

Fixes https://github.com/Shopify/develop-app-management/issues/1621
Fixes https://github.com/Shopify/develop-app-management/issues/1634
Fixes https://github.com/Shopify/develop-app-management/issues/1635
Migrates more stuff to the DeveloperPlatformClient adapter
Dev, dev with theme extensions, versions list

Migrate more stuff to partners adapter

---

.changeset/wise-houses-kick.md

We need to create a [hotfix](https://github.com/Shopify/cli/pull/3565) from this [PR](https://github.com/Shopify/cli/pull/3540). The changelog will be included in the hotfix so we need to remove it from `main` to avoid duplicate entries 

Remove Fix link command for apps with empty scopes changelog

---

packages/app/oclif.manifest.json
packages/app/src/cli/commands/app/release.ts
packages/app/src/cli/commands/app/webhook/trigger.ts
packages/cli/README.md
packages/cli/oclif.manifest.json
packages/cli/src/cli/commands/search.ts
packages/plugin-did-you-mean/oclif.manifest.json
packages/plugin-did-you-mean/src/commands/config/autocorrect/off.ts
packages/plugin-did-you-mean/src/commands/config/autocorrect/on.ts
packages/plugin-did-you-mean/src/commands/config/autocorrect/status.ts
packages/theme/oclif.manifest.json
packages/theme/src/cli/commands/theme/console.ts
packages/theme/src/cli/commands/theme/init.ts
packages/theme/src/cli/commands/theme/push.ts

Apparently it has been broken for a while because we were using the `usage` property incorrectly.
- Remove `usage` unless necessary
- Use `:` as separator in `usage` because oclif needs it to properly parse the commands
- If there are multiple usages, convert to array instead of multiline string.
Nothing, just review that the README is not broken anymore

Fix readme generation

---

packages/cli/.changeset/beans-move-happily.md

Adds changeset for https://github.com/Shopify/cli/pull/3551

add changeset for editor extension collection

---

packages/app/src/cli/services/context.test.ts
packages/app/src/cli/services/context.ts
packages/app/src/cli/services/deploy.test.ts
packages/app/src/cli/services/deploy.ts
packages/app/src/cli/services/deploy/upload.test.ts
packages/app/src/cli/services/deploy/upload.ts
packages/app/src/cli/utilities/developer-platform-client.ts
packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client.ts
packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client/graphql/active-app-release.ts
packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client/graphql/apps.ts
packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client/graphql/organization.ts
packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client/graphql/organizations.ts
packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client/graphql/user-info.ts
packages/cli-kit/src/private/node/session/authorize.ts
packages/cli-kit/src/private/node/session/device-authorization.ts
packages/cli-kit/src/public/node/api/business-platform.ts

For prototyping, we've hardcoded the organization ID. Instead, we'll pull the list from business platform.
Enables fetching a list of orgs to select from.
`app config link` should prompt for an organization to connect to, and use the organization you selected. You can check by running `--verbose` and seeing that the URL includes the correct `organizationId` (2 vs 5 for the dev user).

Add organization selection to ShopifyDevelopersClient

---

RELEASE_NOTES/3.58.md

add release notes

---

.changeset/silver-mails-build.md

- Adding back a changeset that wasn't included in the commit https://github.com/Shopify/cli/pull/3670

Add changeset for Theme Push theme selection text update

---

packages/app/src/cli/models/app/app.test-data.ts
packages/app/src/cli/models/app/app.test.ts
packages/app/src/cli/models/app/app.ts
packages/app/src/cli/models/app/loader.test.ts

All information and details contained in https://github.com/Shopify/develop-app-management/issues/1707

Filter out declarative webhooks config

---

packages/cli-kit/src/public/node/is-global.test.ts
packages/cli-kit/src/public/node/is-global.ts

As part of the global cli we need some utilities to detect and work with the global CLI.
Add some utilities to cli-kit to detect and install CLI, or infer the global CLI package manager.

Add is-global with global utilities

---

bin/bundling/cjs-shims.js
bin/bundling/clean-bundled-dependencies.js
bin/bundling/esbuild-plugin-stacktracey.js
bin/bundling/esbuild-plugin-vscode.js
package.json
packages/cli/bin/bundle.js
packages/cli/package.json
packages/cli/project.json
packages/create-app/bin/bundle.js
packages/create-app/package.json
packages/create-app/project.json
pnpm-lock.yaml

As part of the Global CLI project we are also introducing dependency bundling. This PR adds all the necessary scripts to bundle the CLI.
- Add bundle scripts for `cli` and `create-app`.
- Add some utilities shared by both bundle scripts.
- Add new `bundle` script in package.json and project.json for both packages.
THIS PR ONLY ADDS THE SCRIPTS, the bundling is not being triggered yet anywhere,
Nothing to test.

Bundling scripts

---

packages/cli-kit/src/public/node/is-global.test.ts
packages/cli-kit/src/public/node/is-global.ts
packages/create-app/src/commands/init.test.ts
packages/create-app/src/commands/init.ts
packages/create-app/src/prompts/init.test.ts
packages/create-app/src/prompts/init.ts
packages/create-app/src/services/init.ts
packages/create-app/src/utils/template/npm.test.ts
packages/create-app/src/utils/template/npm.ts

Shopify CLI is now Global by default, and `create-app` should reflect that during app creation.
- When running `npm create @shopify/app` we will check if the Global CLI is installed. If not, we'll prompt the user whether to install it or keep it as a local dependency.
- `@shopify/app` is never added to the project in any case from now on as it is bundled with CLI.
You can see this working by:
- Uninstall Global CLI if you have it (`npm uninstall -g @shopify/cli`)
- Run `pnpm create-app`
It should prompt you to install the CLI, if you select to do so we will install it and it won't appear as a dependency in the app's package.json.

`create-app` changes for Global CLI

---

packages/app/src/cli/services/dev/graphiql/templates/graphiql.tsx
packages/app/src/cli/services/dev/graphiql/templates/unauthorized.tsx

JS delivr looks to be slightly more production/scale oriented than unpkg. Given our GraphiQL feature relies on a CDN, we need it to be a more reliable one.
Switch CDNs -- its not too complex.
Run `dev`, launch GraphiQL

Switch to jsdelivr for generic CDN

---

dev.yml

PNPM within shopify will use the latest version (9) if not explicitly provided. 9 is a bit fresh for us, and doesn't work yet.
Make the version explicit
`dev up`

Specify an explicit pnpm version

---

packages/app/src/cli/models/app/loader.test.ts
packages/app/src/cli/models/extensions/load-specifications.ts
packages/app/src/cli/models/extensions/specification.ts
packages/app/src/cli/models/extensions/specifications/app_config_privacy_compliance_webhooks.ts
packages/app/src/cli/models/extensions/specifications/app_config_webhook.ts
packages/app/src/cli/models/extensions/specifications/app_config_webhook_schemas/webhook_subscription_schema.ts
packages/app/src/cli/models/extensions/specifications/app_config_webhook_schemas/webhooks_schema.ts
packages/app/src/cli/models/extensions/specifications/app_config_webhook_subscription.test.ts
packages/app/src/cli/models/extensions/specifications/app_config_webhook_subscription.ts

https://github.com/Shopify/develop-app-management/issues/1722
See description in issue
See description in issue

Webhook Subscription Specification

---

.changeset/new-glasses-punch.md
packages/app/package.json
pnpm-lock.yaml

Resolves https://github.com/Shopify/cli/issues/3768
resolve security advisory https://github.com/advisories/GHSA-rv95-896h-c2vc by upgrading Express to a newer minor revision
Run dev, and launch GraphiQL -- thats what uses express.

Update express to 4.19.2

---

package.json
pnpm-lock.yaml

The latest knip release removes a few dependencies:
- https://www.npmjs.com/package/knip/v/5.6.0?activeTab=dependencies
- https://www.npmjs.com/package/knip/v/5.10.0?activeTab=dependencies
Upgrades knip
`p knip`

Upgrade knip

---

packages/theme/src/cli/commands/theme/push.test.ts

- Applying some feedback from [[Themes][Bugfix] - Fix unpublished themes being marked as development themes by jamesmengo · Pull Request #3798 · Shopify/cli](https://github.com/Shopify/cli/pull/3798)
- Migrates mocks into individual tests
- Rearranged a test

[Themes] Improve clarity of tests for push command

---

packages/cli-kit/src/public/node/analytics.ts

With the bundling process, we can't differenciate anymore by package name in our code, because everything is part of `shopify/cli` when being run by a user. 
We were fetching app metadata and filtering by the package as `shopify/app` but we need to filter by `shopify/cli` instead.
Fixes #0000 
- Update the `buildPayload` function from analytics to take into account the package name when including the metadata in the events.

Fix app metadata not being included in monorail events

---

packages/app/src/cli/models/extensions/extension-instance.test.ts
packages/app/src/cli/models/extensions/extension-instance.ts
packages/app/src/cli/services/dev/extension/payload.ts
packages/app/src/cli/services/dev/extension/payload/store.ts
packages/app/src/cli/services/dev/processes/draftable-extension.ts
packages/app/src/cli/services/dev/ui.tsx
packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.test.tsx
packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx
packages/cli-kit/src/public/node/ui/components.ts

Exploring alternative to existing approach in #3797, will merge there if it looks to be the better solution.

Dynamic log prefixes for `app dev` via `AsyncLocalStorage`

---

docs-shopify.dev/generated/generated_static_pages.json
docs-shopify.dev/static/cli.doc.ts

Closes https://github.com/Shopify/cli/issues/3816
We haven't supported 2.7.2 for some time.
Updates to the correct minimum Ruby version in docs
It's docs so... don't?

Update Ruby version in docs to 2.7.5

---

packages/app/src/cli/services/app-logs/poll-app-logs.test.ts
packages/app/src/cli/services/app-logs/poll-app-logs.ts
packages/app/src/cli/services/dev/processes/app-logs-polling.ts

Fixes https://github.com/Shopify/shopify-functions/issues/211
Previously, when a token expired, the dev session would simply crash. Instead, we want to restart the polling process to the point prior to getting the token, so that the token will be refreshed and the session can go on perpetually.
- Update partners in a spin environment to always return an expired token (unless you happen to have a 24 hour token for production on hand)
- Turn on app dev on verbose mode
- See that it's continually resubscribing and getting a new token

Resubscribe when token expires

---

packages/app/src/cli/models/extensions/specifications/app_config_privacy_compliance_webhooks.ts
packages/app/src/cli/models/extensions/specifications/app_config_webhook_subscription.test.ts
packages/app/src/cli/models/extensions/specifications/app_config_webhook_subscription.ts
packages/app/src/cli/models/extensions/specifications/transform/app_config_webhook.ts
packages/app/src/cli/models/extensions/specifications/validation/common.ts
packages/app/src/cli/services/app/config/link.test.ts
packages/app/src/cli/services/app/config/link.ts

- we are walking this decision back for now

revert relative declarative webhook URIs

---

packages/app/src/cli/models/app/app.test-data.ts
packages/app/src/cli/services/context/identifiers-extensions.test.ts
packages/app/src/cli/services/context/identifiers-extensions.ts

We weren't taking the filters field into account when comparing the remote and local webhooks. So if you have multiple subscriptions with the same topic and URI, it'll match all and then end up keeping the last match
Fixes https://github.com/Shopify/core-issues/issues/71789
Also compare `filter` when matching
Add something like this to your TOML 
```
[[webhooks.subscriptions]]
topics = [ "products/update" ]
uri = "https://institute-malawi-humans-sympathy.trycloudflare.com/webhooks"
filter = "variants.price:>200"
[[webhooks.subscriptions]]
topics = [ "products/update" ]
uri = "https://institute-malawi-humans-sympathy.trycloudflare.com/webhooks"
filter = "variants.price:>50"
```
Deploy and see that both of subscriptions are on the version page
How do we know this change was effective? …

Also use filter when comparing remote and local webhooks

---

packages/app/src/cli/services/app-logs/poll-app-logs.test.ts
packages/app/src/cli/services/app-logs/poll-app-logs.ts
packages/app/src/cli/services/app-logs/write-app-logs.test.ts

Fixes https://github.com/Shopify/shopify-functions/issues/171.
Blocks https://github.com/Shopify/partners/pull/55178.
Attribute currently named `event_type` is being renamed to `log_type` on the log polling API.
We are simply adding support for the new `log_type` API property and supporting both the legacy `event_type` and the new `log_type` properties simultaneously to avoid breaking changes.
Simply use the log streaming feature as normal and everything should just keep working.
* Remember to enable the beta flag `Enable App Logs Streaming` to your organization in partners internal
* Remember to enable log streaming from the CLI with `export SHOPIFY_CLI_ENABLE_APP_LOG_POLLING=1`
* Use the CLI from this branch with command `dev shopify app dev --path [path to your app with a function in …

[Log Streaming]Add nullable log_type to AppEventData for incoming API changes

---

packages/create-app/src/commands/init.test.ts
packages/create-app/src/commands/init.ts

Recommend the user pass in a URL when the template argument is invalid.

Helpful message for app init template errors

---

packages/app/src/cli/services/deploy/upload.test.ts
packages/app/src/cli/services/deploy/upload.ts

See the description here https://github.com/Shopify/shopify/pull/515947

Do not show duplicate errors

---

.changeset/smart-hounds-reply.md

Changelog in aggregate for this new feature.

Changeset for log streaming

---

packages/app/src/cli/models/app/loader.test.ts
packages/app/src/cli/models/app/loader.ts
packages/app/src/cli/models/extensions/specifications/validation/app_config_webhook.ts

Fixes https://github.com/Shopify/develop-app-inner-loop/issues/1840
See description in https://github.com/Shopify/develop-app-inner-loop/issues/1840
See description in https://github.com/Shopify/develop-app-inner-loop/issues/1840
Measuring impact

duplicate subscripition error

---

RELEASE_NOTES/3.63.md

Add release notes for 3.63.0

---

.changeset/fresh-queens-tell.md
packages/plugin-cloudflare/src/install-cloudflared.test.ts
packages/plugin-cloudflare/src/install-cloudflared.ts

There were some tunneling issues lately and Cloudflare recommended to upgrade our binary
Upgrade cloudflare to the latest version
`p shopify app dev`

 [stable] Upgrade cloudflared

---

packages/plugin-cloudflare/src/install-cloudflared.test.ts
packages/plugin-cloudflare/src/install-cloudflared.ts

Cherrypick commits from https://github.com/Shopify/cli/pull/4126

Upgrade cloudflared

---

.github/workflows/snapit.yml

It will introduce support for the "/snapit" command: when added, it will publish a snapshot of the current branch to npm for easier top-hatting.
This is a Shopify developed tool.
Add support for the /snapit command

Add support for /snapit

---

packages/cli-kit/src/public/node/custom-oclif-loader.ts

Make custom oclif loader default to cwd if path doesnt exist

---

packages/app/src/cli/models/app/loader.test.ts
packages/app/src/cli/models/extensions/specifications/validation/common.ts

https://github.com/Shopify/cli/pull/4177#pullrequestreview-2169091468
Fix wording
Deploy an app with a subscription having an invalid URL like `wrong`

Fix webhooks error wording

---

packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
packages/app/src/cli/utilities/developer-platform-client/app-management-client/graphql/create-app-version.ts
packages/app/src/cli/utilities/developer-platform-client/app-management-client/graphql/create-app.ts

`modules` are being renamed to `appModules` https://github.com/Shopify/shopify/pull/520310 (this is a breaking change)
Renames the field
Things should work after the change.

Rename modules to appModules in API

---

packages/cli/package.json
pnpm-lock.yaml

Contains an important patch for Hydrogen to fix the auth flow: https://github.com/Shopify/hydrogen/pull/2331

Update cli-hydrogen dep

---

packages/cli-kit/src/private/node/analytics.ts
packages/cli/oclif.manifest.json
packages/cli/src/index.ts

With the introduction of bundling we no longer have "plugins" internally, all commands are flattened into the @shopify/cli core plugin. This affected the `plugin` field in our analytics where everyhting is `cli` now.
This PR fixes that by overriding the plugin name for every command coming from a plugin.
- Set a `customPluginName` to every command coming from a plugin.
- Use tha `customPluginName` (if available) when building the analytics payload.
- Set a breakpoint in `packages/cli-kit/src/private/node/analytics.ts`, where we read the `customPluginName`.
- Run a command like `app info`
- The `customPluginName` should contain `@shopify/apo`

Override plugin name when loading commands in CLI

---

RELEASE_NOTES/3.65.md

Adds release notes for [3.65.0](https://github.com/Shopify/cli/releases/tag/3.65.0).
Because it's good to have release notes!
Just adding a README.
Read the file I added :) Make sure it corresponds to the most important [changes](https://github.com/Shopify/cli/pull/4188) from the latest release + is worded/formatted helpfully.

Add release notes for 3.65.0

---

.changeset/fluffy-lobsters-melt.md
packages/app/src/cli/models/extensions/specifications/app_config_app_access.test.ts
packages/app/src/cli/models/extensions/specifications/app_config_app_access.ts

For:
- https://github.com/Shopify/develop-app-runtime-primitives/issues/329
Depends on:
- https://github.com/Shopify/shopify/pull/524792
Add `required_scopes` to `access_scopes` app configuration schema
Tophat instructions detailed in https://github.com/Shopify/shopify/pull/524792
- ❗️ [We'll add documentation once this feature is fully ready](https://github.com/Shopify/develop-app-runtime-primitives/issues/284)

Add 'required_scopes' to 'access_scope' toml schema

---

.changeset/smart-mugs-love.md
packages/app/src/cli/services/function/binaries.test.ts
packages/app/src/cli/services/function/binaries.ts

Same reason as #4274. But backporting the fix.
Same as #4274 but as a backport.
Same as #4274.

Fix Javy and function-runner download on Windows

---

.changeset/thin-wolves-obey.md
docs-shopify.dev/commands/interfaces/hydrogen-dev.interface.ts
docs-shopify.dev/commands/interfaces/hydrogen-env-pull.interface.ts
docs-shopify.dev/commands/interfaces/hydrogen-env-push.interface.ts
docs-shopify.dev/commands/interfaces/hydrogen-preview.interface.ts
docs-shopify.dev/generated/generated_docs_data.json
packages/cli/README.md
packages/cli/oclif.manifest.json
packages/cli/package.json
pnpm-lock.yaml

Bumping Hydrogen version after our new release.

Bump cli-hydrogen version

---

packages/app/src/cli/services/logs.test.ts
packages/app/src/cli/services/logs.ts

[Ticket](https://github.com/orgs/Shopify/projects/2117/views/75?pane=issue&itemId=73736546)
We want the user to know logger cli is ready and functioning (even when there are no app logs) when they start the app logs in cli so they are not confused by absence of any app logs. In other words it is being specific that there isn't(or is) any logs to display
Adding a single line to app logs and app logs json command output that says "Waiting for app logs..."
1. Checkout this branch in local, dev up and pnpm install.
2. Run `pnpm run shopify app logs --path <path to functions app in your local system>` from the cli directory where you have checked out this branch.
3. (Optionally)Trigger functions run from your dev store.
4.  Run `pnpm run shopify app logs --json --path <path to functions app in …

Functions_366 Adding logger waiting for app logs line for app logs cli

---

packages/cli-kit/src/private/node/ui/components/SelectInput.tsx

Fixes https://github.com/Shopify/develop-app-inner-loop/issues/2038
See video in https://github.com/Shopify/develop-app-inner-loop/issues/2038#issuecomment-2290168747
See https://github.com/Shopify/develop-app-inner-loop/issues/2038#issuecomment-2290168747

Wraps stores list

---

packages/app/src/cli/models/extensions/specifications/app_config_privacy_compliance_webhooks.test.ts
packages/app/src/cli/models/extensions/specifications/app_config_privacy_compliance_webhooks.ts

Part of the modules refactor. Include the api version in the module so we can later remove the dependency on the app's webhook api version. 
Cannot be merged until the PR for the new property is merged

Include the webhook api version in the privacy compliance webhooks

---

docs-shopify.dev/generated/generated_static_pages.json
docs-shopify.dev/static/cli.doc.ts

It seems we missed [here](https://github.com/Shopify/shopify-dev/pull/42712/files#diff-8e83fbb07c9aa7adc3ecb982a8eeb09d679ae9508e8e90434980be8587812a8bL2) the package managers requirements by mistake.
Adds them back

Add package manager requirements to the docs

---

packages/app/src/cli/services/context.test.ts
packages/app/src/cli/services/context.ts
packages/app/src/cli/services/logs.test.ts
packages/app/src/cli/services/logs.ts
packages/app/src/cli/services/webhook/trigger-options.test.ts

Fixes https://github.com/Shopify/shopify-functions/issues/378
When user uses the app logs command, possibly with the `--store` flag, we want the info box the user sees to have relevant data such as dev stores the user entered and `update URLs` not being present as it is not relevant to the app logs command. 
Created our own custom info box that gets used instead of the default one for `app logs` command. 
Before:
App logs
App dev
After: 
App logs
App dev
- Checkout my branch and run ` pnpm run shopify app logs --path <YOUR APP> --store <Store URL 1> <Store URL 2>`

Functions_378 Adding custom info box for app logs

---

packages/cli-kit/package.json
packages/cli-kit/src/public/node/system.ts
pnpm-lock.yaml

Fixes https://github.com/Shopify/develop-app-inner-loop/issues/120
More details in the issue

Improve binary run safety

---

packages/app/src/cli/models/app/app.test-data.ts
packages/app/src/cli/services/context/partner-account-info.ts
packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
packages/cli-kit/package.json
packages/cli-kit/src/private/node/session.test.ts
packages/cli-kit/src/private/node/session.ts
packages/cli-kit/src/private/node/session/device-authorization.test.ts
packages/cli-kit/src/private/node/session/exchange.test.ts
packages/cli-kit/src/private/node/session/exchange.ts
packages/cli-kit/src/private/node/session/schema.ts
packages/cli-kit/src/private/node/session/store.test.ts
packages/cli-kit/src/private/node/session/validate.test.ts
packages/cli-kit/src/private/node/session/validate.ts
packages/cli-kit/src/public/node/crypto.test.ts
packages/cli-kit/src/public/node/crypto.ts
packages/cli-kit/src/public/node/environment.ts
packages/cli-kit/src/public/node/session.test.ts
packages/cli-kit/src/public/node/session.ts
pnpm-lock.yaml

We want to start using the `sub` from the identity token as an identifier for the current user.
Contributes to https://github.com/Shopify/develop-app-inner-loop/issues/2026 
- Extract `sub` from identity token and store it in the session as `userId`
- Update partners-client and app-management-client to receive the userId and include it in the session object.
Nothing to test yet, this is just adding this new value, is not used yet.

Extract user id from identity token and add it to the session

---

.changeset/metal-plants-chew.md
packages/app/src/cli/models/extensions/specifications/app_config_privacy_compliance_webhooks.test.ts
packages/app/src/cli/models/extensions/specifications/app_config_privacy_compliance_webhooks.ts

Cherrypick commits from https://github.com/Shopify/cli/pull/4514

[Stable] Fix duplicated slash compliance webhooks

---

.changeset/nervous-coins-admire.md
packages/cli-kit/src/public/node/output.ts

Cherrypick commits from https://github.com/Shopify/cli/pull/4513

[stable] Avoid errors when trying to output empty variables

---

packages/app/src/cli/models/app/loader.ts
packages/app/src/cli/models/extensions/specification.integration.test.ts
packages/app/src/cli/models/extensions/specification.ts
packages/app/src/cli/services/dev/update-extension.ts
packages/app/src/cli/utilities/json-schema.ts

Improvement of this previous PR: https://github.com/Shopify/cli/pull/4532
- Extract the logic to remove first class fields to a single place
- Call the unified function from wherever needed (it wasn't needed in a specific place)
- Add a test for it.

Extract config clean up to a single place

---

.changeset/silent-parents-destroy.md
packages/theme/src/cli/utilities/theme-environment/proxy.ts
packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts

Backport https://github.com/Shopify/cli/pull/4569

[3.68] Inject CDN in Liquid assets

---

.github/CODEOWNERS
packages/theme/src/cli/commands/theme/check.ts

Add CODEOWNERS back. Hopefully with the right rules this time.

Reinstate CODEOWNERS

---

.github/CODEOWNERS

https://shopify.slack.com/archives/C030LHFCA5T/p1729104412156939
Follows up on https://github.com/Shopify/cli/pull/4672
Enables `advanced edits` to review changes to `oclif.manifest.json

Update CODEOWNERS so anyone can review auto-generated manifest

---

packages/cli-kit/src/public/node/api/graphql.ts
packages/cli-kit/src/public/node/monorail.ts

Blocked on https://github.com/Shopify/monorail/pull/19610
Track additional information on the last used GraphQL request. Helpful for failing commands.

Track the last used GraphQL request ID with all commands

---

packages/app/src/cli/models/app/app.test-data.ts
packages/app/src/cli/models/extensions/load-specifications.ts
packages/app/src/cli/models/extensions/specification.ts
packages/app/src/cli/models/extensions/specifications/data_extension.ts
packages/app/src/cli/models/extensions/specifications/marketing_activity.ts
packages/app/src/cli/services/generate/fetch-extension-specifications.test.ts
packages/app/src/cli/services/generate/fetch-extension-specifications.ts

We want to simplify the process of defining new extension specs, this completely remove the need to update the CLI for simple contract-based extensions.
Before this change we were forced to define a local spec for every extension type, and then when fetching the remote ones, we would merge them.
Now: 
- For remote specs that don't have a local version, but define a validationSchema, automatically create a `contract-based` local extension and merge it with the remote one.
- Also: automatically include the `localization` feature if the jsonSchema expects a localization property.
Create a marketing_activity extension, this spec only exists remotely and has a validationSchema. You should be able to deploy without problems. (you might need a beta flag, ask me)
How do we know this change was …

Auto create contract based specs

---

packages/theme/src/cli/services/dev.ts

Unblocks - https://github.com/Shopify/cli/pull/4560
Fixes `ESlint` issues that come from the new rules
`p test`

[Themes] ESLint fixes in the `theme dev` command

---

packages/app/src/cli/models/app/identifiers.test.ts
packages/app/src/cli/models/app/identifiers.ts

We were writing to `.env` files without properly respecting the existing content of the file.
Fixes https://github.com/Shopify/cli/issues/4704
On app deploy/release, use `patchEnvFile` to update `.env` files with identifiers:
- Comments are preserved
- Order is preserved
- New items are added at the bottom
Run `app deploy` on an app, modify the .env file, add comments and remove IDs, run deploy again and it should append the IDs at the end and respect any other existing content.

Safely patch env files on deploy

---

packages/app/src/cli/services/dev/processes/dev-session.ts

We were using an outdated app in the first dev bundle.
We need to pass the new app to the processOptions object so that it is used downstream

Fix application_url being outdated in manifest

---

packages/app/src/cli/commands/app/import-extensions.ts
packages/app/src/cli/services/import-extensions.test.ts
packages/app/src/cli/services/subscription_link/extension-to-toml.test.ts
packages/app/src/cli/services/subscription_link/extension-to-toml.ts

Closes: https://github.com/Shopify/subscriptions-app-remix/issues/2061
Adding ability to import an existing dashboard-managed subscription link extension to CLI.
Updates the` shopify app import-extensions` command to import existing dashboard-managed subscription link extension to CLI.
1. Spin up a new spin instance - `spin up partners`
2. From the Partner Dashboard create a new app, add a subscription link extension to your app
3. Checkout this branch on your local CLI repository.
4. Create a new app - `bin/spin pnpm shopify app init --path ~/`
5. `cd` into your new app and run `bin/spin pnpm shopify app dev --path ~/<APP_NAME>`. Make sure you connect your app to the app you created in step 2.
6. Run `bin/spin pnpm shopify app import-extensions  --path ~/<APP_NAME>`
Expectation: This …

Supports importing subscription link extensions

---

packages/app/src/cli/prompts/deploy-release.test.ts
packages/app/src/cli/prompts/deploy-release.ts
packages/app/src/cli/services/context.ts

I found the wording of the existing message to be a bit verbose and potentially misleading.
* "be an option" becomes "be optional" because it will continue to be an option to include the config, it'll just be the only option 😉
* "will be included" is shorter, no need for "need to"
* Same for "replacing "included on deploy every time" with "included on every deploy" - less is more!
Before:
After:

Minor wording improvements

---

packages/cli-kit/package.json
packages/cli-kit/src/public/node/system.ts
pnpm-lock.yaml

Related to https://github.com/Shopify/develop-app-inner-loop/issues/120#issuecomment-2476139860
Adds back https://github.com/Shopify/cli/pull/4401 after being reverted in Shopify/cli#4527

Improve binary run safety II

---

packages/app/src/cli/models/extensions/extension-instance.ts
packages/app/src/cli/models/extensions/specification.ts
packages/app/src/cli/models/extensions/specifications/app_config_app_access.ts
packages/app/src/cli/services/dev/processes/dev-session.test.ts
packages/app/src/cli/services/dev/processes/dev-session.ts

Move the responsibility of the "Action Required" message to the specification instead of hardcoding the message in the `dev-session`
Add a new `getDevSessionActionUpdateMessage` to the extension-instance and the extension-specification. And define it for the app access module
Run consistent-dev, make a change in the scopes, you should see the action required message.

Move action required message to the spec

---

.changeset/shaggy-cheetahs-think.md
packages/cli/package.json
pnpm-lock.yaml

Bump cli-hydrogen to 9.0.3

---

.changeset/large-sloths-complain.md
packages/app/src/cli/services/admin-link/utils.test.ts
packages/app/src/cli/services/admin-link/utils.ts

Cherry-pick commits from https://github.com/Shopify/cli/pull/5102

[stable] Fix subdomain underscores in admin link import

---

packages/cli-kit/src/public/node/api/graphql.ts

Fixes an issue where GraphQL request IDs were not being logged when requests failed, making it harder to debug and trace failed requests.
Extracts the request ID logging logic into a separate function and ensures it's called for both successful and failed GraphQL requests. This change captures request IDs from error responses, improving our ability to track and debug failed API calls.
Run the CLI with `--verbose` and confirm the last request ID is logged at the end.
Testing a failure case is harder. You need to get a failing response -- not just an unavailable service.

Correctly log last request ID when the last request was a failure

---

RELEASE_NOTES/3.74.md

Adding a new release notes file for the latest release.
Adding a new release notes file for the latest release.

Add release notes for 3.74

---

.github/workflows/docs.yml

Making the `Version Packages` PR just about versioning packages, instead of being 99.99% static docsite updates every time.
Sets up a GitHub action that should generate and push our API docs to GitHub pages
We'll have to merge and see!

Add workflow to build a deploy artifact and deploy to GH pages

---

dev.yml

Make ourselves aware of build failures without waiting for CI 
Adds checks `dev` can run in the background while we work
Do something wrong, wait a minute, then try and commit. You should see a complaint.

Add dev checks

---

packages/app/src/cli/services/dev.ts
packages/app/src/cli/services/dev/processes/dev-session-status-manager.ts
packages/app/src/cli/services/dev/processes/setup-dev-processes.ts
packages/app/src/cli/services/dev/ui.tsx
packages/app/src/cli/services/dev/ui/components/DevSession.tsx

Create new DevSessionUI

---

packages/app/src/cli/services/dev/ui/components/Dev.test.tsx
packages/app/src/cli/services/dev/ui/components/Dev.tsx

Since we have a dedicated component, we no longer need anything related to dev-sessions in the old component.
- Remove all dev-session related code from the old UI component.
- Just test that running dev (without dev-sessions) continue to work normally.

Remove all traces of dev-sessions from Dev.tsx

---

.changeset/witty-planes-crash.md
packages/cli/package.json
packages/features/snapshots/commands.txt
pnpm-lock.yaml

CLI Hydrogen just had a release to version 9.0.5

Bump cli-hydrogen

---

packages/app/src/cli/api/graphql/business-platform-organizations/generated/types.d.ts

The BP has new GraphQL scalar types. This PR updates the types file.

Support new BP scalar types

---

packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts

Fixes https://github.com/Shopify/develop-app-inner-loop/issues/2444
We weren't submitting source control URL to the App Management API.
Submits it
Run `app deploy` (in a development instance) and specify a `--source-control-url`
In Core, check the most recently created version. You should see the submitted URL.

Include source control URL in version metadata

---

pnpm-lock.yaml

Commit lockfile update

---

.github/workflows/snapit.yml

Continuation of https://github.com/Shopify/cli/pull/5404
The CAUTION block is still not properly formatted
Adds an extra line break
Checked here: https://github.com/Shopify/cli/pull/5348#issuecomment-2663397405

Fix snapit message II

---

.changeset/strange-dogs-rule.md
packages/cli/package.json
pnpm-lock.yaml

Update Hydrogen CLI dependency to fix an issue when running `npx shopify hydrogen deploy --build-command "shopify hydrogen build"`
Updates `@shopify/cli-hydrogen` from version 9.0.6 to 9.0.7.

Update to cli-hydrogen 9.0.7

---

bin/docs/build-dev-docs.sh
docs-shopify.dev/commands/examples/app-config-use.example.sh
docs-shopify.dev/commands/examples/help.example.sh
docs-shopify.dev/commands/examples/search.example.sh
docs-shopify.dev/commands/examples/theme-init.example.sh

Some commands with static arguments don't have accurate examples for shopify.dev
Improve the examples to include the missing arguments
N/A

Improve examples for commands with static args

---

packages/cli-kit/src/private/node/api/graphql.ts
packages/cli-kit/src/public/node/api/graphql.test.ts

There are some lint issues introduced in https://github.com/Shopify/cli/pull/5428
Fix lint issues
CI

Fix lint issues

---

packages/app/src/cli/services/dev/processes/dev-session-status-manager.test.ts
packages/app/src/cli/services/dev/processes/dev-session-status-manager.ts
packages/app/src/cli/services/dev/ui/components/DevSessionUI.tsx
packages/app/src/cli/services/dev/ui/components/Spinner.tsx

Improves the developer experience by introducing a new "status message" in the concurrent log.
Adds a new status message system to the dev session UI that:
- Displays loading states with an animated spinner
- Shows success messages when updates complete
- Presents error messages for build and validation failures
- Maintains persistent status visibility for errors and loading states
Nothing to test in this PR, this one only makes the necessary UI changes. But we are not emitting events yet.

Show a dynamic dev session status message in the UI

---

packages/app/src/cli/api/graphql/business-platform-organizations/generated/types.d.ts

Fixes graphql-codegen [failing](https://github.com/Shopify/cli/actions/runs/13549987606/job/37871027961?pr=5373#step:6:18) in `main`

Update business platform schema

---

.github/workflows/release.yml

Add NPM token to release script

---

.github/workflows/release.yml
bin/release

We want to sign all releases
We don't want changesets to create automatic tags

Add provenance and --no-git-tag to release script

---

packages/app/src/cli/models/extensions/specifications/function.test.ts
packages/app/src/cli/models/extensions/specifications/function.ts

Part of https://github.com/Shopify/shopify-functions/issues/633
Allows a function extension's TOML config to pass in a new property, `features`.
I've tophatted locally, and updated the tests.
Nothing is required at the moment.

add features to config under target

---

.changeset/many-coats-juggle.md
packages/app/src/cli/models/app/app.test-data.ts
packages/app/src/cli/services/app-logs/dev/poll-app-logs.test.ts
packages/app/src/cli/services/app-logs/dev/poll-app-logs.ts
packages/app/src/cli/services/app-logs/logs-command/poll-app-logs.test.ts
packages/app/src/cli/services/app-logs/logs-command/poll-app-logs.ts
packages/app/src/cli/services/app-logs/logs-command/render-json-logs.ts
packages/app/src/cli/services/app-logs/logs-command/ui.tsx
packages/app/src/cli/services/app-logs/logs-command/ui/components/Logs.test.tsx
packages/app/src/cli/services/app-logs/logs-command/ui/components/Logs.tsx
packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.test.tsx
packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.ts
packages/app/src/cli/services/app-logs/utils.ts
packages/app/src/cli/services/dev/processes/app-logs-polling.ts
packages/app/src/cli/utilities/developer-platform-client.ts
packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
packages/app/src/cli/utilities/developer-platform-client/partners-client.ts

Part of: https://github.com/Shopify/shopify-functions/issues/605
This PR adds `appLogs` to the `DeveloperPlatformClient` interface. Currently this is not necessarily needed since when we poll for app logs, we only have one client currently in use. But to integrate app logs streaming with the developer dashboard, this will make calling the correct request (partners vs app management) simpler. 
The next step is this follow Up PR: https://github.com/Shopify/cli/pull/5498
This change enables app logs to be fetched from both the `PartnersClient` and we will update the methods for the `AppManagementClient` in a separate PR, providing a consistent interface regardless of which backend is being used.
- Moving app logs fetching from direct HTTP calls to using developerPlatformClient
- Removes …

Add `appLogs` to DeveloperPlatformClient interface

---

.changeset/sweet-lemons-love.md
packages/app/src/cli/api/graphql/business-platform-organizations/generated/types.d.ts

Updating graphql-codegen so that the release flow can be completed.

Graphql-codegen update

---

RELEASE_NOTES/3.77.md

We released version 3.77 + need release notes.
Adding release notes. Pretty much the same as https://github.com/Shopify/cli/releases/tag/3.77.0
N/A

3.77 Release notes

---

packages/app/src/cli/services/dev/processes/dev-session.ts
packages/app/src/cli/services/dev/processes/dev-session/dev-session-logger.test.ts
packages/app/src/cli/services/dev/processes/dev-session/dev-session-logger.ts
packages/app/src/cli/services/dev/processes/dev-session/dev-session.ts

This refactoring improves code organization by extracting the dev session logic into a dedicated class.
Refactors the dev session implementation by:
- Creating a new `DevSession` class that encapsulates all the dev session functionality
- Moving related types and methods from `dev-session.ts` into the new class
- Simplifying the main process function to use the new class
- Maintaining the same functionality while improving code organization
1. Verify dev sessions continue to work as expected

Refactor DevSession into a class

---

.changeset/rare-ants-rest.md
bin/get-graphql-schemas.js
packages/cli/package.json
pnpm-lock.yaml

Bump cli-hydrogen to 9.0.9

---

.changeset/wise-cycles-juggle.md
packages/cli/package.json
pnpm-lock.yaml

Just released `@Shopify/hydrogen@2025.1.3` with new updates to cli-hydrogen.
Fixes #0000 

Updated @shopify/cli-hydrogen to 9.0.9 (main branched).

---

.changeset/cuddly-pumpkins-promise.md
packages/app/package.json
packages/theme/package.json
pnpm-lock.yaml

Revert "Bump Shopify/theme-tools packages"

---

.changeset/big-singers-pump.md
packages/app/src/cli/models/app/app.test.ts
packages/app/src/cli/models/app/app.ts
packages/app/src/cli/models/extensions/extension-instance.ts
packages/app/src/cli/models/extensions/specification.ts
packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
packages/app/src/cli/models/extensions/specifications/ui_extension.ts

Patch 3.78 to include fix in this [PR](https://github.com/Shopify/cli/pull/5647)
Create a patch release

Merge fix for 

---

packages/app/src/cli/services/dev/processes/dev-session/dev-session.ts

Fixes an issue where network timeouts during dev session uploads were not being properly handled, leading to unclear error messages for users with connectivity issues.
- Moves the try/catch block to encompass all network operations (getting signed URL, uploading to GCS, and updating dev session)
- Adds specific error handling for ETIMEDOUT errors, providing a more user-friendly error message about checking internet connection
1. Simulate a network timeout during dev session upload (can be done by disconnecting internet during upload or with the `Network Link Conditioner` tool)
2. Verify that the new error message appears: "Request timed out, please check your internet connection and try again."
3. Ensure that normal upload flow still works correctly when network is stable
How do we know …

Add timeout error handling in dev session upload process

---

packages/theme/src/cli/utilities/theme-environment/hot-reload/server.ts

Fixes https://github.com/Shopify/cli/issues/5589
The public CDN we use for the hot reloading library had some sort of outage recently. I'm moving this library to our CDN for now.

Use Shopify CDN to server hot reloading library

---

.changeset/purple-seals-exist.md
packages/app/src/cli/api/graphql/extension_specifications.ts
packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
packages/eslint-plugin-cli/rules/no-inline-graphql.js

Fixes #5654
Inconsistent naming has messed with our scrubbing in debug view.
Names the parameter `apiKey` as properly camelCased so it gets scrubbed like the rest.
Anything involving fetching specifications (I used `generate extension` to test) should work as before, but `apiKey` should be scrubbed properly.

Use consistent naming

---

.changeset/fresh-masks-sort.md
packages/app/src/cli/services/dev/ui/components/Dev.tsx
packages/app/src/cli/services/dev/ui/components/DevSessionUI.tsx
packages/cli-kit/src/public/node/ui/components.ts

Adds use of hyperlinks to the `app dev` URLs.
* Ensures that links can be clicked even in narrow width terminals.
* Formats links consistently with other terminal links
Example in iTerm of URL cutoff creating a link which will 404, or worse:
Uses the `<Link>` component to conditionally output these URLs as terminal hyperlinks, if the terminal supports them.
Use `pnpm shopify app dev --path <path>` on both Partners and Dev Dash apps in a terminal that supports hyperlinks, such as iTerm or VSCode. Ensure links render and are clickable, especially with a narrow width.
Turn off hyperlinks with `export FORCE_HYPERLINK=0` and do the same. Links should render with plain text, as before, and the wrapping issue will persist in this case.

Use terminal links for `dev` URLs for better formatting and text wrapping support.

---

bin/create-doc-pr.js
bin/create-homebrew-pr.js
bin/github-utils.js
bin/post-release

Straightforward improvements to the release script
1. Cleans up the code (it had some extra imports)
2. Run `print-auth` with the `--password` flag so we can get rid of the extra parsing code
3. Check early if credentials are available; sometimes this results in only part of the script running
4. Make it idempotent; don't submit PRs unless something has changed
I tested locally, you can:
1. Cherry-pick the commits on top of the current stable branch
2. Confirm everything works and no PRs are created
Of course it'll be exercised manually next time there's a release.

Post release improvements

---

packages/app/src/cli/services/dev.ts

Displays a feedback banner when using dev sessions.

add early access feedback banner for new app dev

---

.changeset/mighty-horses-fetch.md
packages/cli-kit/src/public/node/api/admin.ts
packages/cli-kit/src/public/node/api/graphql.ts
packages/cli-kit/src/public/node/themes/api.test.ts
packages/cli-kit/src/public/node/themes/api.ts

Back-port: https://github.com/Shopify/cli/pull/5711

[3.79] Custom network settings for theme commands

---

packages/app/src/cli/api/graphql/app-dev/generated/dev-session-update.ts
packages/app/src/cli/api/graphql/app-dev/queries/dev-session-update.graphql
packages/app/src/cli/services/bundle.ts
packages/app/src/cli/services/context.ts
packages/app/src/cli/services/dev/processes/dev-session/dev-session-process.test.ts
packages/app/src/cli/services/dev/processes/dev-session/dev-session.ts
packages/app/src/cli/utilities/developer-platform-client.ts
packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
packages/cli-kit/src/public/node/fs.ts

Incremental dev - implementation

---

.changeset/hungry-ravens-wink.md
.changeset/sharp-kiwis-invite.md
packages/theme/src/cli/utilities/theme-environment/hot-reload/server.test.ts
packages/theme/src/cli/utilities/theme-environment/hot-reload/server.ts
packages/theme/src/cli/utilities/theme-environment/local-assets.ts
packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts

Back-port:
- https://github.com/Shopify/cli/pull/5815
- https://github.com/Shopify/cli/pull/5832

[3.80] Enhance hot-reload events for stylesheet/javascript tags and improve their resilience

---

RELEASE_NOTES/3.80.md

- Update release notes for 3.80.0

3.80.0 release notes

---

.changeset/gorgeous-parents-impress.md
packages/app/src/cli/services/function/binaries.ts

Function Runner 8.0.x introduced a breaking change the JSON outputs. Version 9.0.0 fixes that.
This updates the preferred version of Function Runner to 9.0.0.
Run `shopify app function run` on a function

Update function-runner to v9.0.0

---

packages/app/src/cli/utilities/developer-platform-client/partners-client.ts

Cherry-pick commits from https://github.com/Shopify/cli/pull/5836

Force the token refresh when starting a new session

---

packages/cli-kit/src/public/node/archiver.ts

Cherry picked from https://github.com/Shopify/cli/pull/5865

Fix brotli dynamic import

---

packages/app/src/cli/services/dev/processes/dev-session/dev-session-process.test.ts
packages/app/src/cli/services/dev/processes/dev-session/dev-session.ts
packages/cli-kit/src/public/node/serial-batch-processor.test.ts
packages/cli-kit/src/public/node/serial-batch-processor.ts

To improve the handling of rapid file changes during development by implementing a queue system for app events, preventing race conditions and ensuring all changes are properly processed.
Implements a more robust event handling system in the DevSession class:
1. Adds a queue system for app events to handle rapid changes
2. Introduces a consolidation mechanism that merges multiple events into a single update
3. Replaces the abort controller approach with a more reliable state tracking system
4. Ensures events are processed sequentially, preventing race conditions
5. Optimizes the update process by combining related changes
1. Run `dev` on a project with multiple extensions
2. Make rapid changes to multiple extension files
3. Verify that all changes are properly processed and reflected in …

Queue and consolidate app events during dev session updates

---

package.json
packages/ui-extensions-dev-console/package.json
packages/ui-extensions-server-kit/package.json
pnpm-lock.yaml

Fixes https://github.com/Shopify/develop-app-inner-loop/issues/2609
Fixes https://github.com/Shopify/cli/security/dependabot/149
Fixes https://github.com/Shopify/cli/security/dependabot/153
Fixes https://github.com/Shopify/cli/security/dependabot/154
Fixes https://github.com/Shopify/cli/security/dependabot/160
Fixes https://github.com/Shopify/cli/security/dependabot/164
Upgrades Vite to the latest version (6.3.5)
A few random commands and CI

Upgrade Vite

---

docs-shopify.dev/generated/generated_static_pages.json
docs-shopify.dev/static/cli.doc.ts

Recreates [this pull request](https://github.com/Shopify/shopify-dev/pull/56125) in the proper location.

Recreated network proxy docs in CLI repo

---

.changeset/angry-comics-greet.md
packages/theme/package.json
packages/theme/src/cli/utilities/theme-environment/hot-reload/server.test.ts
packages/theme/src/cli/utilities/theme-environment/hot-reload/server.ts
packages/theme/src/cli/utilities/theme-environment/liquid-tag-content.test.ts
packages/theme/src/cli/utilities/theme-environment/liquid-tag-content.ts
packages/theme/src/cli/utilities/theme-environment/local-assets.ts
pnpm-lock.yaml

Fixes https://github.com/Shopify/cli/issues/5918
This PR addresses two problems: the dev server hanging during startup and dev server requests occasionally taking up to a minute to load.
When we introduced support for hot-reloading `{% stylesheet %}` and `{% javascript %}` tags, we started using the `@shopify/liquid-html-parser` to extract JavaScript and CSS content from Liquid files and locally generate compiled assets.
Using a parser is the most accurate way to get this content, but parsing has a performance cost. Even though we used caches to reduce the impact, there was still a noticeable slowdown for large themes, especially during cache warm-up.
This PR switches from using the Liquid parser to using a regex to support hot-reloading of the `{% stylesheet %}` and `{% javascript %}` …

Fix performance issue on `shopify theme dev` command

---

packages/app/src/cli/api/graphql/app-management/generated/apps.ts
packages/app/src/cli/api/graphql/app-management/queries/apps.graphql
packages/cli-kit/package.json
packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.tsx
packages/cli-kit/src/public/common/function.ts
pnpm-lock.yaml

The autocomplete was:
- Firing too often (not debouncing properly due to React recreating the function)
- Making a query that was too expensive (no reason to return app modules)
1. Makes the query itself less expensive (not fetching app modules)
2. Replaces debounce with throttle, so we will search as the user types but in a throttled fashion
Run `app config link` and search for an existing app

Slow autocomplete prompt to avoid rate limiting

---

packages/cli-kit/src/public/node/api/admin.ts

To support local development by modifying the admin API request behavior when running in a local environment.
This PR modifies the admin API request functionality to handle local development environments differently:
1. When in a local service environment, it:
- Adds the original store domain as an `x-forwarded-host` header
- Uses the DevServer app host as the domain for the admin URL
These changes allow admin API requests to be properly routed during local development.
1. Run the CLI in a local development environment
2. Make an admin API request (e.g. `$ SHOPIFY_SERVICE_ENV=local pnpm shopify theme list --store=shop2`).
3. Verify that command is executed successfully.

Use correct domain/headers for Admin API requests in local environment

---

packages/app/src/cli/services/dev/urls.test.ts
packages/app/src/cli/services/dev/urls.ts

Resolve https://github.com/shop/issues-develop/issues/21038
Fixes a bug where relative URLs are not being applied through `dev`
https://screenshot.click/13-17-n7y6x-r93yb.mp4

[Bugfix] allow relative urls to apply during `app dev` sessions

---

.changeset/six-masks-jump.md
packages/theme/src/cli/utilities/theme-environment/dev-server-session.ts
packages/theme/src/cli/utilities/theme-environment/storefront-session.test.ts
packages/theme/src/cli/utilities/theme-environment/storefront-session.ts

Handles migration of storefront_digest to essentials cookie.

Handles migration of storefront_digest to essentials cookie

---

.changeset/rotten-ties-flash.md
.changeset/wild-moles-help.md
packages/app/src/cli/api/graphql/business-platform-organizations/generated/types.d.ts
packages/app/src/cli/services/generate/extension.test.ts
packages/app/src/cli/services/generate/extension.ts
packages/app/src/cli/services/import-extensions.test.ts
packages/app/src/cli/services/import-extensions.ts
packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts

Cherrypicked commits from:
- [Fix URL generation for release message](https://github.com/Shopify/cli/pull/6325)
- [Fix UID generation for new extensions](https://github.com/Shopify/cli/pull/6320)
- [Better handling on import-extensions with existing folder](https://github.com/Shopify/cli/pull/6326)
- [Update generated GraphQL files](https://github.com/Shopify/cli/pull/6324)

[Stable] Port some bugfixes for 3.84.1

---

.changeset/twelve-ravens-fail.md
packages/app/src/cli/services/deploy.ts

Dont delete .env files after the first deploy to dev dash

---

.changeset/lemon-boxes-impress.md
packages/app/package.json
packages/theme/package.json
pnpm-lock.yaml

Back-port https://github.com/Shopify/cli/pull/6428

[3.85] Bump Shopify/theme-tools packages

---

packages/cli-kit/src/public/node/error-handler.test.ts
packages/cli-kit/src/public/node/error-handler.ts

Cherrypick commits from https://github.com/Shopify/cli/pull/6446

[stable] Add slice_name to error handler

---

packages/cli-kit/package.json
packages/cli-kit/src/public/node/error-handler.ts
pnpm-lock.yaml

Apply project root fixes
