Shopify/cli

.changeset/fair-buckets-beam.md, packages/cli-hydrogen/src/cli/services/eslint.test.ts, packages/cli-hydrogen/src/cli/services/eslint.ts, packages/cli-hydrogen/src/cli/services/info.ts
Adds TypeScript support in `hydrogen add eslint` command, meaning that if we detect a project with TypeScript is running this command, we will automatically configure the eslintrc to extent the `plugin:hydrogen/typescript` config.
- Adds a condition on the `app.language` key, pushing the `plugin:hydrogen/typescript` into the `extends` of the projects eslintrc file.
- Adds tests for this feature as well as back-fills tests for this command.
```
dev shopify hydrogen add eslint --path PATH
```
Run the above command, where `PATH` is the path to a typescript hydrogen project. (for example `../hydrogen/templates/hello-world`)
And then check the eslintrc file in that project and make sure it has:
```
module.exports = {
extends: ['plugin:hydrogen/recommended', 'plugin:hydrogen/typescript'],
}; …
```
=> `hydrogen add eslint` TypeScript support

packages/app/src/cli/prompts/dev.ts, packages/app/src/cli/services/environment/identifiers.ts, packages/cli-kit/src/output.ts, packages/cli-kit/src/session.ts
The success message after scaffolding an extension has an extra period after the exclamation mark ([screenshot](https://screenshot.click/16-31-mnk2n-97o8c.png))
It removes the trailing period that appears in the extension scaffolding success message.
- scaffold an extension to see the success message
=> Remove trailing period that appears in the extension scaffolding success message

.changeset/afraid-panthers-invent.md, packages/cli-hydrogen/src/cli/commands/hydrogen/info.test.ts, packages/cli-hydrogen/src/cli/models/hydrogen.test.ts, packages/cli-hydrogen/src/cli/services/info.test.ts, packages/cli-hydrogen/src/cli/services/info.ts
This PR adds validation for the eslint set up of a hydrogen project by asserting that if `eslint` is installed, that `eslint-plugin-hydrogen` is also install. I imagine us expanding greatly on the logic here to do more granular checks, this PR is just setting up the ground work and backfilling tests so we can build on this.
Run `dev shopify hydrogen info` in a project that has `eslint` but not `eslint-plugin-hydrogen` and you should see an error.
@Shopify/hydrogen
=> Show error when ESLint is not configured correctly

.changeset/loud-carrots-flow.md, packages/app/package.json
As part of [this effort](https://github.com/Shopify/shopify-cli-next/pull/543) to loose version requirements and stop using peer dependencies, I forgot to move the `@shopify/cli-kit` dependency of `@shopify/app` to the `dependencies` group in the `package.json`.
I'm making `@shopify/cli-kit` a `dependency` of `@shopify/app`. This should mitigate the issues trying to create an app with `pnpm`.
=> Turn `@shopify/cli-kit` into a `dependency` of `@shopify/app`

.github/workflows/shopify-cli.yml
Acceptance tests are slow by nature and they are currently taking a lot of time from our CI quota because we run them in all the OSs that we support. GitHub prices Windows and macOS builds more expensive than Linux ones.
I'm adjusting the CI workflow to run acceptance tests:
- Only in Linux for PRs and branches.
- In all the OSs for commits in `main`.
CI should pass.
=> Only execute acceptance tests on Linux

.changeset/bright-rocks-yawn.md, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/urls.test.ts, packages/app/src/cli/services/dev/urls.ts, packages/app/src/cli/services/environment.test.ts, packages/app/src/cli/services/environment.ts, packages/cli-kit/src/api.ts, packages/cli-kit/src/api/identity.ts, packages/cli-kit/src/session/exchange.ts, packages/cli-kit/src/session/validate.test.ts, packages/cli-kit/src/session/validate.ts, packages/features/features/hydrogen.feature
There is a weird case where an Identity token would become invalid and any attempt to exchange it for app tokens will fail.
We need to check if the identity token is valid before using the session and handle better any possible error.
Fixes https://github.com/Shopify/cli/issues/67
Fixes https://github.com/Shopify/shopify-cli-planning/issues/269
- When calling `ensureAuthenticated...` validate that the identity token is still valid using the new introspection query
- If not, force a full auth.
- If for some reason this validation is passed but after trying to exchange the token we still receive the error: show a better error message.
Unfortunately there is no way (at least that I know of) to reproduce this issue in a real case scenario, but you can invalidate your identity tokens manually …
=> Fix error when exchanging identity tokens

.changeset/popular-pants-behave.md, packages/cli-hydrogen/package.json, yarn.lock
There have been a lot of fixes to mini-oxygen. The last release was 3 months ago (April 5).
1. Setup a hydrogen project: `npm init @shopify/hydrogen`
2. From the shopify cli directory, run `dev shopify hydrogen preview --path ../path-to-created-hydrogen-project`
=> Update mini-oxygen to the latest

.changeset/six-laws-vanish.md, packages/cli-kit/src/analytics.test.ts, packages/cli-kit/src/analytics.ts, packages/cli-kit/src/environment/local.test.ts, packages/cli-kit/src/environment/local.ts, packages/cli-main/package.json, packages/cli-main/src/hooks/prerun.ts
Fixes https://github.com/Shopify/shopify-cli-planning/issues/272
- Adds a prerun hook to start a timer before running a command
- Calculate the total time when the command finishes and send the right start time and total time
- Comment out [this line](https://github.com/Shopify/shopify-cli-next/blob/8d24d8311e8c4a07161f932ffef1e5762b589363/packages/cli-main/bin/dev.js#L5) to disable debug mode
- `yarn shopify app info --path fixtures/app`
=> Add total time to analytics reports

.changeset/tricky-goats-jam.md, packages/app/src/cli/services/dependencies.test.ts, packages/app/src/cli/services/dependencies.ts, packages/app/src/cli/services/dev/select-store.ts, packages/app/src/cli/services/environment.ts, packages/app/src/cli/services/scaffold/extension.ts, packages/cli-hydrogen/src/cli/services/build.ts, packages/cli-hydrogen/src/cli/services/eslint.ts, packages/cli-hydrogen/src/cli/services/tailwind.ts, packages/cli-kit/src/output.ts, packages/cli-kit/src/ruby.ts, packages/cli-kit/src/ui.ts, packages/create-app/src/services/init.ts, packages/create-hydrogen/src/services/init.ts
Listr output isn't reflected in the logfile, which makes it hard to understand what logs are associated with which steps.
Wraps created listrs in a function that subscribes to progress/rendering updates and figured out what steps to log out. It's a bit hacky but seems to work, and there doesn't seem to be a cleaner solution short of creating our own entirely new custom renderer.
Run anything with Listr and watch the logfile.
=> Write Listr output to logs

packages/app/package.json, packages/cli-hydrogen/package.json, packages/cli-kit/package.json
With the move from `rollup` to `tsc` we forgot to move `devDependencies` to `dependencies` to make sure they get installed on the user-side. Without this change, development and tests pass, but the CLI will fail at runtime when users install it.
Move the production dependencies to `dependencies`.
=> Move devDependencies to dependencies

packages/app/package.json, packages/app/tsconfig.build.json, packages/cli-hydrogen/package.json, packages/cli-hydrogen/tsconfig.build.json, packages/cli-kit/package.json, packages/cli-kit/tsconfig.build.json, packages/cli-main/package.json, packages/cli-main/tsconfig.build.json, packages/create-app/package.json, packages/create-app/tsconfig.build.json, packages/create-hydrogen/package.json, packages/create-hydrogen/tsconfig.build.json, packages/theme/package.json, packages/theme/tsconfig.build.json
I noticed with the recent replacement of Rollup with `tsc`, `build` also outputs the `.test.ts` files into the `dist` directory.
Since excluding the `test.ts` files from the `tsconfig.json` would yield to the IDE not assisting with types in test files, I created a separate `tsconfig.build.json` file in each package and adjusted the `build` script to use that configuration file instead.
My first approach to solve this was to use a flag, for example `--exclude`, but the `tsc` CLI doesn't support excluding via flags.
Run `yarn build `and check that there are no `.test.js` files in the `dist/` directory.
=> Exclude tests when building for distribution

.changeset/perfect-rats-retire.md, packages/cli-hydrogen/src/cli/services/build.ts, packages/cli-hydrogen/src/cli/services/dev.ts
There are many errors thrown by Vite that are reported as bugs to Bugsnag.
I'm wrapping the Vite build promise in a `try/catch` to map the errors to aborts.
Try to build a Hydrogen storefront project that doesn't compile, for example due to a broken import.
=> Report Vite build errors as aborts

.github/workflows/shopify-cli.yml
We've had many CI builds failing due to yarn install taking too long.
Extends the timeout from the 30-second default to 5 minutes. According to [this](https://github.com/yarnpkg/yarn/issues/8242#issuecomment-661881292) it should be a good enough workaround, as the problems are likely caused by the filesystem of Windows/Mac being significantly slower than Linux, so it needs some extra time.
CI
=> Increase yarn timeout to handle slower CI installs on Windows/Mac

.changeset/strange-pots-jump.md, packages/cli-kit/src/api/identity.ts
After releasing https://github.com/Shopify/cli/pull/70, we are now trying to validate the Identity token, but we are using Node's fetch, [which is only available after Node 18](https://nodejs.org/en/blog/announcements/v18-release-announce/#fetch-experimental), so it's failing for older versions:
`The identity token is invalid: ReferenceError: fetch is not defined`
And this is requiring a new login on every command.
Use the right fetch function from the cli-kit to support all the Node versions
`yarn dev` 2 times
=> Fix identity validation

.changeset/lazy-teachers-battle.md, packages/cli-kit/src/port.test.ts, packages/cli-kit/src/port.ts
Fixes #109
* Added a retrying implementation over the third party method that obtains a random port. Ocassionally that method seems to fail and raises an exception unhandled, so the execution of the command fails. The problem was solved executing the command again
I can't replicate the problem in my local environment, so unit tests were added to verify the implementation. Executing `shopify app dev` should never fails now due to the local port problem
=> Retrying implementation for obtaining a random port

packages/cli-kit/src/node/ruby.ts
Fixes https://github.com/Shopify/cli/issues/112
Bumping `theme-check` version to unblock `yarn deploy` (needed for checkout-ui-extension development)
This PR bumps the version of `theme-check` to the latest version, which does not fail when checking `theme-app-extensions` using `app` liquid drops.
=> Bumping theme-check version to 1.10.3

.vscode/settings.json
Before removing Rollup, when module identifiers didn't require to include the extensions, VSCode's auto-import behaviour aligned with what Rollup expected (i.e. module ids were added without extension). However, with the replacement for `tsc`, which requires the `.js` extension in the module identifiers, VSCode's auto-import behaviour broke.
I'm setting the necessary VSCode configuration to align with `tsc`.
Try to use the auto-import functionality.
=> Configure VSCode to add the `.js` extension automatically when auto-importing

.changeset/weak-humans-mix.md, packages/app/src/cli/services/dev/output.ts
Fixes https://github.com/Shopify/shopify-app-template-php/issues/237 
A line of code uses `btoa` which only works in the browser and is undefined in nodejs. 
This PR replaces that with a working code.
Removes `btoa` which is only available in the browser and replaces with `Buffer.from` which is the common approach to convert into a base64 string in node js
https://nodejs.org/api/buffer.html#bufferbtoadata
=> Replaces btoa to Buffer.from

.changeset/lazy-teachers-battle.md, .changeset/many-meals-fly.md, .changeset/quick-pandas-boil.md, .changeset/soft-students-refuse.md, .changeset/stale-cobras-boil.md, .changeset/weak-humans-mix.md, fixtures/app/CHANGELOG.md, fixtures/app/package.json, packages/app/CHANGELOG.md, packages/app/package.json, packages/cli-hydrogen/CHANGELOG.md, packages/cli-hydrogen/package.json, packages/cli-kit/CHANGELOG.md, packages/cli-kit/package.json, packages/cli-main/CHANGELOG.md, packages/cli-main/package.json, packages/create-app/CHANGELOG.md, packages/create-app/package.json, packages/create-hydrogen/CHANGELOG.md, packages/create-hydrogen/package.json
- [Retry system to obtain a random port](https://github.com/Shopify/cli/pull/117)
- [Improve performance when fetching shops](https://github.com/Shopify/cli/pull/103)
- [Upgrade theme check to 1.10.3](https://github.com/Shopify/cli/pull/113)
- [Improve error reporting to Bugsnag](https://github.com/Shopify/cli/pull/129)
- [Fix btoa issue for old Node versions](https://github.com/Shopify/cli/pull/116)
=> Release v3.1.0

.changeset/tasty-feet-wave.md, packages/app/package.json, packages/cli-hydrogen/package.json, packages/cli-main/package.json, packages/create-app/package.json, packages/create-hydrogen/package.json, packages/theme/package.json, yarn.lock
Until now we used a loose version requirement between all the packages and `@shopify/cli-kit`. This helps eliminate potential duplicates under `node_modules`, but requires following semver in `@shopify/cli-kit` and do major bumps when breaking changes are introduced. Unfortunately, detecting breaking changes is a human task in PR reviews and therefore very error-prone that might lead to runtime errors on the user side. The alternative model is to not follow semver, pin the version, and accept that some duplication might happen when developers add plugins.
Considering the size of the package and putting users' first, we've leaned towards accepting potential duplications but less risk of breaking users' setup.
I'm pinning the `@shopify/cli-kit` version from all the other packages.
=> Stop following semantic versioning in `@shopify/cli-kit` and pin the version from the dependent packages

packages/cli-kit/src/error.ts, packages/cli-kit/src/node/error-handler.ts, packages/cli-kit/src/ui.ts
There are still some error scenarios that are not handling gracefully and that lead to wrongly-formatted and classified errors.
=> More error handling fixes

.changeset/dirty-zoos-wait.md, packages/app/src/cli/services/dev/select-app.test.ts, packages/app/src/cli/services/dev/select-app.ts, packages/app/src/cli/services/dev/urls.test.ts
We are removing the need to provide URLs when creating a new app in the partner dashboard. The aligns the partners experience with the CLI's experience today. We were going to use the same placeholder URLs as the CLI but discovered that one of them points to a 404 page. 
We had a discussion and collected opinions on what a better placeholders could be ([thread 1](https://shopify.slack.com/archives/C036LL9T0NT/p1657554614844549), [thread2](https://shopify.slack.com/archives/C036LL9T0NT/p1657658050659049)) 
We have aligned on:
1. Placeholder app URL is `https:/example.com`
2. Placeholder redirection URLs are `https:/example.com/api/auth` (aligning on the NodeJS app template's OAuth URL conventions)
We have taken the initiative to apply them across the Partners Dashboard and CLI code bases. …
=> create app - updating placeholder app urls

bin/update-bugsnag.js, packages/cli-kit/src/error.test.ts, packages/cli-kit/src/error.ts, packages/cli-kit/src/node/error-handler.ts, packages/cli-kit/src/output.ts
Fixes Shopify/shopify-cli-planning#308
- Updated the Bugsnag source map uploader to tweak package folders to match their underlying name (i.e. `@shopify/cli`, not `packages/cli-main`)
- Don't follow source maps by default for all errors (partial reversion of https://github.com/Shopify/shopify-cli-next/pull/237 )
- And _do_ follow source maps when displaying an error's stack trace
Same as https://github.com/Shopify/cli/pull/185
Run a command that breaks. I tested by tweaking the info command to have an unexpected null:
=> 308 - source maps to plugins

.vscode/launch.json, dev.yml, packages/app/src/cli/utilities/extensions/cli.ts
Reduces friction for new developers by adding interactive debug configs and tying debug execution to the Go binary.
- Adds debugging configuration for commands that execute the Development Extension Server Go binary. Debug configurations are generalized and will display prompts where appropriate.
- Switches on the introduced `DEBUG_GO_BINARY` environment variable to launch the Delve (Go) debugger. This enables a (mostly) seamless transition from the JS/TS debugger to the Go debugger (requires `brew install delve`)
https://user-images.githubusercontent.com/4490738/180455487-e8c5bc25-8cae-47f2-8c4f-e069ecfb875e.mp4
1. Due to an incompatibility between Node.js v.18 and the node-sass dependency, it is necessary to manually *comment out* the [make build lines from …
=> Enhance Debug Capabilities w/ Go Binary

.changeset/light-apples-jump.md, packages/app/src/cli/utilities/app/http-reverse-proxy.ts
Initially we only supported 1 websocket through our reverse proxy (because of how it worked), this was the extensions websocket needed for updates and dev-console.
With the proxy refactor we can now easily support multiple websockets, basically 1 per route. So one for `/` and one for `/extensions`
Allow websockets in `/`, fixing the vite HMR issue
=> Allow WS connections to the app and not only extensions

README.md
This was a hassle when I first landed on this readme that there wasn't a docs page- I wanted information about a specific command and had to find it by trawling shopify.dev.
Thoughts on adding a link to that overview within the repository somewhere?
I have no opinion on where to include it or the copy, I just would like a link to be somewhere.
There's a link to how to create an app, but that only answers one specific query. Another link to the root of the docs page would be helpful.
=> Add a link to the docs

.changeset/smart-dodos-battle.md, packages/cli-kit/src/api/admin.test.ts, packages/cli-kit/src/api/admin.ts, packages/cli-kit/src/api/common.ts, packages/cli-kit/src/api/partners.test.ts, packages/cli-kit/src/api/partners.ts, packages/cli-kit/src/session.ts
I noticed that we [are reporting](https://app.bugsnag.com/shopify/cli/errors/62ac4e8ed3273c0008d0b78a?filters[event.since]=30d&filters[error.status]=open&filters[release.seen_in]=3.3.2) 5xx responses from the Partners' API as bugs to Bugsnag. That's not necessary because 5xx errors coming from the API are already tracked server-side.
I adjusted the logic to use an `Abort` error when the response status code is `5xx`.
=> Report 5xx responses from the Partners' API as Aborts

.github/workflows/shopify-cli.yml
Our CI pipeline [started failing](https://github.com/Shopify/cli/runs/7536501405?check_suite_focus=true) because the Bundler version that ends up getting installed in the environment is not compatible with the version required by the CLI to install all Ruby dependencies (e.g. theme-check and the Ruby CLI)
I'm adjusting the pipeline to fix the Bundler version that's being installed.
CI should pass
=> Fix continuous integration

packages/cli-kit/src/node/base-command.ts
This [recent work](https://github.com/Shopify/cli/pull/192) led to warnings when using the CLL in development because we try to register a Bugsnag hook without having initialized `Bugsnag`.
Since we don't initialize `Bugsnag` when in development, we need to take that into account when registering the hooks.
=> Don't register the hook if the ClI is running in debug

fixtures/app/extensions/checkout-ui/shopify.ui.extension.toml
When defining Metafields in the Admin, the app will auto-convert spaces in the metafield name to underscores in the proposed metafield key.  For example, a metafield named "My test metafield" will have a proposed namespace and key of `custom.my_test_metafield`.
This PR is just changing our default metafield config scaffolding for Checkout UI Extensions from dashes to underscores to better align with the "smart defaults" proposed by the Admin.
Changing dashes `-` to underscores `_` in the TOML config scaffolding for Checkout UI extensions.
=> Change dashes to underscores for metafields in Checkout UI Extension config scaffolding

.changeset/tough-jokes-dream.md, packages/app/src/cli/services/scaffold/extension.ts
Related https://github.com/Shopify/shopify-cli-extensions/pull/376
Fixes https://github.com/Shopify/shopify-cli-planning/issues/280
@ani-shopify [noticed](https://github.com/Shopify/shopify-cli-planning/issues/280) inconsistencies in the package manager being used. It turns out that the [extensions' binary](https://github.com/Shopify/shopify-cli-extensions/pull/376) is doing dependency installation on extension generation, and that's causing the inconsistencies. Since that's a responsibility of the CLI, I added an [interface](https://github.com/Shopify/shopify-cli-extensions/pull/376) to opt out from that behaviour, and the changes in this PR consume that interface to disable the behavior.
Fixing the inconsistent usage of package managers.
Once [this …
=> Use the same package manager throughout all the CLI workflows

.changeset/eighty-cameras-nail.md, packages/theme/src/cli/commands/theme/delete.ts, packages/theme/src/cli/commands/theme/dev.ts, packages/theme/src/cli/commands/theme/help-old.ts, packages/theme/src/cli/commands/theme/open.ts, packages/theme/src/cli/commands/theme/package.ts, packages/theme/src/cli/commands/theme/publish.ts, packages/theme/src/cli/commands/theme/pull.ts, packages/theme/src/cli/commands/theme/push.ts, packages/theme/src/cli/commands/theme/share.ts
Aligns 5 more theme commands with the new conventions.
Edits 5 simple commands to make them consistent with how we're making theme commands work:
1. `shopify theme share`
2. `shopify theme package`
3. `shopify theme publish`
4. `shopify theme delete`
5. `shopify theme open`
Also removes `_THEME` from the env variable names associated with theme commands. We don't do this in other areas of the CLI, so this brings themes into alignment with everything else.
Run the commands!
=> Clean Up Theme Lightweight Commands

.changeset/healthy-books-remain.md, packages/cli-hydrogen/src/cli/commands/hydrogen/dev.ts, packages/cli-hydrogen/src/cli/services/dev.ts
Fixes https://github.com/Shopify/cli/issues/226
New `open` flag for the `hydrogen dev` command. When `--open` is passed to this command, the app will automatically open in a browser window. The default value is false.
- Pull this branch
- Run `dev shopify hydrogen dev --path ../hydrogen/templates/hello-world`, note the app does not open in a browser window
- Run `dev shopify hydrogen dev --path ../hydrogen/templates/hello-world --open`, note the app opens in a browser window
@Shopify/hydrogen
=> hydrogen dev open flag

packages/cli-kit/src/node/ruby.ts, packages/theme/src/cli/commands/theme/delete.ts
Improving how theme commands are executed from CLI3.0, this PR fixes some bugs reported by @karreiro 
- Don't show an additional CLI3 error on terminal when CLI2 crashes. CLI2 has it's own errors and showing an extra CLI3 error doesn't add any value
- Add support for multiple IDs in the `delete` command
`yarn shopify theme pull -t 123` should only show a CLI2 error
`yarn shopify theme delete 123 234 345` will pass al IDs to be deleted (and tell you that they don't exists)
=> Themes: add multiple IDs to theme delete, don't show duplicated errors

.changeset/neat-schools-warn.md, dev.yml, packages/cli-kit/src/analytics.test.ts, packages/cli-kit/src/constants.ts, packages/cli-kit/src/environment/local.test.ts, packages/cli-kit/src/environment/local.ts, packages/cli-kit/src/node/base-command.ts, packages/cli-kit/src/node/cli.ts, packages/cli-main/bin/dev.js, packages/create-app/bin/dev.js, packages/create-hydrogen/bin/dev.js
While working with @alvaro-shopify on merging the `shopify-cli-extensions` projects we realized that the `SHOPIFY_CONFIG=debug` environment variable is misleading to represent a development environment. 
I'm renaming the variable to `SHOPIFY_ENV=development`, which aligns with the convention many projects follow.
Tests should pass on CI and you should be able to interact with the fixture project.
=> Rename SHOPIFY_CONFIG to SHOPIFY_ENV

configurations/tsconfig.json, packages/cli-kit/package.json, packages/cli-kit/src/plugins.ts, packages/cli-kit/src/plugins/tunnel.ts
In the process of migrating the ngrok tunnel to use hooks, we first need to define those hooks in cli-kit so that they can be the imported in any tunnel plugin.
Contributes to https://github.com/Shopify/shopify-cli-planning/issues/305
Add two new typed hooks:
- `tunnel_provider` for discoverability. Any plugin implementing this hooks means it can handle tunnels.
- `tunnel_start_${provider}` for execution. After discovering the plugins, each one will report what hook to use to start a tunnel, this hook is unique per plugin.
This approach allow us to have multiple tunnel plugins installed and decide at runtime which one we want to use for tunnelling depending on user input/selection without having incompatibilities.
Nothing to test yet
=> Define new hooks for tunnel plugins

packages/app/src/cli/services/scaffold/extension.test.ts, packages/app/src/cli/utilities/extensions/cli.test.ts, packages/app/src/cli/utilities/extensions/cli.ts, packages/ui-extensions-go-cli/bin/build.js, packages/ui-extensions-go-cli/shopify-extensions-debug
Acceptance tests [are failing](https://github.com/Shopify/cli/runs/7857264246?check_suite_focus=true) on Windows because the logic that runs the Go CLI from within the repository doesn't account for the fact that the output binary in Windows is suffixed with the `.exe` extension. The acceptance tests are failing with the error:
```
node: [DATA] 'D:\a\cli\cli\packages\ui-extensions-go-cli\shopify-extensions' is not recognized as an internal or external command,
[DATA] operable program or batch file.
```
I'm extending the logic to add the right extension based on the platform.
Try to run the `app` package unit tests or the acceptance tests from a Windows environment.
=> Fix ui-extensions-related tests on Windows

.changeset/mighty-crabs-raise.md, .vscode/launch.json, packages/app/src/cli/commands/app/scaffold/extension.ts, packages/app/src/cli/constants.ts, packages/app/src/cli/prompts/scaffold/extension.test.ts, packages/app/src/cli/prompts/scaffold/extension.ts, packages/app/src/cli/services/scaffold/extension.test.ts, packages/app/src/cli/utilities/extensions/template-configuration.test.ts, packages/app/src/cli/utilities/extensions/template-configuration.ts, packages/create-hydrogen/src/commands/init.ts, packages/features/features/app.feature, packages/features/steps/app.steps.ts
Fixes https://github.com/Shopify/shopify-cli-planning/issues/329
The go binary already supported passing an extension flavor that includes the word `typescript`, so we want to leverage that option to allow users to select typescript for ui extension templates.
I've added two new options to the extension flavor question:
- `Typescript React`
- `Typescript`
Run `dev fixture scaffold extension` and choose any of the new options. The file names will be either `ts` or `tsx`.
=> Add option to choose typescript templates for ui extensions

.changeset/red-seas-impress.md, packages/cli-kit/src/node/node-package-manager.test.ts, packages/cli-kit/src/node/node-package-manager.ts, packages/create-app/src/utils/template/npm.test.ts, packages/create-app/src/utils/template/npm.ts, packages/create-hydrogen/src/services/init.ts
Related: https://github.com/Shopify/cli/pull/320
Acceptance tests [uncovered](https://github.com/Shopify/cli/runs/7913938724?check_suite_focus=true) Yarn installation errors in Windows environments when it tries to concurrently access the global cache. 
I'm adjusting the app creation logic to limit the concurrency to one as recommended [here](https://github.com/yarnpkg/yarn/issues/7212) by other Yarn users. Some are experiencing it with newer versions of Yarn too so it seems that the issue is rooted in some core business logic of Yarn.
Acceptance tests should pass on Windows
=> Fix the installation of dependencies on app creation in Windows environments

.changeset/curvy-adults-wash.md, .changeset/shy-dryers-mate.md, .github/workflows/shopify-cli.yml, dev.yml, packages/app/src/cli/models/app/app.ts, packages/app/src/cli/utilities/extensions/cli.ts, packages/cli-hydrogen/src/cli/services/preview.ts, packages/cli-kit/src/file.ts, packages/create-app/src/services/init.ts, packages/create-app/src/utils/versions.ts, packages/features/features/app.feature, packages/features/steps/create-app.steps.ts
[Working on replacing Yarn with PNPM](https://github.com/Shopify/cli/pull/320) that the creation of apps with `pnpm` fails. PNPM fails the installation of peer dependencies are not declared as `dependencies` or `devDependencies` upstream in the graph. In our case, the UI extensions CLI depends on `@luckycatfactory/esbuild-graphql-loader`, which has `graphql` as a `peerDependency`.
I'm adjusting the creation logic to change PNPM's behaviour in the created project such that peer dependencies are installed by default. To prevent bugs like this to happen, I'm adding a short acceptance test that creates an app with an extension and tries to build it.
Acceptance tests should pass.
=> Add a simple test scenario to test the app creation with pnpm

packages/app/src/cli/services/dev/output.ts
The anchor tag to the theme app extensions page in the cli output is outdated, and doesn't take app devs to the correct location on the page.
Fixes the link.
=> Fix link to theme app extensions docs

packages/cli-kit/src/node/ruby.ts
Fixes https://github.com/Shopify/shopify-cli-planning/issues/343
We need to tell CLI2 that upgrade messages can be ingnored when we execute it from CLI3
Pass an env var to CLI2 which it will use to hide the message.
=> Pass env var to CLI2 to hide upgrade warning

packages/cli-hydrogen/src/cli/commands/hydrogen/deploy.ts, packages/cli-hydrogen/src/cli/services/deploy.ts, packages/cli-hydrogen/src/cli/services/deploy/config.integration.test.ts, packages/cli-hydrogen/src/cli/services/deploy/config.ts, packages/cli-hydrogen/src/cli/services/deploy/deployer.test.ts, packages/cli-hydrogen/src/cli/services/deploy/deployer.ts, packages/cli-hydrogen/src/cli/services/deploy/error.ts, packages/cli-hydrogen/src/cli/services/deploy/types.ts
Fix https://github.com/Shopify/oxygen-platform/issues/494
Simply added a health check step with a new flag called `skipHealthCheck` which defaults to false.
=> Added simple health check with incremental rollback

dev.yml
A Homebrew formula for installing pnpm 7.9.4 is not yet available and it causes `dev up` to fail.
I'm reverting the version to `7.9.3`. As soon as the formula is available we can revert this change.
=> Downgrade pnpm version used in the dev.yml

.vscode/launch.json, packages/ui-extensions-go-cli/.vscode/launch.json, packages/ui-extensions-go-cli/init-debug-session
The CLI and Go binary use different tech stacks, and hence, different debuggers. Previously, I set up a debug "pipeline" wherein the CLI Node process would kick off a remote Go debugger via shell script. This needs re-configuring as part of the merge of `shopify-cli-extensions` into `cli`.
Separating out launch configurations for the CLI and Go binaries. This is necessary because a given VS Code instance can only launch one debug config at a time. To debug the entire flow, a CLI config is necessary. The CLI then kicks a Go debugger and then transfers control to the Go binary. A second VS Code instance is then used to attach to the remote debugger. Note that, while this is technically a remote debug scenario, it is all performed on localhost.
1. Open two VS Code instances: One from the …
=> Fix post merge debug flows

.changeset/small-dots-try.md, packages/app/src/cli/services/dev/output.ts
- I'm part of a team (Core > Promote) working on 1P apps in a Discounts context
- we're starting to write docs and I'm on the lookout for 'small wins' and friction points
- this PR slightly reworks the display of App URLs to make them easier to see, and easier to copy and paste from console output
- adds keyword to header title ('shareable link')
- sets off most important information (app URL) with blank lines before and after
- moves less-important context to below the app URL
- run `yarn dev` in a CLI 3.0 app
=> Display App URL more clearly  in console output for easier copy & paste

packages/features/features/app.feature, packages/features/steps/create-app.steps.ts
Our acceptance tests did not test that we were building extensions.  Now they do.
Issue: https://github.com/Shopify/shopify-cli-extensions/issues/373
Update the acceptance test for building an app.  Previously this test simply checked that the build command didn't throw an error.  Now it checks that the UI extensions are built.  We thought it was better to add this to the existing test because we didn't see a way to test the extension functionality without duplicating the existing test.
We do this by checking that there is a main.js file for each UI extension, in the location we expect.
We did not add any tests for the dev command.  The dev command has interactive prompts, which don't work with the current tests setup.  We will chat with Pedro to see what we can do here and understand …
=> Add acceptence test code to check build command builds extensions

.changeset/honest-rules-compete.md, fixtures/app/README.md, packages/app/src/cli/commands/app/dev.ts, packages/app/src/cli/services/dev/output.ts, packages/app/src/cli/services/environment.ts, packages/cli-kit/src/api/graphql/update_draft.ts
Fixes https://github.com/Shopify/shopify-cli-planning/issues/318
This PR changes how we refer to the Partners Dashboard. We were using the term "Shopify Partners" when referring to it.
=> Change Partners Dashboard wording

.changeset/thirty-cooks-drum.md, fixtures/app/web/frontend/package.json, fixtures/app/web/package.json, package.json, packages/cli-kit/package.json, packages/cli-main/package.json, packages/cli-main/project.json, packages/cli-polaris/package.json, packages/cli-polaris/project.json, packages/cli-polaris/src/cli/commands/polaris/migrate.ts, packages/cli-polaris/src/cli/services/migrate.test.ts, packages/cli-polaris/tsconfig.build.json, packages/cli-polaris/tsconfig.json, packages/cli-polaris/vite.config.ts, packages/ui-extensions-cli/package.json, packages/ui-extensions-dev-console/package.json, packages/ui-extensions-server-kit/package.json, packages/ui-extensions-test-utils/package.json, workspace.json, yarn.lock
Related to https://github.com/Shopify/polaris/pull/6852
This allows Shopify app developers to run migrations for Polaris on their codebase, helping them update and stay on the latest version of Polaris.
Available commands:
- `shopify polaris migrate <migration> <path>` – performs a codemod migration related to Polaris components, styles, or other assets
This PR creates a new plugin for the Shopify CLI so Polaris-related tooling can be leveraged from within the same CLI.
I tested using yalc in order to get access to the `@shopify/polaris-migrator` package, but this will be published soon on the npm registry.  _coming soon ✨_
Once published, you can test by running the following commands:
```sh
dev up
dev build
dev shopify polaris migrate <migration> <path>
dev shopify polaris migrate …
```
=> Add `@shopify/cli-polaris` to run Polaris tooling on Shopify apps

.changeset/strong-comics-exist.md, packages/cli-hydrogen/src/cli/services/build.test.ts, packages/cli-hydrogen/src/cli/services/build.ts
Added upon request from @lynchv.
In general, I think we begin to polish some of what we output in the terminal. This is one step toward that effort and this PR may help address this issue as well https://github.com/Shopify/cli/issues/318.
This PR uses the global `verbose` flag in the build command to determine if we should output the list of build files or not. 
1. run ` dev shopify hydrogen build --path ../hydrogen/templates/hello-world --verbose` and you should see something like this:
2. run `dev shopify hydrogen build --path ../hydrogen/templates/hello-world` and you should see something like this:
=> Add verbose flag to hydrogen build

docs/release.md
We extended the release process recently to open a PR in the Shopify Homebrew Formulas repository but forgot to update release documentation.
I'm updating the documentation to mention that the PR opened by the deployment should be merged.
=> Add an additional step to the release docs for merging the formula PR

.changeset/bright-phones-mate.md, packages/ui-extensions-go-cli/build/build.go
Fixes #365
Build command was not logging detailed error due to a bug.
WHAT is this pull request doing?
- Logs the output of the command.CombinedOutput method which is mixing both the stderr and stdout
- Create a [checkout UI extension](https://shopify.dev/apps/checkout/delivery-instructions/getting-started#step-1-scaffold-a-new-extension) with a syntax error like the following in src/index.js:
- Run yarn dev. This shows the error as expected: src/index.js:8:23: error: Expected ";" but found "error"
- Run yarn build. This shows the error as expected: src/index.js:8:23: error: Expected ";" but found "error"
=> Fixed bug by logging the shared output (stderr & stdout are combined)

.vscode/settings.json
I noticed that the configuration of the VSCode ESLint plugin was wrong and that was causing misbehaviours while editing source code.
The `eslint.workingDirectories` attribute has to be a glob pointing to the directories containing ESLint projects.
Pull the changes, edit a file and add a line of code that makes ESLint's validation fail. For example:
```
const name: any = "xxx"
```
ESLint should flag it and if you save the file, it should auto-fix it.
=> Fix the VSConfiguration of the ESLint plugin

nx.json
The [release pipeline](https://shipit.shopify.io/shopify/cli/production/deploys/1786802) is failing when Nx tries to obtain the Go version to calculate the projects' hashes for caching purposes.
Since we rarely change the Go version and we'll remove the dependency with Go in the near future we can drop the Go version from the list of inputs that are considered when calculating the hash. 
CI should pass
=> Don't use the Go version as a runtime cache input

shipit.production.yml
The [deploy with shipit](https://shipit.shopify.io/shopify/cli/production/deploys/1786884) is failing, but it doesn't show much information.
Adds verbose mode to find out why it's failing
shipit
=> Enable verbose mode for changeset publish

shipit.production.yml
The [deploy with shipit](https://shipit.shopify.io/shopify/cli/production/deploys/1786884) is failing because the extensions build, run as part of the prepack task of cli/app, is missing the go binary path.
Adds the go binary to the path before running `changeset publish`
shipit
=> Fix shipit configuration

packages/ui-extensions-go-cli/create/templates/shared/product_subscription/react.js
This PR fixes product subscription react template. Generally, it works right now. However, as soon as we add hook to App component, it breaks. The reason is because the `render` function expects a function returning a React element.
Fix the render call and use `useExtensionApi` to query for `extensionPoint`.
N/A
=> Fix product subscription react template

packages/ui-extensions-server-kit/README.md
More surface areas are using the `@shopify/ui-extensions-server-kit` and we have been missing a README file for a long time.
Add a README to explain how to use the `@shopify/ui-extensions-server-kit`
N/A
~- [ ] I've considered possible cross-platform impacts (Mac, Linux, Windows)~
~- [ ] I've considered possible [documentation](https://shopify.dev) changes~
=> ui-extensions-server-kit: add README

nx.json
This [recently-merged PR](https://github.com/Shopify/cli/pull/388) assumed the path in the `runtimeCacheInputs` property of `nx` has to be relative o the workspace directory but it turns out is relative to either the project or the workspace.
I tried using the `{workspaceRoot}` variable as is supported in other attributes but Nx doesn't replace it. A temporary solution that I found works is having the command for the workspace with a fallback for projects. I'll open an issue in the Nx repository to see if there's a better way to address this.
Run `yarn test` in the repository root in any package under `packages`. The command must succeed.
=> Fix using the wrong path with cache-inputs.js

.github/workflows/shopify-cli.yml
As stated [here](https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value), `github.head_ref` is only present in PRs. That causes the concurrency group to be `shopify-cli-` in `main` builds and that leads to cancellation of builds for some commits.
We don't want to cancel CI builds in `main` when new PRs land because that makes it hard to trace back which merges might have caused `main` to get red and revert it. 
CI should pass in this PR.
=> Not cancel CLI runs in `main` when new PRs land

.changeset/brown-ears-drum.md, packages/cli-kit/src/node/ruby.ts, packaging/src/shopify-cli@3.rb.liquid
The Homebrew formula for installing the CLI globally has an issue that causes the installation to fail.
I'm interpolating `Formula["ruby"].opt_bin` in the script content.
1. Run `brew upgrade`.
2. Edit the formula `/opt/homebrew/Library/Taps/shopify/homebrew-shopify/shopify-cli@3.rb`.
3. Move the fixes in this PR to that Ruby file.
4. Run `brew install shopify-cli@3`
=> Fix the Homebrew formula

.github/workflows/shopify-cli.yml
In https://github.com/Shopify/cli/pull/402 I tried to setup the CI to ignore markdown files, but it was added to the `push main` section instead of `pull_request`.
Example of the CI running after adding only a changelog file: https://github.com/Shopify/cli/pull/408#commits-pushed-78be5e8
Fix the workflow file to ignore md files on pull requests.
Merge and try again
=> Skip CI on PR for markdown files

packages/cli-main/package.json
I noticed we are not currently loading the `@oclif/plugin-plugins` plugin in `cli-main` and therefore CLI users don't have access to the `shopify plugins` API for managing their plugins. Is there are a reason for it?
I'm adding the plugin to the list of plugins that get loaded with the CLI.
`yarn shopify plugins` should show the help.
=> Load the `@oclif/plugin-plugins` plugin in `cli-main`

packages/app/src/cli/prompts/dev.test.ts, packages/app/src/cli/prompts/dev.ts, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/output.ts, packages/app/src/cli/services/dev/urls.test.ts, packages/app/src/cli/services/dev/urls.ts, packages/app/src/cli/services/environment.ts, packages/cli-kit/src/store.ts
As part of the `dev` flow revamp, this PR contributes to the "make localhost default" by adding a prompt when you select to use tunnels.
- Add a prompt to confirm tunnel configuration if a tunnel will be created, this allows the user to "always" use that tunnel, or configure it to ask everytime.
- Add more tests
- Some copies improvements
- ⚠️ Some copies are temporary for this iteration and will change once the full new flow is implemented.
⚠️ ❗ This PR is pointing to `localhost-urls` branch. This work complements the work in that branch, that work is already approved but can't be merged yet. But this PR can be merged against that branch and next week we can merge everything to main
- Execute `dev` with tunnel, either via flag or having extensions.
- You should see the new prompt. 
- If …
=> Localhost & tunnel prompts

.changeset/polite-carpets-roll.md, packages/app/src/cli/commands/app/deploy.ts, packages/app/src/cli/services/deploy.ts, packages/app/src/cli/services/environment.ts
We have it for app dev. It makes sense to add it here, too.
Also serves as a critical workaround in [1 known case](https://github.com/Shopify/cli/issues/317#issuecomment-1232143625).
And eventually will allow users to automate deploys to multiple Partner admin apps from the same codebase.
Adds a flag `--api-key` to `shopify app deploy`. The implementation is nearly identical to the same flag for `shopify app dev`.
`shopify app deploy` without this flag. Then, `shopify app deploy --api-key=WHATEVER` to deploy to another app using its API key. Then `shopify app deploy` and note that your change sticks.
Would be good to check this is used, but I think down the road we'll see tons of use as we roll out more flag automation.
=> Add `--api-key` flag to `shopify app deploy`

.changeset/itchy-cars-grab.md, packages/cli-kit/src/node/cli.ts, packages/cli-kit/src/node/error-handler.test.ts, packages/cli-kit/src/node/error-handler.ts, packages/cli-kit/src/node/hooks/init.ts, packages/cli-kit/src/node/ruby.test.ts, packages/cli-kit/src/node/ruby.ts, packages/cli-kit/src/store.ts, packages/theme/package.json, packages/theme/src/cli/commands/theme/pull.ts, yarn.lock
The init hook for the theme package is not working correctly when installed through Homebrew, causing the CLIKitStore to fail to initialize:
The Homebrew installation is installing two Shopify libraries under node_modules: cli and theme, both of them containing a copy of cli-kit. And for some reason, the current init hook (`@shopify/cli-kit/node/hooks/init`) is calling the file from the cli package instead of theme.
- Remove the explicit initialization at the start for CLIKitStore and Bugsnag, and initialize them when used (only the first time). Both errors from the screenshot above should be gone.
- Remove `--store` from the flags passed to CLI2 for the pull command, as it's not required and throws an error now (`The option --store is not supported.`)
- Remove the RubyGems validation, as …
=> Fix store and Bugsnag initialization for Homebrew

packages/theme/src/cli/services/info.ts
After merging the PR for theme info command I introduced an issue that should've been picked up by CI but didn't.
- Make sure to read the store from `conf.getThemeStore()` and show "Not configured" if there is no saved store.
- Can't read the store from `getThemeStore()` directly because that method throws if there is no store and is intended to ensure that there a store either in flags or cached.
=> Fix load store from theme info

bin/package.js
The displayed URL is from the GitHub JSON API. Not super useful if you'd like a big green button to merge your PR.
Changes the displayed URL to be the URL you'd actually see in your browser when navigating to the PR page.
This code was written based on local testing with Octokit.
```js
const { request } = require("@octokit/request")
const result = await request("GET /repos/{owner}/{repo}/pulls/{id}", {owner: "Shopify", repo: "cli", id: 430})
result.url // 'https://api.github.com/repos/Shopify/cli/pulls/430'
result.data.html_url // 'https://github.com/Shopify/cli/pull/430'
```
=> Display correct usable HTML URL after opening Homebrew PR

.changeset/rich-islands-beg.md, packages/app/src/cli/services/environment/id-matching.test.ts, packages/app/src/cli/services/environment/id-matching.ts, packages/app/src/cli/services/environment/identifiers.test.ts, packages/app/src/cli/services/environment/identifiers.ts, packages/cli-kit/src/common/result.test.ts, packages/cli-kit/src/common/result.ts
Fixes https://github.com/Shopify/shopify-cli-planning/issues/312
Follow-up: https://github.com/Shopify/cli/pull/319
- New `Result` type added. Used as a return type to indicate the operation has suceded or should return an error
- Three utility methods for creating an ok and error response, and to get the value of an ok response or throw a fatal exception (Bug, Abort, AbortSilent) otherwise
- Used new type in `automaticMatchmaking`
TBD: It also should be added to `manualMatchIds` in case the new type is approved
- Run `yarn shopify app deploy` with a remote app that matches local extensions and then with another that does not match to see the abort error message
=> New Result type for handling errors

packages/cli-kit/src/port.ts
Output of `shopify app dev --verbose`:
Before patch:
```
Getting a random port...
Random port obtained: [object Promise]
```
After patch:
```
Getting a random port...
Random port obtained: 39097
```
Output of `shopify app dev --verbose` was not correct.
Fixes the output of `shopify app dev --verbose`.
Run `shopify app dev --verbose`.
This doesn't need measurement, e.g. a linting rule or a bug-fix
=> [Fix] Add missing await for call to retryOnError().

packages/cli-kit/src/node/node-package-manager.ts, packages/cli-main/src/cli/commands/upgrade.ts
The TODO says it all. We should have a straightforward "upgrade without thinking" function which can be called by an "upgrade only certain things" function, not the other way around.
I meant to do this some time ago, especially given it broke `shopify upgrade` right at the Summer Edition launch, but I never got back to it. UNTIL NOW.
Refactors the update code to have functions' dependencies point in the right direction.
Run `shopify upgrade` or generate an extension on an existing project.
=> Refactor structure of package updates functions

.eslintignore, packages/app/package.json, packages/app/src/cli/models/app/app.test-data.ts, packages/app/src/cli/models/app/extensions.ts, packages/app/src/cli/models/app/loader.ts, packages/app/src/cli/services/build.ts, packages/app/src/cli/services/build/extension.ts, packages/app/src/cli/services/deploy/bundle.ts, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/extension.ts, packages/app/src/cli/services/environment.test.ts, packages/app/src/cli/services/environment/id-manual-matching.test.ts, packages/app/src/cli/services/environment/id-matching.test.ts, packages/app/src/cli/services/environment/identifiers.test.ts, packages/app/src/cli/services/extensions/bundle.test.ts, packages/app/src/cli/services/extensions/bundle.ts, packages/app/src/cli/services/web.ts, packages/app/src/cli/utilities/app/http-reverse-proxy.test.ts, packages/app/src/cli/utilities/app/http-reverse-proxy.ts, packages/app/src/cli/utilities/extensions/configuration.test.ts, packages/app/src/cli/utilities/extensions/configuration.ts, packages/cli-kit/src/error.ts, packages/features/steps/create-app.steps.ts, packages/ui-extensions-go-cli/api/api.go, packages/ui-extensions-go-cli/main.go, yarn.lock
Continuation of: https://github.com/Shopify/cli/pull/423
In the aim of removing the unnecessary indirection of having some UI extensions' business logic in Go, I'm moving the `build` workflow from the extensions' CLIs into the `@shopify/app` package.
You can try to build the fixture or any other app.
=> Move the UI extensions' build logic from Go to Node

packages/ui-extensions-server-kit/src/ExtensionServerClient/types.ts
We introduced a new surface [here](https://github.com/Shopify/shopify/pull/362279) in order to support the [returns mission](https://vault.shopify.io/gsd/projects/23677).
In order to improve the dev experience we are now integrating `ui-extensions-server-kit` and the surface is missing.
This is part of [this issue](https://github.com/Shopify/core-issues/issues/43741)
paired with @Safi1012 
Add a surface to the `Surface` type in `ui-extensions-server-kit`
They can't be tested in isolation but nothing should break.
=> Add customer-accounts surface to ui-extensions-server-kit

.changeset/cyan-tables-retire.md, packages/app/src/cli/models/app/app.test-data.ts, packages/app/src/cli/models/app/app.ts, packages/app/src/cli/models/app/loader.test.ts, packages/app/src/cli/models/app/loader.ts, packages/app/src/cli/services/dev/select-app.test.ts, packages/app/src/cli/services/environment.test.ts, packages/app/src/cli/services/environment/identifiers.test.ts, packages/app/src/cli/services/info.test.ts, packages/app/src/cli/services/web-env.test.ts
Resolves https://github.com/Shopify/shopify-cli-planning/issues/310
Documentation PR: https://github.com/Shopify/shopify-dev/pull/26029
Some partners [reported](https://shopify.slack.com/archives/C03NT4BP8N9/p1661967429402539) that the opinion around where extensions should be located within an app is too strong and they can't adopt it easily due to how they are organizing extensions in multiple repositories.
I'm adding support for a new attribute in the `shopify.app.toml`, `extension_directories`, that's an array of glob expressions pointing to directories containing extensions:
```toml
extension_directories = [
"my_other_extension",
"other_directory/extensions/*"
]
``` 
The default value of the attribute is `extensions/*`.
1. Rename the `extensions` directory in the `fixtures/app` …
=> Add `extension_directories` attribute to `shopify.app.toml`

packages/app/src/cli/utilities/extensions/configuration.ts, packages/ui-extensions-server-kit/src/context/ExtensionServerProvider.test.tsx, packages/ui-extensions-server-kit/src/testing/extensions.ts, packages/ui-extensions-server-kit/src/types.ts
We introduced a categories [here](https://github.com/Shopify/shopify/pull/362279) in order to support the [returns mission](https://vault.shopify.io/gsd/projects/23677).
In order to improve the dev experience we are now integrating `ui-extensions-server-kit` and the neither categories nor extension points are exposed on the `ExtensionPayload` type.
This is part of [this issue](https://github.com/Shopify/core-issues/issues/43741)
paired with @Safi1012 
Expose the categories and extensionPoints properties in the `ExtensionPayload` type - both are optional.
They can't be tested in isolation but nothing should break.
=> Expose extension points and categories in ExtensionPayload

.github/PULL_REQUEST_TEMPLATE.md, docs/release.md
We need a way to remember additional steps after releasing, like merging documentation. Example: https://github.com/Shopify/cli/pull/376
Adds the same flow we had in shopify-cli:
- Adds a new section to the PR template
- Adds a step in the release instructions to check post-release actions
N/A
=> Add post-release steps to PR template and release doc

.changeset/sweet-lobsters-check.md, packages/cli-hydrogen/package.json, yarn.lock
This PR upgrades the @shopify/mini-oxygen package in the hydrogen-cli.
Related https://github.com/Shopify/mini-oxygen/pull/187
=> Upgrade mini-oxygen in hydrogen-cli

.changeset/giant-bikes-dream.md, packages/cli-kit/src/constants.ts, packages/cli-kit/src/node/cli.ts, packages/cli-main/bin/run.js, packages/cli-main/src/index.ts
Allows someone who's installed the shopify CLI package globally to run `shopify` instead of `npm/yarn/pnpm shopify`. This should help avoid users getting confused as we will shortly be supporting a globally installed CLI for certain use cases.
Since `run.js` is the entrypoint to the CLI, we hook in there and check if the running script is the same we'd expect based on `npm list` in the current working directory.
If it's the same script, we can just move on as usual.
If `npm list` fails, it's likely because you're not inside a directory with a `package.json` or [your dependencies are messed up](https://github.com/npm/npm/issues/17624#issuecomment-313294516), and we just go on using the current CLI.
If you're running a different script, we run the correct `run.js`, handing over `argv` as is …
=> Allow running `shopify` instead of `npm/yarn/pnpm shopify`

.changeset/spicy-parrots-reflect.md, packages/app/src/cli/models/organization.ts, packages/app/src/cli/prompts/dev.test.ts, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/extension.ts, packages/app/src/cli/services/dev/fetch.test.ts, packages/app/src/cli/services/dev/select-app.test.ts, packages/app/src/cli/services/env/pull.test.ts, packages/app/src/cli/services/env/show.test.ts, packages/app/src/cli/services/environment.test.ts, packages/app/src/cli/services/environment.ts, packages/app/src/cli/services/info.test.ts, packages/app/src/cli/utilities/extensions/configuration.test.ts, packages/app/src/cli/utilities/extensions/configuration.ts, packages/cli-kit/src/api/graphql/create_app.ts, packages/cli-kit/src/api/graphql/find_app.ts, packages/cli-kit/src/api/graphql/find_org.ts, packages/ui-extensions-go-cli/core/core.go, packages/ui-extensions-go-cli/core/core_test.go
Fixes https://github.com/Shopify/checkout-web/issues/13297
Fixes https://github.com/Shopify/checkout-web/issues/13298
Shopify is introducing [stricter controls](https://shopify.dev/apps/store/data-protection/protected-customer-data) for accessing customer data.  Since Checkout UI Extensions expose APIs which also access customer data, we are taking steps to implement similar protections.  This PR supports the use case of enabling Checkout to apply proper data protections when a Checkout UI Extension is being served from the CLI via `yarn dev`.
- `packages/cli-kit/src/api/graphql/*.ts`
- Queries a newly-exposed field, `grantedScopes` from the Partners API
- `packages/app/src/cli/models/organization.ts`
- Adds the new field to the `OrganizationApp` model
- …
=> [Feature] Pass new permissions to apps during `yarn dev` to enable new functionality for Checkout UI Extensions

.changeset/twelve-fireants-deliver.md, packages/app/src/cli/commands/app/dev.ts, packages/app/src/cli/commands/app/generate/extension.test.ts, packages/app/src/cli/commands/app/generate/extension.ts, packages/app/src/cli/models/app/app.test-data.ts, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/theme-extension-args.test.ts, packages/app/src/cli/services/dev/theme-extension-args.ts, packages/app/src/cli/services/environment.test.ts, packages/app/src/cli/services/environment.ts, packages/cli-kit/src/node/ruby.test.ts, packages/cli-kit/src/node/ruby.ts
Fixes https://github.com/Shopify/shopify-cli/issues/2540.
This PR introduces the hot reload feature for theme app extension developers. It reuses the same development server that theme developers use, in the context of theme app extension development.
- Create an app
- Generate a theme app extension with `yarn shopify app generate extension --path <app_directory>`
- Run `yarn shopify app dev --path <theme_app_extension_directory>`
- Notice the CLI 3.x is running the `extension serve` command
Merge the documentation PR https://github.com/Shopify/shopify-dev/pull/26125.
=> Introduce theme app extensions support in the `app dev` command

.changeset/fresh-insects-heal.md, packages/app/src/cli/commands/app/generate/extension.ts, packages/cli-kit/src/analytics.ts
- New feature for overriding default command name was not working properly.
- Fixes command name overriding feature
- `generate` command sends `dev scaffold extension` like it was be doing by `scaffold` command previously
- Run the command `yarn shopify app generate extension --verbose` the command name  `dev scaffold extension` should be shown
=> Fixed analytics name overriding

.changeset/blue-boats-hug.md, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/theme-extension-args.test.ts, packages/app/src/cli/services/dev/theme-extension-args.ts, packages/app/src/cli/services/environment.test.ts, packages/app/src/cli/services/environment.ts
This PR applies fixes proposed by https://github.com/Shopify/cli/pull/370#discussion_r973151352 and https://github.com/Shopify/cli/pull/370#discussion_r973152222.
Also, it relies in the previous selected app.
This PR moves the fetch process of fetching the `adminSession` and `storefrontToken` to a more suitable place.
Also, it relies in the existing `apiKey` to create the theme app extension (in case it doesn't exist).
- Create an app
- Generate a theme app extension with` yarn shopify app generate extension --path <app_directory>`
- Run yarn `shopify app dev --path <theme_app_extension_directory>`
- Notice the CLI 3.x is running the extension serve command
- Run `dev --reset`
- Notice you won't be prompted more than once
Merge the documentation PR …
=> Apply fixes proposed on #370 + use previous selected app

.changeset/large-dodos-unite.md, packages/cli-main/bin/run.js, packages/features/lib/constants.ts
A recent refactoring in the executables led to a missing import that will cause the production version of the CLI not to work.
I'm adding the missing import.
1. `yarn build`.
2. `node packages/cli-main/bin/run.js` should run.
=> Add missing import that causes the production version of the CLI to fail

.changeset/breezy-spiders-explain.md, .github/PULL_REQUEST_TEMPLATE.md, docs/release.md, packages/cli-kit/src/session/validate.test.ts, packages/cli-kit/src/session/validate.ts
Fixes https://github.com/Shopify/cli/issues/500
I'm not able to reproduce the issue, but the logs shows:
```
The validation of the token for application/identity completed with the following results:
- It's expired: true
- It's been revoked: true
- It's invalid in identity: true
The current session is valid but needs refresh. Refreshing...
```
If the session is actually invalid, it doesn't need a refresh, but a full re-authentication.
- Ensure full re-auth when tokens are invalid or revoked
- Fix the PR template
- Improve some links in the release documentation
Not sure how to reproduce without tweaking the code. But CI must work and also regular authentication:
- `yarn shopify auth logout`
- `yarn dev`
=> Fix authentication issue when token is expired and invalid/revoked

packages/cli-main/src/cli/commands/version.ts, packages/cli-main/src/cli/services/commands/version.test.ts, packages/cli-main/src/cli/services/commands/version.ts
While working on the migration from Go to Node I noticed the tests of the `version` command started failing even though there's no connection between that command and the extensions' serve logic.
Placing business logic in commands is a discouraged pattern because it leads to integration tests that test the integration of the business logic and oclif's setup. Therefore I created a service, `versionService` that allows unit-testing the logic in isolation.
Tests should pass and `version` should yield the right content.
=> Extract the business logic of the version command into a service

.eslintrc.cjs, packages/ui-extensions-server-kit/src/ExtensionServerClient/ExtensionServerClient.test.ts, packages/ui-extensions-server-kit/src/state/reducers/extensionServerReducer.test.ts, packages/ui-extensions-server-kit/src/utilities/replaceUpdated.test.ts, packages/ui-extensions-server-kit/src/utilities/resourceURLtoString.test.ts, packages/ui-extensions-server-kit/src/utilities/set.test.ts
I noticed we are inconsistently using `it` and `test` when defining test cases so I'm adding a linting rule to ensure we all use the same one.
`it` seems to exist in Vitest for compatibility reasons with Jest because all [the references](https://vitest.dev/api/#test) in their documentation are to the `test` API so I'm defaulting to that one to align with Vitest's defaults.
Run `yarn lint`.
=> Use `test` over `it` throughout the codebase

.changeset/heavy-ads-sit.md, packages/create-app/src/services/init.ts
After creating an app the help text says to run the `scaffold extension` subcommand.
```bash
yarn create @shopify/app --template node
...
synergistic-deal-app is ready for you to build! Remember to cd synergistic-deal-app
Check the setup instructions in your README file
To preview your project, run yarn dev
To add extensions, run yarn scaffold extension
...
```
Updating the text to say `generate extension` instead.
Locally
None
=> Update app init text with generate instead of scaffold

packages/app/templates/ui-extensions/projects/checkout_ui/README.md
Currently, the template for a Checkout UI extension doesn't contain a basic README.md file that helps guiding developers into what the project contains and how can they work with it. This was reflected in the following Issue:
Fixes https://github.com/Shopify/shopify-cli-extensions/issues/300
The Checkout UI GA Launch will take place next 3rd October, which will make the project template to become more exposed. Therefore, providing a README before the date will improve the developer experience when it becomes more used.
This PR adds a README.md file to the template so that every generated extension in an app contains this guide.
* In this branch, generate a scaffold for Checkout-UI extension
`yarn shopify app generate extension --path ./fixtures/app`
* If the extension created, will be …
=> Add a README.md to the template

.changeset/nervous-deers-play.md, packages/app/src/cli/commands/app/dev.ts, packages/app/src/cli/services/dev/urls.test.ts, packages/app/src/cli/services/dev/urls.ts
In v3.13.0 we enabled localhost by default for `dev` (https://github.com/Shopify/cli/pull/389), but it's not working properly with old templates.
Enable the tunnel flag by default, so that a tunnel is always created unless `--tunnel-url` or `--no-tunnel` are provided. This is a temporal change until we find a way to detect if the current app supports localhost.
- `shopify app dev`
- `shopify app dev --tunel-url https://example.com:3000`
- `shopify app dev --no-tunnel`
Merge documentation PR: https://github.com/Shopify/shopify-dev/pull/26435
=> Tunnel by default again

packages/app/src/cli/services/dev.ts
After merging https://github.com/Shopify/cli/pull/489 some wrong module imports were introduced while fixing the units tests.
- Fixed wrong module imports
- `yarn shopify app dev` command should work properly
=> Fixed wrong module imports

.changeset/chilled-onions-walk.md, packages/app/src/cli/services/deploy/upload.test.ts, packages/app/src/cli/services/deploy/upload.ts
Closes https://github.com/Shopify/script-service/issues/5604
This change will display a relevant error message when the wasm upload fails. Without this step, the user gets an unhelpful server error and does not know why they cannot deploy successfully.
When we make the request to upload the Wasm module, check the response. CLI 2.0 had [logic](https://github.com/Shopify/shopify-cli/blob/0e5eccffe34c245d0e27420bc82c1fff9708b70b/lib/project_types/script/layers/infrastructure/script_uploader.rb) in place to do this, so the code I added just migrates those checks over.
- Try to push a module that is within limits. Everything should succeed.
- Try to push a module that exceeds the 256kb limit. You should get an error:
=> Check response of wasm blob upload request to inform users when upload fails

packages/app/src/cli/services/dev/extension/websocket.test.ts, packages/app/src/cli/services/dev/extension/websocket.ts
We [implemented](https://github.com/Shopify/cli/pull/38) a long ago some logic to automatically ping websocket clients to keep the connection alive through the tunnel. I'm bringing the logic back to the new Node-based workflow for serving extensions.
Extending the websocket setup logic to add the periodic pinger to clients.
- `dev` and open the `dev-console`
- Make sure to open the chrome console and look for Network -> ws (if you don't see anything, reload)
- There should be a connection to `extensions`
- Do not interact with the page for 10 minutes and the connection should still be alive.
=> Ping websocket clients periodically

packages/app/src/cli/services/dev/extension/localization.test.ts, packages/app/src/cli/services/dev/extension/payload/store.test.ts
The flow of fallback to previous successful localization build and lastUpdated timestamp when the current files fail to be parsed is not covered by tests.
Added test coverage to the previously described flow
Just run the tests to check if they pass.
=> Improve dev localization watcher tests

package.json, packages/cli-main/package.json, packages/features/features/commands.feature, packages/features/snapshots/commands.txt, packages/features/snapshots/regenerate.sh, packages/features/steps/commands.steps.ts, yarn.lock
We recently broke cli ([here](https://github.com/Shopify/cli/pull/494) and [here](https://github.com/Shopify/cli/pull/528)) by messing up the imports.
This PR introduces a simple [Golden test](https://ro-che.info/articles/2017-12-04-golden-tests) to ensure that all commands that we expect to be present DO load correctly.
It creates a snapshot of loaded CLI commands inside the `packages/features/snapshots/commands.txt` file.
- Cd into `packages/features`
- Run `FEATURE=features/commands.feature yarn test`, it should say all good
- Change `./snapshots/commands.txt` and add a new line, i.e. `app fun                @shopify/app`
- Run `FEATURE=features/commands.feature yarn test` again and it should complain in this fashion:
```
1) Scenario: No runtime errors happen when loading the CLI …
```
=> Add snapshot test to verify all commands load properly

.changeset/rude-impalas-cheat.md, packages/app/src/cli/constants.ts, packages/app/src/cli/services/generate/extension.test.ts, packages/app/src/cli/services/generate/extension.ts, packages/cli-kit/src/node/node-package-manager.test.ts, packages/cli-kit/src/node/node-package-manager.ts
Fixes #395
- When generating a `Typescript React` extension, `"@types/react": "17.0.30"` dependency is added inside the `resolutions` or `overrides` block of the `package.json` at the app root directory
- Depending on the package manager used to create the app, either `resolution` (yarn) or `overrides` (npm, pnpm) are set
- Run `yarn shopify app generate extension`
- Select `checkout UI` and `Typescript React` as flavor
- Open the app with VS Code and there should be no problems with React components resolution
- Maybe some instructions could be added for users that have generated `Typescript React` extensions without this dependency
=> React types dependency version should be overwritten when generating React Typescript extensions

.github/workflows/shopify-cli.yml
We have some flakey tests and no good ways to debug them. This PR allows to manually trigger a workflow and enable Tmate debugging. In this way, you can ssh into the running container and run commands manually.
- Add a new checkbox to the manual workflow trigger dialog
- Enable tmate debugging when it's checked
- Go to https://github.com/Shopify/cli/actions/workflows/shopify-cli.yml
- Click the Run workflow button
- Choose this branch from the dropdown
- Click on "Enable tmate debugging"
- Wait for the build to complete and you should see a ssh command in the terminal output
- Run that in your terminal and you'll be inside the running container
=> Allow to enable tmate debugging when triggering a build manually

.changeset/warm-beds-repair.md, packages/app/templates/ui-extensions/projects/checkout_ui/src/index.liquid
Solves https://github.com/Shopify/cli/issues/587.
In https://github.com/shopify/cli/pull/577, we implemented the jsx-transform in the new Node CLI flow, but not in the old Go CLI flow. Since publicly, the Node CLI is not being used yet, the jsx-transform is actually not in-place and we removed the import React from the generated template.
This results in a rendering error and the only workaround is to manually add `import React from 'react';` at the top of the file.
This pull request is adding back the React import so that it can be compatible with the Go CLI flow.
Clone this repo.
Scaffold a new app with a React extension (`yarn create-app --path <path-to-app`).
Run `SHOPIFY_RUN_AS_USER=1 yarn shopify app dev --path <path-to-app>`. …
=> Fix to missing React import when running Go build server for checkout ui extensions

packages/app/src/cli/models/app/extensions.ts, packages/app/src/cli/services/dev/extension/payload.test.ts, packages/app/src/cli/services/dev/extension/payload.ts
Fixes #573 
When `shopify.ui.extensions.toml` doesn't include a `capabilities` clause, the browser reports the following error:
```
vendors~app.latest.en.e5376343c5580b97aa7a.js:2 TypeError: Cannot read properties of undefined (reading 'networkAccess')
at app.latest.en.280faa0996ccd0490853.js:1:183003
at Array.map (<anonymous>)
at app.latest.en.280faa0996ccd0490853.js:1:182862
````
This PR sets default values for `capabilities` and `capabilities.network_access` and `capabilities.blocks_progress`. Because omitting any of the defaulted fields in tests is regarded as a syntax error, there is no way I can see to write unit tests.
Create a new checkout extension and `dev` it, ensuring the `shopify.ui.extensions.toml` file has no `capabilities` clause. Click the checkout extension preview link …
=> Fix dev breakage when missing capabilities fields

.changeset/young-bobcats-end.md, packages/cli-hydrogen/src/cli/services/deploy.test.ts, packages/cli-hydrogen/src/cli/services/deploy.ts, packages/cli-hydrogen/src/cli/services/deploy/error.ts, packages/cli-hydrogen/src/cli/services/deploy/graphql/upload_deployment.ts, packages/cli-hydrogen/src/cli/services/deploy/types.ts, packages/cli-hydrogen/src/cli/services/deploy/upload.test.ts, packages/cli-hydrogen/src/cli/services/deploy/upload.ts, packages/cli-kit/src/api.ts, packages/cli-kit/src/api/oxygen.test.ts, packages/cli-kit/src/api/oxygen.ts
Closes https://github.com/Shopify/oxygen-platform/issues/528
This PR introduces error handling and retry logic for the various calls that we make to DMS so that we can be more resilient / provide context to the user on why their deploy might be failing, etc. I also greatly increased the scope of what the unit tests cover.
I also created a new service within the CLI kit that is used for interacting with DMS as it seems this is the pattern and convention that is being used to interact with other APIs (identity, partners, shopify, etc) and removes the need for the CLI kit to export internal functionality (namely `buildHeaders`)
This PR also places the zip file of built assets into a temporary directory to follow the convention that `oxygenctl` is currently using instead of just placing the …
=> add hydrogen deploy error handling & oxygen api service

packages/cli-kit/assets/success.html
There is a typo in the success message. `Successfuly` → `Successfully`. Here is a [relevant Stack Overflow post](https://english.stackexchange.com/questions/435232/successfully-vs-successfuly) about the correct spelling of the word.
Updates the string to the correct spelling. There is a similar PR available for the [`2.x` version](https://github.com/Shopify/shopify-cli/pull/2658)
=> Fix typo in success message.

.changeset/angry-socks-develop.md, packages/cli-kit/src/error.test.ts, packages/cli-kit/src/error.ts, packages/cli-kit/src/output.ts, packages/cli-kit/src/private/node/ui/components/FatalError.tsx, packages/cli-kit/src/public/node/ui.test.ts, packages/cli-main/src/cli/services/kitchen-sink.ts, packages/plugin-ngrok/src/tunnel.test.ts, packages/plugin-ngrok/src/tunnel.ts
We want to render all our errors consistently with the new `Banner` component.
This PR is stacked on top of https://github.com/Shopify/cli/pull/512 so we need to wait for that to be merged first.
You can look at the last few commits related to errors to see changes specific to this PR. 
Render all `Fatal` errors by using the new `Banner` component. For example:
Before:
After:
- Run `yarn shopify kitchen-sink`
=> Render fatal errors with `Banner`

packages/app/src/cli/services/dev/output.test.ts, packages/app/src/cli/services/dev/output.ts
This prints a link when developing customer account ui extensions that will set up the developer experience for your dev store (also works in spin) to load extensions via the cli/ngrok.
This is part of https://github.com/Shopify/core-issues/issues/43741
It constructs a url that will set up customer accounts web to use the local extensions. The construction of the url is not very nice, but given that we will migrate to shopify.com with customer accounts in the near-ish future we did not want to spend a lot of time making this work nicely just to throw it away.
Create a new customer accounts ui extension and run `yarn dev` from this branch - the new url should show up.
For it to work you also need to make sure this [core pr](https://github.com/Shopify/shopify/pull/377520) is either merged …
=> Link to customer account extensions in dev mode

configurations/vite.config.ts
Vitest enables threads by default in order to:
- run tests in parallel
- isolate each test so that there cannot be leaks in the global state
But actual measures show that disabling threading will make our test suits run twice as fast. 
Disable vitest threading.
**before**
**after**
=> Disable threads in vitest

packages/cli-hydrogen/src/cli/services/deploy/config.integration.test.ts
We've witnessed some cli-hydrogen tests flaking very often on Windows
Skip those tests while we investigate what's causing the flakes
=> Skip super flaky tests on windows while we investigate why they're flaking

.changeset/dull-bugs-shop.md, packages/cli-kit/src/error.ts, packages/cli-kit/src/private/node/ui/components/Link.tsx, packages/cli-kit/src/private/node/ui/components/TokenizedText.tsx
From now on we should be trying to style errors better and one step towards that is adding the `Link` and `Command` tokens as part of our `tryMessages` so that the get highlighted by the new error component.
This PR allows developers to build errors by using `TextTokenItem` as the `tryMessage`, so if they need to style a command to run they can do so by doing something like:
```
throw new error.Abort('Unexpected Error', ['Fix this by running', { command: 'npm install' }])
```
=> Document how to style error tryMessage

.github/actions/setup-cli-deps/action.yml, .github/workflows/shopify-cli.yml
It was quite confusing to understand which job we were launching at any given moment and there was a lot of duplication on each one of our jobs.
This PR introduces a new job to handle manually triggered workflows. So we have three flows:
- `main` for only main jobs (whenever we push to main by merging a PR)
- `pr-platform-agnostic` and `pr-platform-dependent` for commits inside a PR
- `manually-triggered` for manually triggered builds
I've also increased the timeout for manual builds since you might need more time to debug the running instance. You can schedule it by going to https://github.com/Shopify/cli/actions/workflows/shopify-cli.yml
=> Refactor github workflow using composite action

.changeset/serious-geese-sort.md, packages/theme/src/cli/commands/theme/dev.ts
Fixes https://github.com/Shopify/cli/issues/648
The `theme/dev.ts` command was not passing the `--only/--ignore` flags to the Ruby CLI.
This PR introduces both flags in the `theme/dev.ts` command.
- Run `shopify theme dev --only sections/announcement-bar.liquid`
- Open the browser at http://127.0.0.1:9292
- Change the `sections/announcement-bar.liquid`
- Notice the file is not ignore (the browser responds and the CLI logs show the file being synced)
- Change the `layout/theme.liquid`
- Notice the file is not ignored by the browser and the CLI logs
- Run `shopify theme dev --ignore sections/announcement-bar.liquid`
- Open the browser at http://127.0.0.1:9292
- Change the `sections/announcement-bar.liquid`
- Notice the file is not ignored by the browser and the CLI logs
- Change the …
=> Introduce `--only/--ignore` support in the `shopify theme dev` command

.changeset/hip-dogs-kiss.md, packages/cli-kit/src/node/ruby.ts, packages/cli-kit/src/session.test.ts, packages/cli-kit/src/session.ts, packages/theme/src/cli/commands/theme/dev.ts, yarn.lock
Up until now our commands execution only needed a valid token during the first seconds (maybe minutes). 
The only command with a long live period is `app dev` and it doesn't need a token once the servers are up.
But with themes this is different, during `theme dev` a valid token is always required to push changes to the remote store.
Fixes https://github.com/Shopify/cli/issues/546
- Before running `theme dev`, always refresh the tokens to be sure they are valid for at least 90min. 
- After running `theme dev` and every 90 min: close the ruby process, refresh tokens and execute it again with updated tokens.
❓  Tokens expire at 120min, should we refresh the tokens every 100, 110 or 115 min maybe?
- To test that the process finishes, refreshes and starts again, you can modify …
=> Automatically refresh Theme session

.changeset/nine-beers-begin.md, fixtures/app/extensions/product-subscription/src/index.js, packages/app/src/cli/services/dev/extension/payload.ts, packages/app/src/cli/services/dev/extension/payload/models.ts
Resolves: https://github.com/Shopify/cli/issues/621
The extension payload returned by the extensions' HTTP and Websocket servers [must return](https://github.com/Shopify/cli/issues/621) the `approvalScopes` attribute when apps are set up as "single-merchant install link. This is the case when serving the extensions through the Go logic, but we introduced a regression in the new Node logic.
I'm making sure the attribute is included in the new Node logic.
1. Create a new app
2. Change the distribution of the app with Choose single-merchant install link
3. Launch yarn dev for the app
4. Check the /extensions local endpoint to see if it includes the approvalScopes key, with an array of strings (scopes)
=> Add missing approval_scopes

.changeset/sharp-items-walk.md, packages/theme/src/cli/commands/theme/open.ts, packages/theme/src/cli/commands/theme/publish.ts
Fixes https://github.com/Shopify/cli/issues/651
Remove the `password` flag from the ones we are sending to CLI2 for `theme open` and `theme publish` commands, as the CLI2 is not expecting it. 
- `yarn shopify theme open --password whatever`
- `yarn shopify theme publish --password whatever`
=> Fix password flag for theme open/publish

.github/workflows/shopify-cli.yml
Only run main workflow on push events on main. Weirdly, even `workflow_dispatch` events have their github ref set to the main branch, so they would end up being triggered there as well.
=> Only trigger main workflow on push events

.changeset/healthy-tips-serve.md, packages/cli-kit/src/private/node/ui/components/Command.tsx, packages/cli-kit/src/public/node/ui.test.ts, packages/cli-kit/src/public/node/ui.tsx
Fixes https://github.com/Shopify/shopify-cli-planning/issues/431
This PR adds backticks surrounding every command.
- Run `yarn shopify kitchen-sink` to see that the example output always uses backticks for commands.
=> Add backticks to command token

.changeset/thin-walls-lick.md, packages/cli-kit/src/error.ts, packages/cli-kit/src/private/node/ui/components/Alert.tsx, packages/cli-kit/src/private/node/ui/components/Banner.tsx, packages/cli-kit/src/private/node/ui/components/FatalError.tsx, packages/cli-kit/src/system.ts
@isaacroldan reported that he saw an error that broke the borders of the banner component.
I've introduced a new type of error called `ExternalError`. This is used when rescuing errors from `execa` and allows us to print these kind of errors differently, like so:
=> Introduce ExternalError and output external errors with a new component

packages/app/src/cli/models/app/loader.ts, packages/app/src/cli/services/dev/extension/payload/models.ts
Fixes #685
We want to be able to parse the new toml format (See [this doc](https://docs.google.com/document/d/1rlv3DcgGZi4_Hf_Ekd14DnYWJ1rjsfZlMBVC80gFWjc/edit#bookmark=id.ri74g3odxziy))
Note, this implementation kinda bad. Because of all the different schema formats, bascially every field becomes optional, which reduces type safety and validation posibilities a lot.  But, I don't want to spend much time on this right now because:
1. This will be merged into a feature branch and then refactored with Isaac's new approach to initializing extensions
2. After this project we will migrate all ui extensions to this new format, so this we can simplify these schemas a lot and reclaim some type safety.
**1) Updates the zod schema** 
This is what the CLI uses to parse the toml file into memory. …
=> [WIP] Add the ability to parse the new schema format

.changeset/dry-llamas-travel.md, packages/cli-kit/src/public/node/ruby.ts
I'm releasing the [Ruby CLI 2.31.0](https://github.com/Shopify/shopify-cli/pull/2679) so I'm updating the Node CLI to use the that version. This PR should only be merged when the release has happened.
Updating the version of the Ruby CLI
Try to run a command that runs through the Ruby CLI, for example `theme pull` and `theme push`. It should work successfully.
=> Update the Ruby CLI version

package.json, patches/@changesets+cli+2.25.2.patch, yarn.lock
Releases [fail](https://shipit.shopify.io/shopify/cli/production/deploys/1888745) because changesets attempts to publish packages that have already been published. The issue seems to be rooted in [flakiness](https://github.com/changesets/changesets/issues/427#issuecomment-668515080) that arises when changesets concurrently sends requests to the NPM API to obtain the packages information. There's a [PR](https://github.com/changesets/changesets/pull/853/files) open to reduce the concurrency but it hasn't been merged.
I'm "patching" the fix at dependency installation time by using [patch-package](https://www.npmjs.com/package/patch-package)
It's tricky to test from a branch. I'd suggest merging and running an actual release.
=> Reduce the changesets concurrency

patches/@changesets+cli+2.25.2.patch
When I patched [@changesets/cli](https://github.com/Shopify/cli/pull/734) to limit the concurrency when interacting with NPM APIs, I missed some lines.
I'm adding the lines that were missing.
=> Add missing patches for @changesets/cli

.changeset/kind-dodos-fry.md, packages/app/project.json
The dev-console fails to load in the most recent release, 3.22.0, because it can't be found:
```json
{
"statusCode": 404,
"statusMessage": "Could not find root directory for dev console",
"stack": []
}
```
It turns out with the removal of the Go binary, the `dev-console` stopped being a project dependency of the `@shopify/app` package and therefore it didn't get bundled when we deployed the packages in the Shipit environment. I'm adding it as a dependency to make sure it's built before the `@shopify/app` package is built.
1. Run `yarn clean`.
2. Go to `packages/app`
3. Run `yarn build`
4. The dev console should show up in `assets/dev-console`.
=> Make ui-extensions-dev-console dependency of @shopify/app

packages/app/package.json, packages/cli-hydrogen/package.json, packages/cli-kit/package.json, packages/cli-main/package.json, packages/create-app/package.json, packages/create-hydrogen/package.json, packages/features/package.json, packages/plugin-ngrok/package.json, packages/theme/package.json
Fixes #697 
Node 14 has issues with M1s, which were solved in 14.17, see https://github.com/nodejs/node/pull/38051
Updates all packages to depend on a Node version compatible with M1 macs.
Shouldn't require testing AFAICT
Need to update the docs that mention Node 14.13.1 to Node 14.17.0
=> Update required node version to be compatible with M1 macs

.github/CODEOWNERS, .github/workflows/reviewers-reminder.yml
We (CLI Foundations) are getting too many notifications, not always from work that actually requires our review.
- Add a new workflow that comments on new PRs suggesting possible reviewers
- Remove CODEOWNERS, so that review requests are not automatically sent
https://github.com/Shopify/cli/pull/770#issuecomment-1313417291
=> Add reviewers reminder for new PRs

packages/ui-extensions-dev-console/README.md, packages/ui-extensions-dev-console/package.json, packages/ui-extensions-dev-console/project.json, packages/ui-extensions-dev-console/src/App.tsx
To develop the extensions dev console it would be handy if:
1. you could connect the UI with real data provided by the CLI.  
2. You could work with vite's dev server so that you have hot module reloading.
In this PR we make these things a little easier.
1. Change `import.meta.env.VITE_WEBSOCKET_HOST` to `VITE_CONNECTION_URL`
2. Parse the env var so that we end up with the correct URL, e.g: `wss://ngrok.url/extensions`
3. Add a README with steps on how to run the dev console 
4. Replace the `start` command wth a `dev` command to run Vite's dev server.  Not sure why we had a start command ? 
1. Read the readme.
2. Follow the steps in the readme.
None
=> Connect UI extensions dev console with cli

.changeset/spicy-seas-play.md, packages/app/src/cli/services/dev.ts
During the migration of the [Forms](https://github.com/shopify/forms) 1P app, which doesn't adhere to the most recent setup proposed by our templates, we realized that some variables were not passed to the frontend process. For instance, one of them is `SHOP_CUSTOM_DOMAIN`, which we need to initialize the Shopify App gem in a single-process app where the main process is of type `frontend`.
I added a new function to obtain the environment variables that are common in the frontend and backend processes. Note that we include `SHOP_CUSTOM_DOMAIN` when we are running the CLI in Spin.
Try to `dev` the fixture app locally and in Spin.
=> Env vars consistency

packages/app/src/cli/models/app/extensions.ts, packages/app/src/cli/models/app/loader.ts, packages/app/src/cli/models/extensions/extension-points.ts, packages/app/src/cli/models/extensions/extension-specifications/checkout_ui_extension.ts, packages/app/src/cli/models/extensions/extension-specifications/ui_extension.ts, packages/app/src/cli/models/extensions/extensions.ts, packages/app/src/cli/models/extensions/schemas.ts, packages/app/src/cli/services/dev/extension.ts, packages/app/src/cli/services/dev/extension/server.ts, packages/app/src/cli/services/dev/extension/server/middlewares.test.ts, packages/app/src/cli/services/dev/extension/server/middlewares.ts, packages/app/src/cli/services/dev/extension/server/utilities.test.ts, packages/app/src/cli/services/dev/extension/server/utilities.ts, packages/app/src/cli/services/dev/extension/utilities.ts, packages/app/src/cli/services/environment.test.ts, packages/app/src/cli/services/environment/id-manual-matching.test.ts, packages/app/src/cli/services/environment/id-matching.test.ts, packages/app/src/cli/services/environment/identifiers-extensions.test.ts, packages/app/src/cli/services/environment/identifiers.test.ts, packages/ui-extensions-dev-console/tests/mount.tsx
Fixes [#1941](https://github.com/Shopify/ui-extensions-private/issues/1941)
Fixes [#1946](https://github.com/Shopify/ui-extensions-private/issues/1946)
A ui_extension supports multiple extension points.  Unlike previous extensions, those extension points can be across multiple surfaces.  Therefore we need a preview link per extension point that an extension supports.
* Add `shouldFetchCartUrl` to `ui_extension`.  This used to exist in the dev console code.  Moving it here means we get complete type safety because the `ui_extension` knows exactly the shape of `extensionPoints`, rather than knowing it's either `string[]` or `{}[]`.  The dev console now uses this code.
* Add `hasExtensionPointTarget` to `ui_extension`.  Same deal here.
* Add a new URL to the dev console, e.g: …
=> [Feature] Add preview links for a ui_extension

packages/app/src/cli/commands/event/trigger.ts, packages/app/src/cli/prompts/event/options-prompt.ts, packages/app/src/cli/prompts/event/trigger.test.ts, packages/app/src/cli/prompts/event/trigger.ts, packages/app/src/cli/services/event/trigger-options.test.ts, packages/app/src/cli/services/event/trigger-options.ts, packages/app/src/cli/services/event/trigger.test.ts, packages/app/src/cli/services/event/trigger.ts
Loose ends we wanted to fix before we remove the hidden flag:
* Use nextSteps from errors.Abort
* http urls should be case insensitive
* Changes in the messages 
Commands executed (first changing hidden to false):
```
yarn shopify event trigger --help
yarn shopify event trigger --topic=t --api-version=v --shared-secret=s --delivery-method=http --address=ftp://a:b@host
yarn shopify event trigger --topic=t --api-version=v --shared-secret=s --delivery-method=google-pub-sub --address=https://example.org
yarn shopify event trigger --topic=t --api-version=v --shared-secret=s --delivery-method=event-bridge --address=https://example.org
```
=> Apply event trigger command bugbash session 1 feedback

packages/app/src/cli/models/extensions/schemas.ts, packages/app/src/cli/services/dev/extension/payload.ts
This PR removes `authenticatedRedirectStartUrl` and `authenticatedRedirectRedirectUrls` from the base extension schema. I mistakenly added those properties in the already merged PR: https://github.com/Shopify/cli/pull/741
For more information please refer to Richard's comments:
https://github.com/Shopify/cli/pull/741/files/c2261a3b6c58880c3228bf8bbe3344a0d6ec4a39#r1035107327
<br/>
@byrichardpowell I decided to leave the `authenticatedRedirectStartUrl` and `authenticatedRedirectRedirectUrls` inside of the `customer_accounts` config instead of using settings, as on the customer_accounts side we currently are only making use of the config so far (see `categories` for example).
Kudos go to @byrichardpowell for bringing this topic up 🙏
- Remove `authenticatedRedirectStartUrl` and …
=> [Fix] remove auth redirect property from base extension schema

packages/app/src/cli/models/extensions/extension-specifications/ui_extension.test.ts, packages/app/src/cli/models/extensions/extension-specifications/ui_extension.ts, packages/app/src/cli/models/extensions/specifications.ts
We shipped the `ui_extension` specification without any tests so that we could unblock a whole heap of work.  In this PR we tidy up and add tests.
Fixes #https://github.com/Shopify/cli/issues/817
Adds tests for the `ui_extension` specification.
Because I changed the code to load the specs let's test that dev works:
1. `yarn && yarn build`
2. `cd fixtures/app`
3. `yarn dev`. Does it work?
Beyond that, do the tests look good?
None
- [z] n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
=> Test UI extension

.changeset/angry-goats-double.md, packages/cli-kit/src/log.ts
When we truncate the logs file we output a message to the user leaking implementation details of our logging system
I'm adjusting the logic to output a `debug` message instead. Users will only see it if they use `--verbose`.
Try to run any CLI command. You shouldn't see the message.
=> Remove the truncate log

packages/cli-kit/src/analytics.ts
It adds 5 seconds of wait time at the end of each command
*before*
```
$ time pnpm shopify help
real	0m7.918s
user	0m7.181s
sys	0m1.501s
```
*after*
```
$ time pnpm shopify help
real	0m2.723s
user	0m1.253s
sys	0m0.362s
```
Stop calling `localCliPackage`, which in turn calls `npm list` to check if the CLI package used is a local one. I think that originally the intent of the code was to verify that we were NOT using a global version (for example installed through homebrew). But I don't think the accuracy of analytics is worth the time we are spending.
`$ time pnpm shopify help`
=> Stop calling localCliPackage because it's super slow

.changeset/tough-houses-dress.md, packages/app/src/cli/commands/webhook/trigger.ts, packages/app/src/cli/prompts/webhook/options-prompt.ts, packages/app/src/cli/prompts/webhook/trigger.test.ts, packages/app/src/cli/prompts/webhook/trigger.ts, packages/app/src/cli/services/webhook/trigger.test.ts, packages/app/src/cli/services/webhook/trigger.ts, packages/features/snapshots/commands.txt
1. To show the command in the list of available commands
2. To improve the error reporting when invalid values for topic and api-version are passed. Feedback received from @jhoffmcd during the bug bash 
For next steps we plan to add client validation to those two fields. Meanwhile, the CLI returns validation errors returned by Core. Those were printed in raw mode and we have added better formatting:
**BEFORE**
**AFTER**
Follow this, possibly, https://github.com/Shopify/cli/pull/870 if you're moving away from yarn for the 1st time.
In vs code, first do `dev up`, then:
1. Show the help and check that the new command appears:
```
pnpm shopify --help
```
2. Execute the command with invalid topic and api-version values:
```
pnpm shopify webhook trigger --topic=pizza/update …
```
=> Activate webhook trigger and improve error message

.changeset/eight-insects-hide.md, packages/app/src/cli/services/dev/extension.test.ts, packages/app/src/cli/services/dev/extension.ts, packages/app/src/cli/services/dev/extension/bundler.test.ts, packages/app/src/cli/services/dev/extension/bundler.ts, packages/app/src/cli/services/dev/extension/localization.test.ts, packages/app/src/cli/services/dev/extension/localization.ts, packages/app/src/cli/services/dev/extension/payload.ts, packages/app/src/cli/services/dev/extension/payload/store.test.ts, packages/app/src/cli/services/dev/extension/payload/store.ts, packages/app/src/cli/services/dev/extension/server/middlewares.ts, packages/app/src/cli/services/dev/extension/websocket.test.ts, packages/app/src/cli/services/dev/extension/websocket/handlers.ts, packages/app/src/cli/services/dev/extension/websocket/models.ts, packages/cli-kit/src/output.ts, packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx
After the migration form the Go extension server to the Node extension server, output messages from extension server logic are not rendered using the UI ConcurrentOutput component.
- Output messages in extension server should use the `stdout` and `stderr` writers that receives when the UI ConcurrentOutput initiates the server.
- Run `yarn shopify app dev --verbose` command for an app that contains at least one extension.
=> Redirect extension output messages to concurrent output UI component

.changeset/pink-pens-trade.md, packages/cli-kit/src/system.ts
Fixes https://github.com/Shopify/cli/issues/630
On Windows, processes are left hanging around after users terminate `dev` with `Ctrl+C`. Digging around I found an [issue](https://github.com/sindresorhus/execa/issues/433) open on the `execa` repo that mentioned [issues](https://github.com/nodejs/node/issues/29837) with `SIGINT` and child processes not getting killed properly on Windows if `windowsHide` is left to its default value of `true`.
This PR changes the value of `windowsHide` from its default of `true` to `false`. This did not seem to have any effect on the behavior of `dev`
- Run `yarn shopify app dev --path fixtures/app` on Windows
- Open the task manager and see all the node processes that the terminal app spawned
- Press `Ctrl+C` and see all the node processes disappear.
There …
=> Change windowsHide to false

.changeset/unlucky-brooms-complain.md, packages/app/src/cli/models/app/app.ts, packages/app/src/cli/services/dev.ts
Fixed backend's shopify.web.toml parsing issue which causes `auth_callback_path` setting getting ignored
`auth_callback_path` on backend's shopify.web.toml is mistakenly ignored when parsing the configuration file.
When decoding the file, the loader (  [`loadConfigurationFile()`](https://github.com/Shopify/cli/blob/ed76c2448345eb6a539c6600cdb023ebf744f3a4/packages/app/src/cli/models/app/loader.ts#L200-L204) ) internally converts all the keys from `snake_case` to `camelCase` so it becomes `authCallbackPath`, but the [`WebConfigurationSchema`](https://github.com/Shopify/cli/blob/8de55df366f6b9b6b7739c616efcc7419a67a2ff/packages/app/src/cli/models/app/app.ts#L20) defined it as `auth_callback_path` so the key won't match and the setting will not be loaded properly.
By fixing the schema, …
=> Fix auth_callback_path getting ignored issue

packages/cli-kit/src/environment/service.test.ts, packages/cli-kit/src/session.test.ts
Fixes https://github.com/Shopify/internal-cli-foundations/issues/476
- There were some tests that sets some environment variables globally. This could cause collateral problems in other tests executed before that depends on that environment variables.
- For instance, the tests in `session.test.ts` don't support executing the device authentication method. There was a condition that checks some environment variables modified in the first point. In case those are modified before some flaky errors are generated
- Restore the original environment variables values, after running each test
- Simulate setting env variable SPIN 1 when running session tests
- `cd packages/cli-kit`
- `SPIN=1 pnpm nx run test session` 
- Errors appeared should match the ones from the flaky test issue
How do we know …
=> Fix flaky test in sessions

nx.json
The new `refresh-manifest` task requires the module graph to be built first so I've adjusted the Nx configuration to declare that dependency. 
You should be able to clean and then run `refresh-manifess` in every package of the project that has the task defined.
=> Build before refreshing the manifest

shipit.production.yml
the pnpm install script does not support `sh`, so before I tried to force it to load `~/.bashrc`. It seems that each command runs in a separate context, so this attempts to modify the `~/.profile` config which every shell should load. Previous error looked like this:
```
$ curl -fsSL https://get.pnpm.io/install.sh | SHELL=`which bash` bash -
pid: 206941
==> Extracting pnpm binaries 7.18.2
Copying pnpm CLI from /tmp/tmp.dXL72YTlDX/pnpm to /app/home/.local/share/pnpm/pnpm
Created /app/home/.bashrc
Next configuration changes were made:
export PNPM_HOME="/app/home/.local/share/pnpm"
export PATH="$PNPM_HOME:$PATH"
To start using pnpm, run:
source /app/home/.bashrc
pid: 206941 finished in: 3.085007023997605 seconds
$ . ~/.bashrc
pid: 206987
pid: 206987 finished in: 0.0037733064964413643 seconds …
```
=> Try overriding profile in shipit

shipit.production.yml
`pnpm run changeset publish` fails with: `ERR_PNPM_NO_SCRIPT  Missing script: changeset`, while `pnpm changeset publish` seems to work.
=> pnpm run expects scripts inside bin

.github/workflows/release.yml, .github/workflows/shopify-cli.yml
We have a workflow which automatically aggregates all changesets and updates all versions of all CLI packages. But we recently added oclif manifests to speed up load times.
The issue is that oclif manifests refer to the npm package versions, which means that all changes made in the "Version Packages" pull request would invalidate our oclif manifests. Sad times.
When generating the changeset pull request, we're going to also update the oclif manifests.
- make a changeset with `pnpm changeset add`
- try running `pnpm changeset version && pnpm refresh-manifests`
- you should see all package.json and README file updates, but also oclif manifests being changed
=> Automatically refresh oclif manifests on release

.changeset/strong-dolls-pay.md, packages/app/src/cli/models/organization.ts, packages/app/src/cli/prompts/dev.ts, packages/app/src/cli/services/app/select-app.ts, packages/app/src/cli/services/dev/fetch.ts, packages/app/src/cli/services/dev/select-app.test.ts, packages/app/src/cli/services/dev/select-app.ts, packages/cli-kit/src/api/graphql/find_org.ts
Fixes the request for an org's apps taking way too long (>10 seconds in some cases if there are many apps!)
It turns out most of the time is spent fetching granted scopes for each app. Given how expensive this is, so we should only request it once on the selected app, not on each returned app.
Any operation (simplest is `shopify app env show --verbose`) you should see the request time for the app list decrease dramatically.
Worth tophatting various affected flows (`dev` and `deploy`) as well.
=> Only request granted scopes on selected app

.github/workflows/release.yml
Yesterday I tried to get the changeset script (the one that generates the Version Packages pr) to also update the oclif manifests. But unfortunately the `version` field only accepts a single npm script. The current failure we are seeing is this:
```
/home/runner/setup-pnpm/node_modules/.bin/pnpm changeset version && pnpm refresh-manifests
🦋  error Too many arguments passed to changesets - we only accept the command name as an argument
```
=> Changeset version only accepts a single npm script

.changeset/thin-students-smile.md, packages/app/src/cli/models/extensions/function-specifications/delivery_customization.ts
https://github.com/Shopify/cli/pull/727#pullrequestreview-1216457506
Fix a typo in the delivery-customization template name
`pnpm shopify app generate extension` and choose Delivery Customization
=> Fix template for Delivery Customization extensions

package.json, pnpm-lock.yaml
Inside our release pipeline we run `pnpm changeset version` to aggregate all changesets and update the packages version. After we do that we need to rerun `pnpm install` to update the versions inside the fixture app, otherwise builds will fail with this error:
```
Run pnpm install
Scope: all 17 workspace projects
Lockfile is up to date, resolution step is skipped
 ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with fixtures/app/package.json
 ```
=> Fix pnpm lock again

package.json
By default on CI you are not supposed to change the pnpm lock file, but in this case we really want to do it, since the resulting diff will be automatically committed and create a new "Version Packages" pull request.
=> We want to update the lock file when doing a release

.changeset/slimy-roses-perform.md, .changeset/stale-pianos-melt.md, packages/app/src/cli/prompts/dev.test.ts, packages/app/src/cli/prompts/dev.ts, packages/app/src/cli/services/app/select-app.ts, packages/app/src/cli/services/dev/fetch.ts, packages/app/src/cli/services/dev/select-app.test.ts, packages/app/src/cli/services/dev/select-app.ts, packages/cli-kit/src/api/graphql/find_org.ts, packages/cli-kit/src/string.ts, packages/cli-kit/src/ui.ts, packages/cli-kit/src/ui/executor.ts, packages/cli-kit/src/ui/inquirer/autocomplete.ts
Fixes #317
Currently Partners can't select an app that's too far down in their org's list of apps. They need to work around using the `--api-key` flag. This PR allows Partners to search by app title if their app count exceeds the number we fetch.
[Videobin](https://videobin.shopify.io/v/Pv11DW)
I think this is best explained by seeing the code comments, which describe the algorithm at length.
TL;DR if they have >100 apps in the organization, typing to search triggers a call to the Partners API searching for the apps by title.
Acting as a 1P developer, connect to the Shopify partners organization and search for an app far down the list.
=> Search for apps by title

.changeset/nervous-carpets-think.md, packages/app/src/cli/models/extensions/specification.integration.test.ts, packages/app/src/cli/models/extensions/specifications.ts, packages/cli-kit/src/path.ts
Fixes https://github.com/Shopify/cli/issues/864#issuecomment-1354088698
The globbing to get the list of specification modules ignores the `ignore` value passed. 
Instead of using `ignore` I'm passing a list of patterns, the second which uses the `!` prefix to exclude the `.d.ts` modules from the list.
Try to generate a new extension in a project.
=> Fix generation of extensions

eslint-rules/specific-imports-in-bootstrap-code.cjs, packages/cli-kit/package.json, packages/cli-main/bin/dev.js, packages/cli-main/bin/run.js, packages/cli-main/package.json, packages/cli-main/project.json
Necessary step to ensure bootstrap code path can be carefully monitored
- Adds an ESLint rule that ensures only specific imports can be used in a file
- Rule can optionally allow/disallow static imports (`import x from 'y'`)
- Rule has been configured for current bootstrap code
- Run eslint
- Try adding a new import to any of the bootstrapping code
=> Bootstrap import linting

.changeset/breezy-bugs-develop.md, packages/create-app/src/prompts/init.ts
We felt that enough time has elapsed since v2.18.1 of the CLI was released, and few enough apps are still created with version prior to that, that we can make the `cli_three` branches the `main`s in the Node and PHP templates.
Now that the branches were renamed, CLI 3 can clone the `main`s directly. We'll keep the `cli_three` branches around to give folks time to update to the version of CLI 3 that includes this PR before deleting / deprecating them.
- Create a node or php app as you normally would
- App should work
☝️ assuming that there is tracking of app creation by CLI version.
=> Remove cli_three branch references

.eslintrc.cjs, packages/cli-kit/src/public/common/array.ts, packages/cli-kit/src/public/node/base-command.ts, packages/cli-kit/src/public/node/checksum.ts, packages/cli-kit/src/public/node/cli.ts, packages/cli-kit/src/public/node/dot-env.ts, packages/cli-kit/src/public/node/error-handler.ts, packages/cli-kit/src/public/node/framework.ts, packages/cli-kit/src/public/node/hooks/prerun.ts, packages/cli-kit/src/public/node/node-package-manager.ts, packages/cli-kit/src/public/node/ruby.ts, packages/create-app/src/commands/init.test.ts
Related to https://github.com/Shopify/internal-cli-foundations/issues/491, we need to have our public interface be locked down. This will make us aware of breaking changes.
Enforces that `public` ts files (i.e. anything we expose as an importable file) have explicit interfaces for functions, so we know if the return types have accidentally changed.
`dev lint` should succeed.
=> Require explicit return types on public functions

.changeset/stupid-games-type.md, packages/cli-kit/src/api/partners.ts, packages/cli-kit/src/http/fetch.ts, packages/cli-kit/src/output.ts
Tracing performance of HTTP requests gives us visibility into what's taking the most time. Let's make the CLI faster.
Using the JS `performance` API, grab timestamps before and after the request, and print the total request time.
Run `dev` with `--verbose` and see the extra log lines! (search for `completed`)
```
2022-12-23T13:11:08.294Z: Reading the content of file at package.json...
2022-12-23T13:11:08.294Z:
Sending "Partners" GraphQL request:
{
organizations(first: 200) {
nodes {
id
businessName
website
appsNext
}
}
}
With variables:
And headers:
- User-Agent: Shopify CLI; v=3.30.0
- Sec-CH-UA-PLATFORM: darwin
- X-Request-Id: 70929890-3feb-4e11-b8a7-98dd49f063e1
- Content-Type: application/json
2022-12-23T13:11:08.759Z: Request to https://partners.shopify.com/api/cli/graphql completed …
```
=> Log request times for partners API and other HTTP fetch

.changeset/little-adults-obey.md, packages/app/src/cli/models/extensions/functions.ts, packages/app/src/cli/services/generate/extension.test.ts, packages/app/src/cli/services/generate/extension.ts
Functions were always using the default template repo, even if a new function specified a custom repo.
Allow to use custom templateURL paths in function specifications
=> Allow function specifications to use a custom template repository

packages/ui-extensions-dev-console/src/sections/Extensions/components/ExtensionRow/ExtensionRow.module.scss, packages/ui-extensions-dev-console/src/sections/Extensions/components/ExtensionRow/ExtensionRow.tsx, packages/ui-extensions-dev-console/src/sections/Extensions/components/ExtensionRow/components/PreviewLinks/PreviewLinks.module.scss, packages/ui-extensions-dev-console/src/sections/Extensions/components/ExtensionRow/components/PreviewLinks/PreviewLinks.tsx, packages/ui-extensions-dev-console/src/sections/Extensions/components/ExtensionRow/components/PreviewLinks/index.ts, packages/ui-extensions-dev-console/src/sections/Extensions/components/ExtensionRow/components/PreviewLinks/translations/en.json, packages/ui-extensions-dev-console/src/sections/Extensions/hooks/useExtensionsInternal.tsx, packages/ui-extensions-server-kit/src/types.ts
A UI Extension renders multiple extension points.  Therefore we need multiple preview links for a UI extension.
Fixes #1006 
1. Fixes a type error in the server kit.
2. Introduce a new PreviewLinks component which handle the now 3 cases (POS extension, Legacy extension, UI Extension)
3. ExtensionRow that component to render the correct preview links
1. `pnpm install && pnpm build`
2. `cd fixtures/app`
3. `pnpm generate extension` (Choose a UI Extension)
4. `pnpm dev`
5. Check the preview links for every extension is correct
None
=> UI extension row

packages/app/src/cli/services/dev/extension/bundler.ts
Related: https://github.com/Shopify/cli/issues/1012
We are improving the CLI launch times
I'm updating the function that uses `chokidar` to import it dynamically.
The dev'ing of functions should work.
=> Import chokidar dynamically

packages/cli-kit/src/file.ts, packages/cli-kit/src/path.ts
Related: https://github.com/Shopify/cli/issues/1012
I'm updating the function that uses `fast-glob` to import it dynamically, and updating `del` to the ESM version.
Building and dev'ing the fixture app should work and tests should pass.
=> Import `fast-glob` dynamically and use the ESm version of `del`

.changeset/cold-clocks-fly.md, packages/theme/src/cli/commands/theme/dev.ts
Apparently `setTimeout` accepts any number, but crashes silently if it's bigger than INT32 max value...
This was preventing OTHER timers to be triggered, which is weird.
Simplified how theme dev timers work, we only need one `setInterval`
=> Fix theme dev session refresh

.github/workflows/shopify-cli.yml
The benchmark reports on PRs sometimes yielded odd diffs beyond 20%.
I did a bit of investigation and we are always running it with the same OS, `ubuntu-latest`, and Node version, `18.7.0`, so my assumption is that GitHub Actions' virtualization doesn't consistently provide the same resources across builds. I'm adjusting the pipelines to use `macOS` instead where resources might be the same across builds.
=> Run performance benchmarking on macOS

packages/cli-kit/src/session/authorize.ts
Related: https://github.com/Shopify/cli/issues/1012
We are [improving](https://github.com/Shopify/cli/issues/1012) the launch time of the CLI.
I'm adjusting the function that uses `kill-port-process` to import it dynamically. That way the module is lazily loaded when needed.
=> Import `kill-port-process` dynamically

README.md
Link points to non-existing page.
Fixes aforementioned link.
Verify that "steps to get started" in https://github.com/Shopify/cli/tree/fix-link-to-get-started-in-readme points to correct page.
=> Fix link to "Get started" page in main README

docs/cli-kit/ui-guidelines.md
To ensure consistency and quality in the Shopify CLI, we have guidelines around commands. We're adding those guidelines into our contributor documentation to scale our teams' work to other contributing teams.
This is a V1. Future work on this doc can include a list of cross-domain flags, more guidance around how env variables work as flags, and more examples gleaned from decisions we've made (for example, we could draw on work on webhooks or the docs search feature).
=> Add command guidelines to the contributor docs

fixtures/app/extensions/pos-ui-extension/shopify.ui.extension.toml, fixtures/app/extensions/pos-ui-extension/src/index.jsx, packages/app/src/cli/models/extensions/ui-specifications/pos_ui_extension.ts, packages/ui-extensions-dev-console/src/sections/Extensions/components/ActionSet/ActionSet.test.tsx, packages/ui-extensions-dev-console/src/sections/Extensions/components/ActionSet/ActionSet.tsx, packages/ui-extensions-dev-console/src/sections/Extensions/components/QRCodeModal/QRCodeModal.test.tsx, packages/ui-extensions-dev-console/src/sections/Extensions/components/QRCodeModal/QRCodeModal.tsx, packages/ui-extensions-server-kit/src/ExtensionServerClient/types.ts
Fixes https://github.com/Shopify/pos-next-react-native/issues/19682
For POS UI Extensions, scanning QRCode from developer console opens Shopify mobile instead of POS.
Fixes the wrong surface name and updating the `retail-ui-extensions` to point to the most recent version,
1. Created a new Extension.
2. Updated Tests
N/A
=> Fix QRCode link when Surface is Point of Sale

packages/cli-kit/package.json, packages/cli-kit/src/private/node/ui/components/FullScreen.tsx, packages/cli-kit/src/private/node/ui/components/SelectPrompt.tsx, pnpm-lock.yaml
I accidentally found a bug with prompts not being cleared properly after submission if the height of the terminal is lower than the height of the prompt itself.
Current implementation doesn't clean the prompt after submission and keeps the last 2 renders in the terminal output:
New implementation:
Use kitchen sink to test prompts at different terminal heights.
=> Fix issue with prompt not being cleared correctly

packages/app/src/cli/commands/webhook/trigger.ts, packages/app/src/cli/prompts/webhook/options-prompt.test.ts, packages/app/src/cli/prompts/webhook/options-prompt.ts, packages/app/src/cli/prompts/webhook/trigger.test.ts, packages/app/src/cli/prompts/webhook/trigger.ts, packages/app/src/cli/services/webhook/request-api-versions.test.ts, packages/app/src/cli/services/webhook/request-api-versions.ts, packages/app/src/cli/services/webhook/request-sample.test.ts, packages/app/src/cli/services/webhook/request-sample.ts, packages/app/src/cli/services/webhook/trigger-local-webhook.test.ts, packages/app/src/cli/services/webhook/trigger.test.ts, packages/app/src/cli/services/webhook/trigger.ts
In the initial version of webhook trigger, several flags that requested as free text fields can be requested as options list. i.e. api-version and topic
This PR addresses the api-version flag and includes several improvements:
1. It is requested before the topic (in a future PR the list of available topics will depend on the api-version you selected)
2. If using prompt, the valid values are presented as a list of options
3. If passed as a flag, the flag value is validated against the list of valid values. If it fails, the whole process stops (no more flags will be requested) 
```
pnpm shopify webhook trigger --api-version=unknown
```
returns:
```
╭─ error ────────────────────────────────────────────────────────────────────────────╮
│ …
```
=> [Feature] Improve apiversion devx for webhook trigger

packages/app/src/cli/models/extensions/functions.ts, packages/app/src/cli/services/environment/id-matching.test.ts, packages/app/src/cli/services/environment/id-matching.ts
It turns out that the automatic id matching logic wasn't fully working for functions. Also functions were being picked up by the extension matching logic.
- fix automatic id matching for functions
- isolate matchmaking between functions and extensions so that existing identifiers only apply for the correct type
- create a new app
- add a function
- deploy
- deploy again
- everything should be normal
=> Fix id matching for functions

.changeset/blue-items-mate.md, packages/theme/src/cli/commands/theme/dev.ts
`theme dev` restarts itself after 2h to refresh tokens, but there seems to be a race condition where we start the new `dev` process before the previous one has been completely closed (so the port 9292 might not be free yet)
Wait for 3 seconds before starting the process again
=> Add extra timeout before restarting `theme dev`

packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.test.tsx, packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.tsx, packages/cli-kit/src/private/node/ui/components/SelectInput.tsx, packages/cli-kit/src/public/node/ui.tsx
@isaacroldan reported the a bug with the autocomplete select in the app selection, where if you selected the first result after searching for an app it wouldn't select that, but instead it would select the first item of the initial list.
The core of the issue is that the `AutocompletePrompt` was removing and hence unmounting the `SelectInput` component when the state changed, but that would mean the internal state of `SelectInput` wouldn't be preserved and we rely on that to trigger `onChange` when the items change.
I've then moved the helper messages logic to `SelectInput` itself so that it can stay in the tree.
I've also fixed an issue with pagination. Items were being reset to the original not sliced list when the input was cleared.
- Run `shopify app dev --reset`
- Try searching for …
=> Fix AutocompletePrompt resetting the SelectInput state

packages/cli-kit/src/private/node/ui/components/SelectInput.test.tsx, packages/cli-kit/src/private/node/ui/components/SelectInput.tsx
@pacocastrotech reported an issue with `SelectInput` throwing error if non existent keys were being pressed.
I've fixed the issue by ignoring non existent keys.
- Run `shopify kitchen-sink prompts`
- In the first select try pressing `11`
- Nothing should happen
=> Fix bug with SelectInput and non existent keys

packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.test.tsx, packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.tsx, packages/cli-kit/src/private/node/ui/components/SelectPrompt.tsx, packages/cli-kit/src/private/node/ui/components/TextPrompt.tsx, packages/cli-kit/src/private/node/ui/utilities.ts
As mentioned [here](https://github.com/Shopify/cli/issues/1147) we want to remove the colon in the AutocompletePrompt text.
This PR removes the colon.
=> Remove colon in AutocompletePrompt

packages/app/src/cli/services/deploy/theme-extension-config.test.ts, packages/app/src/cli/services/deploy/theme-extension-config.ts
Theme app extensions could not be deployed any longer
Use correct variable instead of function. Also adds test to verify correct behaviour.
- Create new app
- Add theme app extension
- Deploy
=> Fix regression caused by using function instead of variable

dev.yml
Whenever we change `package.json` we tell shopifolks to run `dev up`, but it doesn't rerun `pnpm install`
Hack a bit around the custom task syntax to ensure that every time we run `dev up` we also run `pnpm install`.
Basically the way dev works is:
- it checks `met?`
- if it returns false, it crashes
- if it returns true, it runs the `meet` callback
In this change, we set `met?` to `pnpm install` and `meet` to true (a unix command that always returns true)
- Add a dependency in the package.json
- Notice dev telling you to run `dev up`
- Running `dev up` should install the new dep (there is no output, check with `git status`)
=> Always run pnpm install when running dev up

packages/app/src/cli/prompts/webhook/options-prompt.test.ts, packages/app/src/cli/prompts/webhook/options-prompt.ts, packages/app/src/cli/prompts/webhook/trigger.test.ts, packages/app/src/cli/prompts/webhook/trigger.ts, packages/app/src/cli/services/webhook/request-api-versions.ts, packages/app/src/cli/services/webhook/request-sample.ts, packages/app/src/cli/services/webhook/request-topics.test.ts, packages/app/src/cli/services/webhook/request-topics.ts, packages/app/src/cli/services/webhook/trigger-options.ts, packages/app/src/cli/services/webhook/trigger.test.ts, packages/app/src/cli/services/webhook/trigger.ts
https://github.com/orgs/Shopify/projects/4831/views/1?pane=issue&itemId=8991753
Fast follow up to our first version
We want to validate the topic ASAP in the client. For that means, we collect the available topics and force the user to use a valid one from an autocomplete list
**Before:** 
The user has to add a topic in an free text input box
**After:**
Use the following branches:
* Partners: available-webhook-topics-endpoint (https://github.com/Shopify/partners/pull/44762)
* Core: apiversion-topics-cli-endpoint (https://github.com/Shopify/shopify/pull/400352)
None yet
=> [Feature] Change webhook topic DX offering autocompletion

.changeset/warm-tools-wash.md, packages/cli-kit/src/public/node/fs.test.ts, packages/cli-kit/src/public/node/fs.ts
We found some issues when formatting large typescript files using the babel parser in hydrogen. This PR specifically uncovered [the issue](https://github.com/Shopify/h2/pull/365) and found that adding that specifying the `typescript` parser resolved this issue. 
Sets the 'typescript' parser explicitly for typescript extensions (.tsx and .ts)
I've added tests to demonstrate the desired behaviour.
=> Set TypeScript parser explicitly when formatting .ts and .tsx files

packages/app/src/cli/services/dev/extension/payload.test.ts, packages/app/src/cli/services/dev/extension/payload.ts, packages/app/src/cli/services/dev/extension/payload/models.ts, packages/app/src/cli/services/dev/extension/payload/store.test.ts, packages/app/src/cli/services/dev/extension/payload/store.ts, packages/ui-extensions-dev-console/src/sections/Extensions/components/ExtensionRow/components/PreviewLinks/PreviewLinks.tsx, packages/ui-extensions-server-kit/src/types.ts
Enable support for resource.url per extension point.
Currently the extension points array creates a union when the update payload comes in because it doesn't account for objects. For example, when the current payload is `[{target: 'A', {target: 'B'}]` and the update payload is  `[{target: 'A', {target: 'B', foo: 'bar'}]`  we get a combined array of `[{target: 'A', {target: 'B'}, {target: 'A', {target: 'B', foo: 'bar'}] `
Add special logic to merge extension points when the array contain extension points objects.
The unit tests should cover the changes
=> Enable Dev Server to handle updates to extension points payload and support resource.url per extension point

.changeset/sour-games-happen.md, packages/theme/src/cli/services/delete.test.ts, packages/theme/src/cli/services/delete.ts, packages/theme/src/cli/services/publish.test.ts, packages/theme/src/cli/services/publish.ts
Following the https://github.com/Shopify/cli/issues/1171 issue and the DX feedback, this PR adds periods in the end of sentences.
This PR adds periods in the end of sentences.
None.
=> Slightly improve the text messages in the `shopify theme delete` and `shopify theme publish` commands

.changeset/many-zoos-care.md, packages/cli-kit/src/public/node/ruby.ts
I've extracted this fix from https://github.com/Shopify/cli/pull/1185
Fix execCLI2 running tasks inside renderConcurrent. Previously renderTasks was trying to be rendered inside renderConcurrent, but that's not possible.
- Run `pnpm shopify app dev --path fixtures/app`
- Output shouldn't break
=> Fix issue with CLI2 process printing tasks inside concurrent output

.github/workflows/benchmark.yml, .github/workflows/shopify-cli.yml
Some GitHub Actions are not working on forks (like [here](https://github.com/Shopify/cli/pull/1035)) because of missing permissions. 
Specifically, the failing steps are benchmark and coverage because both use an action to comment on the PR.
We could use the [pull_request_target event](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target), but it's not recommended for security reasons in our case, as we build and run code. More details [here](https://securitylab.github.com/research/github-actions-preventing-pwn-requests).
Skip the benchmark and coverage steps on forks, as it's not essential.
We have to merge 🤷 
=> Skip benchmark and coverage steps on forks

.changeset/modern-chefs-trade.md, packages/app/src/cli/services/dev.ts
In https://github.com/Shopify/cli/pull/1194 I forgot to include this change as well, so they fix didn't really go live.
=> Fix an issue with CLI2 not printing to the right stdout

packages/app/src/cli/services/dependencies.ts, packages/app/src/cli/services/generate/extension.ts, packages/cli-hydrogen/src/cli/services/eslint.ts, packages/cli-hydrogen/src/cli/services/tailwind.ts, packages/create-app/src/utils/template/npm.test.ts, packages/create-app/src/utils/template/npm.ts
When you create a node app, our task list is printing this messages:
- `Installing dependencies in / ...`
- `Installing dependencies in /web/ ...`
- `Installing dependencies in /web/frontend/ ...`
This is mildly alarming as it looks we are installing things at the root of the filesystem.
Change the above messages to:
- `Installing dependencies ...`
- `Installing dependencies in web/ ...`
- `Installing dependencies in web/frontend/ ...`
Also make sure we use 'Installing dependencies' messaging consistently.
- Create a new node app
=> Improve the message we display when installing deps

.changeset/stupid-kangaroos-suffer.md, packages/app/src/cli/models/extensions/schemas.ts, packages/app/src/cli/models/extensions/ui-specifications/pos_ui_extension.ts, packages/app/templates/ui-extensions/projects/pos_ui/shopify.ui.extension.toml.liquid
Unblocks https://github.com/Shopify/shopify/pull/402073
Required to resolve https://github.com/Shopify/pos-next-react-native/issues/20351
For the [Native App Extensions for POS](https://vault.shopify.io/gsd/projects/21763) project we need to support merchants easily differentiating between extensions in a human-friendly manner.
The [registration title is consider internal and only viewable to the partner](https://github.com/Shopify/extensions-runtime/pull/285#issuecomment-1404131949), so instead we can put a "description" into the extension config and provide that to POS. Partners will specify this description via shopify.ui.extension.toml - which is what this PR enables.
```bash
$ pnpm run generate extension
> my-app-1@1.0.0 generate /Users/me/my-app-1
> shopify app generate "extension" …
```
=> Add description to POS UI Extension

package.json, packages/app/package.json, packages/cli-hydrogen/package.json, packages/cli-kit/package.json, packages/cli/package.json, packages/create-app/package.json, packages/create-hydrogen/package.json, packages/features/package.json, packages/plugin-ngrok/package.json, packages/theme/package.json, packages/ui-extensions-dev-console/package.json, packages/ui-extensions-server-kit/package.json, packages/ui-extensions-test-utils/package.json, pnpm-lock.yaml
We recently had a bug https://github.com/Shopify/cli/pull/1156 that would have been caught by the latest TS compiler.
- Upgrade to latest TypeScript.
- Fix version of `@types/node` everywhere to latest version available for node 14 (which is the oldest we support).
- Edit `packages/app/src/cli/services/deploy/theme-extension-config.ts`
- Change `files[relativePathName]` to `files[relativePath]`
- You should see the TS compiler complaining about it with
`type '(from: string, to: string) => string' cannot be used as an index type`
=> Upgrade to TypeScript 4.9.4

.changeset/fast-ants-invite.md, packages/app/src/cli/models/extensions/schemas.ts, packages/app/src/cli/models/extensions/ui-specifications/ui_extension.test.ts, packages/app/src/cli/models/extensions/ui-specifications/ui_extension.ts, packages/app/src/cli/services/dev/extension/payload.test.ts, packages/app/src/cli/services/dev/extension/payload.ts, packages/app/src/cli/services/dev/extension/payload/models.ts
We are working on adding [API versioning](https://github.com/Shopify/ui-extensions-private/discussions/1931) to checkout UI extensions, and are planning to do it as part of migrating to the new UI extension type. This PR adds the code to the CLI to have it pass the API version from a developer's extension configuration file, to the dev server and deploy commands.
In this PR, I've included the four versions we are likely to care about for the initial release: `2023-01` (the first real version), `2022-10` (a backfilled version that gets developers on the new UI extension, without the breaking API changes introduced in `2023-01`), `unstable` (the most recent public version of the API), and `internal` (the most recent private version of the API). There is more detail about the proposed …
=> [Feature] Add `api_version` to UI extension type

.changeset/cuddly-papayas-own.md, packages/theme/src/cli/services/package.test.ts, packages/theme/src/cli/services/package.ts
Fixes https://github.com/Shopify/cli/issues/1249
Fix to add template/customers sub directory to be added to zip file when matching directories
- Checkout branch 
- `pnpm shopify theme init` or use existing Dawn theme
- `pnpm shopify theme package --path /path/to/package`
- Open zip file and navigate to templates directory, confirm customers sub directory included
=> Fix to include customer JSON templates in `theme package`

packages/app/src/cli/models/extensions/ui-specifications/customer_accounts_ui_extension.ts
Adds localization to the deployment of customer accounts extensions. This PR basically reverts the changes we had to do in this [old PR here](https://github.com/Shopify/cli/pull/725).
**Depends on:**
- https://github.com/Shopify/shopify/pull/403936
- adds `localization` to the deployment of customer accounts extensions
- [Instance](https://development-store-1.account.shopify.localization.filipe-correa.eu.spin.dev/e/ea089092-1013-47b8-83ed-7321e74e50d6)
- [Identity Mailer](https://identity.localization.filipe-correa.eu.spin.dev/services/mail/)
- The instance contains a deployed customer accounts extension with locales.
1. Navigate to [self-serve hub](https://development-store-1.account.shopify.localization.filipe-correa.eu.spin.dev/e/ea089092-1013-47b8-83ed-7321e74e50d6)
2. Sign in with …
=> [Feature] add localization to deployment (customer_accounts_ui)

packages/app/src/cli/api/graphql/extension_migrate_to_ui_extension.ts, packages/app/src/cli/services/dev/migrate-to-ui-extension.test.ts, packages/app/src/cli/services/dev/migrate-to-ui-extension.ts, packages/app/src/cli/services/environment/id-matching.ts, packages/app/src/cli/services/environment/identifiers-extensions.test.ts, packages/app/src/cli/services/environment/identifiers-extensions.ts, packages/app/src/cli/services/environment/prompts.ts
WIP PR to confirm this is the experience we want.
Partially implements https://github.com/Shopify/shopify/issues/398990 
Deploy now checks for extensions that changed type from 'checkout_ui` to `ui_extension`.  If it finds any, it prompts the user to migrate the extension.  If they cancel deploy is cancelled.  If they accept the CLI performs a graphQL mutation.  Right now the GraphQL mutation is not in prod, but can be seen here: https://github.com/Shopify/partners/pull/44865
1. `pnpm clean && pnpm install && pnpm build`
2. `pnpm shopify app deploy --path ./fixtures/app --verbose` to deploy the existing extensions.
3. Edit `shopify.ui.extension.toml` to migrate the checkout_ui extension. It should be like this:
```
name = "checkout-ui"
[capabilities]
api_access = true
network_access = …
```
=> [WIP] Migrate checkout UI extension

.changeset/config.json
Hydrogen packages are being developed and published to the NPM registry from the https://github.com/shopify/h2 and therefore we should stop publishing them from here.
I'm adjusting the changesets configuration to untie the versioning of the packages from the rest of the packages in the monorepo.
=> Not release Hydrogen

packages/cli/package.json, packages/features/snapshots/commands.txt, pnpm-lock.yaml
The workflow that bumps the versions [is failing](https://github.com/Shopify/cli/actions/runs/4084144314/jobs/7040497134) because `@shopify/cli-hydrogen` is ignored but `@shopify/cli` depends on it as a `devDependency`.
I'm removing `@shopify/cli-hydrogen` as a dev dependency of `@shopify/cli`.
You can checkout this branch, change [this pipeline](https://github.com/Shopify/cli/blob/main/.github/workflows/release.yml#L7) to run on your branch, and push it upstream.
=> Remove the dev dependency between `@shopify/cli` and `@shopify/cli-hydrogen`

.changeset/config.json
Changeset [doesn't like](https://github.com/Shopify/cli/actions/runs/4084690749/jobs/7041689317) having a mix of ignored and not-ignored packages and that's causing the release workflow to fail.
Removing the `ignored` list. Since they are removed from the `fixed` list and we are not including changesets for the `create-hydrogen` and `hydrogen` packages, the versioning will yield no updates for them.
`pnpm changeset version` should run successfully
=> Remove ignored from changeset's configuration

packages/app/src/cli/services/webhook/send-app-uninstalled-webhook.test.ts
I merged a couple new eslint rules [here](https://github.com/Shopify/cli/pull/1283), but my `main` branch was out of date.
Fix leftover test.
=> Get webhook test to pass new eslint rules

packages/cli-hydrogen/package.json, packages/create-hydrogen/package.json
Hydrogen packages are not released anymore from this repository and [Version Packages PR](https://github.com/Shopify/cli/pull/1246) was not generating the expected versions.
Make the packages private
`p changeset version`
=> Make Hydrogen packages private

.changeset/forty-cobras-warn.md, packages/app/src/cli/services/conf.test.ts, packages/app/src/cli/services/conf.ts
Paths are weird. At some points in the CLI execution, when working on windows, a directory path might use `/` or `\`. 
Since we use the the directory as the key to store local information about the app, this led to inconsistencies reading the cached values.
- Normalize the directory path before getting/setting values
- `yarn dev` caches any selected value and a 2nd run should load those values.
- `yarn run info` should read the same values
=> Fix: conf store not saving some values on windows

.github/actions/download-and-publish-test-coverage/action.yml, .github/actions/run-and-save-test-coverage/action.yml, .github/actions/setup-cli-deps/action.yml, .github/workflows/benchmark.yml, .github/workflows/changelog-reminder.yml, .github/workflows/cla.yml, .github/workflows/cli-ruby.yml, .github/workflows/release.yml, .github/workflows/reviewers-reminder.yml, .github/workflows/shopify-cli.yml, .github/workflows/stale.yml, .github/workflows/workflow-cleaner.yml, bin/pin-github-actions.js, package.json, packages/features/features/github-actions.feature, packages/features/steps/github-actions.steps.ts, pnpm-lock.yaml
We use quite a lot of open source Github actions, which are inherently vulnerable to supply chain attacks.
- Pin all unofficial Github actions to a specific sha
- add a feature test to verify that all unofficial github actions are pinned
- unpin any OSS github action
- run `cd packages/features`
- run `FEATURE=features/github-actions.feature pnpm test`
- you should see this test failing
```
1) Scenario: All non-official github actions are pinned # features/github-actions.feature:3
✔ When I look at the github actions we use # steps/github-actions.steps.ts:6
✖ Then I see all non-official actions being pinned # steps/github-actions.steps.ts:11
AssertionError [ERR_ASSERTION]: The following unofficial github actions have not been pinned:
- mxschmitt/action-tmate@v3
Run the …
```
=> Pin all unofficial github actions

.changeset/blue-dots-build.md, packages/app/src/cli/models/app/app.test-data.ts, packages/app/src/cli/services/deploy.test.ts, packages/app/src/cli/services/deploy.ts, packages/app/src/cli/services/deploy/bundle.ts, packages/app/src/cli/services/deploy/upload.ts
A bug was reported that theme extensions were not being uploaded. It's true in the case where you don't have other UI extensions.
Fixes https://github.com/Shopify/cli/issues/1311
- Enable bundling if there are any `ui` OR `theme` extensions.
- Create a new project with just a theme app extension and try to deploy, you should see a new version in your partners dashboard
=> Fix theme extensions not being bundled when there are no other ui extensions

.changeset/long-melons-burn.md, .github/workflows/cli-ruby.yml, packages/cli-kit/assets/cli-ruby/.npmignore, packages/cli-kit/assets/cli-ruby/shopify-cli.gemspec
Fixes https://github.com/Shopify/cli/issues/1308
Fixes https://github.com/Shopify/cli/issues/1320
- Exclude `.ruby-version` from cli-kit NPM package
- Relax bundler version requirements for bundled CLI
- Install bundler 2.4 and run `shopify theme dev`
=> Fix theme issues with bundler and Ruby version managers

.changeset/spotty-ways-jump.md, packages/cli-kit/src/public/node/ruby.test.ts, packages/cli-kit/src/public/node/ruby.ts
Some problems have appeared using the embedded version of `cli-ruby` to run `themes` commands or `dev` command with `theme-app-extensions`
Those problems seem to be related with the method used to install Ruby requirements in the local environment. There are also some problems with `theme-app-extensions` in windows as well
- Every command related with `themes` and `theme-app-extension` will use the bundled version of `cli-ruby`
- Add a the new env variable `SHOPIFY_CLI_EMBEDDED_THEME_CLI` to run the command using the embedded version.
- Run any `theme` command with `--verbose` flag and you should see an output similar to this:
```
Running system process:
· Command: bundle exec shopify theme check /Users/alvarogutierrez/cli-themes/first-theme --output text
· Working directory: …
```
=> Bundled cli-ruby used by default

.changeset/clever-paws-double.md, packages/cli-kit/assets/cli-ruby/.npmignore
Fixes https://github.com/Shopify/cli/issues/1320
The Gemfile.lock was forcing to use bundler 2.3.20, but we are not ensuring it is present
Remove useless Gemfile.lock from the NPM package
- `brew install shopify-cli`
- Temporarily remove `/opt/homebrew/lib/ruby/gems/3.2.0/gems/bundler-2.3.20/exe/bundle`
- `shopify theme dev` should raise an error about bundler not being found
- `rm /opt/homebrew/Cellar/shopify-cli/3.42.0/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/Gemfile.lock`
=> Fix embedded CLI (remove Gemfile.lock)

.changeset/silent-bats-invite.md, packages/app/src/cli/services/deploy.test.ts, packages/app/src/cli/services/deploy.ts, packages/app/src/cli/services/extensions/bundle.ts, packages/cli-kit/src/private/node/constants.ts, packages/cli-kit/src/public/node/context/local.ts
Theme bundling was turned on by default and resulted in a lot of deployment errors popping up for partners. We want to revert this change to give us more time to investigate the issue before turning it back on. 
Fixes https://github.com/Shopify/cli/issues/1325
Changing the environment variable to be opt-in usage instead of opt-out. 
=> Reverting theme-bundling on by default

packages/cli-kit/src/private/node/api/headers.test.ts, packages/cli-kit/src/private/node/api/headers.ts
Something I noticed when using cli-kit for my hackdays project. For some reason, `Bearer` needs to be left out of the headers when using a custom app access token. This is preventing us from leveraging the existing `adminRequest` using a pseudo AdminSession.
Removes `Bearer` from the header when using a `shpat` token (i.e. custom token from the store dashboard)
1. Generate a custom access token
2.
```js
const query = "{ shop { name }}"
const adminSession = {
storeFqdn: "MY_STORE.myshopify.com",
token: "shpat_whatever"
}
await adminRequest(query, adminSession)
```
=> Don't use Bearer in header when shpat token

packages/cli-kit/src/public/node/path.test.ts
Cwd tests would fail if ran through a node script, such as `pnpm test`
Only run path.cwd test if executed from a node script
- `pnpm test`
=> Run cwd test only if env var is defined

packages/cli-kit/assets/cli-ruby/test/shopify-cli/commands/populate/product_test.rb, packages/cli-kit/assets/cli-ruby/test/test_helper.rb
A [Ruby test](https://github.com/Shopify/cli/actions/runs/4165833712/jobs/7209375738) failed as part of a PR that didn't modify any Ruby code.
I'm disabling the test and customizing the `MiniTest` reporter to output the failing tests at the bottom. This will help spot the failing tests quicker. I'll refrain from creating an issue to fix it because it's logic that we no longer use in the CLI 3 so it doesn't make sense investing in fixing it.
CI should be green.
=> I'm disabling the flaky test `test_populate_if_no_shop`

.changeset/thick-trainers-rhyme.md, .eslintrc.cjs, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/hot_reload.rb, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/hot_reload/script_injector.rb
Fixes #1119
When HMR code (`SSRClient` etc.) is injected into the HTML returned by `/`, no CORS error happens, and HMR is running. However, URL `http://127.0.0.1:9292/web-pixels-manager@0.0.219/sandbox/` is being requested too. This URL returns HTML, in which HMR code is injected and tried to be loaded a second time, “thankfully” leading to the CORS error, because the `Origin` is `null`.
Injects HMR code for all requests which return HTML **and** whose URL is not matching `web-pixels-manager…sandbox`.
1. Serve your favorite theme with `shopify theme dev`
2. Open your browser’s Network tab and make sure that `/hot-reload` is only called **once**.
3. Open your browser’s console and make sure that no CORS errors appear anymore.
=> Do not inject hot-reload code into web-pixels-manager sandbox

bin/prettify-manifests.js, package.json, packages/app/oclif.manifest.json, packages/cli-hydrogen/oclif.manifest.json, packages/cli/oclif.manifest.json, packages/create-app/oclif.manifest.json, packages/create-hydrogen/oclif.manifest.json, packages/plugin-ngrok/oclif.manifest.json, packages/theme/oclif.manifest.json
Current oclif manifests are not human readable and when they are updated, it's impossible to understand the diffs
Prettify all the manifests after refreshing them
`pnpm refresh-manifests`
=> Prettify oclif manifests

packages/cli-kit/src/public/node/context/local.test.ts, packages/cli-kit/src/public/node/context/local.ts, packages/cli-kit/src/public/node/context/spin.ts
Improves the internal Shopify developer experience by defaulting to the most common use case. 
This change could be merged on its own, but it should depend on https://github.com/Shopify/partners/pull/45140 which removes the binary choice between the Shopify or Italic apps org; instead both will be returned.
Enables `firstPartyDev` mode when in Spin.
Run `yarn dev --reset` or `yarn deploy --reset` to see the list of partner organizations fetched.
=> [Feature] Set firstPartyDev to true when env is Spin

packages/ui-extensions-dev-console/src/components/Tooltip/tests/Tooltip.test.tsx
Tooltips presently have no tests so I added some, albeit basic tests that cover:
- component visibility when hovered/focused and when not
- verify ENTER key forwarding to interactable component child
=> add tests for tooltip

.changeset/spicy-parrots-do.md, fixtures/app/web/package.json, packages/app/src/cli/utilities/app/http-reverse-proxy.test.ts, packages/app/src/cli/utilities/app/http-reverse-proxy.ts, packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx, pnpm-lock.yaml
Whenever one of the processes connected to the proxy crashes, the CLI crashes as well.
Add error handling to the proxy we use for web requests and websockets.
=> Improve error handling in proxy 

workspace/src/benchmark.js
The benchmarking workflow yields non-deterministic numbers in PRs. This PR is an attempt to reduce the non-determinism by ignoring the results of the first iteration assuming the engine does some optimizations that persist across runs.
This might not work as expected because GitHub Actions is most likely sharing the virtual environment in which the workflows run with other virtual environments and therefore the CPU and the Memory that's available is impacted by the load of other jobs running in the same host. The only way to achieve full determinism is running it in a more controlled environment like our laptops or a baremetal host.
I adjusted the `benchmark.js` script to ignore the first results.
We should see the report in this PR. …
=> Skip first run

.github/workflows/checks.yml, workspace/src/benchmark.js
The comment that posts the benchmark results in PRs adds a lot of noise.
I adjusted the logic to only report the results if there are commands with a high deviation in startup time. Only those commands are listed on the table. 
We shouldn't see the table posted in this PR.
=> Only report benchmark results if there are commands with high deviation

.changeset/five-books-wave.md, packages/cli-kit/src/public/node/ruby.test.ts, packages/cli-kit/src/public/node/ruby.ts
Related to https://github.com/Shopify/cli/issues/1314
Windows gem dependencies needed for the `theme-app-extension` are not installed when the embedded `cli-ruby` version is used so this error is displayed
- Added windows gem dependencies when the embedded `cli-ruby` is used
- Run a `dev` command for an app with `theme-app-extension` in windows.
=> Added windows gem depencies to embedded cli-ruby

.changeset/curvy-papayas-travel.md, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb, packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/dev_server/proxy_test.rb
When you run the `dev` command with a `theme app extension` the cli is running the ruby-cli `extension serve` command. This command is running a http server that allows the user to preview the content of the extension. 
This feature is working when you run the command against `shopify.com` but not when the command uses a `spin` environment.
These are the verbose messages of the proxy when it's working properly
These ones are when it run against `spin`
- Add support to the theme app extension server for spin domains
- Run the following command `NODE_TLS_REJECT_UNAUTHORIZED=0 SHOPIFY_SERVICE_ENV=spin SPIN_INSTANCE=$(spin show -o name) yarn shopify app dev` with an app that includes a theme app extension
=> Fixed problem with theme app extension server in spin

.changeset/slimy-cherries-smoke.md, packages/cli-kit/assets/cli-ruby/lib/project_types/theme/commands/push.rb, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/syncer.rb, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/syncer/standard_reporter.rb, packages/cli-kit/assets/cli-ruby/test/project_types/theme/commands/push_test.rb, packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/syncer_test.rb
Fixes https://github.com/Shopify/cli/issues/1377
When some bulk upload fails, the `Syncer::Uploader` relies on regular uploads as a fallback, however, regular uploads print success messages even when the `--json` flag is passed.
This PR fixes that by deactivating the `standard_reporter` when the `--json` flag is passed.
- First of all, let's emulate the fallback scenario
- Open the `packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/syncer/uploader.rb`
- Update the `bulk_upload!` method with this body:
```ruby
def bulk_upload!
update_progress_bar!
enqueue_bulk_updates(liquid_files)
enqueue_bulk_updates(json_files)
enqueue_bulk_updates(config_files)
enqueue_updates(static_asset_files)
wait!(&@update_progress_bar_block) unless delay_low_priority_files?
end
```
- Now, run `shopify-dev …
=> Fix: The `Syncer::Uploader` should not report IO messages when the `--json` flag is passed

packages/cli-kit/src/private/node/conf-store.test.ts, packages/cli-kit/src/private/node/conf-store.ts, packages/cli-kit/src/private/node/session/identity-token-validation.ts
Replaces https://github.com/Shopify/cli/pull/712
Fixes https://github.com/Shopify/internal-cli-foundations/issues/489 with the blessing of the identity team
The identity introspection endpoint is supposed to be fetched dynamically, BUT that makes less sense for the CLI which launches a new process frequently while a user sits there, vs. servers spinning up which can take a half-second hit.
This small change will make most command runs up to 0.5s faster on average (since most frequently-used commands require authentication).
Caches the identity introspection endpoint for a period of 1 week. If the existing endpoint 404s, we can retry with fetching the correct endpoint first, as we do now.
It's technically slower in the rare case of the endpoint changing, but honestly I don't think it's …
=> Cache identity introspection endpoint

.changeset/curvy-fishes-buy.md, packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/context.ts, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/select-store.ts, packages/cli-kit/src/private/node/api/graphql.ts, packages/cli-kit/src/private/node/api/headers.test.ts, packages/cli-kit/src/private/node/api/headers.ts, packages/cli-kit/src/private/node/session.test.ts, packages/cli-kit/src/private/node/session.ts, packages/cli-kit/src/public/node/api/admin.ts
Partners requests are the heaviest part of initiating the `app dev` command. By running some of them in parallel (plus a few other small optimizations), we can shave about 1.3 seconds off command startup in most cases. This makes for a much snappier CLI experience.
1. Take Partners API GraphQL queries that can be run in parallel (i.e. they don't depend on each other) and make them parallel.
2. Use keepAlive to ensure we don't waste time re-establishing the connection to the Partners API each time
3. Eliminate waste. Don't save the session to secure storage (which takes about 20-30ms) if the session hasn't changed.
Make sure `app dev` still works in `--reset`, cached, and non-cached cases.
=> Parallelize partners requests

.changeset/cuddly-months-draw.md, packages/cli-kit/assets/cli-ruby/Gemfile, packages/cli-kit/assets/cli-ruby/Gemfile.lock, packages/cli-kit/src/public/node/ruby.ts
Fixes #1327 
Older cli-ruby was using `gemspec` to run several configurations needed to registry the cli as a gem. Once we copied the whole content of the cli2 repo to the cli3 this script is not needed anymore and in fact it was causing an error message in Windows when the `gemspec` set the list of files that should be added to the gem using `git`.
- Moving needed dependencies directly to `Gemfile` and remove the using of the `gemspec` file 
Run any `theme` command in Windows enabling the embedded cli-ruby
```sh
$Env:SHOPIFY_CLI_EMBEDDED_THEME_CLI="1"
shopify theme dev
```
=> Move embedded cli-ruby dependencies to Gemfile

.changeset/rude-geckos-raise.md, packages/cli-kit/src/public/node/environment.ts, packages/cli-kit/src/public/node/ruby.test.ts, packages/cli-kit/src/public/node/ruby.ts
In the first try to use the `embedded cli-ruby` some problems arise so we had to [revert the activation ](https://github.com/Shopify/cli/pull/1346) and opt-it by default only for `shopifolk` users.
There were three main problems:
* Running the Ruby `shopify-cli` bin script using the `env` Ruby version. Solution [PR](https://github.com/Shopify/cli/pull/1304)
* Running `bundler` with a fixed version because of the `Gemfile.lock` presence. Solution PR](https://github.com/Shopify/cli/pull/1347)
* Missed the installation of specific gems in Windows for `theme-app-extension`. Solution [PR](https://github.com/Shopify/cli/pull/1350)
- Modify the check condition that evaluates when the `embedded cli-ruby` must be used. Now is opted-in by default and the environment variable …
=> Embedded cli-ruby opt-in by default

.changeset/shy-comics-arrive.md, packages/app/src/cli/services/function/common.ts, packages/theme/src/cli/commands/theme/dev.ts
Bugs found during the release QA
- JS functions weren't loading correctly if there were other UI extensions present, fixed that.
- Theme dev was adding an extra waiting time that wasn't necessary on the first run.
=> Fix loading JS functions & Improve theme dev loading time

.changeset/shy-windows-poke.md, packages/app/src/cli/services/dev.ts
In order to avoid [non-populated host themes](https://github.com/Shopify/cli/pull/1264#pullrequestreview-1295240819), they should be populated _every time_, until Ruby CLI dependency has been removed.
Treats a host theme as always `createdAtRuntime`, so that `--generate-tmp-theme` is always passed to CLI 2.
- `shopify app dev` in your favorite app directory.
=> Always populate host theme

packages/cli/src/cli/services/upgrade.test.ts, packages/cli/src/cli/services/upgrade.ts
Currently running `shopify upgrade` on a homebrew executable does not update the homebrew executable. Instead it says:
```
$ shopify upgrade
Upgrading CLI from 3.44.0 to 3.44.1...
Homebrew installation detected. Attempting to upgrade via brew upgrade...
Warning: shopify/shopify/shopify-cli 3.44.0 already installed
✅ Success! Upgraded Shopify CLI to version 3.44.1.
```
but the version remains unchanged:
```
$ shopify --version
@shopify/cli/3.44.0 darwin-arm64 node-v19.7.0
```
this is because we fetch the latest version from npm, but we are not updating the brew sources.
Run `brew update` before `brew upgrade shopify-cli`
=> We need to update brew before upgrading the cli

fixtures/app/package.json, pnpm-lock.yaml
What the title says
- `pnpm shopify auth logout`
- logout from https://partners.shopify.com/
- (only once) Login to partners internal with your shopify account
- Find your organization and enable the “Customer accounts ui extensions” beta
- `pnpm shopify app dev --path fixtures/app --reset`
- Install the app on your store and verify it loads
- `pnpm shopify app deploy --path fixtures/app`
=> Update dependencies on fixture app, make sure you can dev and deploy it

tsconfig.json
@nikijiandani noticed that Typescript was complaining about the reference to `./workspace` from the root `tsconfig.json`. 
The reference is not necessary. The `./workspace` directory doesn't have a `tsconfig.json`
=> Remove invalid reference in the workspace `tsconfig.json`

packages/cli-kit/src/public/node/ruby.ts
I noticed that we're making users install development and test gems when they're installing CLI2. Those gems are only necessary while developing the library, but not at runtime. 
Skip development and test gems when installing CLI2
On the `main` branch.
- Make sure to remove these local folders:
- `rm -rf packages/cli-kit/assets/cli-ruby/{ruby,.bundle}`
- Now create a theme:
- `pnpm shopify theme init "theme-fun-$(date '+%Y-%m-%d')" && cd theme-fun-$(date '+%Y-%m-%d')`
- `pnpm shopify theme dev --store=<your-store>` should work
- you can check live reload works on the theme
- If you run `ls -al ../packages/cli-kit/assets/cli-ruby/ruby/3.1.0/gems/ | wc -l` you should see **73 packages**
Now switch to this branch.
- Make sure to remove these local folders:
- `rm -rf …
=> Don't make users install dev or test gems when bundle installing

.changeset/neat-avocados-peel.md, packages/app/src/cli/services/dev/extension/payload.test.ts, packages/app/src/cli/services/dev/extension/server/utilities.test.ts, packages/app/src/cli/services/dev/extension/utilities.ts
Adds support for both the `Admin::XX::XX` syntax and the `admin.x.x` syntax when extracting the surface of an extension. This will allow to fix the issue where `No extensions found for the surface: admin` is returned in the embedded admin console.
Just  changing the regex to support both `::` or `.` as delimiter. (Can current extension points use a `.` that would influence this?)
=> support new extension point names format

.changeset/pretty-dryers-drop.md, packages/app/templates/ui-extensions/projects/ui_extension/shopify.ui.extension.toml.liquid
The existing template for `ui_extension` is missing the require `api_version` in the TOML. I've set this to the default `2022-10` version. 
NOTE: There will be further changes to the template when this [PR](https://github.com/Shopify/cli/pull/1275) is revived
=> Add missing api_version in ui-extension template

.changeset/blue-jokes-worry.md, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb, packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/dev_server/proxy_test.rb
While previewing a theme, both the CLI and Chrome consoles show a lot of errors related to analytics requests that are not needed:
Ignore requests to monorail, mini-profiler or web pixels, so that the consoles are clean:
`shopify theme dev --verbose`
=> Clean errors on theme dev

.changeset/great-guests-yell.md, packages/cli-kit/src/private/node/ui/hooks/use-layout.test.ts, packages/cli-kit/src/private/node/ui/hooks/use-layout.ts
Fixes https://github.com/Shopify/internal-cli-foundations/issues/559
Buildkit has a very narrow stdout and was producing very weird squeezed logs.
For terminals narrower than 20 characters we want to force a minimum width of 20.
Resize your terminal to less than 20 characters and run kitchen-sink. Boxes should look a bit broken unless you resize the terminal up.
=> Fix layout width for very narrow terminals

fixtures/app/web/frontend/package.json, packages/app/package.json, packages/cli-kit/package.json, pnpm-lock.yaml
Related to https://github.com/Shopify/internal-cli-foundations/issues/502
Our current `graphql-request` version is a CommonJS dependency, so it's not loaded concurrently with the rest of ESM modules. 
Upgrades `graphql-request` to the latest version, which [supports ESM](https://github.com/jasonkuhrt/graphql-request/releases/tag/5.2.0).
`shopify app dev`
=> Upgrade graphql-request (ESM)

bin/prettify-manifests.js, packages/app/oclif.manifest.json, packages/app/src/cli/commands/app/build.ts, packages/app/src/cli/commands/app/deploy.ts, packages/app/src/cli/commands/app/dev.ts, packages/app/src/cli/commands/app/env/pull.ts, packages/app/src/cli/commands/app/env/show.ts, packages/app/src/cli/commands/app/function/schema.ts, packages/app/src/cli/commands/app/generate/extension.ts, packages/app/src/cli/commands/app/info.ts, packages/app/src/cli/flags.ts, packages/app/src/cli/services/function/common.ts, packages/cli-kit/src/public/node/base-command.test.ts, packages/cli/oclif.manifest.json, packages/cli/src/cli/commands/upgrade.ts, packages/create-app/oclif.manifest.json, packages/create-app/src/commands/init.ts, packages/theme/src/cli/commands/theme/init.ts, packages/theme/src/cli/commands/theme/package.ts, packages/theme/src/cli/commands/theme/pull.ts, packages/theme/src/cli/commands/theme/share.ts, packages/theme/src/cli/flags.ts
I noticed that theme commands didn't work well handling the local folder as the root of the commands
- Unify how we handle `path` flags everywhere
- Move parsing and defaulting logic inside the definition of the flag itself
- Switch to `async` style when defining custom `parse` functions
- from the cli repo
- `pnpm shopify theme init "theme-preview-2023-03-01" && cd theme-preview-2023-03-01`
- `pnpm shopify theme check` should work
- before this PR you would have to write `pnpm shopify theme check --path theme-preview-2023-03-01` and pass the path again
=> Improve how we handle the `path` flag

.github/workflows/shopify-cli.yml, bin/create-test-app.js, dev.yml, package.json
Add a cross-env script to test releases
- `node bin/create-test-app.js`
- this command will create a new app on your Desktop called `nightly-app-{date}`
- open link with `p`, install app in your shop and verifies it loads
- press `q` to continue and test the UI extension in `extensions/sub-ui-ext`
- use dev console to go to admin page, click “Add purchase option > Select existing option”, you’ll see a message
- change the message inside `src/index.js`, you should see it hot reload
- press `q` to continue and test the theme extension in `extensions/theme-app-ext`
- enable the theme extension in your app
- in the theme editor, click “Add section” > choose your nightly app, then “Save”
- make a change to the theme’s `blocks/star_rating.liquid`
- open http://localhost:9292/ and verifies it …
=> Add a script to create a test app for releases

packages/app/src/cli/services/function/build.test.ts, packages/app/src/cli/services/function/build.ts
So that functions can deploy to Shopify!
=> Enable javy dynamic linking for function build

packages/app/src/cli/services/function/build.test.ts, packages/app/src/cli/services/function/build.ts
Workaround for [unexpected behavior](https://github.com/kamilkisiela/graphql-config/issues/1266) in graphql-config.
If a developer has a root `.graphqlrc` or similar in their app, typegen fails with an error such as
```
ENOENT: no such file or directory, scandir './sample-apps/discounts/extensions'
```
Explicitly pass `--config package.json` to `graphql-code-generator`. This makes us more opinionated but matches the structure of our boilerplate. I don't have a known use case at the moment which would require customizing this.
* Attempt typegen against a JavaScript function in our examples repo, e.g. [product-discount-js](https://github.com/Shopify/function-examples/tree/sample-apps-javascript/sample-apps/discounts/extensions/product-discount-js)
* The same is successful using a local …
=> Explicitly use package.json for functions typegen

packages/app/src/cli/constants.ts, packages/app/src/cli/services/function/common.ts, packages/app/src/cli/services/generate/extension.test.ts, packages/app/src/cli/services/generate/extension.ts
Function teams will likely be adding JavaScript templates over the course of our dev preview, before GA. If a certain function type doesn't have JS yet, the current error message is:
```
Building Function - Payment customization graphql types ...
Unable to find Codegen config file! 
── external error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error coming from `npm exec -- graphql-code-generator`
Command failed with exit code 1: npm exec -- graphql-code-generator
Unable to find Codegen config file!
Please make sure that you have a configuration file under the current directory!
─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── …
```
=> Validating function flavor existence

packages/app/src/cli/services/context.ts
We store information about apps using [conf](https://github.com/sindresorhus/conf). But if the user deletes their app from the local filesystem and from the partners portal, they can get in weird situations where the api key that we cached is no longer valid. 
Tell users that they can retry their command with `--reset` which should solve their problem.
- Create a new app and run `pnpm dev`
- Press p to preview it
- Now go to your partners portal and delete the app
- Run `pnpm dev` and you should see a message that tells you to rerun the command with `--reset`
=> Tell users to try with '--reset' when we can't find apps, orgs, or stores

pnpm-lock.yaml
We had a reference to a private package in our `pnpm-lock.yaml`
=> Grab @shopify/eslint-plugin from public registry

packages/app/package.json, packages/app/src/cli/services/dev/extension/server.ts, packages/app/src/cli/services/dev/extension/server/middlewares.test.ts, packages/app/src/cli/services/dev/extension/server/middlewares.ts, packages/app/src/cli/services/dev/extension/server/utilities.ts, packages/app/src/cli/services/dev/extension/websocket/handlers.test.ts, packages/app/src/cli/services/dev/extension/websocket/handlers.ts, packages/cli-kit/package.json, packages/cli-kit/src/private/node/session/redirect-listener.ts, packages/cli-kit/src/public/node/http.ts, pnpm-lock.yaml
H3 is an http server package that is used only in two places:
- The auth redirect listener
- The app dev console / extensions server
For the redirect listener we can use the default node's http server which allows us to remove h3 as a dependency from cli-kit and move it to `app`. Cli-kit shouldn't have dependencies just to re-export them.
- Try to logout/login
- Try to dev an app with extensions
=> Remove h3 from cli-kit

packages/app/package.json, packages/cli-kit/assets/cli-ruby/test/project_types/extension/tasks/find_package_from_json_test.rb, pnpm-lock.yaml
Newest version fixes some issues when we need to redownload the cached binary
=> Update javy-cli to 0.1.4

packages/app/src/cli/services/webhook/request-sample.test.ts, packages/app/src/cli/services/webhook/request-sample.ts, packages/app/src/cli/services/webhook/trigger-options.test.ts, packages/app/src/cli/services/webhook/trigger-options.ts, packages/app/src/cli/services/webhook/trigger.test.ts, packages/app/src/cli/services/webhook/trigger.ts
Because we want to validate that the event-bridge arn is owned by a known app.
See:
* https://github.com/Shopify/shopify/pull/411020
* https://github.com/Shopify/partners/pull/45998
**IMPORTANT:** this PR has to be deployed after those two
Making sure that we have an api-key if event-bridge is used and passing it to Partners
No UI changes, only prompted for app (if you belong to more than one org) if secret not set manually
See the PRs above for testing instructions.
With that spin setup:
* execute the command with a non even-bridge url: Check the logs of partners and core to see that api_key is not sent ✅ 
* execute the command with an event-bridge url and set secret manually: api-key will be get from .env or partners and sent ✅ 
* execute the command with an event-bridge url and set …
=> Pass api-key for Event-Bridge validation

packages/app/package.json, pnpm-lock.yaml
Related issue: https://github.com/Shopify/script-service/issues/6449
This PR uses the `@shopify/function-runner` package instead of `function-runner`. It's functionally the same, but published under the `@shopify` scope now.
- Run `cat <path-to-input-json> | pnpm shopify app function run --path <path-to-function-dir>` and see that the function runner works.
=> Use @shopify/function-runner instead of function-runner

packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.test.tsx, packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx, packages/cli-kit/src/public/node/ui.tsx
A small detail that was bothering me is that the vertical lines weren't solid in the `ConcurrentOutput` component. This PR uses the `figures.lineVertical` to display them. Check out the updated docs and tests to see how the change looks visually.
=> Use `figures.lineVertical` instead of `|`

.vscode/launch.json, packages/app/src/cli/constants.ts, packages/app/src/cli/models/extensions/function-specifications/fulfillment_constraints.ts
These changes will allow us to stop using the [corresponding `internal-cli-plugin`](https://github.com/Shopify/internal-cli-plugins/blob/main/packages/fulfillment-constraints/src/hooks/function_specs.ts), and instead use the main `cli` repo to deploy `fulfillment_constraint` functions.
Exposes the `fulfillment_constraints` extension type and allows us to deploy `fulfillment_constraints` functions. I copied the `order_routing_location_rule` config.
Was able to deploy a function to spin with these changes on my branch.
N/A, `shopify.dev` documentation for this extension type is live behind a betaflag.
=> Add `fulfillment_constraints` extension type

.eslintrc.cjs, packages/app/src/cli/services/dev/fetch.test.ts, packages/app/src/cli/services/generate.test.ts, packages/cli-kit/bin/documentation/examples.ts, packages/cli-kit/package.json, packages/cli-kit/src/private/node/ui/components/Alert.test.tsx, packages/cli-kit/src/private/node/ui/components/Banner.tsx, packages/cli-kit/src/private/node/ui/components/FatalError.test.tsx, packages/cli-kit/src/private/node/ui/components/Link.tsx, packages/cli-kit/src/private/node/ui/contexts/LinksContext.ts, packages/cli-kit/src/public/node/ui.test.ts, packages/cli-kit/src/public/node/ui.tsx, packages/cli/src/cli/services/kitchen-sink/static.ts, pnpm-lock.yaml
Fixes https://github.com/Shopify/internal-cli-foundations/issues/520
Links could wrap inside boxes and be hard to copy and paste
I've added some footnotes below the boxes that display all the links so that they can be easily copy and pasted. Here's an example.
Run `kitchen-sink static` and see the changes
=> Add links to footnotes if terminal doesn't support hyperlinks

docs/README.md, docs/cli/performance.md
I built some knowledge around how to do performance benchmarking and what are important things to keep in mind regarding performance, and I'm capturing it in this document for other CLI contributors.
I'm adding a new documentation page that includes the following:
- How to profile the CLI using Node's `--cpu-prof` flag:
- Principles around performance
=> Document how to do performance benchmarking and some principles to be mindful of

packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.test.tsx
A test in `AutocompletePrompt.test.tsx` was flakey.
I've moved the `setTimeout` inside the `search` function definition instead of letting it start immediately from the outside which sometimes would cause the function to resolve before the end of the test.
I've tried this 100 times with a script and couldn't reproduce the issue after the fix. Before the fix the issue would appear ~1/20 times.
=> Fix flakey test in AutocompletePrompt.test.tsx

packages/app/oclif.manifest.json, packages/app/src/cli/commands/app/deploy.ts, packages/app/src/cli/services/deploy.test.ts, packages/app/src/cli/services/deploy.ts
Users have to write the deployment label in the prompt at the moment, but we want to let them pass the `label` as a flag as well so that they can use it from CI environments.
Add the `label` flag to the deployment command.
With the `appUiDeployments` beta flag enabled you can run `shopify app deploy --label myLabel` and verify that it's using it. You also shouldn't be asked to enter the label in a prompt.
=> Allow passing deployment label to deploy command

packages/app/src/cli/constants.ts
In reference to https://github.com/Shopify/partners/pull/46274#discussion_r1146028024.
Changing the extension type group here to reflect that this API is now public for 3p use via a private beta.
Changing the extension type group.
N/A
N/A
=> Move `fulfillment_constraints` to public extension type group

.changeset/cold-points-provide.md, packages/app/src/cli/services/deploy/theme-extension-config.test.ts, packages/app/src/cli/services/deploy/theme-extension-config.ts, packages/app/src/cli/utilities/extensions/theme.test.ts, packages/app/src/cli/utilities/extensions/theme.ts, packages/app/src/cli/validators/extensions/theme.ts, release_notes_draft.md
Fixes https://github.com/Shopify/shopify-cli/issues/2171#issuecomment-1479087268 noting we don't filter out `.DS_STORE`
All kinds of invalid system files get included in theme extension uploads.
Filters system files from theme extensions, similar to what we already do in themes: https://github.com/Shopify/cli/blob/6735253e6f6055b7f79093e409574dcda28f378a/packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/ignore_filter.rb#L12-L26).
1. Create a `.DS_STORE` in one of the directories of `fixtures/app/extensions/theme-extension`
2. `dev shopify app deploy --path=fixtures/app`
This works on the branch, but fails on `main`.
=> Exclude system files in theme extensions

.changeset/gorgeous-ducks-yawn.md, package.json, packages/app/package.json, packages/app/src/cli/services/dev/extension/bundler.test.ts, packages/app/src/cli/services/dev/extension/bundler.ts, packages/app/src/cli/services/extensions/bundle.test.ts, packages/app/src/cli/services/extensions/bundle.ts, pnpm-lock.yaml
As part of the work done here https://github.com/Shopify/cli/pull/1641 we'd like to upgrade esbuild so that we can run async functions in the event running after the build. I thought it would be better to make this upgrade separate so we can test it in isolation.
This PR upgrades esbuild to the latest version. The main change is that there is no longer a `build` function, but rather a `context` function that returns an object with `watch`, `rebuild`, etc... These functions can then be called to trigger the previous behavior. There is also no longer an `onRebuild` param as part of `watch`.
As a result, we need to add a plugin that subscribes to the `onEnd` event. This event gets run after every build, not just the second rebuild, so we don't need to trigger `onResult` manually on the first …
=> Upgrade esbuild to 0.17.10

.changeset/rare-windows-obey.md, packages/cli-kit/src/private/node/ui/components/SelectPrompt.test.tsx, packages/cli-kit/src/private/node/ui/components/SelectPrompt.tsx, packages/cli-kit/src/public/node/ui.tsx, packages/cli/src/cli/services/kitchen-sink/prompts.ts
We want to allow developers to specify if the default value should be true or false in confirmation prompts. This can be useful for dangerous type of actions
Implement the above requirement.
Run `kitchen-sink prompt` and the last prompt will be a "dangerous" prompt with `Cancel` preselected.
=> Add default value option to renderConfirmation prompt

.changeset/silent-dancers-tan.md, packages/theme/src/cli/utilities/theme-selector.test.ts, packages/theme/src/cli/utilities/theme-selector.ts
Improve theme selector component to group themes by role (following DX feedback).
This PR improves the `[theme-selector.ts](https://github.com/Shopify/cli/compare/fix-572?expand=1#diff-7633fa15fdce1b666ec9e64add1637d9a51d681f0ea67bfbda93a396198b4b8d)` to group themes by role and to properly apply the `[yours]` label
- Run `shopify theme delete`
None.
=> Improve theme selector component by grouping themes by role

packages/cli-kit/src/public/node/ruby.test.ts, packages/cli-kit/src/public/node/ruby.ts, packages/plugin-cloudflare/scripts/postinstall.js
If the username contains a UTF8 character, bundler will crash with this error:
```
PS C:\Users\Jöhnny Ärkhåm> bundle --version
C:/Ruby30-x64-utf8/lib/ruby/3.0.0/pathname.rb:50:in `match?': invalid byte sequence in UTF-8 (ArgumentError)
from C:/Ruby30-x64-utf8/lib/ruby/3.0.0/pathname.rb:50:in `chop_basename'
from C:/Ruby30-x64-utf8/lib/ruby/3.0.0/pathname.rb:374:in `plus'
from C:/Ruby30-x64-utf8/lib/ruby/3.0.0/pathname.rb:354:in `+'
from C:/Ruby30-x64-utf8/lib/ruby/3.0.0/pathname.rb:420:in `join'
```
Fixes https://github.com/Shopify/cli/issues/868 and https://github.com/Shopify/cli/issues/1634
Set a custom `BUNDLE_USER_HOME` var on Windows so that instead of using the user home folder we use `C:\Users\Public\AppData\Local\shopify-bundler-nodejs\Cache` as the Bundler user home.
- On …
=> Set a custom BUNDLE_USER_HOME env var on Windows

packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb, packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/dev_server/proxy_test.rb
Continuation of https://github.com/Shopify/cli/pull/1484
As @Poitrin mentioned [here](https://github.com/Shopify/cli/issues/1675#issuecomment-1486965718), there's a new Web Pixels Manager endpoint we are not ignoring when running `theme dev` with a password.
Ignore requests containing `wpm` as well.
`shopify theme dev --password XXX --verbose`
=> Clean wpm errors on theme dev

packages/app/src/cli/services/dev.ts
Users are mistaking this message as a cause of problem (example [here](https://github.com/Shopify/cli/issues/1603)).
Remove output message
- `bin/create-test-app.js -e ui`
- see that message isn't output anymore
=> Remove webhook uninstall message

packages/app/src/cli/api/graphql/all_orgs.ts, packages/app/src/cli/api/graphql/find_app.ts, packages/app/src/cli/api/graphql/find_org.ts, packages/app/src/cli/api/graphql/find_org_basic.ts, packages/app/src/cli/api/graphql/find_store_by_domain.ts, packages/app/src/cli/models/organization.ts, packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/context.ts, packages/app/src/cli/services/deploy.test.ts, packages/app/src/cli/services/deploy.ts, packages/app/src/cli/services/dev/fetch.test.ts, packages/app/src/cli/services/dev/fetch.ts, packages/app/src/cli/services/generate-schema.test.ts, packages/app/src/cli/services/generate-schema.ts
We want to move the beta flag for unified deployments to the org level because we're getting rid of the org level one and also because the partners token doesn't have permission to fetch organizations, so the `deploy` command couldn't make use of such flags.
I've removed `appUiDeployments` from organizations and added `unifiedAppDeployment` to apps.
- Enable the `unified_app_deployment` beta flag in partners
- The new flow should be active when deploying
=> Use unifiedAppDeployment flag instead of appUiDeployments

.github/workflows/cli-ruby.yml, .github/workflows/shopify-cli.yml
What the title says. Change suggested in the Github tutorial: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
=> Add merge_group so that CI checks are run in the merge queue

.changeset/shaggy-lizards-grow.md, packages/cli/src/cli/services/upgrade.test.ts, packages/cli/src/cli/services/upgrade.ts
When a Homebrew-managed installation of the CLI tries to upgrade itself via Homebrew, it leads to [an error](https://shopify.slack.com/archives/C030LHFCA5T/p1680618843167109) because Homebrew deletes modules of the current version that OCLIF fails to load dynamically.
Upgrades and installation should be managed from a process other than the CLI's, otherwise we'll continue to find race conditions like this one where the package manager has replaced modules that are needed for the CLI process that initiates the upgrade. Because installing and upgrading packages is the package managers' responsibility, we should not have that responsibility in the CLI.
**Note:** If the issue is that `package.json` have two packages that need to be in sync, for example `@shopify/app` and `@shopify/cli`, we …
=> Not upgrade the global Homebrew-managed installation of the CLI on `shopify upgrade`

packages/app/src/cli/api/graphql/create_deployment.ts, packages/app/src/cli/services/deploy.test.ts, packages/app/src/cli/services/deploy.ts, packages/app/src/cli/services/deploy/upload.test.ts, packages/app/src/cli/services/deploy/upload.ts
Fixes https://github.com/Shopify/app-deploys/issues/349
Following up the work done [here](https://github.com/Shopify/partners/pull/46209) we want to enable deployments without extensions if you have the beta flag.
- Enable the `appUiDeployments` beta flag
- Try deploying in an app with no extensions
- It should work
- It shouldn't work if you don't have the beta flag
=> Allow running deploy without extensions

packages/app/src/cli/services/context.ts, packages/app/src/cli/services/context/identifiers-extensions.test.ts, packages/app/src/cli/services/context/identifiers-extensions.ts, packages/app/src/cli/services/context/identifiers.ts, packages/app/src/cli/services/context/prompts.ts, packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx, packages/cli-kit/src/private/node/ui/components/List.tsx, packages/cli-kit/src/private/node/ui/components/Prompts/InfoTable.tsx, packages/cli-kit/src/public/node/ui.tsx
Fixes https://github.com/Shopify/app-deploys/issues/274
We want to show a warning that, with the unified deployments flow, publishing a deployment after having deleted extensions will result in such extensions being removed for app users.
I've added a warning message only if the beta flag is set that explains the above.
Example:
- Deploy an app with some extensions
- Delete the extension
- Deploy again, you should see the message
=> Deployment warning

packages/cli-kit/src/public/node/fs.test.ts, packages/cli-kit/src/public/node/fs.ts
cli-kit exports `createFileReadStream` (from `filehandle.createReadStream`) but doesn't expose its `options` argument. We'd like this available so we can set a `start` and `end` to read a range of bytes in our plugin.
This PR adds an optional `options` parameter exposing `start`, `end` and `encoding`. I also added a test.
=> [cli-kit] add options argument to createFileReadStream

packages/cli-kit/src/public/common/string.ts
We have a test that expects a certain folder name structure, and the extra hyphen is throwing it off.
=> Drop hyphenated random name

packages/app/src/cli/utilities/app/http-reverse-proxy.ts, packages/cli-kit/bin/documentation/examples.ts, packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.test.tsx, packages/cli-kit/src/public/node/ui.tsx, packages/cli/src/cli/services/kitchen-sink/async.ts
The dev command is now showing these shortcuts:
```
Press p | open your browser
Press q | quit
```
But it's a bit weird to use `p` for `open your browser`.
Reword it to use `preview`:
```
Press p | preview in your browser
Press q | quit
```
`pnpm shopify app dev`
=> Reword preview label

bin/spin
While testing on spin, it's not convenient to force to use the latest spin instance. This PR changes that behavior which allows developer to select which spin instance to use. 
Change spin command
Run `./bin/spin`. Expect spin instances selector shows up. 
=> Allow to select spin instance

.changeset/small-buses-build.md, packages/cli-kit/src/private/node/constants.ts, packages/cli-kit/src/public/node/context/local.test.ts, packages/cli-kit/src/public/node/context/local.ts
The default auth flow doesn't work in Google Cloud Shell
Auto-detect Cloud Shell environment to use device auth flow, as we do for Gitpod or Codespaces.
- `p build`
- Copy the content of `packages/cli-kit/dist/public/node/context/local.js`
- https://ide.cloud.google.com/
- `npm init @shopify/app`
- `npm run dev` ❌ 
- Paste the content in `node_modules/@shopify/cli-kit/dist/public/node/context/local.js`
- Add `cloudShell: 'CLOUD_SHELL',` to `environmentVariables` in `node_modules/@shopify/cli-kit/dist/private/node/constants.js`
- `npm run dev` ✔️
=> Add support for Google Cloud Shell

.changeset/heavy-flies-begin.md, packages/cli/oclif.manifest.json, packages/cli/package.json, packages/cli/src/cli/commands/plugins/index.ts, packages/features/snapshots/commands.txt
We don't want to show anything about plugins:
- Hides the plugins topic by configuration
- Creates a wrapper for the plugin index command to hide it, as [there's no way to do it by configuration](https://github.com/oclif/oclif/issues/269)
- `pnpm shopify`
- `pnpm shopify plugins`
- `pnpm shopify plugins -h`
- `pnpm shopify plugins install @oclif/plugin-which`
=> Hide plugins commands

.changeset/four-adults-flash.md, packages/cli-kit/assets/cli-ruby/lib/project_types/extension/messages/messages.rb, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/shopifolk.rb, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/extension/dev_server.rb, packages/cli-kit/src/public/node/ruby.ts, packages/cli/src/index.ts
Right now, there is a [demo app](https://shopify.workplace.com/groups/1207479046824983/permalink/1262249938014560/) that includes a patched CLI version that make it to be run as a service.
After generating a theme app extension, some problem arose after running the dev command:
- Extension specs partners API operation returns an empty response if the request is made as an employee
- One of the instructions displayed to preview the TAE requires to access to the details of the extension in the partners dashboard. It's not possible to access to Shopify Organization partners dashboard using a partners account session. You need to login as an employee
- The TEA preview urls are cut so user have to modified them previous to paste them in the browser
The modifications that are included in those …
=> Add support for 1P app with theme app extensions in Spin

packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.tsx, packages/cli-kit/src/private/node/ui/components/SelectPrompt.tsx, packages/cli-kit/src/private/node/ui/components/TextAnimation.tsx, packages/cli-kit/src/private/node/ui/hooks/use-layout.ts
In certain cases we were using `useEffect` where we should have been using `useLayoutEffect`. The difference is that `useLayoutEffect` will block painting until its effect has been processed, wether with `useEffect` the component would first render and paint to the screen and then the function would be called.
This means that in certain cases we were showing a first non-processed frame that would be immediately corrected by `useEffect`. With `useLayoutEffect` this first frame won't even show as its function is run synchronously with render.
=> Use useLayoutEffect where appropriate

packages/app/oclif.manifest.json, packages/app/src/cli/commands/app/dev.ts, packages/theme/oclif.manifest.json, packages/theme/src/cli/commands/theme/dev.ts
This PR is a minor followup regarding the https://github.com/Shopify/cli/pull/1821 effort to remove `-n` aliases, following [this guideline](https://github.com/Shopify/cli/blob/main/docs/cli-kit/command-guidelines.md#aliases--shortcuts-for-flags).
This PR removes `-n` aliases.
- Run `shopify theme dev -h`
- Run `shopify app dev -h`
After the release, merge this PR: https://github.com/Shopify/shopify-dev/pull/33036.
=> Remove `-n` alias for `--notify`

packages/app/src/cli/prompts/dev.ts, packages/cli/src/cli/services/kitchen-sink/prompts.ts, packages/eslint-plugin-cli/config.js, packages/eslint-plugin-cli/index.js, packages/eslint-plugin-cli/rules/no-choose-select-message-prompts.js, packages/eslint-plugin-cli/rules/prompt-message-format.js, packages/plugin-ngrok/src/tunnel.ts
We had been discussing with @MeredithCastile the option of encouraging people to not use words like "choose" or "select" in prompt messages as it can conflict with the wording used in the footer of the prompt. Also these words are simply redundant.
This PR introduces a rule that will simply warn users if they include these words.
=> Add eslint rule to warn users with certain prompt messages

.changeset/clean-feet-judge.md, packages/cli-kit/src/private/node/ui/components/TextPrompt.test.tsx, packages/cli-kit/src/private/node/ui/components/TextPrompt.tsx
When you deploy an app using the new unified deployment system you could add a label value to the deployment. This input is optional so if the user does not enter a value the text prompt displays nothing which looks a bit weird
In that case we would want to add the option of displaying en empty message
- Add an new optional parameter to the `TextPrompt` component with a default value `(empty)`. In case you don't want to display an empty message you could set it to empty in the call
- In case the user submit an empty value the empty message will be displayed with a dimmed style
- The value submitted should be an empty string regardless the empty value is displayed
- Activate the `unified deployment beta flag` in your app
- Run the `deploy` command and leave empty the `Deployment label` …
=> Text prompt displays an specific empty value when no input is entered

packages/app/src/cli/models/extensions/ui-specifications/checkout_ui_extension.ts, packages/app/src/cli/models/extensions/ui-specifications/ui_extension.ts
Follow-up to https://github.com/Shopify/ui-extensions/pull/902. This PR updates the dependancies for `@shopify/checkout-ui-extensions` and `@shopify/checkout-ui-extensions-react` to the latest version **0.26.0**. This ensures scaffolded extensions will be on the latest version.
Updates the checkout ui extensions version.
Create a new app and scaffold a Checkout UI extension. It should use the `0.26.0` versions for both a React or a JavaScript extension.
=> checkout-ui-extensions 0.26.0 update

.changeset/wise-fans-rest.md, packages/app/src/cli/api/graphql/get_variant_id.ts, packages/cli-kit/assets/cli-ruby/lib/graphql/get_variant_id.graphql
Fixes https://github.com/Shopify/build-learn-dev-tools-issues/issues/199
Development stores with generated test data have products that are not published. When a non-published product is the first product, the CLI checkout extensions test will still put it in the cart and then have a no inventory error.
[Video demonstration](https://videobin.shopify.io/v/pgQdLq)
This PR adds a query filter to the GraphQL calls to only fetch the first published product.
Before:
https://screenshot.click/28-28-504w1-bgf8u.png
After:
https://screenshot.click/28-27-itq1j-o8myj.png
=> [Bug Fix] only retrieve published products

.changeset/silver-onions-tease.md, packages/app/src/cli/models/extensions/ui-specifications/pos_ui_extension.ts, packages/app/templates/ui-extensions/projects/pos_ui_extension/shopify.ui.extension.toml.liquid, packages/app/templates/ui-extensions/projects/pos_ui_extension/src/index.liquid
This is a cherry pick from main to unblock POS UI Extensions from GA launch on Monday next week.
Copies the changes from main for select files. 
Scaffold a POS UI Extension. 
=> POS UI Extensions cherry pick for 3.45.3

.changeset/fluffy-peas-admire.md, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/cdn_fonts.rb
Fixes https://github.com/Shopify/cli/issues/1893
Theme development is currently dead in the water, due to introducing a constant reference we don't actually have access to during `theme dev`.
Removes the references to `Rack`, using the standard Rack `[status, headers, body]` interface instead.
`theme dev` should work now
=> Remove references to rack, which we don't need to use

packages/cli/oclif.manifest.json, packages/cli/src/cli/commands/debug/command-flags.ts
Help us identify discrepancies in how flags and environment variables are used, by being able to export a list of them.
Adds ` shopify debug command-flags` -- similar to the `commands` command from `plugin-commands`. Outputs all the flags used by all the commands.
Run `shopify debug command-flags`
=> Add `debug command-flags` command

.changeset/little-eels-study.md, packages/theme/src/cli/services/package.test.ts, packages/theme/src/cli/services/package.ts
Fixes [#420493](https://github.com/Shopify/shopify/issues/420493)
Introduces support to `update_extension.json` files.
- Run `shopify theme init my_theme`
- Run `cd my_theme`
- Run `touch update_extension.json`
- Run `shopify theme package`
- Unzip the generated zip file
- Notice the `update_extension.json` was included in the zip
None.
=> Introduce support for update extension files

.changeset/lemon-feet-begin.md, packages/app/src/cli/utilities/app/http-reverse-proxy.ts, packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.test.tsx, packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.tsx, packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.test.tsx, packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx, packages/cli-kit/src/private/node/ui/components/SelectPrompt.test.tsx, packages/cli-kit/src/private/node/ui/components/SelectPrompt.tsx, packages/cli-kit/src/private/node/ui/components/Tasks.test.tsx, packages/cli-kit/src/private/node/ui/components/Tasks.tsx, packages/cli-kit/src/private/node/ui/components/TextPrompt.test.tsx, packages/cli-kit/src/private/node/ui/components/TextPrompt.tsx, packages/cli-kit/src/private/node/ui/hooks/use-abort-signal.ts, packages/cli-kit/src/private/node/ui/hooks/use-async-and-unmount.ts, packages/cli-kit/src/public/node/ui.tsx
At the moment there is no way for async processes to make the async prompts quit. For example in this scenario, the prompt would still remain in the terminal:
```
const templatesPromise = getLatestTemplates()
.catch((error) => {
renderFatalError(error);
process.exit(1);
});
await renderXPrompt(...);
```
This PR adds the ability to pass an abort controller from outside. Prompts and `Tasks` will clear the output before quitting when the abort controller signal receives the `abort` event.
`ConcurrentOutput` will clear only the dynamic part, currently the preview URL and the shortcuts, but will preserve the logs.
I've tested it modifying `kitchen-sink prompts` and replacing the first prompt with this code
```
const controller = new AbortController()
// after 2 seconds call abort
setTimeout(() …
```
=> Add abortController to async ui function parameters

.changeset/big-goats-share.md, .changeset/sixty-gifts-tan.md, packages/app/src/cli/services/generate/extension.ts, packages/cli-kit/src/public/node/node-package-manager.test.ts, packages/cli-kit/src/public/node/node-package-manager.ts
In https://github.com/Shopify/cli/pull/1913, we added a fix to avoid NPM not installing the exact version of a dependency for a specific extension, but we have realized that the different package managers are not consistent when adding dependencies with exact versions:
- When you run `npm install whatever@1.2.3`, it adds `whatever: ^1.2.3` to the package.json.
- But if you run `yarn/pnpm add whatever@1.2.3`, they add `whatever: 1.2.3`
- Reverts Shopify/cli#1913
- Adds `--save-exact` only to NPM install commands when the provided version is exact (same behavior as Yarn/PNPM)
- `p create-app --name test-npm  --path ~ --package-manager npm --template node`
- `p shopify app generate extension --path ~/test-npm`
- `cat ~/test-npm/package.json` should contain …
=> Install exact versions with NPM by default

packages/cli-kit/src/private/node/constants.ts, packages/cli-kit/src/public/node/context/local.ts
Fixes https://github.com/Shopify/app-deploys/issues/318
We want to make theme bundling opt-out instead of opt-in now that we're more confident in the feature.
- Create a new app with `./bin/create-test-app.js -e theme`
- Try deploying, it should work
- Try introducing an error in the theme
- Try deploying, the error should be visible in the error messages banner
=> Use theme bundling by default

.changeset/soft-oranges-greet.md, packages/cli-kit/src/public/node/tcp.ts
Some users are receiving this error when they try to run the `dev` command.
```sh
╭─ error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                    │
│  Unable to obtain an available random port number!                                                                                                                 │
│                                                                                                                                                                    │ …
```
=> Fix localhost as host to run the library get port please

packages/app/src/cli/api/graphql/all_app_extension_registrations.ts, packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/context/identifiers-extensions.test.ts, packages/app/src/cli/services/context/identifiers-extensions.ts, packages/app/src/cli/services/context/identifiers-functions.test.ts, packages/app/src/cli/services/context/identifiers-functions.ts, packages/app/src/cli/services/context/identifiers.test.ts, packages/app/src/cli/services/context/identifiers.ts, packages/app/src/cli/services/context/prompts.ts, packages/app/src/cli/services/deploy.test.ts, packages/cli-kit/src/private/node/ui/components/Prompts/InfoTable.test.tsx, packages/cli-kit/src/private/node/ui/components/Prompts/InfoTable.tsx
This is a companion PR to https://github.com/Shopify/partners/pull/47589 and should only be merged afterwards.
Fixes https://github.com/Shopify/app-deploys/issues/372
Add the `Included from Partners dashboard` section:
1. Create a spin instance with partners on the `expose-dashboard-managed-extensions` branch
2. Create an app with some extensions
3. Deploy
4. In the partners admin, add dashboard-managed extensions (e.g. admin links)
5. Deploy and see the `Included from Partner dashboard` is included
=> Add dashboard-managed extensions to infoTable

packages/app/src/cli/services/generate/extension.ts
Since https://github.com/Shopify/cli/pull/1941, the generation of Javascript/Typescript functions is broken. It's generating an empty index.js/index.ts.
Add missing liquid variable to generate JS functions
- `p shopify app generate extension --type=product_discounts --name=prod-discount --template=typescript --path ~`
- Check that the generated src/index.ts contains the corresponding code from [this template](https://github.com/Shopify/function-examples/blob/main/discounts/javascript/product-discounts/default/src/index.liquid)
=> Fix JS function generation

packages/app/src/cli/models/extensions/ui-specifications/ui_extension.test.ts, packages/ui-extensions-server-kit/src/ExtensionServerClient/ExtensionServerClient.test.ts, packages/ui-extensions-server-kit/src/ExtensionServerClient/ExtensionServerClient.ts, packages/ui-extensions-server-kit/src/i18n.ts
Fixes [#134](https://github.com/Shopify/app-ui/issues/134)
Add localizable label on dev server kit, enabling this feature when running `dev.
- Added `label` and `original_label` to `ExtensionPoint type`.
- Translate base in the user locale the label and keep original label to recover the value.
- Remove the translated value and rollback to original value when persisting.
It isn't possible to do an end-to-end test at this stage (follow up PRs in Web will be tested end-to-end). The unit tests should be sufficient.
=> 134 add localizable label dev server kit

packages/app/src/cli/models/extensions/ui-specifications/ui_extension.ts
Generic UI Extension needs to be previewable so that we don't upload the draft while running dev.
=> Make the generic ui extensions previewable

.changeset/funny-snails-give.md, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/version.rb, packages/cli-kit/src/public/node/ruby.ts
Fixes partially https://github.com/Shopify/internal-cli-foundations/issues/633
- Set a new env variable `SHOPIFY_CLI_VERSION` when a cli-ruby command is executed
- cli-ruby api requests use the SHOPIFY_CLI_VERSION version to set the proper cli version header when it makes API request
- Create a new partners instance from this branch `spin up partners -c partners.branch=filter-request-from-old-cli-version`
- Using an app with a TAE, run the CLI3  `dev` command against spin `SHOPIFY_SERVICE_ENV=spin SPIN_INSTANCE=$(spin show -o name) yarn shopify app dev` and it should work as usual
- Using an app with a TAE, run the CLI3  `dev` command against production services `yarn shopify app dev` and  it should work as usual
- Run any `theme` command against production services and it should work as …
=> Set current CLI3 version as the version used by the cli-ruby API requests

packages/app/src/cli/services/function/build.test.ts, packages/app/src/cli/services/function/build.ts
Apparently, the cli crashes running deploy using the javascript debug terminal when there is a JS function. This is because of the `stdout` config used when running `javy`
Force `javy` to run using `inherit` 
- Create an app with a JS function
- run deploy inside vscode's javascript debug terminal
- Also test running function build and function run
=> Use `stdout: inherit` when running javy

.changeset/kind-melons-swim.md, packages/app/src/cli/api/graphql/template_specifications.ts, packages/app/src/cli/services/generate.ts, packages/app/src/cli/services/generate/fetch-template-specifications.test.ts, packages/app/src/cli/services/generate/fetch-template-specifications.ts
Related to https://github.com/Shopify/internal-cli-foundations/issues/635
Adds the api key to the template specifications query, so that the server can filter out templates under a beta flag.
- `p shopify app generate extension --path ~/your-app`
To test with a beta flag:
- `spin up partners`
- `spin code --latest partners`
- Edit `app/operations/apps/templates/specifications/base.rb` and add `organization_beta_flags: ['tax_calculation']` to any template specification
- `SHOPIFY_SERVICE_ENV=spin p shopify app generate extension --path ~/your-app` with/without the `Tax Calculation App Extension` beta flag enabled for your org (it should show/hide the template)
=> Fetch templates with api key

.changeset/tall-cycles-think.md, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/webhook/send-app-uninstalled-webhook.ts
Currently, we run the `APP_UNINSTALLED` webhook when the CLI switches apps, so that we can clean up the database and trigger a new install flow.
The issue here was that the CLI was assuming a `backend` config would always be present, which isn't necessarily true, since apps can sometimes use only `frontend` configs.
Ensuring that the webhook flow also works for frontend-only apps, preferring the backend config when present.
I've also added a 3s backoff period before firing the first attempt to give the app some time to spin up before we start trying, since it's almost guaranteed that the first try will fail if we fire it right away.
Run `dev --reset` and ensure the webhook is fired and received.
None!
=> Also run webhook requests in frontend-only apps

.changeset/small-fishes-sleep.md, packages/app/src/cli/models/app/loader.ts
When you run any command for an app that includes an extension and the specification for the type inside the `shopify.ui.extension.toml` is not found, an error like this should be shown:
```sh
╭─ error ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                              │
│  Unknown extension type web_pixel_extension2 in                                                                              │
│  /Users/alvarogutierrez/cli-apps/0531-webpixel/extensions/web-pixel/shopify.ui.extension.toml.                               │
│  You might need to enable some beta flags on your Organization or App …
```
=> Fix app loader error message when not specification found

packages/app/src/cli/services/generate/fetch-template-specifications.test.ts, packages/app/src/cli/services/generate/fetch-template-specifications.ts
We were only checking specification access for local templates, but we need to verify remote ones too.
Only show a template if you have access to the app module specification that it uses.
Check that remote templates are accessible for the current user depending on the app module specifications.
=> Validate specification access for remote templates

.changeset/three-students-whisper.md, packages/theme/src/cli/commands/theme/dev.ts, packages/theme/src/cli/utilities/theme-selector.ts
Fixes https://github.com/Shopify/cli/issues/2036
This PR changes the `packages/theme/src/cli/commands/theme/dev.ts` command to find the ID of the theme, before rendering theme links.
**Before**
**After**
None.
=> Fix `shopify theme dev` command to show valid URLs when `--theme` flag is used with a theme name

packages/app/src/cli/services/deploy.ts
Fixes https://github.com/Shopify/app-deploys/issues/514
We want to notify users that changes are coming to deployments. This banner still lacks the URL so either way for it if it's going to come soon or ship it without the `Reference` section for now.
=> Add warning message to deploy

packages/app/src/cli/models/extensions/specifications/flow_action.ts, packages/app/src/cli/models/extensions/specifications/flow_trigger.ts, packages/app/src/cli/models/templates/flow_action.ts, packages/app/src/cli/models/templates/flow_trigger.ts, packages/app/src/cli/services/generate/fetch-template-specifications.ts, packages/app/templates/extensions/projects/flow_action/shopify.extension.toml.liquid, packages/app/templates/extensions/projects/flow_trigger/shopify.extension.toml.liquid
We're moving the Flow extension generation process from the Partner's Dashboard to the CLI. This is the first step towards that.
We're adding the capacity to generate both Flow actions and triggers from the CLI. This feature will be gated by a [beta flag in Partners](https://github.com/Shopify/partners/pull/48052).
You can use my [spin instance](https://generic-extensions-1.maxime-leduc.us.spin.dev/) to test this out or create your own with these PRs from [Core](https://github.com/Shopify/shopify/pull/430734) and [Partners](https://github.com/Shopify/partners/pull/48052).
=> [Feature] Add Flow Extensions to the CLI

.changeset/silly-shoes-visit.md, packages/theme/src/cli/commands/theme/dev.ts, packages/theme/src/cli/services/dev.test.ts, packages/theme/src/cli/services/dev.ts
Fixes https://github.com/Shopify/cli/issues/1843
Fixes https://github.com/Shopify/cli/issues/1554
In https://github.com/Shopify/cli/pull/2137 I made a small refactor that broke a fresh login from `theme dev` when no password is provided.
Ensures the auth tokens are stored in CLI2's cache after a new login, and not only when they are refreshed.
- `p shopify auth logout`
- `p shopify theme dev`
=> Fix login on theme dev

docs/cli-kit/ui-kit/readme.md, packages/app/oclif.manifest.json, packages/app/src/cli/api/graphql/app_release.ts, packages/app/src/cli/api/graphql/app_versions_diff.ts, packages/app/src/cli/commands/app/release.ts, packages/app/src/cli/models/app/identifiers.ts, packages/app/src/cli/prompts/release.test.ts, packages/app/src/cli/prompts/release.ts, packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/context.ts, packages/app/src/cli/services/deploy.test.ts, packages/app/src/cli/services/release.test.ts, packages/app/src/cli/services/release.ts, packages/cli-kit/bin/documentation/examples.ts, packages/cli-kit/src/private/node/ui/alert.tsx, packages/cli-kit/src/private/node/ui/components/Alert.tsx, packages/cli-kit/src/public/node/ui.tsx, packages/cli/src/cli/services/kitchen-sink/static.ts, packages/eslint-plugin-cli/rules/banner-headline-format.js, packages/features/snapshots/commands.txt
Fixes https://github.com/Shopify/app-deploys/issues/474
We want to add a `release` command to make a specific `version` active.
We've added a `app release --version=1` command to make the specified version active. If the version doesn't exist we throw an error. The user is then prompted with a diff of all the extensions from the last released version to the one specified. If the user confirms we then call the `appRelease` mutation. Releases might have to be reviewed so we handle that scenario.
It seems like the `versionsDiff` not returning what we expect for now.
- Run `shopify app deploy --no-release`
- Copy the version number
- Run `shopify app release --version={versionNumber}`
We need to add this command to the docs.
=> Add app_release mutation

.changeset/loud-hairs-sell.md, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/extension/payload/store.test.ts, packages/app/src/cli/services/dev/extension/payload/store.ts, packages/app/src/cli/utilities/app/app-url.ts
We'd like the flexibility to modify the install process in the future, so move install URL generation to the platform.
Sends the developer through `redirect_from_cli` instead of the app home.
1. Run `app dev`
2. Verify that the preview URL correctly installs the app.
3. Run `app dev` again.
4. Verify that the preview URL correctly loads the app.
=> Use dynamic install URL

.changeset/tender-dogs-train.md, packages/ui-extensions-server-kit/src/types.ts
Related to https://github.com/Shopify/app-ui/issues/154
The CLI was passing through the `apiVersion` but the Dev Server Kit was missing this in the UIExtension interface
Add the missing `apiVersion` prop
N/A
=> Add missing apiVersion type in ui-extension-server-kit

.changeset/tall-tables-hug.md, packages/app/src/cli/models/app/loader.test.ts, packages/app/src/cli/models/app/loader.ts
1. We were double-counting webs in workspaces of npm-managed projects, as npm uses symlinks to manage workspaces.
2. We were wasting time scanning `node_modules` for webs, to the tune of 500ms per command run on my machine. Also extensions if they have node_modules (though I'm guessing in most cases they don't, but maybe in the future with workspaces they might?)
Excludes `**/node_modules/**` from the scan for `shopify.(web|.*\.extension).toml` files.
Everything should work as before.
`shopify app info` is your friend.
=> Skip scanning node modules

.changeset/hip-brooms-mate.md, packages/cli-kit/assets/cli-ruby/lib/project_types/theme/commands/serve.rb, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server.rb, packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/dev_server_test.rb, packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/extension/dev_server_test.rb, packages/theme/oclif.manifest.json, packages/theme/src/cli/commands/theme/dev.ts, packages/theme/src/cli/services/dev.test.ts, packages/theme/src/cli/services/dev.ts
Fixes https://github.com/Shopify/cli/issues/1777
During the modifications in the theme development server to ensure better integration with the UI kit, we introduced a change to auto-open the browser. However, this change led to more difficulties than support for theme developers.
As a result, this PR rolls back that change, and now, if developers want to open the browser, they need to specifically request it with the `--open` flag.
This PR introduces the `--open` flag, which defaults to `false`.
- Notice the development server no longer auto opens the browser
- Run `shopify theme dev --open`
- Notice the development server no longer auto opens the browser
**Before**
**After**
Introduce documentation at [shopify.dev](https://shopify.dev/docs/themes/tools/cli/comma …
=> Introduce the `--open` flag to open a browser window only when users specifically request it

packages/app/src/cli/api/graphql/push_config.ts, packages/app/src/cli/models/app/app.ts, packages/app/src/cli/services/app/config/push.test.ts, packages/app/src/cli/services/app/config/push.ts
Resolves: https://github.com/Shopify/internal-cli-foundations/issues/667
Adds support for setting `requestedAccessScopes` via the `push`.
Omission / null field behaviour will be handled separately as part of this [issue](https://github.com/Shopify/partners/issues/48089).
=> Add support for requestedAccessScopes to push command

packages/app/src/cli/services/deploy/upload.ts
Fixes https://github.com/Shopify/app-deploys/issues/592
It updates the error message we are going to show when we force users to upgrade their Shopify CLI version when everyone is opted into using deployments.
- Set the CLI version to 3.46
- Make sure the `app_unified_deployment` beta flag is enabled
- Run `app deploy`
You should get the error in the screenshot below.
=> Updated the upgrade error message

packages/app/src/cli/models/extensions/specifications/flow_action.ts, packages/app/src/cli/models/extensions/specifications/flow_trigger.ts, packages/app/src/cli/services/flow/constants.ts, packages/app/src/cli/services/flow/serializeFields.ts, packages/app/src/cli/services/flow/tests/serializeFields.test.ts, packages/app/src/cli/services/flow/tests/validation.test.ts, packages/app/src/cli/services/flow/types.ts, packages/app/src/cli/services/flow/validation.ts, packages/app/templates/extensions/projects/flow_action/shopify.extension.toml.liquid, packages/app/templates/extensions/projects/flow_trigger/shopify.extension.toml.liquid
- We're aligning with the TOML config file standards as discussed on the `#unified-extension-config` channel and in our proposal [PR](https://github.com/Shopify/core-build-north-star-app/pull/9).
- We're also introducing more comprehensive validation to match the current Partner's Dashboard validation.
```
name = "Send Email"
description = "An action that sends and email."
type = "flow_action"
[[extensions]]
runtime_url = "https://url.com/api/execute"
[settings]
[[settings.fields]]
type = "customer_reference"
required = true
[[settings.fields]]
type = "single_line_text_field"
key = "email-subject-line"
name = "Email Subject Line"
description = "The subject line to your email."
required = true
```
```
name = "Bid Placed"
description = "A trigger for when bids are placed on your products." …
```
=> Updated TOML file format + validation for Flow extensions

.changeset/sharp-wasps-attend.md, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/hot_reload/resources/theme_extension.js
The hot-reload mechanism for themes and theme app extensions rely on a injected script to change DOM elements when a change happens on developers machine.
In the context of theme app extensions, the mechanism was being too strict and it was not handling the following scenario:
This PR changes the logic the prefix that identifies sections from `shopify-section-template` to `shopify-section-`.
- Run `yarn create @shopify/app`
- Run `yarn shopify app generate extension  -t theme_app_extension`
- Run `yarn dev`
- Install the app
- Enable extension
- Add a section in the editor
- Modify something in blocks/star_rating.liquid
None.
=> Fix `app dev` hot reload for theme app extensions when blocks are rendered on section groups

.changeset/slimy-icons-flash.md, packages/cli/package.json, packages/features/snapshots/commands.txt, packages/theme/oclif.manifest.json, packages/theme/src/cli/commands/theme/update/check.ts, packages/theme/src/cli/commands/theme/update/init.ts
Related to https://github.com/Shopify/cli/pull/1909
- Checkout the feature branch
- Run `pnpm shopify:run theme` 
- Confirm no update commands are present
=> Hide `shopify theme update init` and `shopify theme update check` commands

.changeset/wet-mice-smell.md, packages/app/src/cli/models/app/app.test-data.ts, packages/app/src/cli/models/extensions/extension-instance.test.ts, packages/app/src/cli/models/extensions/extension-instance.ts
Cherrypicking commits from https://github.com/Shopify/cli/pull/2259 to create a patch release on 3.47 branch.
=> Fix tax calculation deployment (on stable/3.47)

packages/app/templates/ui-extensions/projects/checkout_ui_extension/package.json.liquid, packages/app/templates/ui-extensions/projects/ui_extension/package.json.liquid
A new version `0.27.0` of `@shopify/checkout-ui-extensions` was just published. We'd like to update the CLI template so newly scaffolded extensions are on the latest version by default.
Changes the version number used in a scaffolded checkout ui extension.
Scaffold a new extension and expect to see version `0.27.0`.
N/A
=> bumped checkout-ui-extensions version to 0.27.0

.changeset/nine-elephants-applaud.md, packages/cli-kit/src/public/node/ui.tsx
The [most common error in Bugsnag](https://app.bugsnag.com/shopify/cli/errors/63e122a25a1dd100099b390c) is `Error process.stdin.setRawMode is not a function`, which is shown when the CLI tries to authenticate in a non-tty terminal.
Check if the terminal is compatible before prompting for a key press and show a proper error otherwise, as we do for other prompts, and avoid reporting it to Bugsnag.
**Before**:
**After**:
`true | p shopify app dev`
=> Improve error message on login from non-tty

.changeset/short-yaks-smile.md, packages/app/oclif.manifest.json, packages/app/src/cli/commands/app/dev.ts, packages/cli-kit/src/public/node/error.ts, packages/cli-kit/src/public/node/plugins/tunnel.ts, packages/plugin-cloudflare/src/tunnel.test.ts, packages/plugin-cloudflare/src/tunnel.ts
The error `Could not start tunnel, max retries reached` is quite common in [Bugsnag](https://app.bugsnag.com/shopify/cli/errors/646b95f4a1b867000842c8b8), but we don't provide additional help.
- Adds a `What to try` section to Cloudflare errors:
- Unhides the `tunnel` flag in the CLI help
- `p shopify app dev`
- Turn off the internet connection before creating the tunnel (I add a sleep to make it easier)
- 💥 
Release [documentation PR](https://github.com/Shopify/shopify-dev/pull/34881)
=> Improve Cloudflare errors

packages/app/src/cli/models/extensions/specifications/flow_action.ts, packages/app/src/cli/models/extensions/specifications/flow_trigger.ts
Resolves https://github.com/Shopify/flow/issues/19464
Adds `bundling` feature to flow extensions to update extension config on deploy. We need to use the bunlding feature to update the extension's config since the initial registration call sends in a empty config object
- Config is hardcoded to empty [here](https://github.com/Shopify/cli/blob/3f7fbad7db0c6e28c10a70a550d5a859cd5eddc7/packages/app/src/cli/services/dev/create-extension.ts#L36)
- Code path deploy.ts -> [`ensureDeployContext`](https://github.com/Shopify/cli/blob/cedea083cccbd10f0cf0ca4d09a7a8e7dfb2c34b/packages/app/src/cli/services/context.ts#L291) ->[`ensureDeploymentIsPresence`](https://github.com/Shopify/cli/blob/3f7fbad7db0c6e28c10a70a550d5a859cd5eddc7/packages/app/src/cli/services/context/identifiers.ts#L38) -> …
=> Adds `bundling` feature to flow extensions to update extension config on deploy

packages/app/src/cli/models/extensions/extension-instance.test.ts, packages/app/src/cli/models/extensions/extension-instance.ts
Currently, functions dev mode only watches for GraphQL files starting with `input.*`. Because we don't know how people will name their GraphQL files, it's best not to force a `input.*` prefix. The main reason for this prefix is because our current Rust crate touches a hidden GraphQL file which sends the CLI in a build loop (rebuild triggers a file change, which triggers a rebuild, rinse & repeat).
Instead of using a prefix, this commit fixes that by globbing on all non-hidden graphql file.
Run `shopify app dev` with a function:
- change any graphql file, notice the CLI updates the draft
- change a rust file (which will touch a hidden file) and notice the CLI does not fall in loop.
=> Watch all non-hidden GrahpQL files in functions

.changeset/shy-students-admire.md, packages/cli-kit/src/public/node/base-command.ts
There have been tons of questions/issues because of people running NPM scripts without using the `--` separator. Like running `npm run dev --reset` instead of `npm run dev -- --reset`.
Shows a warning when passing a CLI flag with NPM without the separator:
Idea by @shauns
- `npm run shopify app dev --reset`
- `npm run shopify app dev -- --reset`
- `npm run shopify app dev --not-existing`
- `npm run shopify app info --path=whatever`
- `pnpm run shopify app dev --reset`
- `yarn run shopify app dev --reset`
=> Show a warning when using NPM without the -- separator

.changeset/many-chefs-invent.md, packages/create-app/oclif.manifest.json, packages/create-app/src/prompts/init.test.ts, packages/create-app/src/prompts/init.ts
Allows developer to select the "none" template on app creation (see: https://github.com/Shopify/internal-cli-foundations/issues/666)
Adds "none" template option with custom label
1. `pnpm create-app`
2. Select "none" option
3. Validate that the "none" template was used.
I'm assuming we have existing analytics as all I'm doing is adding a new option to an existing list.
=> Add none template

packages/app/src/cli/services/context.ts, packages/app/src/cli/services/deploy.ts
Fixes https://github.com/Shopify/app-deploys/issues/608
We were showing the "Stay tuned" banner even after opting in the unified deployments feature.
This PR makes sure we don't do that.
Try running `deploy` and opting in, the "stay tuned" banner should not be shown the second time you deploy.
=> Hide "Stay tuned" banner after opting in

packages/app/src/cli/services/deploy/upload.test.ts, packages/app/src/cli/services/deploy/upload.ts
Fixes https://github.com/Shopify/app-deploys/issues/587
We want to show a custom error message when the version is already taken.
Add that error message.
- Deploy with `--version=something`
- Deploy again with the same version
- You should see the error message above
=> Show custom error message when version already taken

packages/create-app/src/prompts/init.test.ts, packages/create-app/src/prompts/init.ts
We shouldn't show `Let’s get started by naming your app project.` if we're not going to prompt them for a name.
Before:
```
$ npm init @shopify/app --name somename
Welcome. Let’s get started by naming your app project. You can change it later.
?  Which template would you like to use?
>  (1) node
(2) php
(3) ruby
(4) none (build an app with extensions only)
Press ↑↓ arrows to select, enter to confirm.
```
After:
```
$ npm init @shopify/app --name somename
Welcome. Let’s get started by choosing a template for your app project.
?  Which template would you like to use?
>  (1) node
(2) php
(3) ruby
(4) none (build an app with extensions only)
Press ↑↓ arrows to select, enter to confirm.
```
`dev create-app` with and without `--name`
You can also run `bin/ create-test-app.js` for another …
=> Show intro line on first used prompt during app create

.changeset/warm-ears-laugh.md, packages/app/src/cli/models/app/app.ts, packages/app/src/cli/services/dev.ts, packages/app/src/cli/utilities/app/http-reverse-proxy.ts
Some frameworks might use a separate server to handle HMR requests, which would typically require:
- a separate TCP port
- the ability to handle _some_ HTTP requests in the sidekick server
Adding a new `[hmr_server]` config option to the web TOML file, which must contain an `http_paths` array. If that is present, we'll spin up another port and redirect websocket (and HTTP within `http_paths`) traffic to that port.
A framework that does this is Remix, but it's not very simple to set up for testing. Ping me if you want to actually run this. But essentially, if you add the config, you should see a new env var called `HMR_SERVER_PORT`.
We'll need to document the new fields in https://shopify.dev/docs/apps/tools/cli/structure#shopify-web-toml.
How do we know this change was effective? Please …
=> Add support for configuring a sidekick HMR server

packages/app/src/cli/api/graphql/create_app.ts
Resolves: Part 3 of https://github.com/Shopify/partners/issues/48560
We need to set scopes to the empty Scope Set for non-launchable apps.
It is adding requestedAccessScopes to the Partners CLI AppCreate mutation.
bin/spin pnpm shopify app config link --path={PATH_TO_REPO}
=> Add scopes during app creation for non-launchable apps

packages/app/src/cli/models/extensions/extension-instance.ts
Resolves https://github.com/Shopify/flow/issues/19493
- Flow needs to use `handle` to simplify the trigger method for Flow triggers.
- This change is temporary until the `handle` config spec is fully developed.
- Temporarily pass `handle` from `deployConfig` to `context`.
- Generate a Flow Action/Trigger extension and use `handle` in the config TOML.
=> [Temp Fix] Use `handle` as context if available on extension deployConfig

bin/create-test-app.js, packages/app/src/cli/commands/app/generate/extension.ts, packages/app/src/cli/models/app/app.test-data.ts, packages/app/src/cli/services/app/config/use.test.ts, packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/context.ts, packages/app/src/cli/services/generate.test.ts, packages/app/src/cli/services/generate.ts
Fixes https://github.com/Shopify/internal-cli-foundations/issues/682
Fixes https://github.com/Shopify/internal-cli-foundations/issues/688
Make it so that `ensureDevContext`, `ensureGenerateContext`, and `ensureDeployContext` use the config-as-code information instead of prompting the user.
`bin/create-test-app.js -i local -e ui --config-as-code --deploy`
=> Use config to deploy, release or generate

packages/theme/src/cli/services/update/check.test.ts, packages/theme/src/cli/services/update/schemas/update_extension_schema_v1.ts
Fixes https://github.com/Shopify/shopify/issues/437598
tl;dr: Update action is descoped from the project. Further context can be found [here](https://docs.google.com/document/d/1kfeB1SFg9oygW_0mEHON51eB4du_2QNq5US46mEJd_A/edit#heading=h.243m6mt93xx0)  
Removing the Update action from the update_extension schema. The zod schema should be consistent with core and [theme-liquid-docs](https://github.com/Shopify/theme-liquid-docs). Given I've already updated the schema in our liquid-docs ([PR](https://github.com/Shopify/theme-liquid-docs/pull/228)), I regenerated the schema here by running `pnpm run schema:generate` which in turn generates the schema based on the [theme-liquid-docs](https://github.com/Shopify/theme-liquid-docs). 
Updated and ran the related test suite, which is …
=> remove the update action from theme update_extension schema

packages/app/src/cli/services/flow/extension-to-toml.test.ts, packages/app/src/cli/services/flow/extension-to-toml.ts
It is important to maintain the same name when importing existing Partners Dashboard managed Flow extensions as that name is what appears in the Flow app.
Changes the `import-flow-legacy-extensions` command to use the name from the Flow action or trigger's configuration instead of the extension's name.
=> Use config name in flow migrate command

packages/app/src/cli/services/app/config/use.test.ts, packages/app/src/cli/services/app/config/use.ts, packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/context.ts, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/local-storage.ts
We want to preserve previous app switching behavior from `dev --reset` where an uninstall webhook is sent to avoid issues with local database install info.
Saves previous app id when switching between configurations on `use` and sets current app id as previous id on `dev`. `dev` uses this previous app id to choose when webhook is sent.
1. Create a new app with `pnpm create-app --local --template=node --path ~/Desktop`
2. Run `pnpm shopify app dev --path ~/Desktop/your-app` (legacy behavior)
3. Run `pnpm shopify app dev --path ~/Desktop/your-app --reset` and switch to new app
4. 👀 See how uninstall webhook is still being sent
5. Run link `pnpm shopify app config link --path ~/Desktop/your-app` 
6. Run `pnpm shopify app dev --path ~/Desktop/your-app` (new config behavior)
7. 👀 See how …
=> Keep track previously used app id

.changeset/dry-moose-raise.md, packages/app/src/cli/services/dev.ts
When a single `web` has both frontend and backend roles, it gets assigned 2 ports, which doesn't make sense.
Ensures that a monolithic app will have only 1 port assigned. This is first felt in terms of webhooks.
Before:
After:
1. Run `dev`, open the preview link, install the app.
2. Kill dev and change [this line](https://github.com/Shopify/cli/blob/45f52b1530b11f98bdf821b922b0968075992a78/packages/app/src/cli/services/dev.ts#L117C1-L117C1) to `const sendUninstallWebhook = true`
3. Run `dev` again and watch what happens with the webhook.
=> Always assign only 1 port to a monolith

packages/app/src/cli/services/deploy/upload.test.ts, packages/app/src/cli/services/deploy/upload.ts
We don't want to show the Next Steps section in the error banner when deploy because it's not very useful.
Removes that section.
=> Remove next steps from deploy error banner

.changeset/new-masks-divide.md, packages/ui-extensions-server-kit/src/ExtensionServerClient/ExtensionServerClient.test.ts, packages/ui-extensions-server-kit/src/ExtensionServerClient/ExtensionServerClient.ts
Enables users of `@shopify/ui-extensions-server-kit` to subscribe to open/close web socket events
Add a new `onConnection` method on the client
The unit tests should suffices. The full flow will be tested in subsequent PRs.
=> Dev-server-kit: enable adding a handler for when the websocket opens and closes

packages/app/src/cli/services/app/config/link.ts, packages/app/src/cli/services/release.test.ts, packages/app/src/cli/services/release.ts, packages/app/src/cli/services/release/version-diff.test.ts, packages/app/src/cli/services/release/version-diff.ts
CI is [failing for main](https://github.com/Shopify/cli/actions/runs/5517272912/jobs/10059663582)
```
> nx run app:lint
/home/runner/work/cli/cli/packages/app/src/cli/services/app/config/link.ts
10:9  error  'getAppInfo' is defined but never used  unused-imports/no-unused-imports
/home/runner/work/cli/cli/packages/app/src/cli/services/release.ts
62:7  warning  The headline attribute should end with punctuation  @shopify/cli/banner-headline-format
/home/runner/work/cli/cli/packages/app/src/cli/services/release/version-diff.ts
37:7  warning  The headline attribute should end with punctuation  @shopify/cli/banner-headline-format
✖ 3 problems (1 error, 2 warnings)
```
Fix them
CI
=> Fix lint issues

packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/context.ts, packages/app/src/cli/services/dev/select-app.test.ts, packages/app/src/cli/services/dev/select-app.ts
Fixes #[690](https://github.com/Shopify/internal-cli-foundations/issues/690)
We need to set the scopes when creating new launchable apps via the CLI.
- [ x I've considered possible cross-platform impacts (Mac, Linux, Windows)
=> Set scopes when creating new launchable apps

packages/app/src/cli/api/graphql/create_app.ts, packages/app/src/cli/api/graphql/find_app.ts, packages/app/src/cli/models/app/app.test-data.ts, packages/app/src/cli/models/organization.ts, packages/app/src/cli/services/app/config/link.test.ts, packages/app/src/cli/services/app/config/link.ts, packages/app/src/cli/services/app/config/push.test.ts, packages/app/src/cli/services/app/config/push.ts
This PR adds all the remaining fields to be queried and updated when running `link` and `push`, respectively.
This PR adds all the remaining fields to be queried and updated when running `link` and `push`, respectively. It also updates the delete logic for declared scopes.
1. create an app
```bash
pnpm create-app --local --template=node --path ~/Desktop/multi-config-app
```
2. run `dev`
```bash
pnpm shopify app config link --path ~/Desktop/multi-config-app
```
3.  Add any of the fields on the `AppSchema` and run `push`:
```bash
pnpm shopify app config push --path ~/Desktop/multi-config-app`
```
4. Enable `access_scopes_as_configuration` for your app and remove `use_legacy_install_flow = true` from the TOML file.
```bash
pnpm shopify app config push --path ~/Desktop/multi-config-app`
``` …
=> Add remaining declarative fields

packages/create-app/src/prompts/init.ts
Fixes https://github.com/Shopify/internal-cli-foundations/issues/697
Prefer hasOwnProperty as its supported on Node 14 (which is no longer supported itself... but no need to break it if it can be avoided)
=> Prefer hasOwnProperty to hasOwn

packages/app/src/cli/services/flow/constants.ts
Typo is causing task not to sync to Flow when `multi_line_text_field` is used.
Corrects the typo.
Create a Flow extension that uses a `multi_line_text_field` field
=> Correct typo in multi_line_text_field mapping

packages/app/src/cli/models/app/app.test-data.ts, packages/app/src/cli/models/app/app.test.ts, packages/app/src/cli/models/app/app.ts, packages/app/src/cli/models/app/loader.ts, packages/app/src/cli/services/app/config/push.ts, packages/app/src/cli/services/info.ts
Setting scopes with commas was not passing validation.
I added a `trim()` to the split scope names and extracted into a function and used it wherever we were splitting the scopes before.
1. create an app
```bash
pnpm create-app --local --template=node --path ~/Desktop
```
2. link an app
```bash
pnpm shopify app config link --path ~/Desktop/scopes-app
```
3. enable the scopes betas
4. change scopes to contain a space, like `scopes = "write_products, read_themes"`
5. push config
```bash
pnpm shopify app config push --path ~/Desktop/scopes-app
```
6. 👀 see how read themes was added as a requested scope
=> Accept scopes with spaces between commas

bin/create-test-app.js
As per title, this is useful to test templates like `none`.
=> Allow passing -t to the create-test-app script

.changeset/silent-pigs-wonder.md, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/output.ts, packages/app/src/cli/utilities/app/http-reverse-proxy.ts, packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.test.tsx, packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx
Ensures that we are consistent in showing the preview footer in dev
Keeps the dev task list open, with its footer, even when the tasks have completed running.
Init a "none" app, and add a subscription ui extension. Run dev and observe that the footer is displayed and can be previewed with (p)
=> Always show the footer in dev, by keeping the task display running

packages/app/src/cli/models/app/app.ts, packages/app/src/cli/services/app/config/link.test.ts, packages/app/src/cli/services/app/config/link.ts
@alvaro-shopify realized that the link command was crashing when there is no shopify.app.toml.
Fixes it so the command works anyway
- Remove shopify.app.toml
- `p shopify app config link`
=> Fix config link when there is no shopify.app.toml

.changeset/moody-forks-exercise.md, packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.test.tsx, packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx, packages/cli-kit/src/public/node/ui.tsx
They make the output of `dev` longer and add very little benefit.
=> Remove dates from concurrent output

packages/app/src/cli/prompts/config.test.ts, packages/app/src/cli/prompts/config.ts, packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.test.tsx, packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.tsx, packages/cli-kit/src/private/node/ui/components/Prompts/GitDiff.test.tsx, packages/cli-kit/src/private/node/ui/components/Prompts/GitDiff.tsx, packages/cli-kit/src/private/node/ui/components/Prompts/InfoMessage.test.tsx, packages/cli-kit/src/private/node/ui/components/Prompts/InfoMessage.tsx, packages/cli-kit/src/private/node/ui/components/Prompts/PromptLayout.tsx, packages/cli-kit/src/private/node/ui/components/SelectInput.tsx, packages/cli-kit/src/private/node/ui/components/SelectPrompt.test.tsx, packages/cli-kit/src/private/node/ui/components/SelectPrompt.tsx, packages/cli-kit/src/private/node/ui/components/TextPrompt.test.tsx, packages/cli-kit/src/private/node/ui/components/TextPrompt.tsx, packages/cli-kit/src/private/node/ui/hooks/use-prompt.ts, packages/cli-kit/src/public/node/ui.tsx
In order to create a multi-select prompt we first need to refactor prompts so that a large part of their code can be reused to build other prompts. This is also going to be useful for text prompt and the work that @amcaplan is doing in https://github.com/Shopify/cli/pull/2451
=> Refactor AutocompletePrompt and SelectPrompt

packages/app/src/cli/api/graphql/create_app.ts, packages/app/src/cli/api/graphql/find_app.ts, packages/app/src/cli/api/graphql/get_config.ts, packages/app/src/cli/api/graphql/push_config.ts, packages/app/src/cli/models/app/app.test-data.ts, packages/app/src/cli/models/app/app.test.ts, packages/app/src/cli/models/app/app.ts, packages/app/src/cli/models/app/loader.test.ts, packages/app/src/cli/models/organization.ts, packages/app/src/cli/prompts/dev.test.ts, packages/app/src/cli/prompts/dev.ts, packages/app/src/cli/services/app/config/link.test.ts, packages/app/src/cli/services/app/config/link.ts, packages/app/src/cli/services/app/config/push.test.ts, packages/app/src/cli/services/app/config/push.ts, packages/app/src/cli/services/app/config/use.test.ts, packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/info.test.ts
We are removing `api_contact_email` for the following reasons:
- Storing the `api_contact_email` could possibly store PII about developers in source control. 
- Updating `api_contact_email` is not an active part of the development loop.
- It is already pre-configured when a new app is created upstream and is very rarely changed.
- We'll want to be more careful as to how we expose emails and will be worth taking more time and looking into better alternatives post-Editions.
Removes `api_contact_email` as a declarative configuration.
Run `dev`, `link` and `push` to make sure that `api_contact_email` is no longer declarative.
=> Remove api contact email from configuration file

packages/app/src/cli/services/app/config/link.test.ts, packages/app/src/cli/services/app/config/link.ts, packages/app/src/cli/services/context.ts
Ensures that we don't have a success banner from the `link` process in the middle of running `dev`.
Generate and app template and run `dev` for the first time. The success banner shouldn't be there anymore.
=> Prevent link success banner from showing up when linking on dev

packages/app/src/cli/prompts/generate/extension.test.ts, packages/app/src/cli/prompts/generate/extension.ts, packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/syncer/uploader/bulk_test.rb, packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/syncer_test.rb
The name is actually not internal only in every case.
Fixes https://github.com/Shopify/internal-cli-foundations/issues/705
Change the prompt message to: `Name your extension:`
=> Remove `(internal only)` from extension name prompt

packages/app/src/cli/services/app/config/link.test.ts, packages/app/src/cli/services/app/config/link.ts
If only a subset of privacy compliance webhooks are updated, then linking will trigger the following error. This is because we are setting undefined values as hardcoded empty strings, which fails the URL validation in the schema.
Removes hardcoded string for privacy compliance webhook urls.
Ensure a subset of privacy compliance webhooks are set and run link successfully.
=> Remove hardcoded string when optional webhook urls are undefined

.changeset/sixty-pumpkins-sleep.md, packages/app/src/cli/prompts/release.test.ts, packages/app/src/cli/prompts/release.ts, packages/app/src/cli/services/context/identifiers-extensions.test.ts, packages/app/src/cli/services/context/identifiers-extensions.ts, packages/app/src/cli/services/context/identifiers-functions.test.ts, packages/app/src/cli/services/context/identifiers-functions.ts, packages/app/src/cli/services/context/prompts.test.ts, packages/app/src/cli/services/context/prompts.ts, packages/eslint-plugin-cli/rules/prompt-message-format.js
Fixes https://github.com/Shopify/app-deploys/issues/628
We want to warn more strongly when deploying dangerously.
Regular deploys are as before.
Deploys that remove extensions are prompted in a way that requires a more deliberate response.
Deploy an app with an extension, then remove the extension and deploy again. You should see the dangerous prompt.
=> Render DangerousConfirmationPrompt when removing an extension

.changeset/heavy-singers-speak.md, packages/app/src/cli/validations/version-name.test.ts, packages/app/src/cli/validations/version-name.ts
Closes: https://github.com/Shopify/app-deploys/issues/646
Closes: https://github.com/Shopify/app-deploys/issues/649
Change the forward slash to be an invalid character for version_tag to avoid issues when used in URLs (details in [issue](https://github.com/Shopify/app-deploys/issues/646)).
Updates the regex, error copy, and tests to make `/` an invalid character
Try to create an app version with a name including a forward slash.
=> Change forward slash to be an invalid character for app version tag

.changeset/long-bees-clean.md, packages/app/src/cli/services/deploy/mode.test.ts, packages/app/src/cli/services/deploy/mode.ts
Fixes https://github.com/Shopify/app-deploys/issues/653
Added a new note with bolded date to indicate the on **September 5, 2023** all apps will be automatically opted into the app simplified deployment on the "Simplified deployment available now!" banner.
It would push developers to opt in earlier than later (or seemingly never).
Create an app locally: `bin/create-test-app.js --bare`
Enable `app_unfied_deployments_opt_in` beta flag only for this app
Go to newly created app folder and deploy: `npm run deploy`
=> Add automatic app unified deployment upgrade date to banner

packages/app/src/cli/models/app/loader.test.ts
Want to make sure we have sufficient coverage over the current and new format of extension toml files so that regressions aren't introduced.
Testing the following
Just tests
N/A
=> Add integration tests for all of the extension tomls

packages/app/package.json, packages/app/src/cli/hooks/clear_command_cache.ts, packages/app/src/cli/prompts/dev.test.ts, packages/app/src/cli/prompts/dev.ts, packages/app/src/cli/services/app/config/link.test.ts, packages/app/src/cli/services/app/config/link.ts, packages/app/src/cli/services/dev/select-app.ts, packages/app/src/cli/services/local-storage.ts, packages/app/src/cli/utilities/app/config/getTomls.ts
Add a command cache to store state for the duration of the command lifecycle. Use this cache to decide whether to ask the config name.
It's becoming exceeding less efficient to pass state around to 5+ functions to avoid using module state. The app cache serves an entirely different purpose -- there are a number of cases where we don't yet have an app at all but still need to understand what step we're at in the command and what preceded. A lightweight cache for the command itself is a useful abstraction for this.
Run `link` and re-link a previously linked file. It should skip the command name step.
=> add cache for duration of command lifecycle

packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/context.ts, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/urls.test.ts, packages/app/src/cli/services/dev/urls.ts
When running `shopify app dev --client-id <app-client-id>`, if there is a current linked configuration, the changes to the app URLs and configuration get updated to the file even if the config file is linked to a different app.
Ensures that the loaded configuration file does not get updated if the `client_id` on file does not match with the app that is fetched from the `--client-id` flag.
**1st scenario**
1. Run `shopify app config link` to link a `shopify.app.toml` to an app upstream.
1. Run `shopify app dev --client-id <different-id-than-linked>` and see that `different-id-than-linked` URLs are updated upstream, with no changes to `shopify.app.toml`.
**2nd scenario**
1. Run `shopify app config link` to link a `shopify.app.toml` to an app upstream.
1. Run `shopify app dev --reset` up …
=> Fix dev behavior with reset and client-id flags

packages/app/src/cli/models/app/template.ts, packages/app/src/cli/models/extensions/extension-instance.ts, packages/app/src/cli/models/extensions/specifications/function.ts, packages/app/src/cli/services/context/id-matching.ts, packages/app/src/cli/services/context/identifiers-extensions.ts, packages/app/src/cli/services/context/identifiers.ts, packages/app/src/cli/services/context/prompts.test.ts, packages/app/src/cli/services/context/prompts.ts, packages/app/src/cli/services/deploy/upload.test.ts, packages/app/src/cli/services/deploy/upload.ts, packages/app/src/cli/services/dev/extension/localization.ts, packages/app/src/cli/services/dev/migrate-to-ui-extension.test.ts, packages/app/src/cli/services/dev/migrate-to-ui-extension.ts, packages/app/src/cli/services/info.test.ts, packages/app/src/cli/services/info.ts
With the introduction of localizable names, using the extension name in prompts / logs leads to undesirable results (like showing a generig `t:name`). We should use the `handle` instead.
- Use handle in all logs/prompts where the name was being used before
- Update tests
- Also update some other logic that was using the name
- Show `extensions.targeting` in errors instead of `extension_points`
- generate an admin action extension
- try to deploy
- you should see an error but with the correct namings
- run `app info` you should see the handle in the info section
=> Use handle instead of name in prompts/logs

packages/app/src/cli/models/app/loader.test.ts, packages/app/src/cli/models/app/loader.ts, packages/app/src/cli/services/app/config/use.test.ts, packages/app/src/cli/services/app/config/use.ts, packages/app/src/cli/services/context.ts
When a config file that was cached with `link` or `use` doesn't exist anymore, we want to allow them to choose a new file.
When the cached file does not exist, we call `use` which will let users choose another file.
1. Link a config file
2. Rename it
3. Run any command that uses the current config, like `dev`, `deploy`, etc
4. 👀 See how you can now choose the correct file
=> Run use to select config when current config file does not exist

.changeset/nasty-melons-attack.md, packages/app/src/cli/services/dev/extension/server/middlewares.test.ts, packages/app/src/cli/services/dev/extension/server/middlewares.ts
Update the 404 error messages to refer to "extension target" instead of "extension point"
=> Update Extensions Dev Server 404 message to say extension targets

packages/app/oclif.manifest.json, packages/app/src/cli/commands/app/build.ts, packages/app/src/cli/commands/app/dev.ts, packages/app/src/cli/commands/app/function/schema.ts, packages/app/src/cli/commands/app/generate/extension.ts, packages/app/src/cli/commands/app/import-flow-legacy-extensions.ts, packages/app/src/cli/commands/app/release.ts, packages/app/src/cli/commands/app/versions/list.ts
`--client-id`/`--api-key` can't be used with `--config` for most `shopify app` commands
=> Exclude client-id/api-key flags from being run with --config except in link

.changeset/rude-seals-draw.md, packages/app/src/cli/models/templates/ui-specifications/product_subscription.ts, packages/app/src/cli/models/templates/ui-specifications/web_pixel_extension.ts
Updating extension groups + template names per @MeredithCastile's latest designs
relates to https://github.com/Shopify/partners/pull/48763 and https://github.com/Shopify/shopify-dev/pull/35237
This PR updates the extension specifications in this repo. The remainder of the specifications are in `partners`, those changes are encapsulated in https://github.com/Shopify/partners/pull/48763. FWIW https://github.com/Shopify/internal-cli-foundations/issues/637 will centralize all of the specifications in `partners` which I strongly support.
**Screenshots to come once this is no longer WIP**
**🎩  steps to come once this is no longer WIP**
=> updated `extension generate` groupings and names

.changeset/hot-carrots-confess.md, packages/app/src/cli/services/deploy.test.ts, packages/app/src/cli/services/deploy.ts, packages/app/src/cli/services/release.test.ts, packages/app/src/cli/services/release.ts, packages/app/src/cli/services/versions-list.test.ts, packages/app/src/cli/services/versions-list.ts
Fixes https://github.com/Shopify/app-deploys/issues/659
Removes the distribution percentage from app versions list in order to not confuse the users.
Removes the distributionPercentage info
**Before changes:**
1. From the `main` branch create an app by running `bin/create-test-app.js --bare` 
2. Create a deployable app module `pnpm shopify app generate extension --type=subscriptions-ui`
3. Run run through the various deployments-related commands (`deploy`,  `release`, and `versions list`)
4. Check that `deploy` success message shows `Next steps`,  and references "rollout progress"
5. Check that distribution percentage is visible for active app version
6. Check that `release` success message shows `Next steps`,  and references "rollout progress"
**After changes:**
(Switch on …
=> Remove distribution percentage and rollout progress references

packages/app/src/cli/models/extensions/specifications/flow_trigger.ts
Fixes https://github.com/Shopify/flow/issues/19543
This PR adds extra validation to `flow_trigger` field `key`s. This validation is currently present in core and is being replicated here to offer app developers better error messaging
- Pull in changes
- Create a new `flow_trigger` extension
- Change field `key` value to include a non-alpha or space character
- Deploy and observe that validation error pops up in CLI
=> Add flow trigger field name validation

packages/cli-kit/src/public/node/toml.ts
Taking inspiration from https://github.com/cloudflare/workers-sdk/pull/936
Our TOML parsing code is susceptible to the same issue so I'm preventively fixing it.
=> Support Windows line-endings in TOML files

packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/context.ts, packages/app/src/cli/services/release.test.ts, packages/app/src/cli/services/release.ts
We were using the title in the local toml file as the name of the app in prompts, but that name might not match the name of the app you are deploying/releasing to.
Fixes https://github.com/Shopify/app-deploys/issues/657 
Use the name from the partners app in prompts.
=> Use title from partnersApp in release prompts

packages/app/src/cli/prompts/config.test.ts, packages/app/src/cli/prompts/config.ts
**Steps to reproduce**
1. Ensure app has a linked config file
2. Run `shopify app dev`
3. Run `shopify app config push` and notice the following
This ensures that we don't show the diff of `[build]` changes when pushing up app config as `[build]` is only a local CLI setting.
1. Ensure app has a linked config file
2. Run `shopify app dev`
3. Run `shopify app config push` and notice the following
4. 
=> Ensure [build] is not compared against remote app config

packages/app/src/cli/commands/app/config/link.ts
We don't have alignment on the `--config` name and behavior. This is a hotfix to simply stop passing the flag in the command, so the behavior won't currently exist.
=> hotfix to remove config flag

packages/app/src/cli/services/dev/extension/utilities.test.ts, packages/app/src/cli/services/dev/extension/utilities.ts
Fixes errors when using the dev console with a new-style thank-you page extension target:
I fixed this by just treating these as "checkout" extensions, like we do for the order status page.
=> Fix Thank You page redirect URLs

.changeset/light-fireants-share.md, packages/cli-kit/src/public/node/node-package-manager.ts, packages/cli/src/cli/services/upgrade.test.ts, packages/cli/src/cli/services/upgrade.ts
Pnpm upgrade was broken
Fix the above issue.
=> Add -w option to pnpm upgrade command

packages/cli-kit/src/private/node/api.ts, packages/cli-kit/src/private/node/api/graphql.ts, packages/cli-kit/src/private/node/api/headers.ts, packages/cli-kit/src/private/node/api/urls.test.ts, packages/cli-kit/src/private/node/api/urls.ts, packages/cli-kit/src/public/node/http.ts
Fixes #0000 
Noticed that tokens are being logged to console in `--verbose` mode
Sanitizes the URL parameters where they are printed.
Unit tests and did a 🎩 
=> Sanitize tokens in verbose mode

packages/app/src/cli/services/dev/output.test.ts, packages/app/src/cli/services/dev/output.ts
When there is no config selected we would show this message:
```
npm run shopify app config push -- --config=undefined
```
Don't show when the config is undefined
=> Don't show config argument when it's missing

docs/cli/cross-os-compatibility.md
A small addition to your cross os testing docs.
Without installing chocolatey and visual studio code tools 2019, I wasn't able to run `pnpm install`
=> Add note about node installation

.changeset/fuzzy-oranges-juggle.md, packages/app/src/cli/models/app/loader.ts, packages/app/src/cli/prompts/dev.ts, packages/app/src/cli/services/dev/update-extension.test.ts, packages/app/src/cli/services/dev/update-extension.ts, packages/app/src/cli/utilities/app/config/getTomls.ts, pnpm-lock.yaml
Fixes https://github.com/Shopify/cli/issues/2623
Improve the error message when a configuration file is invalid, showing the file path and exact problem.
**Before**:
**After**:
- Create an app with an extension
- Put a wrong value (like `asdf`) for any field in shopify.extension.toml
- `p shopify app dev`
- Revert the change in shopify.extension.toml
- Put a wrong value (like `asdf`) for any field in shopify.app.toml
- `p shopify app dev --reset` and choose to use an existing app
=> Improve error message for invalid configuration files

packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/context.ts, packages/app/src/cli/services/dev/select-app.test.ts, packages/app/src/cli/services/dev/select-app.ts
In this way we also fix a bug in handling scopes with whitespaces.
Currently trying to create a new app with these scopes `write_products, write_discounts` fails.
Reuse `getAppScopesArray` so we can take advantage of the trimming logic.
=> Reuse getAppScopesArray function while selecting an app

.changeset/young-birds-yell.md, packages/cli/src/cli/services/upgrade.test.ts, packages/cli/src/cli/services/upgrade.ts
If your app includes a valid app config file `shopify.app.production.toml` but does not the default one  `shopify.app.toml`  this error is shown when you run the `upgrade` command
```
╭─ error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                        │
│  Couldn't find the configuration file for /your/app/path, are you in a Shopify project directory?                          │
│                                                                                                                                                        │ …
```
=> Fix upgrade command using a non default app config file

packages/app/src/cli/services/dev/fetch.test.ts, packages/app/src/cli/services/dev/fetch.ts, packages/cli-kit/src/private/node/session/exchange.ts, packages/cli-kit/src/public/node/dot-env.test.ts, packages/cli-kit/src/public/node/dot-env.ts, packages/cli-kit/src/public/node/node-package-manager.test.ts, packages/cli-kit/src/public/node/node-package-manager.ts, packages/eslint-plugin-cli/rules/no-error-factory-functions.js, packages/plugin-cloudflare/src/tunnel.ts
I noticed that the `no-error-factory-functions` rule was broken
- fix the eslint rule
- fix all failures, mostly by inlining the error or creating subclasses
=> Fix rule that detects functions that create errors

package.json, packages/app/package.json, packages/features/features/node-deps.feature, packages/features/package.json, packages/features/steps/node-deps.steps.ts, pnpm-lock.yaml
I noticed that it was easy for dependencies shared across multiple packages to get out of sync.
- Add a new feature test that ensures that 'important' node deps are in sync across all workspaces
- Update some shared dependencies that were out of sync
- Make a change in `package/app/package.json` and change the version of `vitest` to `4.6.8`
- Run `FEATURE=features/node-deps.feature p test:features` from the root of the repo
- You should see this error:
```
Feature: Node Dependencies # features/node-deps.feature:1
Scenario: Shared node dependencies are in sync across packages # features/node-deps.feature:3
When I look at the package.json files in all packages
Then I see all shared node dependencies on the same version
✖ failed
AssertionError [ERR_ASSERTION]: The following node dependencies …
```
=> Add feature test to ensure that important shared node deps are in sync

.changeset/rotten-mirrors-march.md, packages/app/src/cli/api/graphql/development_preview.ts, packages/app/src/cli/api/graphql/find_app.ts, packages/app/src/cli/commands/app/dev.ts, packages/app/src/cli/models/organization.ts, packages/app/src/cli/services/context.ts, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/extension.ts, packages/app/src/cli/services/dev/output.ts, packages/app/src/cli/services/extensions/common.ts, packages/app/src/cli/utilities/app/http-reverse-proxy.test.ts, packages/app/src/cli/utilities/app/http-reverse-proxy.ts, packages/cli-kit/src/private/node/tree-kill.ts, packages/cli-kit/src/private/node/ui.tsx, packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.test.tsx, packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx, packages/cli-kit/src/public/node/base-command.ts, packages/cli-kit/src/public/node/hooks/postrun.ts, packages/cli-kit/src/public/node/system.ts, packages/cli-kit/src/public/node/tree-kill.ts, packages/cli-kit/src/public/node/ui.tsx
Closes https://github.com/Shopify/internal-cli-foundations/issues/713
Implements solution agreed upon in this [doc discussing Dev Preview](https://docs.google.com/document/d/1pJiB-ZWFP7ieKTVAhmC6hEtI2ZuIoNGH7iFhqO-zhXA/edit?usp=sharing).
IMPORTANT!!!! This [PR](https://github.com/Shopify/cli/pull/2637) should be merged or rejected first. Other alternative is rebase this branch to the PR's one and then merge this PR
**Previously**, when running `shopify app dev`, if you have at least one `draftable` extension you are prompted to turn on Developer Preview in your store via the green underlined link to "Partner Dashboard".
**After this PR,** when running `shopify app dev`, it will automatically set dev preview to 'on' and render another shortcut in the footer that will allow you to toggle …
=> Added back GQL for enabling developer preview, updated renderDev footer to include toggle for developer preview

.changeset/yellow-jeans-beam.md, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/extension/dev_server.rb, packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/extension/dev_server_test.rb
Command `dev` is not working for 1P dev using an app with a theme app extension. After the theme content is pushed to the server by the TAE and error is returned when the instructions should be displayed
```sh
┃ Pushing theme...    80%
┃ Pushing theme...    90%
┃ Pushing theme...   100%
┃ ------------------
┃ --------- Viewing extension…
┃ ✗ An unexpected error occurred.
```
Fix a typo error in this [PR](https://github.com/Shopify/cli/pull/2171), `extension.preview_message` does not exist and `extension.location` should be used instead
- Create an app with a theme app extension
- Create a partners spin instance `spin up partners`
- Run the command `NODE_TLS_REJECT_UNAUTHORIZED=0 SHOPIFY_SERVICE_ENV=spin SPIN_INSTANCE=$(spin show -o name) SHOPIFY_CLI_1P_DEV=1 p shopify app dev --path …
=> Fix dev for 1P devs using app with a theme app extension

.changeset/chatty-ghosts-compare.md, packages/app/src/cli/commands/app/deploy.ts, packages/cli-kit/src/public/node/base-command.test.ts, packages/cli-kit/src/public/node/base-command.ts
We [already throw an error](https://github.com/Shopify/cli/pull/1964) when prompting in non-TTY environments. However, the errors are thrown a bit too late. Sometimes it's hard to understand what's the required action, especially for something like `--force`. Or even something like `client-id` which ends up initially prompting for a choice of Partner org. So we want to allow the command itself to define required flags for non-TTY environments.
We've added the ability to define a required flag set for non-TTY environments in the command, with the format:
```ts
{
// Requires `as const` because only `true` not `false` is valid
force: true as const,
// A function taking the parsed flags as input, and returning a boolean.
// In this case, `client-id` is only required to be passed if we haven't …
```
=> Require flags in non-TTY environments

bin/create-test-app.js, bin/create-test-theme.js, packages/cli-kit/src/public/node/path.ts
When running `theme package` without the `--path` flag we use `cwd()` as the default directory.
That's correct,  but on windows this path is not normalized to be used with `glob` which is what we use to find the files we need to package.
Fixes https://github.com/Shopify/cli/issues/2634
- Normalize the result of `cwd()`
- Add a `theme package` step to the `create-test-theme` script
- run `shopify theme package` in windows from a theme folder, it should produce a valid `.zip` file
=> Fix windows theme package

packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/ui/components/Dev.test.tsx, packages/app/src/cli/services/dev/ui/components/Dev.tsx, packages/app/src/cli/utilities/app/http-reverse-proxy.ts
We noticed that the tunnel was already getting killed by `treeKill` so there is no need to also stop it before.
Remove the tunnelClient handler in `abort`.
- Run `dev`
- Check your processes for the presence of `cloudflared`
- Kill `dev` (either `q` or `ctrl+c`)
- That process should have disappeared
=> Remove tunnelClient.stop()

.changeset/tall-frogs-turn.md, packages/cli/README.md, packages/cli/oclif.manifest.json, packages/cli/src/cli/commands/search.ts, packages/cli/src/cli/services/commands/search.test.ts, packages/cli/src/cli/services/commands/search.ts, packages/features/snapshots/commands.txt
Introduces the `search` command which lets users search the shopify.dev docs by optionally passing a query argument to the command - it then opens shopify.dev with that query passed in as a parameter to search. If no query argument is passed, it opens the search modal with an empty string prompting the user to initiate a search.
This PR adds the search command and service. 
~~It depends on https://github.com/Shopify/shopify-dev/pull/29072~~ 
P.S. [The search URL param feature has been introduced to shopify.dev recently](https://github.com/Shopify/shopify-dev/pull/34419) which makes the above corresponding PR  for shopify-dev irrelevant.
checkout this branch and run `pnpm shopify search` followed by your search query. If it's a multiple word search, you'll need quotes around the search …
=> Feature: Implement shopify.dev doc search

.vscode/launch.json, packages/app/src/cli/models/extensions/specifications/function.ts
Issue: https://github.com/Shopify/shopify/issues/446570
These changes will allow us use the main cli repo to deploy local_pickup_delivery_option_generator functions.
Exposes the local_pickup_delivery_option_generator extension type and allows us to deploy local_pickup_delivery_option_generator functions.
I am able deploy a function to spin with these changes on my branch.
=> Add `local_pickup_delivery_option_generator` extension type

.changeset/tough-dolls-sort.md, packages/cli-kit/src/private/node/ui/components/Command.test.tsx, packages/cli-kit/src/private/node/ui/components/Command.tsx
Make command tokens more visible
Adds a bright magenta color to command tokens (after UX consultation with @MeredithCastile)
Before:
After:
`$ pnpm shopify kitchen-sink static`
=> Make command token pop with magenta coloring

.changeset/four-walls-report.md, packages/app/src/cli/services/dev/ui/components/Dev.test.tsx, packages/app/src/cli/services/dev/ui/components/Dev.tsx, packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx
There are currently 2 UX issues with dev preview in `dev`.
- At the start the status flickers from "off" to "on" because in the beginning dev preview is turned off and gets automatically turned on
- When pressing `d` there is a delay so the user might think that nothing is happening
By showing the real value in the backend we're optimizing for the failure state. What I mean is that if turning on/off dev preview fails then the status will be correctly displayed without extra effort.
What I propose instead is to "lie" to the user by showing instant change and only revert back if the operation fails.
- At startup we immediately show `dev` preview as turned on. If turning it on fails we show an error message AND the correct "off" status.
- When pressing `d` we immediately toggle the state, …
=> Show developer preview state change immediately

.changeset/fast-bobcats-bathe.md, packages/app/src/cli/services/dev/extension/bundler.ts, packages/app/src/cli/services/extensions/bundle.ts
Fixes https://github.com/Shopify/develop-app-management/issues/34
Source maps provide a better developer experience.
Adding sourcemaps to the output of esbuild when running `dev`.
- Generate a subscription UI extension in JS
- Add a debugger statement
- Go to the test product page with the Chome dev tools open
- It should stop at the debugger and provide clean code to read
Before this change this is the code on a fresh subscription UI extension
```js
(() => {
// node_modules/.pnpm/@shopify+admin-ui-extensions@1.1.0/node_modules/@shopify/admin-ui-extensions/build/esm/api.mjs
function extend(extensionPoint, callback) {
return self.shopify.extend(extensionPoint, callback);
}
// node_modules/.pnpm/@remote-ui+core@2.1.17/node_modules/@remote-ui/core/build/esm/component.mjs
function …
```
=> Generate source maps in dev

packages/app/src/cli/services/dev/ui/components/Dev.tsx, packages/cli-kit/package.json, packages/cli-kit/src/private/node/ui.tsx, packages/cli-kit/src/public/node/system.ts, packages/cli-kit/src/public/node/tree-kill.ts, pnpm-lock.yaml
I’ve been unhappy with how opaque is our current way of terminating all processes spawned by the CLI:
- we can’t tell at a glance which are the processes being killed, so we can’t tell if we’re doing a good clean up job
- even when pressing q the dev process terminates with an error code, which forces automation scripts to wrap everything in a try catch
I’ve vendored in and refactored the `tree-kill` dependency inside `cli-kit`, so that we now have a clean exit code when exiting the program normally and also have this nice output in verbose mode:
```
$ cat log.txt | grep Killing
2023-08-31T11:22:15.331Z: Killing process 30862: npm exec remix dev
2023-08-31T11:22:15.342Z: Killing process 30870: npm exec -- graphql-code-generator --config package.json
2023-08-31T11:22:15.353Z: Killing …
```
=> Implement our own version of tree-kill

nx.json, package.json, packages/app/oclif.manifest.json, packages/app/src/cli/commands/app/function/run.ts, packages/app/src/cli/services/function/build.test.ts, packages/app/src/cli/services/function/build.ts, packages/cli/README.md
Fixes https://github.com/Shopify/script-service/issues/6712
- Create a new app with a js function
- Create a JSON like this one `{"discountNode":{"metafield":null}}` and call it `input.json`
- Run `npm run shopify app function run -i input.json`
=> Allow to pass an input JSON to 'app function run'

.changeset/twelve-hounds-fetch.md, packages/app/src/cli/services/deploy/mode.test.ts, packages/app/src/cli/services/deploy/mode.ts
These changes are introduced to reflect the changes how we rollout simplified deployments.
Updates the date from `Sept 5, 2023` to `September 2023` to match with the updated rollout plan.
Run the `app deploy` command. Should expect to see this banner:
=> Update simplified deployment info banner

.changeset/angry-jars-worry.md, packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts, packages/app/src/cli/models/extensions/specifications/ui_extension.ts, packages/app/src/cli/services/dev/extension/payload.ts, packages/app/src/cli/services/dev/extension/payload/models.ts, packages/ui-extensions-server-kit/src/ExtensionServerClient/ExtensionServerClient.test.ts, packages/ui-extensions-server-kit/src/ExtensionServerClient/ExtensionServerClient.ts, packages/ui-extensions-server-kit/src/i18n.ts, packages/ui-extensions-server-kit/src/testing/extensions.ts, packages/ui-extensions-server-kit/src/types.ts, pnpm-lock.yaml
Enabling localized description for deving ui_extensions.
Fixes [#393](https://github.com/orgs/Shopify/projects/7275/views/3#:~:text=Update%20dev%2Dserver%2Dkit%20with%20localized%20description)
The optional description field is supported on the deploy flow for UI Extensions but there was this missing pice to be able to `dev` it.
Adding `description` and the translation logic to the websocket message payloads.
- In the cli folder checkout this branch: `git checkout update-drafts-for-all-extensions-in-dev`
- Create a new app and admin extension (or reuse existing ones)
- Add a new locales entry for the description
- Add description to the toml file: `description: 't:new_key'`
- Run `shopify app dev --path your_app_folder_here`
- Open the dev console and navigate to the extension point of …
=> Add localized description to the dev server kit

.github/ISSUE_TEMPLATE/config.yml
See https://github.com/Shopify/partners/issues/45465
The shopify.com/partners/community page is being sunset. Update the Partner Community link to the new page.
Updating the link to the Partners community in the issue tempate.
Test after deploy, issues template previews not enabled for this repo.
Ensure issue template updated. 
=> Update Partner community link

packages/cli-kit/src/private/node/analytics.ts, packages/cli-kit/src/public/node/node-package-manager.test.ts, packages/cli-kit/src/public/node/node-package-manager.ts, packages/cli-kit/src/public/node/output.test.ts, packages/cli-kit/src/public/node/output.ts, packages/cli/src/cli/services/commands/version.test.ts, packages/cli/src/cli/services/commands/version.ts, packages/create-app/src/services/init.ts
Fixes https://github.com/Shopify/develop-app-management/issues/15
Analytics reporting in `create-app` was throwing an error in the postrun hook because `getPackageManager` was trying to guess the package manager from a folder which, because it's the app's parent folder, doesn't have a package.json.
If there is no package.json we can try to use the existing function `packageManagerFromUserAgent` to guess it.
Unless we publish this it won't be easy to test because if you run `pnpm create-app --verbose` from the root `cli` folder there is going to be a package.json there and you won't see the exception.
Once this is merged we can test `npm init` with nightly.
=> Fix create-app analytics throwing error in postrun hook

.changeset/purple-trees-sin.md, packages/ui-extensions-dev-console/src/sections/Extensions/Extensions.tsx, packages/ui-extensions-dev-console/src/sections/Extensions/components/AppHomeRow/AppHomeRow.tsx, packages/ui-extensions-dev-console/src/sections/Extensions/components/ExtensionRow/ExtensionRow.test.tsx, packages/ui-extensions-dev-console/src/sections/Extensions/components/ExtensionRow/ExtensionRow.tsx, packages/ui-extensions-dev-console/src/sections/Extensions/components/PostPurchaseRow/PostPurchaseRow.test.tsx, packages/ui-extensions-dev-console/src/sections/Extensions/components/PostPurchaseRow/PostPurchaseRow.tsx
With the introduction of automatic draft updates during dev for extensions, toggling between local and a deployed no longer provide any value and results in a confusing experience.
Closes https://github.com/Shopify/app-ui/issues/407
Remove show/hide button for extensions
- Follow steps to run the console locally here https://github.com/Shopify/cli/tree/main/packages/ui-extensions-dev-console
- Confirm that the show/hide button isn't present for extensions
=> Remove show/hide button for extensions

.changeset/silver-ravens-compare.md, packages/app/package.json, pnpm-lock.yaml
=> Remove react peer dep

.changeset/eighty-pets-approve.md, .changeset/empty-cobras-do.md, packages/app/src/cli/services/context.ts, packages/cli-kit/src/public/node/error-handler.test.ts, packages/cli-kit/src/public/node/error-handler.ts, packages/cli-kit/src/public/node/error.ts
Fixes https://github.com/Shopify/develop-app-management/issues/195
We are reporting to Bugsnag user errors (like "App not found") mixed with unexpected errors.
Example: https://app.bugsnag.com/shopify/cli/errors/64b0140d6b457e000847a018
- Set `unhandled = true` for all bugs and unexpected errors
- Set `unhandled = false` for controlled errors (like AbortError), and always report
- Replace a few BugError with AbortError
- Add verbose logs to know when the error is reported as handled, unhandled or skipped
Example of handled error report: https://app.bugsnag.com/shopify/cli/errors/64f70a3fe74a7000083d69d7?filters[event.unhandled]=false&filters[event.severity]=error
- Update the client ID in your `shopify.app.toml` with an invalid value
- `p shopify app dev --path ~/your-app --verbose | grep …
=> Report any kind of error to Bugsnag as handled/unhandled

.github/workflows/shopify-cli.yml
We were skipping CI when the PR only contained changes in *.md files, but now the workflow is required to merge.
Example PR: https://github.com/Shopify/cli/pull/2785
GitHub note found by @alvaro-shopify:
Always run CI, no matter the changes
Merge and create a PR with a single change in README.md 🤷 
=> Remove workflow path filtering

package.json
This reflects most users' experiences and is expected to surface bugs that we wouldn't see using pnpm (especially regarding peer dependencies)
Adds a default package manager `npm` to `create-app`.
You can still override passing e.g. `--package-manager pnpm`
Run `create-app` and see it uses npm. Run again with `--package-manager pnpm` and see it uses pnpm.
=> Default to npm when running create-app

.changeset/perfect-points-agree.md, packages/app/src/cli/services/dev/ui/components/Dev.test.tsx, packages/app/src/cli/services/dev/ui/components/Dev.tsx, packages/cli-kit/src/private/node/ui/hooks/use-abort-signal.ts
Right now if you run the `dev` command with an app with a theme app extension using a wrong Ruby version, the command exists silently without any error message.
When one of the process included in the `dev` command throws an exception the CLI exists silently
The exception should managed by the global error handler so among other things the error banner is displayed
When the `Dev` component catches an exception from one of the processes, the exception is sent with the abort signal so the ink library can rethrow it once the component is unmounted.
- Change your Ruby version to an unsupported one (< `2.7.1`) 
- Run the dev command with an app with a theme app extension
- You should see an error like this
```
╭─ error ──────────────────────────────────────────────────────────────────────────── …
```
=> Dev component exits with exception when error received from processes

packages/app/src/cli/services/dev/extension/server/utilities.test.ts, packages/app/src/cli/services/dev/extension/utilities.ts
When inferring a surface from a target, only targets prefixed with `customer-account` are currently recognized as customer account extensions.
We are in the process of migrating 1p apps from the legacy format to the new format so we need to support the legacy targets (that are prefixed with `CustomerAccount`) in the interim.
Adds a fallthrough case statement for handling `customeraccount` in addition to `customer-account`.
* Follow up to step 7 from [this doc](https://docs.google.com/document/d/1T5yHuJxGPg37IQhT7uNOcJb8Ned5GXc_y-rCOJDRcJU/edit#heading=h.ua5trnf4kn9g) to generate a new customer account extension
* Navigate to the app directory and use `pwd` to find the path
* Return to the `cli` directory and run `pnpm shopify app dev --path {path_to_your_app}`
* Once the dev server is …
=> Recognize surface for legacy customer account extension targets

.changeset/proud-lemons-dress.md, packages/app/src/cli/services/function/build.test.ts, packages/app/src/cli/services/function/build.ts
The prelude for building a JS function collides with exports using the name `run`. 
This PR updates the prelude import to `__runFunction` so that it's less likely to collide with an export name.
Deploy a JS function that has a `run` export against a `run` target and ensure it doesn't stack overflow.
=> Rename `run` import to `__runFunction` to avoid naming collisions

.changeset/modern-ears-draw.md, packages/cli-kit/src/public/node/node-package-manager.ts
`yarn shopify upgrade` is broken when the project includes workspaces:
Similar to https://github.com/Shopify/cli/pull/2540
Pass the `-W` flag to the internal `yarn add` command when workspaces is enabled to force installation in the root folder.
`pnpm shopify upgrade --path ./old-yarn-project`
=> Fix upgrade with yarn and workspaces

packages/app/src/cli/models/extensions/specifications/function.test.ts, packages/app/src/cli/models/extensions/specifications/function.ts
In order to establish a connection between a UI extension and a function, we will provide partners with the ability to define a ui.handle string within their TOML file. This specific value will be directly associated with the handle value of their UI extension within the local app.
During the deployment, the `ui.handle` needs to be stored as part of the functions config. This ensures that the value can be easily accessed and retrieved at a later point in time.
Addresses: https://github.com/Shopify/script-service/issues/7307
https://github.com/Shopify/shopify/pull/449584 will be merged prior to this PR.
- **Commit 1**: Updates `function.ts` so that it can parse `ui.linkedExtensions.handle` _(cleaned needed, left comments in for now)_
- Add `ui.linkedExtension.handle` to your function's …
=> [ShopifyVM] Store `ui.handle` as part of a functions config on deploy

.changeset/clever-socks-sort.md, packages/app/package.json, packages/app/src/cli/services/generate/extension.ts, pnpm-lock.yaml
Fixes https://github.com/Shopify/cli/issues/2809
- Make it so the `app` package only declares `ink` and `react` as peer dependencies
- In this way, the only copy of those deps come from the `cli-kit` package
- Stop adding `react` as a top level dependency
- `npm init @shopify/app@experimental` choose none
- `npm run generate extension` choose checkout
- `npm run dev` runs successfully
- `npm ls react` prints this:
```
├─┬ @shopify/app@0.0.0-experimental-20230913134317
│ ├─┬ @shopify/cli-kit@0.0.0-experimental-20230913134317
│ │ └── react@18.2.0 deduped
│ ├─┬ ink@4.4.1
│ │ ├─┬ react-reconciler@0.29.0
│ │ │ └── react@18.2.0 deduped
│ │ └── react@18.2.0 deduped
│ └── react@18.2.0
└─┬ checkout-ui@1.0.0 -> ./extensions/checkout-ui
├─┬ @shopify/ui-extensions-react@2023.7.2
│ ├─┬ …
```
=> Fix issue with multiple copies of react being loaded

packages/app/package.json, packages/app/src/cli/constants.ts, packages/app/src/cli/services/generate/extension.ts, packages/features/steps/node-deps.steps.ts
A PR targeting main that backports changes from https://github.com/Shopify/cli/pull/2822
- Make it so the `app` package only declares `ink` and `react` as peer dependencies
- In this way, the only copy of those deps come from the `cli-kit` package
- Stop adding `react` as a top level dependency
- `npm init @shopify/app@experimental` choose none
- `npm run generate extension` choose checkout
- `npm run dev` runs successfully
- `npm ls react` prints this:
```
├─┬ @shopify/app@0.0.0-experimental-20230913134317
│ ├─┬ @shopify/cli-kit@0.0.0-experimental-20230913134317
│ │ └── react@18.2.0 deduped
│ ├─┬ ink@4.4.1
│ │ ├─┬ react-reconciler@0.29.0
│ │ │ └── react@18.2.0 deduped
│ │ └── react@18.2.0 deduped
│ └── react@18.2.0
└─┬ checkout-ui@1.0.0 -> ./extensions/checkout-ui
├─┬ …
```
=> Fix duplicate react

.changeset/fair-rabbits-cheat.md, packages/app/src/cli/services/dev/urls.test.ts, packages/app/src/cli/services/dev/urls.ts, packages/cli-kit/src/private/node/constants.ts, packages/cli-kit/src/public/node/context/local.ts
Backports https://github.com/Shopify/cli/pull/2824 to the 3.49 stable branch
=> Use env var on codespaces to detect the correct port forwarding domain

packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/graphiql/server.ts, packages/app/src/cli/services/dev/processes/graphiql.ts
Running the integrated GraphiQL toll inside spin is returning an error related to shop domains validation
- When the app is run inside spin, set the proper `customShopDomains` when the `shopifyApi` is created from the `graphiQL server`
- The PR should be merged to test it inside `spin`
- Check that the app and the graphiQL tool is working properly as usual against the PRO environment
=> Fix integrated GraphiQL tool in spin

packages/app/src/cli/services/app/config/link.test.ts, packages/app/src/cli/services/app/config/link.ts, packages/app/src/cli/services/app/config/push.ts, packages/app/src/cli/services/app/config/use.test.ts, packages/app/src/cli/services/app/config/use.ts, packages/app/src/cli/services/context.ts
As per https://github.com/Shopify/develop-app-management/issues/40 we want to track more metadata for `config` commands as well.
This PR adds a new function called `logMetadataForLoadedConfigContext` that tracks `partner_id` and `api_key`.
=> Add more metadata for the config commands

.changeset/friendly-nails-listen.md, packages/app/src/cli/commands/app/deploy.ts, packages/app/src/cli/commands/app/dev.ts
Fixes #2841
We [recommend](https://shopify.dev/docs/apps/tools/cli/ci-cd#github-actions) for CI/CD to specify the `SHOPIFY_API_KEY` env variable. But it's not taken into account when requiring `client-id` for non-TTY environments.
Considers `SHOPIFY_API_KEY` as though `--api-key` has been specified. We also consider it deprecated because `client ID` is now the preferred terminology (we should update the docs as well to reflect this).
```
echo | SHOPIFY_API_KEY=SOME-API-KEY pnpm shopify app deploy --path /path/to/your/app -f
```
Before: fails
After: passes, warns that the `api-key` flag is deprecated
=> Read SHOPIFY_API_KEY as a way to specify --api-key

packages/app/src/cli/services/dev/extension/utilities.test.ts, packages/app/src/cli/services/dev/extension/utilities.ts
Resolves: https://github.com/Shopify/core-issues/issues/60345
In cli, it redirects all targets start from `customer-account.order-status` to checkout. [Code is here.](https://github.com/Shopify/cli/blob/main/packages/app/src/cli/services/dev/extension/utilities.ts#L44)
We should only redirect [these 4 checkout targets](https://github.com/Shopify/shopify/blob/main/components/apps/app/services/apps/models/ui_extension/schema/groups/checkout_ui.rb#L222-L227) to checkout instead of all of them
1. Enable customer account and ui extension flags for your partner account.
2. Create a new customer account ui extension locally.
3. dev clone cli and checkout to this branch.
`pnpm shopify app dev --path your_extension_app_path --reset`
4. Test different targets in your extension (by updating …
=> Fix issue of redirecting customer account ui extension to checkout

.changeset/eleven-lions-eat.md, packages/app/src/cli/commands/app/config/use.ts, packages/app/src/cli/services/app/config/link.test.ts, packages/app/src/cli/services/app/config/link.ts
When you run either `app config link` or `app config use` inside an app subfolder, the folder used to search/create app toml is not correct.
- Use the commands `path` flag to load the app. Once it's loaded, the logic uses the app directory
- Run `shopify app config link` outside the root app folder
```
npm run shopify app config link --path /your/app/path/extensions --reset
```
- Select a different app so a new toml file is created
=> Fix run config commands outside app root folder

.changeset/cuddly-pillows-occur.md, packages/app/src/cli/services/generate/extension.test.ts, packages/app/src/cli/services/generate/extension.ts
New templates being released for functions will include `.graphql` files under `src`. Without this change, the CLI will attempt to rename them.
Excludes `src/*.graphql` from the rename operation for functions.
Unit test, and on a local app against the [new templates](https://github.com/Shopify/function-examples/pull/347).
```
pnpm shopify app generate extension --path /Users/nickwesselman/src/scratch/luxury-capital-app --clone-url https://github.com/Shopify/function-examples#template-updates-2023-10 --template product_discounts --name another-discount-ts
```
=> Dont rename graphql on generate for functions

.changeset/light-pianos-perform.md, packages/plugin-cloudflare/src/tunnel.ts
There is a different error message returned by the cloudfare binary when the default `quic` used is not supported by the user. The CLI displays an empty error message like this:
- Add the new error message to the list of supported cloudfare error messages, so it's detected as a known message and the error banner could display it.
- Not possible to reproduce locally without blocking the required `udp` port against the cloudfare servers. More info [here](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/install-and-setup/ports-and-ips/)
=> Support new cloudfare error message

package.json, pnpm-lock.yaml
The deploy is throwing a Nx error: https://shipit.shopify.io/shopify/cli/stable_3_49/deploys/2326247
Upgrade some dependencies as in https://github.com/Shopify/cli/pull/2829:
- All nx dependencies
- @typescript-eslint/parser, which was causing a peer dependencies conflict in stable
Deploy 
=> [stable] Upgrade nx and @typescript-eslint/parser packages

packages/app/src/cli/api/graphql/functions/target_schema_definition.ts, packages/app/src/cli/services/generate-schema.test.ts, packages/app/src/cli/services/generate-schema.ts
With target support, the `generate schema` command for functions no longer works.
Related issue: https://github.com/Shopify/script-service/issues/7327
This PR uses a new GraphQL field to fetch the schema definition by target. The CLI uses the first target defined in a function to fetch the schema.
1. Create a function that uses targets
2. Run `generate schema` in the function directory
3. Ensure that the schema is fetched successfully
=> Generate schema from targets if present

packages/app/src/cli/api/graphql/functions/target_schema_definition.ts, packages/app/src/cli/services/generate-schema.test.ts, packages/app/src/cli/services/generate-schema.ts
With target support, the generate schema command for functions no longer works.
Related issue: https://github.com/Shopify/script-service/issues/7327
Stable release of #2899
=> [stable] Generate schema from targets if present

packages/app/src/cli/services/dev/ui/components/Dev.tsx, packages/cli-kit/src/public/node/monorail.ts
To know what people are using `dev` for.
Adds tracking to hotkeys used in `dev` to launch GraphiQL, launch preview, or toggle development preview mode.
1. Checkout this branch
2. Run `app dev` in verbose mode, and use some hotkeys
3. See that the event sent at the end includes the correct keys with `true` as the value
4. For bonus points, run with `SHOPIFY_CLI_ALWAYS_LOG_ANALYTICS=1`, check when the events appear in monorail, and confirm the data is there (I've done this already)
=> Analytics for dev hotkeys

packages/app/src/cli/models/app/app.ts, packages/app/src/cli/services/dev/processes/draftable-extension.ts
Fixes [#461](https://github.com/Shopify/app-ui/issues/461)
UI extensions, in order to have live reload, communicate with Web by web sockets. The payload of the WS does not have the uuid updated to the one in the draft. As the UUID is used for reconciliation in EH dev plugin, this results in having two extensions rendered, the one stored in the DB as a draft and the one specified by the WS payload.
The CLI already resolves the matching extensions, but this matching process was not updating the extension instance. To solve this:
- Added a new method to the App which updates all extension UUIDS to the ones provided in a map
- Force the update of the UUIDS after reconciliation of local and remote extensions0
- 
- create an app with a block extension.
- dev the app and see the extension …
=> Fix extension devUUID to match remote extension UUID if exists

packages/app/src/cli/services/context/id-matching.test.ts, packages/app/src/cli/services/context/id-matching.ts, packages/app/src/cli/services/context/identifiers.ts, packages/app/src/cli/services/dev/migrate-to-ui-extension.test.ts, packages/app/src/cli/services/dev/migrate-to-ui-extension.ts, pnpm-lock.yaml
We were using `handle` to match extensions, but not in every part of the flow, we missed a key comparison and this caused all matching to fail when the local extension has a localized name.
It started to fail now because before introducing localized names, the `name` and `handle` were always the same initially.
Compare local `handle` with remote `title`. 
(When we create an extension, we use the initial `handle` to populate the `title`)
Create a new app with a few extensions using unified-config and localized names (admin block for instance)
Try to `dev` multiple times (without deploying first, to avoid caching UUIDs)
=> Fix automatic matching for extensions with localized names

.changeset/polite-masks-hide.md, packages/app/src/cli/services/context/id-matching.test.ts, packages/app/src/cli/services/context/id-matching.ts, packages/app/src/cli/services/context/identifiers.ts, packages/app/src/cli/services/dev/migrate-to-ui-extension.test.ts, packages/app/src/cli/services/dev/migrate-to-ui-extension.ts, pnpm-lock.yaml
We were using `handle` to match extensions, but not in every part of the flow, we missed a key comparison and this caused all matching to fail when the local extension has a localized name.
It started to fail now because before introducing localized names, the `name` and `handle` were always the same initially.
Compare local `handle` with remote `title`. 
(When we create an extension, we use the initial `handle` to populate the `title`)
Create a new app with a few extensions using unified-config and localized names (admin block for instance)
Try to `dev` multiple times (without deploying first, to avoid caching UUIDs)
=> [stable] Fix automatic matching for extensions with localized names

packages/app/src/cli/models/app/app.test.ts, packages/app/src/cli/models/app/app.ts, packages/app/src/cli/services/deploy.ts
Fixes https://github.com/Shopify/script-service/issues/7308
This PR will add an extra validation when deploying a app that contains a function and an ui extension. 
For validating when an app that contains a function with `ui.handle`:
- The function with a `ui.handle` must contain another extension with a matching `handle` in the same local app. This will be used to link a UI extension with a function, so we can [surface that information to domains](https://github.com/Shopify/shopify/pull/452100). 
- We should ensure the matching extension is of type `ui_extension`. If we match solely on the existence of the handle, we could have a situation where partners link a function `ui_handle` to another extension type. 
This validation should check that if a function has the `ui.handle` …
=> Validate function's ui.handle matches local extension in app

packages/app/src/cli/services/app/config/link.ts, packages/app/src/cli/services/app/config/push.ts, packages/app/src/cli/services/app/config/use.test.ts, packages/app/src/cli/services/app/config/use.ts, packages/app/src/cli/services/context.ts
Fixes https://github.com/Shopify/develop-app-management/issues/1463
We weren't logging `partner_id` and `api_key` for the `generate command, this fixes that.
- Run generate command with `--verbose`
- See that those attributes are present in the metadata
=> Fix generate context not logging relevant metadata

packages/app/src/cli/models/extensions/specifications/function.test.ts, packages/app/src/cli/models/extensions/specifications/function.ts
Thanks for spotting this Detla!
Right now, we are incorrectly adding `ui.handle` to the configuration of a function when `ui.handle` is set to an empty string. 
The way we add either the ui.paths or ui.handle to the config when deploying , is from setting the ui property by:
(previously)
```
let ui: UI | undefined
if (config.ui?.paths) {
ui = {
app_bridge: {
details_path: config.ui.paths.details,
create_path: config.ui.paths.create,
},
}
}
**This check returns false when ui.handle is emptry string**
if (config.ui?.handle) {
ui = {
...ui,
ui_extension_handle: config.ui.handle,
}
}
```
**thus sending ui propery as undefined when deploying**
Updates the check above to correctly send `ui.handle` properties when they are set to empty string. 
Added some tests for when ui.handle is `""` or …
=> sends ui.handle as empty string instead of undefined when set

.changeset/olive-vans-buy.md, packages/cli-kit/src/public/node/base-command.test.ts, packages/cli-kit/src/public/node/base-command.ts
In https://github.com/Shopify/cli/pull/2348 we added a warning when using NPM and passing flags without the separator (`--`).
But it turns out that NPM removes the `no_` prefix for the flags. For example, passing `--no-release` will result in a `npm_config_release` environment variable. So our code to show the warning wasn't working in that case.
Ignore the `no_` prefix from the flags to show the warning in all cases
`npm run shopify app deploy --no-release -- --path your-app`
=> Fix NPM separator warning for negated flags

.changeset/sixty-crews-enjoy.md, packages/app/src/cli/services/deploy/bundle.ts
Fixes https://github.com/Shopify/cli/issues/2877
We are building the functions in parallel and when the `javy-cli` binary is not present, all of them will try to download and run it at the same time, causing an error sometimes.
When the deploy includes functions, pre-download the javy binary (by running a simple javy command, which automatically downloads it when it's not present) to avoid issues when running build concurrently, which might cause multiple downloads in parallel.
Alternatives:
- Do not build functions in parallel when there are several
- Try to make javy more robust by preventing multiple processes from downloading/accessing the binary simultaneously
- Generate 3+ functions (more likely to crash)
- Remove the javy binary, so that it has to be downloaded again: `rm …
=> Fix concurrent function builds

.changeset/modern-snakes-occur.md, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/ui/components/Dev.tsx, packages/app/src/cli/services/extensions/common.ts
Fixes https://github.com/Shopify/develop-app-management/issues/1475
There are cases, like when developers only have dashboard managed extensions, when we weren't showing the dev preview toggle.
Allow enabling and disabling dev store preview mode with dashboard managed extensions when running `dev`.
- Add a dashboard managed extension (e.g. admin link)
- Run `dev`
- Dev preview should be enabled and the toggling should be possible with `d`
=> Allow enabling and disabling dev store preview mode with dashboard managed extensions

packages/create-app/oclif.manifest.json, packages/create-app/src/commands/init.test.ts, packages/create-app/src/commands/init.ts, packages/create-app/src/prompts/init.test.ts, packages/create-app/src/prompts/init.ts
We'll have multiple options of the Remix app template going forward, and we want users to be able to select between a TS or JS version of the template.
Setting up the form so it asks a second question for the remix template, so the user can select a branch.
I implemented this as a generic way of adding branch options so that other templates can benefit from this in the future.
- Run `dev create-app`, and select the remix template
- OR run `dev create-app --template remix`
Merge [this template PR](https://github.com/Shopify/shopify-app-template-remix/pull/372) which makes `main` the TS version of the code.
=> Support template branches when creating apps

.changeset/smart-cherries-joke.md, packages/create-app/src/services/init.ts
Fixes https://github.com/Shopify/cli/issues/2866
Current default CLI templates don't include the folders `web` and `web/frontend`. For that reason the command to create an app[ was adapted ](https://github.com/Shopify/cli/pull/2523)to remove those folders from the `workspaces` setup
However the CLI supports the creation of app using the older templates using the flag `-t|--template`. Old templates include the react frontend inside the folder `web/frontend`, so after configuring the `workspaces` section and installing the dependencies, the ones for the frontend are not installed. Due to this, when the command `app dev` is run it breaks with errors similar to this one (in this case for the `node` template)
```sh
── external error ────────────────────────────────────────────────────────────── …
```
=> Fix create app for apps with old templates

.changeset/rich-zebras-suffer.md, packages/app/src/cli/services/dev/fetch.test.ts, packages/app/src/cli/services/dev/fetch.ts
When a user authenticates using an staff account that does not include `Manage app` permission an error banner is displayed with some `try with` suggestions. However none of them references the problem with the permission.
- Add a this suggestion about missing `Manage app` permission to the error banner
```
Does your account include  Manage app  permissions?, please contact the owner of the organization to grant you access. 
```
- Run the `dev` command
- Authenticate using a staff account without `Manage app` permissions
- Output
```
╭─ error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ …
```
=> Add missing Manage app permission to the organization not found error banner

.changeset/tough-badgers-peel.md, package.json, packages/app/package.json, packages/app/src/cli/services/dev.ts, packages/cli-kit/package.json, packages/cli-kit/src/private/node/session/authorize.ts, packages/cli-kit/src/public/node/analytics.test.ts, packages/cli-kit/src/public/node/analytics.ts, packages/cli-kit/src/public/node/api/graphql.ts, packages/cli-kit/src/public/node/error-handler.test.ts, packages/cli-kit/src/public/node/error-handler.ts, packages/cli-kit/src/public/node/hooks/postrun.ts, packages/cli-kit/src/public/node/http.ts, packages/cli-kit/src/public/node/metadata.test.ts, packages/cli-kit/src/public/node/metadata.ts, packages/cli-kit/src/public/node/monorail.ts, packages/cli-kit/src/public/node/node-package-manager.ts, packages/cli-kit/src/public/node/ui.tsx, packages/cli/package.json, packages/create-app/package.json, packages/eslint-plugin-cli/config.js, packages/features/package.json, packages/theme/package.json, packages/ui-extensions-dev-console/package.json, packages/ui-extensions-server-kit/package.json, packages/ui-extensions-test-utils/package.json, pnpm-lock.yaml
Tracks data on CLI performance:
- command exits: ok, unexpected error, expected error
- how long spent on network calls and prompts (and infers how long the command is active for)
Introduces new monorail fields and instrumented calls.
The `runWithTimer` function wraps up another function and times how long it takes to finish. There's some complexity there in dealing with nested timers -- we essentially want to pause a timer whilst nested ones are running.
(PS: its not a decorator as decorators are for class methods only)
Run with `--verbose` and check out the new fields.
=> Add reliability metrics to monorail tracking

.changeset/empty-actors-bow.md, packages/plugin-cloudflare/src/tunnel.test.ts, packages/plugin-cloudflare/src/tunnel.ts
We are re-throwing some errors directly from Cloudflare, and it may be not very useful. Also, they differ too much, so it's hard to group them in Bugsnag ([example](https://app.bugsnag.com/shopify/cli/errors/6524ea64e7bfa100077025f9)).
- Prefix all Cloudflare errors with the same phrase: `Could not start Cloudflare tunnel: xxx`
- Always show some `What to try` options
- Remove some noise from Cloudflare errors, like `2023-10-10T06:07:59Z ERR` or the IPs
Before:
```
╭─ error ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                           │
│ …
```
=> Unify Cloudflare errors

packages/cli-kit/package.json, packages/cli-kit/src/private/node/__snapshots__/otel-metrics.test.ts.snap, packages/cli-kit/src/private/node/constants.ts, packages/cli-kit/src/private/node/otel-metrics.test.ts, packages/cli-kit/src/private/node/otel-metrics.ts, packages/cli-kit/src/public/node/analytics.ts, packages/cli-kit/src/public/node/context/local.ts, pnpm-lock.yaml
Adds reliability metric tracking to the CLI. After running a command, report back minimal stats on command timing and exit state.
Metric tracking is disabled through `SHOPIFY_CLI_NO_ANALYTICS=1` as usual
If tracking is enabled, the same numbers currently being sent to monorail are also reported to the opentelemetry metric tracker.
Internal instructions here: https://vault.shopify.io/snippify/snippets/2ad01d9804a0303a47f4
=> Reliability metric tracking

.changeset/eight-days-promise.md, packages/cli-kit/src/public/node/node-package-manager.ts, packages/theme/src/cli/commands/theme/check.ts
The previous implementation of `shopify theme check --dev-preview --version` was causing nightly CI to fail. 
Reimplemented the logic to get the package version of `@shopify/theme-check-node`
=> Fixed CI issue due to theme check --dev-preview --version

.changeset/six-windows-enjoy.md, packages/app/src/cli/constants.ts, packages/app/src/cli/services/extensions/bundle.test.ts, packages/app/src/cli/services/extensions/bundle.ts, packages/app/src/cli/services/function/build.test.ts, packages/app/src/cli/services/function/build.ts
We introduced a feature to sustitute environment variables in extensions/functions at build time. But we need to validate that they are supported by esbuild first.
This PR filters variables to keep the ones having just letters/numbers/underscores
=> Replace esbuild variables that have letters/numbers only

.changeset/dull-mirrors-yawn.md, packages/cli/README.md, packages/theme/oclif.manifest.json, packages/theme/src/cli/commands/theme/open.ts
Fixes https://github.com/Shopify/cli/issues/2972
The aliases for `--editor` and `--environment` were conflicting. Since partners require an alias for [both](Fixes https://github.com/Shopify/cli/issues/2972) flags, `--editor` now uses `-E` instead of `-e`.
Run: `shopify theme open -E -e <your_environment>`
None.
=> Fix ambiguity between `--editor` and `--environment` flags in the `shopify theme open` command

.changeset/ten-pillows-attend.md, packages/theme/src/cli/services/delete.test.ts, packages/theme/src/cli/services/delete.ts
Fixes https://github.com/Shopify/cli/issues/2812
There was an issue in the theme selection logic when the users passes some flag (such as `-f`, `-d`, etc.) but doesn't pass the `-t/--theme` flag. This PR fixes that issue.
Run `shopify theme delete -f`
**Before**
**After**
None.
=> The `shopify theme delete` command no longer fails when some flags (`-f`, `-d`, etc.) are passed without the `-t` flag

.changeset/sour-toys-scream.md, packages/theme/src/cli/commands/theme/dev.ts, packages/theme/src/cli/commands/theme/pull.test.ts, packages/theme/src/cli/commands/theme/pull.ts, packages/theme/src/cli/utilities/embedded-cli-warning.test.ts, packages/theme/src/cli/utilities/embedded-cli-warning.ts
These changes fix an issue related to https://github.com/Shopify/cli/issues/2665.
The `SHOPIFY_CLI_BUNDLED_THEME_CLI` environment variable should not be used, as it points to the legacy/unsupported Shopify CLI 2.0 (`shopify/shopify-cli`) commands. Instead, theme commands should execute the Ruby classes at `shopify/cli`.
This PR introduces a warning with a call to action for users who currently rely on `SHOPIFY_CLI_BUNDLED_THEME_CLI`. It also resolves a compatibility issue for users who currently activate the `SHOPIFY_CLI_BUNDLED_THEME_CLI`.
- Run `export SHOPIFY_CLI_BUNDLED_THEME_CLI=1`
- Run `shopify theme pull -d`
**Before**
**After**
None.
=> Clarify `SHOPIFY_CLI_BUNDLED_THEME_CLI` environment variable should not be used, yet resolve its compatibility issue

.changeset/green-needles-taste.md, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/extension/dev_server/local_assets.rb, packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/extension/dev_server/local_assets_test.rb
Fixes https://github.com/Shopify/develop-app-management/issues/1515
- Modify the regexp that replace the production urls with relative urls. These url are used by the browser to load the `assets` files
- Create a spin instance `spin up partners`
- Once the instance is up access the remote terminal `spin ssh`
- Create a new only extensions app `npm init @shopify/app@latest -- --template none`
- `cd` into the folder app and generate a theme app extension `npm run shopify app generate extension -- --template theme_app_extension`
- open the app in the vs code `code .`
- modify the `start_rating.liquid` and add `"javascript": "example.js",` inside the `{% schema %}` section
- create a the file `example.js` in the `assets` folder with this content
```js
(function load() {
alert('hello')
})(); …
```
=> Fix TAE hot code reloading in spin

.changeset/late-cooks-worry.md, packages/cli-kit/src/public/node/ruby.test.ts, packages/cli-kit/src/public/node/ruby.ts
Fixes https://github.com/Shopify/develop-app-management/issues/1517
- Instead of modifying the local bundle configuration that could be used by the app, equivalent env variables are used
- Fix ruby unit tests as some of them were not being run because the method `inTemporaryDirectory` was mocked
- Create a spin instance for a 1P app that uses local bundle config 
```sh
spin up shopify_chat:theme-extension -c shopify_chat.branch=theme-extension-spin
````
- Access the spin terminal 
```sh
spin ssh
````
- Modify the `package.json` to use the cli version `0.0.0-experimental-20231027101204`
- Restart the `cli` process
- Restart the `server` process
- No error should be shown
-  `npm init @shopify/app@0.0.0-experimental-20231027101204 -- --template ruby`
-  cd in the app folder and `npm run …
=> Fix ruby bundler config when app is of rails type and uses bundler local config

.github/workflows/reviewers-reminder.yml
Renaming `@shopify/theme-code-tools` to `@shopify/advanced-edits`.
=> Rename @shopify/theme-code-tools to @shopify/advanced-edits

packages/cli-kit/src/public/node/analytics.test.ts, packages/cli-kit/src/public/node/analytics.ts
Related to https://github.com/Shopify/develop-app-management/issues/1531
Monorail is expecting `long` values for command timing data, but we were in some instances submitting `double`s, leading to some odd behaviour. Round the measures down instead.
`SHOPIFY_CLI_ALWAYS_LOG_ANALYTICS=1 p shopify app info --path="<path to your app>" --verbose`
With this change, the monorail logging works, without it, it doesn't.
=> Timing metrics shouldn't be reported with sub-ms precision

.changeset/old-goats-leave.md, .changeset/unlucky-cars-perform.md, packages/app/src/cli/services/dev.test.ts, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/ui.test.tsx, packages/app/src/cli/services/dev/ui.tsx, packages/app/src/cli/services/dev/ui/components/Dev.test.tsx, packages/app/src/cli/services/dev/ui/components/Dev.tsx, packages/cli-kit/src/private/node/session.test.ts, packages/cli-kit/src/private/node/session.ts, packages/cli-kit/src/public/node/session.ts
Fixes https://github.com/Shopify/develop-app-management/issues/215
`dev` is crashing after an hour because we aren't refreshing the access token. This adds that functionality. It also extracts much of the logic from the `Dev` component into the caller.
1. `ensureAuthenticatedPartners` gets a new option, `noPrompt` which will fail instead of prompting.
2. We extract the logic to fetch/update development store preview mode to `dev`. (Theoretically it could live in its own file, I'm debating whether it's worth extracting already, but wanted to get feedback on the approach first.)
3. Adds a step when hitting Partners where we rescue => refresh the token => try again. The logic is pretty generic (no analysis of the error) since the cost of retrying is low and there is little potential to cause …
=> Refresh token when necessary during dev

packages/app/src/cli/services/dev.ts
Makes dev loading more tolerable
Cashing in on the recent changes to the Dev implementation. Uses `renderTasks` to show a loader while dev is starting up.
Run `dev`. Try with `--reset` and also try after logging out.
In the case of logging out first, the login shouldn't interfere with the taskbar.
In the case of `--reset`, we should basically just lose the rainbow taskbar, and things should proceed as they did before. It's sadly inconsistent, but it's no worse than what we have now.
=> Use rainbow bar for dev launch

packages/cli-kit/src/public/node/ruby.ts
Related to https://github.com/Shopify/develop-app-management/issues/1531
Wrap up the call to `bundle install...` such that its treated as time spent on the network, rather than actively processing the command.
=> Bundle install should count as network rather than active usage

.changeset/khaki-colts-remember.md, packages/plugin-cloudflare/scripts/postinstall.js
Attempting to create an app on Windows ARM, with Node ARM installed resulted in the following error:
```
npm ERR!   if (!response.ok) throw new Error("Couldn't download file")
npm ERR!                           ^
npm ERR!
npm ERR! Error: Couldn't download file
npm ERR!     at downloadFile (file:///C:/Users/NICKWE~1/AppData/Local/Temp/9a90443df0b5afec2bfd15aa70426016/app/node_mod
ules/@shopify/plugin-cloudflare/scripts/postinstall.js:107:27)
```
This pointed to a few issues in the cloudflared download:
* No handling for Win ARM (it can just use the x64 version)
* The error handling for platform/arch in this script doesn't work (URL was never undefined, it just ended with the string `undefined`)
* The download error message is not helpful (which I encountered again while testing this when …
=> Improvements to cloudflared download

.changeset/afraid-cameras-yell.md, .changeset/curly-buckets-hug.md, packages/app/src/cli/services/flow/constants.ts, packages/app/src/cli/services/flow/serialize-fields.test.ts, packages/app/src/cli/services/flow/serialize-fields.ts, packages/cli-kit/src/public/common/string.ts
- Resolves https://github.com/Shopify/flow/issues/21146
- Depends on 
- https://github.com/Shopify/shopify/pull/462061 
- https://github.com/Shopify/flow/pull/21328
- https://github.com/Shopify/flow/pull/21366
- Adds support for Company and Company Contact references
- Adds support for Company and Company Contact references
- Manual test and automated tests
=> Adds Company and Company Contact reference type to flow action/trigger fields serialization

packages/app/src/cli/models/app/app.test-data.ts, packages/app/src/cli/models/extensions/extension-instance.ts, packages/app/src/cli/models/extensions/specification.integration.test.ts, packages/app/src/cli/services/context/id-matching.test.ts, packages/app/src/cli/services/context/identifiers-extensions.ts
All extensions use the extension framework now, this PR just cleans up some old code.
remove the `useExtensionFramework` property for functions.
=> Remove "useExtensionFramework" from functions config

.changeset/purple-birds-film.md, packages/cli/README.md, packages/theme/oclif.manifest.json, packages/theme/package.json, packages/theme/src/cli/commands/theme/check.test.ts, packages/theme/src/cli/commands/theme/check.ts, pnpm-lock.yaml
Fixes https://github.com/Shopify/theme-tools/issues/208 
The docs for our CLI was stating that for `theme check` the `--config :theme_app_extension` would auto load the [TAE config](https://github.com/Shopify/theme-tools/blob/main/packages/theme-check-node/configs/theme-app-extension.yml), but this was not working. After some digging, I realized we did not support this command, and hence added a backwards compatibility to ensure if `:theme_app_extension` was run, `theme-check:theme-app-extension,` was called.
This pull request is updating our docs for the config value, and is adding backwards compatibility.
Simply run `pnpm run shopify theme check --dev-preview --config :theme_app_extension` and make sure it run's succesfully.
=> Fix support for legacy theme check configuration identifiers

packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/context.ts, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/extension.ts, packages/app/src/cli/services/dev/extension/payload.test.ts, packages/app/src/cli/services/dev/extension/server/utilities.test.ts, packages/app/src/cli/services/dev/extension/server/utilities.ts, packages/app/src/cli/services/dev/processes/previewable-extension.ts, packages/app/src/cli/services/dev/processes/setup-dev-processes.test.ts, packages/app/src/cli/services/dev/processes/setup-dev-processes.ts
Redirect to customer account on `shopify.com/shop_id/account`
Details could be seen here: https://github.com/Shopify/core-issues/issues/51644#issuecomment-1804714760
1. Use my cli console: https://literally-children-drag-lighting.trycloudflare.com/extensions/dev-console  (let me know if the server is down)
2. Open browser dev console. Cope-paste the link on any target name . Check if will redirect to `shopify.com/shop_id/account`
=> Redirect to shopify com for customer account extension

packages/app/src/cli/services/dev/extension/server/utilities.test.ts, packages/app/src/cli/services/dev/extension/server/utilities.ts
Redirect to spin shopify domain if it in a spin env
Is this the correct way to check the spin env?
1. use my dev console:  https://mailed-emacs-victorian-canon.trycloudflare.com/extensions/dev-console
2. Cope the link behind any target name. You will be redirect to 
`https://shopify.create-an-order.hao-li.us.spin.dev/8/account/extensions-development`
=> Redirect to spin shopify domain if it in a spin env

packages/app/src/cli/models/extensions/extension-instance.test.ts, packages/app/src/cli/models/extensions/extension-instance.ts, packages/app/src/cli/services/dev/extension/bundler.test.ts, packages/app/src/cli/services/dev/extension/bundler.ts
I recently introduced some changes in the extensions watcher to unify them into a single one.
However, I made a last minute change: from watching only inside `src` to watching in any folder. I didn't test that properly and it obviously breaks everything because we shouldn't watch in folders like `dist` or `node_modules`
- Only watch for files inside the `src` folder
- Ignore test files  (we don't need to upload a new draft if you change the tests)
- run `dev` in an app with different extension types and try to make changes in files inside src/dist/node_modules and also test file. Only actual source files should trigger a re-build
=> Fix extension watcher infinite loop

packages/app/src/cli/models/app/app.test-data.ts, packages/app/src/cli/models/app/app.test.ts, packages/app/src/cli/models/app/app.ts, packages/app/src/cli/models/app/loader.test.ts, packages/app/src/cli/models/organization.ts, packages/app/src/cli/services/app/write-app-configuration-file.ts, packages/app/src/cli/services/deploy.test.ts, packages/app/src/cli/services/deploy.ts, packages/app/src/cli/utilities/app/config/webhooks.ts
closes: https://github.com/Shopify/develop-app-management/issues/1500
- Introduces schema changes to the app TOML that will provide the parsing and validation for declarative webhooks
- Also somewhat consumes the beta, but not fully wired up to the mutation yet
- The rest of the tidy up/wire up can come once we have mutations created to push declarative webhook data
- Adds new TOML fields, all are currently optional and validation is not checked until we turn it on. See the full property break down and content in which they refer to below
- Validates the declarative webhook subscription heavily. Trying to give the best DX by surfacing errors early and often
- Normalizes the TOML input into an easily consumable and consistent format we will ingest
- spin up local branch, otherwise review …
=> Toml webhook subscription parsing

.changeset/brown-ravens-clean.md, packages/cli-kit/src/public/node/ruby.test.ts, packages/cli-kit/src/public/node/ruby.ts
Fixes #3102  
Fixes #3125 
`BUNDLE_APP_CONFIG` sets the expected location of a configuration file. `BUNDLE_PATH` sets the location for the cache. The explanation is pretty clear [here](https://github.com/Shopify/cli/issues/3102#issuecomment-1819420714), and I confirmed on a Linux VM.
Install ruby and node on Linux using raw `apt-get`, and see this fail when running `theme-check`. On this branch, you don't see the same failure.
=> Use correct env variable

.changeset/eight-eagles-explain.md, packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/syncer/checksums.rb, packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/syncer/checksums_test.rb
Fixes #3138
We only want to reject duplicate `*.json` and `*.json.liquid` for files under `assets/*` and not files under other directories.
1. Add `product.json` and `product.json.liquid` to your theme
2. `shopify theme pull`
3. See that both files are pulled locally
=> Update reject_duplicated_checksums to only apply to asset files

packages/app/src/cli/models/app/app.ts, packages/app/src/cli/models/app/loader.test.ts, packages/app/src/cli/services/deploy.test.ts
- we're moving away from `xml` webhook payloads, so we want to not support the option to set this proprty, and just default to `json`
- documented more in the [decision log](https://vault.shopify.io/gsd/projects/36745/decisions/4088)
- the related core changes to the module are in https://github.com/Shopify/shopify/pull/466324
- remove the format property from the schema as we don't need it and wont process it anymore
=> remove format config option as we default to json

packages/app/src/cli/models/extensions/specifications/flow_template.ts
Related task: https://github.com/Shopify/flow-app/issues/3100
Marking some template extension fields as optional as we'll provide defaults if these values are not provided
Updates some properties on the Flow template extension schema to be optional
[Video](https://screenshot.click/21-18-jbz9p-ftrjn.mp4)
None, unreleased feature to be tested with 1p later this year.
=> Update flow template spec for allowOneClickActivate

packages/app/src/cli/services/dev/extension/bundler.test.ts, packages/app/src/cli/services/dev/extension/bundler.ts, packages/app/src/cli/services/dev/processes/draftable-extension.ts, packages/app/src/cli/services/dev/update-extension.test.ts, packages/app/src/cli/services/dev/update-extension.ts
We watch for changes in extensions files to trigger updates during dev, but the current process is long and involves moving a lot of parameters around.
Current flow of information (we need to pass everything from the first step to the last):
```
Dev 
-> Draftable process 
-> Watchers 
-> Update extension config 
-> Update draft extension
```
Proposed change:
```
Dev 
-> Draftable process 
-> watchers (with callback to draftable process)
-> Update draft extension
```
This allows the draftable process decide what to do after an extension change is detected.
And this will be useful for consistent-dev where we want to do a different thing on every change.
Relevant outcomes: less responsability for each function in the flow
- **The watcher** is now only responsible for watching and reporting …
=> Improve extension file watcher flow

packages/app/src/cli/services/dev/graphiql/templates/graphiql.tsx
Responding to https://github.com/Shopify/cli/pull/3152#issuecomment-1834606516
There is a desire to make changes to the wording and style of the banner that appears after disconnecting.
Before:
After:
Run `dev`, open GraphiQL, and WITHOUT CLOSING THE TAB quit `dev`. See the error banner.
=> Improve styling and wording of disconnected banner

.changeset/dry-sloths-tickle.md, .changeset/odd-flies-poke.md, packages/app/src/cli/services/context.ts, packages/cli-kit/src/private/node/session.ts
Fixes #3173
We aren't actually refreshing the token in the background during `dev`, because the error wasn't bubbling up and we have a mechanism to only refresh on error:
https://github.com/Shopify/cli/blob/f2e51f8aae2c48a5e8d95607b2761b189829048a/packages/app/src/cli/services/dev.ts#L331-L333
We seem to use these functions in a limited number of other places, but I don't see anywhere they shouldn't cause a failure.
Run `dev` overnight on an app with UI extensions. You should never see a complaint that dev preview mode isn't being updated.
=> Bubble up failure from developerPreviewUpdate

.changeset/honest-dragons-yell.md, packages/app/oclif.manifest.json, packages/app/src/cli/commands/app/dev.ts, packages/app/src/cli/constants.ts, packages/app/src/cli/services/dev.ts, packages/app/src/cli/services/dev/graphiql/server.ts, packages/app/src/cli/services/dev/graphiql/templates/graphiql.tsx, packages/app/src/cli/services/dev/processes/graphiql.ts, packages/app/src/cli/services/dev/processes/setup-dev-processes.test.ts, packages/app/src/cli/services/dev/processes/setup-dev-processes.ts, packages/app/src/cli/services/dev/ui.test.tsx, packages/app/src/cli/services/dev/ui.tsx, packages/app/src/cli/services/dev/ui/components/Dev.test.tsx, packages/app/src/cli/services/dev/ui/components/Dev.tsx
Allows us to maintain query history and not lose work. Also, if `dev` dies or is killed, you can restart `dev` and your tab starts working again. Woot!
Uses a primary method of localhost access to GraphiQL, while leaving the proxy-based option open for now (though we should consider removing it entirely).
Defaults to port 3457 for serving; we should give the option of specifying another port by ENV variable and/or config file to enable running `dev` on multiple apps simultaneously.
1. Spin up `dev` and verify that GraphiQL still works.
2. Quit `dev` and restart. Your tab should restore itself.
3. Open a new tab after the restart, and it should still keep your history.
=> Localhost GraphiQL

.changeset/red-houses-rule.md, packages/app/src/cli/models/app/app.test-data.ts, packages/app/src/cli/models/app/loader.test.ts, packages/app/src/cli/models/extensions/schemas.ts, packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts, packages/app/src/cli/services/context/id-manual-matching.test.ts, packages/app/src/cli/services/context/id-matching.test.ts, packages/app/src/cli/services/context/identifiers-extensions.test.ts, packages/app/src/cli/services/context/identifiers.test.ts, packages/app/src/cli/services/dev/extension/localization.test.ts, packages/app/src/cli/services/dev/extension/payload.test.ts, packages/app/src/cli/services/dev/extension/payload.ts, packages/ui-extensions-server-kit/src/types.ts
Partially resolves [#1529](https://github.com/Shopify/develop-app-management/issues/1529) (3rd party cookies/consent settings management is TBD).
This PR introduces support for a new extension capability under the `collect_buyer_consent` category: `write_privacy_consent` as part of the [Privacy Consent API](https://vault.shopify.io/gsd/projects/37679) project.
Note:  The `privacy_cookies` capability will be handled separately after requirements are confirmed.
This PR allows users to set and update the `collect_buyer_consent.write_privacy_cookies` capability. It also updates the extensions query to return the capability value.
This CLI branch has been added to a spin constellation and was used to set the writePrivacyConsent capability to true for the `checkout-ui` extension.
query …
=> [Checkout extensibility] Adds support for collect_buyer_consent.write_privacy_consent capability

.changeset/green-hornets-chew.md, packages/app/src/cli/services/function/build.test.ts, packages/app/src/cli/services/function/build.ts
Closes https://github.com/Shopify/script-service/issues/7416
> the WIT file format will transition from not accepting semicolons, to accepting but not requiring semicolons, and finally to requiring semicolons
[WIT spec](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md)
Adds semicolons to WIT statements (`package` and `export`)
> 1. Set the `WIT_REQUIRE_SEMICOLONS` environment variable to `1`
> 2. Run the CLI command to deploy the function on the main branch, confirm Javy raises an error about not being able to parse the WIT file
> 3. Run the CLI command to deploy the function on the branch with the changes to emit semicolons, confirm Javy does not raise an error about not being able to parse the WIT file …
=> [Functions] Add semicolons to generated WIT

packages/app/src/cli/services/dev/processes/setup-dev-processes.ts
Previously we used the default local app name instead of the actual name of the remote app.
Uses `remoteApp` (i.e., what we've actually connected to) as the source of truth for the app name in the GraphiQL web UI.
On an app with multiple configs, switch between the configs and relaunch GraphiQL. It should show the correct app title each time in the top bar.
=> Use correct source for app name for GraphiQL

.changeset/afraid-countries-melt.md, packages/app/src/cli/services/dev/graphiql/templates/graphiql.tsx
There's an odd-looking status flicker (status goes quickly disconnected => running => disconnected => running) when reconnnecting to `dev`. This PR eliminate that. (video [here](https://videobin.shopify.io/v/k56dJm?t=160))
The problem was that even if the most recent request to the server succeeded, a prior request could fail (because it was sent before the server was up), and we incorrectly activated "disconnected" status due to a timeout that wasn't cleared.
The previous strategy was to associate each timeout with a request and a function to clear the timeout:
```
Timeout A => Function A => make request A, if it succeeds then clear Timeout A and consider GraphiQL "connected"
Timeout B => Function B => make request B, if it succeeds then clear Timeout B and consider GraphiQL "connected" …
```
=> Eliminate flicker on reconnection to dev

packages/app/src/cli/api/graphql/extension_specifications.ts, packages/app/src/cli/commands/app/deploy.ts, packages/app/src/cli/models/app/app.test-data.ts, packages/app/src/cli/models/app/app.ts, packages/app/src/cli/models/app/loader.ts, packages/app/src/cli/models/extensions/extension-instance.ts, packages/app/src/cli/models/extensions/specifications/app_config_app_access.test.ts, packages/app/src/cli/models/extensions/specifications/app_config_app_access.ts, packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/context.ts, packages/app/src/cli/services/deploy.test.ts, packages/app/src/cli/services/deploy.ts, packages/app/src/cli/services/generate/fetch-extension-specifications.ts
Follow-up: https://github.com/Shopify/cli/pull/3170
Follow-up:  https://github.com/Shopify/cli/pull/3214
- Make `specifications` optional for the `App loader`. Set default value to an empty array so no extensions are loaded in this case.
- `deploy` command loads the app again with the extensions once the `remote app` is selected, thus, the `gated` specs are applied and in case they are not allowed the extensions are not loaded
- Temporal `app access` config module added. Supports the new section `access`
- `direct_api_offline_access` true | false to enable Online access for Direct API
- Create a new `cli` app and run the `app config link` command to link it to a new remote app. 
- With the org beta flag `App Access Module` disabled
- Add the section `access` with whatever value 
- Run the …
=> Deploy fetch remote specs

packages/app/src/cli/api/graphql/app_versions_diff.ts, packages/app/src/cli/prompts/deploy-release.test.ts, packages/app/src/cli/prompts/deploy-release.ts, packages/app/src/cli/services/context/breakdown-extensions.test.ts, packages/app/src/cli/services/context/breakdown-extensions.ts, packages/app/src/cli/services/release.ts
Follow-up: https://github.com/Shopify/cli/pull/3205
UX: [figma](https://www.figma.com/file/cTu9Ag52V4IdqZe1cij6kK/Versioned-app-config?type=design&node-id=10462%3A3898&mode=design&t=oBcgyeoQdDYSZWPc-1) 
Right now the source extension breakdown info data is different for the `deploy` and the `release` command. The former uses the `local` information and the second the API operation `appVersionDiff`
The `appVersionDiff` API return properly classified the `dashboard` extensions as `new`, `update` or `removed` (but it doesn't distinguish between `dashboard` or `extension`), however the local logic in the `deploy` command manages a list of `affected` dashboard extension regardless the modification made to them.
This drives us to a situation like this.
- `release` command prompt
- `deploy` …
=> Manage new_updated_removed dashboard extensions in confirmation prompt

packages/app/src/cli/models/app/app.ts, packages/app/src/cli/models/extensions/load-specifications.ts, packages/app/src/cli/models/extensions/specifications/app_config_app_access.test.ts, packages/app/src/cli/models/extensions/specifications/app_config_app_access.ts, packages/app/src/cli/models/extensions/specifications/types/app_config.ts, packages/app/src/cli/prompts/config.ts, packages/app/src/cli/services/app/config/link.test.ts, packages/app/src/cli/services/app/config/link.ts, packages/app/src/cli/services/app/config/push.test.ts, packages/app/src/cli/services/app/config/push.ts, packages/app/src/cli/services/app/write-app-configuration-file.test.ts, packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/dev/urls.ts
Follow-up: https://github.com/Shopify/cli/pull/3237
Add support for the new fields added to the [app_access](https://github.com/Shopify/shopify/pull/471575) module
- Move the new `app_access` fields from the `AppSchema` to the `app_access` spec definition
- Removed the `NonVersionedSchema`. This means that the config `[build]` section will be written inside the `toml` in a different position than the one used to be. Plus the new `branding` app module that versions the `name` property, the modifications applied to the `toml` structure will be:
- `name` after the `client_id`, rather than before
- `[build]` sections is the first one after the top level properties
- Fixed an issue with the `link` command. The file used as reference to create/update the final `toml` file was the `default` one …
=> Add support for new access module fields

packages/theme/src/cli/commands/theme/pull.ts, packages/theme/src/cli/services/open.test.ts, packages/theme/src/cli/services/open.ts, packages/theme/src/cli/utilities/theme-selector.test.ts, packages/theme/src/cli/utilities/theme-selector.ts
- Remove unused arg from function call
- Removes the `developmentTheme` property from the `options` for the function `findOrSelectTheme` in the `theme-selector` module.
- This property was previously used to specify the ID of the current development theme but is no longer needed, as we are now calling `getDevelopmentTheme` as of [Improve theme selector component by grouping themes by role (#1662) · Shopify/cli@dcc95e1](https://github.com/Shopify/cli/commit/dcc95e191bcaf1cd580aaf6ed3ba605e5b5fb303#diff-7633fa15fdce1b666ec9e64add1637d9a51d681f0ea67bfbda93a396198b4b8dR35-R36)
- Run automated unit tests
- Execute a command such as 
=> [Cleanup] Remove unused developmentTheme parameter in findOrSelectTheme function

packages/app/src/cli/api/graphql/functions/upload_url_generate.ts, packages/app/src/cli/services/deploy.test.ts, packages/app/src/cli/services/deploy/upload.test.ts, packages/app/src/cli/services/deploy/upload.ts, packages/cli-kit/src/public/node/api/partners.test.ts, packages/cli-kit/src/public/node/api/partners.ts
Part of https://github.com/Shopify/script-service/issues/7746
Replaces `functionProxyRequest`, a concept that used to make sense with script service, with something more aligned with how things are done today, `getFunctionUploadUrl`
Cleans up a bunch of unused code, such as everything related to `uploadFunctionExtensions`, since functions are no longer uploaded this way.
Retains many of the relevant `uploadFunctionExtensions` relating to uploading the wasm blob by moving them under a new `describe uploadWasmBlob` section in the test file.
=> Clean up legacy function upload code

packages/app/src/cli/models/extensions/specifications/payments_app_extension.ts, packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/redeemable_payments_app_extension_schema.test.ts, packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/redeemable_payments_app_extension_schema.ts
**Why are these changes introduced?**
This PR introduces a `redeemable` payments extension schema.
Subsequent PRs will include additional schema definitions, one for each payments extension, that will populate the schema union.
These changes will be behind a feature flag and the current CLI version `3.53` will not have `Payment Extensions` available as an option to choose from
- Create app with `npm init @shopify/app@latest`
- Pull this branch into your local `cli` copy
- Run `SHOPIFY_SERVICE_ENV=spin SPIN_INSTANCE={YOUR-SPIN-INSTANCE} NODE_TLS_REJECT_UNAUTHORIZED=0 SHOPIFY_CLI_VERSIONED_APP_CONFIG=1 pnpm shopify app config link --path {YOUR-APP-PATH}`
- Run `SHOPIFY_SERVICE_ENV=spin SPIN_INSTANCE={YOUR-SPIN-INSTANCE} NODE_TLS_REJECT_UNAUTHORIZED=0 SHOPIFY_CLI_VERSIONED_APP_CONFIG=1 pnpm …
=> Add redeemable schema to payments extension

packages/app/src/cli/services/dev/extension/utilities.test.ts, packages/app/src/cli/services/dev/extension/utilities.ts, packages/ui-extensions-dev-console/src/sections/Extensions/components/ExtensionRow/ExtensionRow.test.tsx, packages/ui-extensions-dev-console/src/sections/Extensions/components/ExtensionRow/ExtensionRow.tsx
POS is moving to support the unified ui-extensions package. However, as it is currently, the QR code for mobile is not generated when we detect that the extension is using the new ui-extension. 
This PR adds some logic to check and see if the ui-extension has POS UI Extension targets. If it does, then we generate the QR code modal, and the proper kind of URL.
1. You'll need to use pnpm to create an with a POS UI Extension.
2. Since generating will create the old style of template, you'll need to add `"@shopify/ui-extensions": "unstable"` to the package json. 
3. In your POS UI Extension, you can use the following toml code: 
```
api_version = "2024-01"
[[extensions]]
type = "ui_extension"
name = "pos-ui"
handle = "pos-ui"
[[extensions.targeting]]
module = "./src/Tile.ts"
target = …
```
=> Create mobile QR code for POS UI Extensions using unified config

.changeset/empty-chicken-tap.md, packages/plugin-cloudflare/scripts/postinstall.js
Fixes https://github.com/Shopify/cli/issues/3267
When running the postinstall script for the Cloudflare plugin, after checking that a binary already exists, we try to check the version by running `cloudflare --version` to see if it needs an upgrade.
But if the binary is damaged, or you don't have Rosetta installed and it needs it, it crashes and it doesn't reinstall.
Adds a try/catch to avoid crashing when checking the version. If it fails, it just continues with the reinstallation.
That would fix the broken binary, and if Rosetta is missing, the CLI will show a [proper message](https://github.com/Shopify/cli/blob/8ad91863e038a4207c81802bfd126be46233db29/packages/plugin-cloudflare/src/tunnel.ts#L130) on the next run.
- `rm packages/plugin-cloudflare/bin/cloudflared`
- `echo 'fail' > …
=> Fix postinstall step for Cloudflare when the binary fails

packages/app/src/cli/models/extensions/specifications/payments_app_extension.ts, packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/credit_card_payments_app_extension_schema.test.ts, packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/credit_card_payments_app_extension_schema.ts
**Why are these changes introduced?**
This PR introduces a `credit-card` payments app schema.
Subsequent PRs will include additional schema definitions, one for each payments extension type, that will populate the schema union.
These changes will be behind a feature flag and the current CLI version `3.53` will not have `Payment Extensions` available as an option to choose from
- Create app with `npm init @shopify/app@latest`
- Pull this branch into your local `cli` copy
- Run `SHOPIFY_SERVICE_ENV=spin SPIN_INSTANCE={YOUR-SPIN-INSTANCE} NODE_TLS_REJECT_UNAUTHORIZED=0 SHOPIFY_CLI_VERSIONED_APP_CONFIG=1 pnpm shopify app config link --path {YOUR-APP-PATH}`
- Run `SHOPIFY_SERVICE_ENV=spin SPIN_INSTANCE={YOUR-SPIN-INSTANCE} NODE_TLS_REJECT_UNAUTHORIZED=0 SHOPIFY_CLI_VERSIONED_APP_CONFIG=1 pnpm …
=> Add credit card schema to payments extension

packages/app/src/cli/api/graphql/get_config.ts, packages/app/src/cli/models/app/app.ts, packages/app/src/cli/models/app/loader.test.ts, packages/app/src/cli/models/app/loader.ts, packages/app/src/cli/prompts/config.test.ts, packages/app/src/cli/prompts/config.ts, packages/app/src/cli/prompts/deploy-release.test.ts, packages/app/src/cli/prompts/deploy-release.ts, packages/app/src/cli/services/app/config/link.test.ts, packages/app/src/cli/services/app/config/link.ts, packages/app/src/cli/services/app/config/push.test.ts, packages/app/src/cli/services/app/select-app.ts, packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/context.ts, packages/app/src/cli/services/context/breakdown-extensions.test.ts, packages/app/src/cli/services/context/breakdown-extensions.ts, packages/app/src/cli/services/context/identifiers-extensions.test.ts, packages/app/src/cli/services/context/identifiers-extensions.ts, packages/app/src/cli/services/context/identifiers.ts, packages/app/src/cli/services/deploy.test.ts, packages/app/src/cli/services/deploy.ts, packages/app/src/cli/services/dev/processes/setup-dev-processes.test.ts, packages/cli-kit/src/public/common/version.ts, packages/cli-kit/src/public/node/context/local.test.ts, packages/cli-kit/src/public/node/context/local.ts
Follow-up: https://github.com/Shopify/cli/pull/3250
Depends-on:
- Partners: https://github.com/Shopify/partners/pull/52536
From the first PR regarding the n[ew versioned app configuration feature](https://github.com/Shopify/develop-app-foundations/issues/841) users could opt-in it using the env variable `SHOPIFY_CLI_VERSIONED_APP_CONFIG=1` in the `deploy` and `link` commands.
As it's required to opt-in for everyone at once, the CLI will switch from the use of the env variable to the use of the remote app `versioned app configuration` beta flag. This flag is used as well by the server side to enable the registration of the new `configuration` app modules
- Remove the support for the env variable `SHOPIFY_CLI_VERSIONED_APP_CONFIG` 
- Add support for the new app beta flag …
=> Switch to versioned app configuration beta flag

packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb, packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/dev_server/proxy_test.rb
Related to https://github.com/Shopify/cli/pull/3249
This PR changes the approach adopted on  https://github.com/Shopify/cli/pull/3249 to not modify headers when users are on Chrome.
- Open the browser in a incognito window
- Type the password
- Notice the password page works on all browsers
**Before (Chrome)**
https://github.com/Shopify/cli/assets/1079279/d5f62f6d-e41b-4064-bedb-441df0fccdd2
**After (Safari, Firefox, and Chrome)**
https://github.com/Shopify/cli/assets/1079279/d8e09883-4ac4-40b5-897a-e4d8b6ed8f39
None.
=> Fix password page redirect in Safari [2]

packages/app/src/cli/api/graphql/get_config.ts, packages/app/src/cli/prompts/config.ts, packages/app/src/cli/services/app/config/push.test.ts, packages/app/src/cli/services/app/config/push.ts, packages/app/src/cli/services/app/select-app.ts, packages/app/src/cli/services/app/update-url.test.ts, packages/app/src/cli/services/app/update-url.ts
Follow-up: https://github.com/Shopify/cli/pull/3262
Partially-fixes: https://github.com/Shopify/develop-app-foundations/issues/855
Depends-on: https://github.com/Shopify/partners/pull/52716
- Check the `versioned_app_config` beta flag value once the remote app is selected for both commands
- If `enabled` the commands will display an error banner.
- Otherwise the current flow is executed
- Create a new spin instance `spin up partners@app-update-return-error-versioned-app`
- Run `NODE_TLS_REJECT_UNAUTHORIZED=0 SHOPIFY_SERVICE_ENV=spin SPIN_INSTANCE=$(spin show -o name) npm run shopify app config link --path /PATH/TO/YOUR/APP` and create a new remote app
- Add a versioned app property to the `toml` (ie handle = 'My handle'). Modify the `name` value. Run `NODE_TLS_REJECT_UNAUTHORIZED=0 …
=> `app config push` and `app update-url` commands deprecation

packages/app/src/cli/prompts/deploy-release.test.ts, packages/app/src/cli/prompts/deploy-release.ts, packages/app/src/cli/services/context.test.ts, packages/app/src/cli/services/context.ts, packages/cli-kit/src/private/node/analytics.ts, packages/cli-kit/src/public/node/monorail.ts
Depends-on: https://github.com/Shopify/monorail/pull/17518
- Send metrics for the `configuration breakdown info` 
- The info included is the same displayed in the `deploy/release` prompt:
- Affected top level fields
- Affected sections (ie. modifying `api_version` returns `webhooks` as affected section`
- Tracks the response of the `include config` deploy prompt, only is case it's rendered
- Sends `force` flag used only for commands that supports it
- Create a new `cli` app and run the `SHOPIFY_CLI_VERSIONED_APP_CONFIG=1 p shopify app config link --path /PATH/TO/YOUR/APP` command to link it to a new remote app.
- Enable `versioned_app_config` beta flag for the created app in partners internal
- Modify/add/remove sections inside the `toml`
- Run `p shopify app deploy --path …
=> Add versioned app config metrics

packages/app/src/cli/models/app/app.test-data.ts, packages/app/src/cli/models/app/app.ts, packages/app/src/cli/models/app/loader.test.ts, packages/app/src/cli/models/app/loader.ts, packages/app/src/cli/models/extensions/extension-instance.test.ts, packages/app/src/cli/models/extensions/extension-instance.ts, packages/app/src/cli/services/context.ts, packages/app/src/cli/services/context/identifiers-extensions.test.ts, packages/app/src/cli/services/context/identifiers-extensions.ts, packages/app/src/cli/services/context/identifiers.ts, packages/app/src/cli/services/deploy.test.ts, packages/app/src/cli/services/deploy.ts, packages/app/src/cli/services/dev/extension/bundler.test.ts, packages/app/src/cli/services/dev/extension/bundler.ts, packages/app/src/cli/services/dev/processes/draftable-extension.ts, packages/app/src/cli/services/dev/update-extension.test.ts, packages/app/src/cli/services/dev/update-extension.ts, packages/cli-kit/src/public/common/object.ts, packages/cli-kit/src/public/node/schema.test.ts, packages/cli-kit/src/public/node/schema.ts
WIP: Missing unit tests
Right now, when you run the `dev` command, `configuration` extensions draft content are not pushed. This means that for instance ui extensions that rely on some configuration value when the `developer preview` is enabled, their preview mode is not working properly
- `deploy` rely on the local flag `include_config_on_deploy` to include the config module (and create them if they don't exist) 
- `dev` always includes the config modules as draft extensions (creates the extensions if they don't exist)
- both command should not include the config extensions in case the `versioned_app_beta` is not enabled
- pushed deploy success message is not displayed for `config modules`
- config errors messages are displayed in the `dev console` using a human readable format
- Create …
=> Push config draft in dev

packages/app/src/cli/models/app/app.ts, packages/app/src/cli/models/app/loader.test.ts, packages/app/src/cli/models/app/loader.ts, packages/app/src/cli/models/extensions/specification.ts, packages/app/src/cli/models/extensions/specifications/app_config_app_access.test.ts, packages/app/src/cli/models/extensions/specifications/app_config_app_access.ts, packages/cli-kit/src/public/node/toml.test.ts
These changes are being introduced to make the Direct API toml config more explicit.  
TLDR: 
```toml
[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = false
```
- Adds `access` to `accessConfiguration`
- Adds `admin` inside `access`
- Adds `directApiMode` inside `admin`
- Adds `embedded_app_direct_api_access` inside `admin`
- Replaces the old config (`[access.direct_api_offline_access]`) with the new config (`[access.admin.direct_api_mode]`). 
- Adds `admin`, `directApiMode`, embeddedAppDirectApiAccess` to `AppAccessSchema`
- Passes `directApiMode` to the `dev` service
- Fixes some typos
- Adds/updates tests
- Docs
- [Direct API access](https://shopify.dev/docs/api/admin-extensions#direct-api-access)
- [Access …
=> [Direct API] Update Direct API Access Config

packages/app/src/cli/prompts/deploy-release.test.ts, packages/app/src/cli/prompts/deploy-release.ts, packages/app/src/cli/prompts/ui/deploy-release-info-table-section.test.ts, packages/app/src/cli/prompts/ui/deploy-release-info-table-section.ts
The configuration diff content display in the deploy/release prompts don't differentiate when a config field is updated or not. 
The user should be able to check if a config property has changed or not
- Adds a new list of items to the configuration diif prompt
- Create a new app
- Enable versioned app config beta flag
- Run deploy
- Modify some value in the `toml``
- Run deploy again
=> Highlight updated config field in the diff prompt

packages/app/src/cli/models/extensions/specifications/app_config_privacy_compliance_webhooks.test.ts, packages/app/src/cli/models/extensions/specifications/app_config_privacy_compliance_webhooks.ts, packages/app/src/cli/models/extensions/specifications/transform/app_config_webhook.ts, packages/app/src/cli/services/app/config/link.ts
There's a backfill process that is creating/updating configuration app modules for every app with at least once app version. 
The `privacy_compliance_webhooks` app module is being populated with the current url values in case they exist. Otherwise they are set to `null` but the app module is created.
Something similar is happening with the `webhooks` app modules, the `subscriptions` property is set to an empty array
To avoid some issues with the information displayed in the `diff` content, these specs will consider these use cases as empty app modules so the diff content will not display any differences for them if they don't exist in the local `toml`
Besides this, a fix has been added to the method that builds the remote configuration content from using the `configuration` app modules …
=> Webhooks specs doesn't parse empty privacy compliance urls or subscriptions

package.json
Previously, oclif treated `--flag=a --flag=b` as the second overriding the first. In v3, though, oclif [treats that as an invalid condition](https://github.com/oclif/core/blob/54447d4f1c849714c7b6f2b9f4f011ae3e27cb0e/src/parser/parse.ts#L147-L150).
We use this double-specification in `bin/create-test-app.js`, where the default is `--package-manager=npm` but we override with `--package-manager=yarn`. Hence:
Use an ENV var to specify the npm default instead.
`node bin/create-test-app.js -p yarn` should work without seeing a failure.
=> Specify package manager default by ENV var not flag
