- .changeset/chatty-steaks-draw.md
- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/services/app/config/link.test.ts
- packages/app/src/cli/services/app/config/link.ts
When you run the `link` command the CLI creates the final configuration content following these steps:
- Content from the current used local `toml` 
- Overwrites the previous content with the remote `Api Client Configuration`
- Overwrites the previous content with the existing remote `configuration` App Modules
`link` command lets you select an existing app or a new one.
There's an issue because  in case you don't select the same remote app than the current used locally the CLI should skip the first step from the ones above and use an empty configuration instead.
- Checks if the local app to link matches the remote one
- Writes the configuration in the default `shopify.app.toml` file only when the file is missing or the remote app matches its `client_id`
- Run the `link` command an create …
> `link` uses an empty app if the current used app is different from the remote one

- packages/cli-kit/src/public/node/themes/factories.ts
- packages/cli-kit/src/public/node/themes/types.ts
Hey @jamesmengo,
I've opened this PR because I believe the original naming convention I used in [`factories.ts`](https://github.com/Shopify/cli/pull/3331/files#diff-6c0bc949bbf87917ae230deef790e87623d0da2635c24333f4967270cdc2958a) was a bit misleading. So:
- I've updated `RemoteThemeJson`, `RemoteAssetJson`, and `BulkUploadResponse` to clarify that they are private types, aligning them with the same naming convention
- I've replaced `RemoteAssetJson` with `ThemeAsset, as `types.ts` holds our public types
> Avoid `RemoteAssetJson` + naming suggestions

- packages/app/src/cli/services/context/breakdown-extensions.test.ts
- packages/app/src/cli/services/context/breakdown-extensions.ts
When you create a new remote app, the `branding` configuration app module is automatically created including a default `handle` value. For current existing remote apps, a backfill process has also been triggered to run the same logic
This means, that the first time the user runs the `deploy` command with a `toml` that doesn't include the `handle` property, the `handle` property appears in the list of removed attributes. This is a confusing UX because the current users don't know anything about this new field.
`handle` property should not be shown in the removed list. Only in case the user adds it manually it should be displayed in the prompt diff content
- Adds a fixed check in the configuration breakdown info builder to remove the `handle` attribute explicitly
- Create a new remote app …
> `handle` not shown in the removed list in the deploy prompt

- packages/app/src/cli/services/app/config/link.ts
If you create a new `remix` app from scratch, run `dev` and create a new remote app, the default scopes fetched from the `remix templates` are lost.
In this use case, the local scopes should be kept
- When the local app configuration uses the legacy format, the scopes are used to create the new remote app
- This is a regression introduced by this two PRs:
- [link uses an empty app if the current used app is different from the remote one](https://github.com/Shopify/cli/pull/3333)
- [dev with the default toml without client_id reuses it](https://github.com/Shopify/cli/pull/3336)
so this fix is working for those use cases too
- Create a new app using Remix
- Run the dev command and create a new remote app
- Check that the `write_products` scope is included in the `toml`
- Open the app and …
> link command uses local scopes to create a new remote app

- .changeset/fifty-waves-wait.md
- packages/cli-kit/assets/cli-ruby/bin/shopify
Ruby 3.3.0 has deprecated readline [[1]](https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/) in favor of Reline, but the it does that by falling back to Reline [[2]](https://github.com/ruby/readline/blob/6e1e5d0eb8613d5522d0195779d1040b1bc5f078/lib/readline.rb#L4). Because Shopify CLI overrides the require method [[3]](https://github.com/Shopify/cli/blob/143521bb72cd7a172f6e2c30d43848addc13ee02/packages/cli-kit/assets/cli-ruby/bin/shopify#L8), an error message appears in our console (but the CLI internally fallbacks to Reline).
The CLI prevents the error message from being displayed when a `readline` load error happens (as that's expected).
- Run `export SHOPIFY_RUBY_BINDIR=/opt/homebrew/Cellar/ruby/3.3.0/bin`
- Run `shopify theme console` on Ruby 3.3.0
**Before this PR** …
> Fix the error message that started occurring since Ruby 3.3.0

- .changeset/tidy-stingrays-sit.md
- packages/cli-kit/src/private/node/ui/components/TextInput.test.tsx
- packages/cli-kit/src/private/node/ui/components/TextInput.tsx
Makes a small quality-of-life improvement to the CLI experience.
When there is placeholder text, allows the user to tab-complete. It moves the cursor to the end of the text, so they can then continue to edit as usual.
I imagine this being especially useful for internal developers who generate many apps, extensions, etc. and might want to append some information to the auto-generated title.
`pnpm create-app` should do the trick! See the generated name, press `tab` to complete and see that you can edit as usual.
> Text input tab completion

- .changeset/wet-socks-hope.md
- packages/app/src/cli/prompts/deploy-release.test.ts
- packages/app/src/cli/prompts/deploy-release.ts
When there are no extensions and no configuration changes, CLI shows an empty deploy confirmation. 
When there are no extensions, we should explicitly show "Extensions: none" in the prompt. And if there are no config changes, we should say "Configuration: no changes"
- `Configuration` sections is always shown regardless the content of the `Extensions` sections. This sections is optional, so in case no value is received the sections is not displayed
- `Extensions` section is always rendered either with the breakdown info content or the message `None` is case no value is received
- Run the `deploy` command with `--reset` and create a new remote app
- Confirm the prompt to `include the configuration`
- Diff content shown
> Display empty sections inside the deploy release prompt

- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/models/app/loader.ts
- packages/app/src/cli/models/extensions/extension-instance.ts
- packages/app/src/cli/models/extensions/specification.ts
- packages/app/src/cli/services/app/config/link.ts
- packages/app/src/cli/services/draft-extensions/push.ts
- We were using an appModule feature (`app_config`) to identify configuration modules
- We should use the same property Core uses for this: a new field called `experience`
Fixes https://github.com/Shopify/develop-app-management/issues/1602
- Remove `app_config` from the list of features
- Add a new `experience` field to the specs, either `extension` or `configuration`
- Migrate all uses of `app_config` to the new `experience`
Configuration extensions work as expected, try with some deploys and enabling/disabling the deploy of configs
> Refactor app_config feature to the new experience field

- packages/app/src/cli/services/dev/processes/theme-app-extension.ts
- packages/cli-kit/assets/cli-ruby/lib/project_types/theme/commands/token.rb
- packages/cli-kit/src/public/node/session.ts
Fixes #3173 
Pushing Theme App Extension drafts requires unexpired Partners auth. Unfortunately, given the Ruby subprocess system we live with (for now), nothing is refreshing authentication, so sometime within ~2 hours the authentication expires, and the theme app extension silently stops reloading on save.
1. Instead of sending a Partners auth token Node => Ruby by CLI flag, we use the hidden `theme token` command to pass a Partners token and save in the local `Shopify::DB`. That token is utilized by the `extension serve` process because we no longer pass a `token` flag.
2. The token is refreshed once before `theme extension serve` is called, and refreshed again every 3 minutes.
3. If the token fails to refresh, we make 2 more attempts after a 30-second window. Failing that, we kill the …
> Refresh theme auth

- .changeset/slow-kiwis-beg.md
- packages/app/src/cli/services/app/config/link.test.ts
- packages/app/src/cli/services/app/config/link.ts
Fixes https://github.com/Shopify/develop-app-foundations/issues/886
- In the `link` command when local configuration is merged the remote one, a replace with remote strategy is used instead of union, for any array property
- Run `dev` to automatically update app URLs
- Run `link`, the `redirect_urls` property content is overwritten with the remote one
> Link overwrites redirect urls

- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/models/app/loader.ts
- packages/app/src/cli/models/extensions/extension-instance.ts
- packages/app/src/cli/models/extensions/specification.ts
- packages/app/src/cli/models/extensions/specifications/function.test.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.ts
- packages/app/src/cli/services/dev/update-extension.test.ts
- packages/app/src/cli/services/dev/update-extension.ts
- packages/app/src/cli/services/info.test.ts
- packages/app/src/cli/services/info.ts
- At some point we added `path: string` as an extra field of the extensions configuration (to make it possible to do `ext.configuration.path` instead of passing a different parameter: `ext.configurationPath`
- This has added complexity when dealing with the configuration objects because they no longer follow the expected schema defined in each specification and the toml
Contributes to https://github.com/Shopify/develop-app-management/issues/1603
- Remove`& {path: string}` from the extensions configuration, make it a separate field.
Nothing in particular, creating and deploying extensions continues to work
> Remove path from extension instance configuration schema

- .changeset/hip-jobs-jog.md
- packages/app/src/cli/api/graphql/get_config.ts
- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/organization.ts
- packages/app/src/cli/services/app/config/link.test.ts
- packages/app/src/cli/services/app/config/link.ts
- packages/app/src/cli/services/app/select-app.ts
- packages/app/src/cli/services/context.test.ts
- packages/app/src/cli/services/context.ts
- packages/app/src/cli/services/context/breakdown-extensions.test.ts
- packages/app/src/cli/services/context/identifiers-extensions.test.ts
- packages/app/src/cli/services/deploy.test.ts
Versioned app configuration has been 100% rolled out altogether with the 3.55.0 release. This means that all conditional logic depending on the value of the beta should be always executed
- Doesn't fetch deprecated and non used `betas` property from the partners `app` API
- Removes `VersionedApp` from the local `BetaFlags` 
- Removes references to `VersionedApp`  BetaFlag. In those case the logic that was executed when the beta was enabled should be executed
- Run `app deploy`, `app link` and `app dev` commands doing different modifications in the `toml` including the flag `include_config_on_deploy`. All versioned app features should be available
- Prompt to include config on deploy
- Any update configuration message displayed in banners should indicate `app deploy`
How do we know this …
> Removed versioned app config beta flag

- .changeset/loud-grapes-change.md
- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/services/app/config/link.test.ts
- packages/app/src/cli/services/app/config/link.ts
- packages/app/src/cli/services/app/select-app.test.ts
- packages/app/src/cli/services/app/select-app.ts
- packages/app/src/cli/services/context/breakdown-extensions.ts
`link` command was using the content from the `configuration` extension registration to build the remote configuration. Although the content of the registrations should be equivalent to the current app version configuration modules, it's better to use always the current app version content because the api to get the extension registrations will be eventually deprecated
- Create a new method to fetch the content of the remote configuration
- Use this method in whatever place where the remote config is required in the code base
- `deploy` and `link` command should work as expected
> Link use version app configuration

- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/extensions/specifications/web_pixel_extension.ts
- packages/app/templates/ui-extensions/projects/web_pixel_extension/shopify.extension.toml.liquid
As part of https://github.com/Shopify/ce-customer-behaviour/issues/3598
Tech Design: https://docs.google.com/document/d/1Qmvp6Xw1KUPC-Lj-c6fo8lHh0KtaLNtc-4vgMKIOuYI/edit#heading=h.62oius9y1lvr
We are now enabling partners to provide their custom granular privacy settings to their pixel. (I.e. does their pixel require customers to allow analytics consent, marketing consent, preferences or sale of data)
Presently every pixel is given a default analytics and marketing setting. We load every pixel if the customer has given consent to those 2 purposes. However, every pixel is different! So we are now offering the ability for app pixels to specify their own granular consent. 
This pull request creates a new input config field for app pixels to specify their app pixel privacy settings. It is …
> add new optional privacy settings config to web pixels

- .changeset/hip-pets-wave.md
- packages/app/src/cli/api/graphql/create_app.ts
- packages/app/src/cli/api/graphql/find_app.ts
- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/models/organization.ts
- packages/app/src/cli/services/app/config/link.test.ts
- packages/app/src/cli/services/app/config/link.ts
- packages/app/src/cli/services/app/select-app.test.ts
- packages/app/src/cli/services/app/select-app.ts
Versioned app configuration has been 100% rolled out altogether with the 3.55.0 release. That means that the CLI should not use `api client configuration` anymore
- `link` command is not merging the remote API Client configuration
- Removed unused `API Client configuration` from the `app` API requests
- `link` command should work as expected
> Remove API Client config from `link` command

- packages/app/src/cli/services/dev/select-store.ts
Right now it's not possible to run the `dev` command for `1p apps` using the env variable `SHOPIFY_CLI_1P_DEV`
In that case the server is returning the following error is returned
```
─ error ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                                           │
│                                                                                                                                                                                           │
│  The Partners GraphQL API responded …
```
> Run dev for 1p apps against production services

- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/credit_card_payments_app_extension_schema.test.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/credit_card_payments_app_extension_schema.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/custom_credit_card_payments_app_extension_schema.test.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/custom_credit_card_payments_app_extension_schema.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/custom_onsite_payments_app_extension_schema.test.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/custom_onsite_payments_app_extension_schema.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/redeemable_payments_app_extension_schema.test.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/redeemable_payments_app_extension_schema.ts
Update payment apps capabilities
This PR:
- Introduces a new field to the schema validations, `ui_extension_handle`, so it can be sent to the backend.
- Makes the encryption certificate optional, so developers can test their apps without filling the values (by running `app dev`)
Unit tests should pretty much cover everything.
N/A
> Adds support for ui extension handle

- packages/app/package.json
- packages/theme/package.json
- packages/theme/src/cli/commands/theme/check.ts
- packages/theme/src/cli/services/check.ts
- pnpm-lock.yaml
- Bump Shopify/theme-tools packages
- Fixes a couple of CLI issues
- `pnpm shopify theme check --path ../dawn` should pickup the `.theme-check.yml` file
- `pnpm shopify theme check --path ../dawn --config :theme_app_extensions --print` should not print `extends: theme-check:recommended`
- `pnpm shopify theme check --path ../dawn --print` should not print `extends: theme-check:recommended`
- `pnpm shopify theme check --path ../dawn --list` should not show stuff that shouldn't be loaded if the .theme-check.yml file has extends nothing in it
> Bump Shopify/theme-tools packages

- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/services/app/config/link.test.ts
- packages/app/src/cli/services/app/config/link.ts
- packages/app/src/cli/services/context.test.ts
- packages/app/src/cli/services/context.ts
- packages/app/src/cli/services/deploy.ts
- packages/app/src/cli/services/generate.test.ts
- packages/app/src/cli/services/generate.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
Related to https://github.com/Shopify/develop-app-management/issues/1621 and https://github.com/Shopify/develop-app-management/issues/1622
Replace all the `fetchSpecifications` with the DeveloperPlatformClient adapter.
- `p shopify app dev`
> Migrate fetchSpecifications to Partners adapter

- packages/app/src/cli/services/app/config/link.ts
In https://github.com/Shopify/cli/pull/3456 we made a refactor, but there's an issue in the Link service, where `loadLocalApp` could be receiving an undefined `developerPlatformClient`.
Spotted by @oluwatimio 
Pass the initialized `developerPlatformClient` to all the functions in the Link service
`p shopify app config link`
> Fix link refactor

- .changeset/fair-goats-sip.md
- packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb
- packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/dev_server/proxy_test.rb
Fixes https://github.com/Shopify/cli/issues/3466
It seems like the caching policy at SFR has changed, so we're implementing this temporary solution to clean it and mitigate the issue.
- Delete your current development theme with `shopify-dev theme delete -t <development_theme_id>`
- Notice that the localhost no longer loads the live theme; and the theme in localhost matches with the preview theme
**Before**
**After**
None.
> Fix `shopify theme dev` issue to avoid previewing the live theme instead of the development one

- packages/plugin-cloudflare/package.json
- packages/plugin-cloudflare/scripts/postinstall.js
- pnpm-lock.yaml
From node v18 it's possible to use node's native `fetch`, so we don't need the `node-fetch` dependency anymore. (because we require node >= 18.12.0
❗ This removes `node-fetch` and 5 other transitive dependencies.
- Remove node-fetch from plugin-cloudflare
- Add extra validation because our shipit release process uses node 16 and it'd crash.
- Delete the cloudflare binary from the bin folder
- run `pnpm install` and check that it is installed
- run `pnpm install` again and check that it doesn't do anything (it's already installed)
> Use native fetch instead of node-fetch

- packages/app/src/cli/services/info.test.ts
- packages/cli-kit/src/private/node/content-tokens.ts
- packages/cli/src/cli/services/commands/version.test.ts
- packages/cli/src/cli/services/upgrade.test.ts
The command tokens look different depending on whether we're using the output system vs. `cli-kit` UI kit. They should be aligned.
Changes the `output` system to align with UI kit, using `magentaBright` color and backticks.
`shopify version` should use the correct coloring for the upgrade command.
> Align command token with UI kit

- .changeset/strange-drinks-move.md
- packages/app/src/cli/services/info.ts
It's not valuable to the user, and it's 80% of output lines.
On a sample local app, we went from 2717 lines of JSON to 562.
Removes the Zod schemas from app info when you run `--json`
Compare `npm run info --json` with and without this change.
> Remove zod schemas from app info JSON format

- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/services/app/select-app.ts
- packages/app/src/cli/services/context.test.ts
- packages/app/src/cli/services/context.ts
- packages/app/src/cli/services/dev/fetch.test.ts
- packages/app/src/cli/services/dev/fetch.ts
- packages/app/src/cli/services/dev/processes/setup-dev-processes.test.ts
- packages/app/src/cli/services/dev/processes/setup-dev-processes.ts
- packages/app/src/cli/services/dev/processes/uninstall-webhook.ts
- packages/app/src/cli/services/dev/select-store.ts
- packages/app/src/cli/services/webhook/find-app-info.test.ts
- packages/app/src/cli/services/webhook/find-app-info.ts
- packages/app/src/cli/services/webhook/request-api-versions.test.ts
- packages/app/src/cli/services/webhook/request-api-versions.ts
- packages/app/src/cli/services/webhook/request-sample.test.ts
- packages/app/src/cli/services/webhook/request-sample.ts
- packages/app/src/cli/services/webhook/request-topics.test.ts
- packages/app/src/cli/services/webhook/request-topics.ts
- packages/app/src/cli/services/webhook/send-app-uninstalled-webhook.test.ts
- packages/app/src/cli/services/webhook/send-app-uninstalled-webhook.ts
- packages/app/src/cli/services/webhook/trigger-flags.test.ts
- packages/app/src/cli/services/webhook/trigger-flags.ts
- packages/app/src/cli/services/webhook/trigger-options.test.ts
- packages/app/src/cli/services/webhook/trigger-options.ts
- packages/app/src/cli/services/webhook/trigger.test.ts
- packages/app/src/cli/services/webhook/trigger.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
- packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client.ts
Fixes https://github.com/Shopify/develop-app-management/issues/1642
Fixes https://github.com/Shopify/develop-app-management/issues/1643
- Migrate all the code related to webhooks to use Partners adapter
- Simplify organizations query as commented [here](https://github.com/Shopify/cli/pull/3510#discussion_r1511057202)
dev, webhook trigger
> Migrate webhooks code to Partners adapter

- packages/app/src/cli/models/extensions/load-specifications.ts
- packages/app/src/cli/models/extensions/specifications/editor_extension_collection.test.ts
- packages/app/src/cli/models/extensions/specifications/editor_extension_collection.ts
Fixes https://github.com/Shopify/core-issues/issues/66051
Also check your spin branch out to 
https://github.com/Shopify/shopify/pull/490149
https://github.com/Shopify/partners/pull/53863
Adding new extension collection spec to the cli
To have an extension code locally clone Shopify/customer-accounts-ui-extension-dev and also clone CLI locally
1. Clone CLI locally
2. Run `spin up customer-accounts-ui-extension-dev`
3. Checkout my branches in partners and shopify core
4. Run dev refresh on both shopify core and partners in spin.
5. Go to partners org internal, and for your org enable the beta flag `'editor_extension_collection'` for example the link looks like https://partners.build-extension-collections.oluwatimi-owoturo.us.spin.dev/internal/organizations/1
6. In the CLI run the following …
> Add editor extension collection spec

- packages/cli/src/index.ts
Sometimes unhandled exception errors do not have a stack property. We spent a long time debugging a vite issue, where an unhandled exception error was getting swallowed. It has a `.message` property but not a `.stack` property. It's probably worthwhile to make this handler rather defensive.
Log in this precedence: `.stack`, `.message`, the whole arg.
Throw an unhandled exception. Make sure it logs.
> Fix unhandled exception error logging

- .changeset/honest-lamps-itch.md
- packages/app/src/cli/prompts/dev.test.ts
- packages/app/src/cli/prompts/dev.ts
- packages/app/src/cli/services/app/select-app.ts
- packages/app/src/cli/services/dev/select-app.test.ts
- packages/app/src/cli/services/dev/select-app.ts
- packages/app/src/cli/services/webhook/find-app-info.test.ts
- packages/app/src/cli/services/webhook/find-app-info.ts
Fixes #3626 
If an app was found after searching, it won't be sufficient to return the API key, as the app may not be in the original list which the caller has access to.
Returns the full selected `OrganizationApp` from `selectApp` instead of just the API key.
Select something past the first 25 in the list of apps. It shouldn't get the error: `Cannot destructure property 'apiKey' of 'undefined' as it is undefined.`
NOTE: We have another open issue around older apps predating versioned app config, so you may see a TOML validation error. That isn't related.
> Return full app from selectApp

- .changeset/dull-tips-wait.md
- packages/theme/src/cli/commands/theme/push.test.ts
- packages/theme/src/cli/commands/theme/push.ts
- packages/theme/src/cli/services/push.ts
- https://github.com/Shopify/develop-advanced-edits/issues/186
- Fixes the command execution when executed from environments such as CI
- Certain environments use the [Theme Access app](https://shopify.dev/docs/themes/tools/theme-access)) for authentication. Unfortunately, this app doesn't provide access to the bulk asset upload endpoint, which was causing nothing to get pushed (and errors to get swallowed)
- Calls the legacy (ruby) implementation of the `push command` when the `password` flag is provided
- _This is a temporary solution to fix the `push command` and any CI consumers without needing to explicitly provide the `--stable` flag_
- This PR will be reverted once ThemeKit adds support for calling the Bulk Upload endpoint in the Asset API
1) Checkout `Main`
2) Install the [theme …
> [Themes] Fix Theme Push Execution when password flag is provided

- .changeset/dull-tips-wait.md
- packages/theme/src/cli/commands/theme/push.test.ts
- packages/theme/src/cli/commands/theme/push.ts
- packages/theme/src/cli/services/push.ts
Backporting the fix below:
- https://github.com/Shopify/cli/pull/3645
> [3.58] Fix `shopify theme push` issue when password flag is provided

- .changeset/clever-windows-count.md
- packages/app/src/cli/constants.ts
- packages/app/src/cli/services/extensions/bundle.test.ts
Nothing beginning with a number!
More details at https://github.com/evanw/esbuild/blob/44e746965d783646f97daf3d0617ff816727e7fb/internal/js_ast/js_ident.go#L9-L25
Fixes #3649 
ESBuild has [very strict rules](https://github.com/evanw/esbuild/blob/44e746965d783646f97daf3d0617ff816727e7fb/internal/js_ast/js_ident.go#L9-L25) about which ENV variables are allowed. One of the rules is no numeric characters at the beginning.
Disallows numeric characters at the start of the ENV variable name.
For an app with an extension:
```
$ env '1VAR=value' p shopify app dev --path /path/to/your/app/with/ui/extensions
```
This should fail on `main` and succeed on this branch.
> Filter env vars to always be valid for ESBuild

- packages/cli-kit/src/public/node/monorail.test.ts
- packages/cli-kit/src/public/node/monorail.ts
Fixes https://github.com/Shopify/cli/issues/3518 
The `api_key` is visible in the verbose log on `shopify app config link`. While this isn't critical as this is on the developers machine, these logs are required when opening a bug ticket.
Replaces the `api_key` with `****` for the logs output.
> Sanitize "api_key" from verbose log

- .changeset/spotty-badgers-attack.md
- packages/theme/src/cli/utilities/asset-ignore.test.ts
- packages/theme/src/cli/utilities/asset-ignore.ts
- https://github.com/Shopify/cli/issues/3664
- https://github.com/Shopify/develop-advanced-edits/issues/188
This warning was added to surface some work that we were always doing on the Ruby side to include subdirectories when pattern matching theme files (`.shopifyignore`, `--ignore`, `--only`)
Technically, the pattern `templates/*.json` **should not** match subdirectories, but this would be a largely breaking change, so we apply this change on the platform side when needed.
- Instead of doing this work silently in the background, the warning informs devs of the modification we were making to their patterns. 
- Fixes an issue where the warning was rendering on all pattern mismatches ( we now only render the message if the modified pattern leads to a match a hit while the original pattern …
> [Themes] Improve Glob Pattern subdirectory mismatch error handling

- packages/app/src/cli/commands/app/config/link.ts
- packages/app/src/cli/commands/app/dev.ts
- packages/app/src/cli/commands/app/generate/extension.ts
- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/app/loader.ts
- packages/app/src/cli/prompts/config.ts
- packages/cli/src/cli/services/upgrade.ts
Some `app` commands start doing work or presenting prompts before validating if the current directory is a valid app directory, which eventually will fail.
We should fail early if we are not working in an app directory.
- Look in the active directory for app toml files, if there aren't any, throw an error.
- Update the error message to be more clear that an app toml file couldn't be found.
Try to run this both in main and this branch:
`pnpm shopify app dev --path ../invalid-path`
It should show prompts in main, and an early error in this branch
> Throw error early if active directory is not an app folder

- packages/app/src/cli/api/graphql/extension_migrate_app_module.ts
- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/services/context/identifiers-extensions.ts
- packages/app/src/cli/services/dev/migrate-app-module.test.ts
- packages/app/src/cli/services/dev/migrate-app-module.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
- packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client.ts
To ensure dashboard payments extensions that are imported can be appropriately migrated over. 
Ensure payments extension that are eligible for migration are migrated during `app deploy`
How to test your changes?
```
Create app with npm init @shopify/app@latest
Pull this branch into your local cli copy
Run SHOPIFY_SERVICE_ENV=spin SPIN_INSTANCE={YOUR-SPIN-INSTANCE} NODE_TLS_REJECT_UNAUTHORIZED=0 SHOPIFY_CLI_VERSIONED_APP_CONFIG=1 pnpm shopify app config link --path {YOUR-APP-PATH}
Run SHOPIFY_SERVICE_ENV=spin SPIN_INSTANCE={YOUR-SPIN-INSTANCE} NODE_TLS_REJECT_UNAUTHORIZED=0 SHOPIFY_CLI_VERSIONED_APP_CONFIG=1 pnpm shopify app deploy --path {YOUR-APP-PATH}
View Payments Extensions
```
> Migrate payment extensions in dev deploy if eligible

- package.json
- packages/app/src/cli/services/extensions/bundle.test.ts
- packages/app/src/cli/services/extensions/bundle.ts
- packages/app/src/cli/services/info.test.ts
- packages/app/src/cli/services/info.ts
- packages/features/steps/app.steps.ts
- pnpm-lock.yaml
In preparation for Global CLI this PR introduces 3 minor fixes.
- Add back `esbuild` as a top-level dependency, it will be used in the bundling scripts
- Improve how the graphql esbuild plugin is loaded to use ESM
- Fix `app info` showing an incorrect CLI version
- App info shows the real version and not what you have in your package.json.
> Add esbuild back, improve esbuild plugin import, fix app info

- .changeset/lazy-maps-retire.md
- packages/theme/src/cli/commands/theme/push.test.ts
- packages/theme/src/cli/commands/theme/push.ts
We've introduced support for the CLI in the Theme Access app supports the CLI, so we may rollback this change.
This PR updates the push command to no longer rely in the legacy implementation when the `--password` flag is passed
None.
> Introduce support to Theme Access app in the new `shopify theme push` implementation

- .changeset/shiny-trainers-ring.md
- packages/theme/src/cli/utilities/theme-fs.ts
Introduce support to the [`blocks/`](https://shopify.dev/docs/themes/architecture/blocks/theme-blocks) directory in the `shopify theme push` command
This PR updates the theme filesystem module to support the `blocks/` directory locally.
- Create a theme with files in the `blocks/` directory
- Run `shopify-dev theme push -u -t test`
- Notice they get uploaded
None.
> Introduce support to the `blocks/` directory in the `shopify theme push` command

- packages/cli-kit/src/public/node/themes/api.test.ts
- packages/cli-kit/src/public/node/themes/api.ts
- packages/cli-kit/src/public/node/themes/factories.ts
- packages/theme/src/cli/utilities/theme-uploader.ts
- https://github.com/Shopify/develop-advanced-edits/issues/187
- This PR adds error handling for the case when the bulk asset upload endpoint responds with an empty object
- See https://github.com/Shopify/cli/pull/3645 for more context 
- Rather than failing silently, we should return a response to the user that indicates an issue
- I've chosen to Abort the operation rather than continuing to execute.
- Another option is to try to execute the remaining uploads, but there is little value in doing so as this type of response indicates a larger issue (in the case linked above, bulk uploads are not supported by the theme access proxy) - this means that all the subsequent requests will also fail.
- Checkout main
- run `pnpm shopify theme push -u --password <PASSWORD> --verbose`
- Observe that …
> [Theme] Add handling when server does not respond to bulk asset upload

- .changeset/clean-badgers-deny.md
- .github/workflows/cli-ruby.yml
- packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb
- packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/repl/auth_middleware.rb
Fix the `shopify theme dev` proxy to use the development theme, even when users have a browser session with the live theme loaded. I noticed this edge case while conducting additional manual tests for https://github.com/Shopify/cli/pull/3769.
This PR updates the proxy to serve the 302 response when the development theme ID is set.
**Before**
**After**
None.
> [3.59] Fix `shopify theme dev` proxy to use development theme

- .github/workflows/cli-ruby.yml
Rubocop is failing on [`main`](https://github.com/Shopify/cli/commits/main/).
Updates the `.github/workflows/cli-ruby.yml` to make it pass.
N/A
N/A
N/A
N/A
> Fix Rubocop CI

- .changeset/late-flowers-yell.md
- packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/repl/auth_middleware.rb
When another theme is set in the session, `shopify theme console` tries to evaluate Liquid snippets using the wrong remote theme.
This PR adopts [this fix](https://github.com/Shopify/cli/pull/3771) to make sure that Liquid snippets are evaluated using the expected remote theme.
**Before**
**After**
None.
> Fix issue that prevents `shopify theme console` from evaluating results when another 'preview_theme_id' is set

- .changeset/curvy-crabs-rule.md
- packages/theme/src/cli/commands/theme/push.test.ts
- packages/theme/src/cli/commands/theme/push.ts
- packages/theme/src/cli/services/local-storage.ts
- packages/theme/src/cli/utilities/development-theme-manager.test.ts
- packages/theme/src/cli/utilities/unpublished-theme-manager.test.ts
- packages/theme/src/cli/utilities/unpublished-theme-manager.ts
Backporting
- https://github.com/Shopify/cli/pull/3798
TL;DR - Unpublished themes were getting marked as development themes
> [3.59][Themes][Bugfix] - Fix unpublished themes being marked as development themes

- .changeset/curvy-deers-wink.md
- packages/app/src/cli/models/extensions/specifications/theme.ts
- packages/cli-kit/assets/cli-ruby/lib/project_types/extension/models/specification_handlers/theme_app_extension.rb
Fixes #1962 
Adds `.json` asset support to theme app extensions. Another PR has already been shipped to enable this upstream
- Create a new app with a theme app extension
- Add a .json file in the assets folder
- Run the app dev command
- Notice the theme app extension is pushed as expected
None
> [Feature] Introduce `.json` asset support in theme app extensions

- .changeset/tough-kids-guess.md
- packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb
- packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/repl/auth_middleware.rb
- packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/dev_server/proxy_test.rb
Fixed the `shopify theme dev`/`shopify theme console` proxy to handle cookies as expected, and ensured they no longer render the live theme instead of the development theme.
With the session cookie being renamed, the CLI needed to follow that change [[1]](https://github.com/Shopify/cli/pull/3791/files#diff-4a33c3fb0b66e923abaaf8d530a2303552bf820cda31bf47d88961d2caba1d57L28) [[2]](https://github.com/Shopify/cli/pull/3791/files#diff-4a33c3fb0b66e923abaaf8d530a2303552bf820cda31bf47d88961d2caba1d57L28). However, the new regular expression captures the `;`, which was creating a scenario like this:
**This is not an issue when the session cookie is the last one** in the cookie string, but when it's in the middle of the string, it depends on the client's fallback behavior, which creates an …
> Fix the `shopify theme dev`/`shopify theme console` proxy to handle cookies as expected

- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/credit_card_payments_app_extension_schema.test.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/credit_card_payments_app_extension_schema.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/custom_credit_card_payments_app_extension_schema.test.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/custom_credit_card_payments_app_extension_schema.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/custom_onsite_payments_app_extension_schema.test.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/custom_onsite_payments_app_extension_schema.ts
Fixes https://github.com/Shopify/payments-platform/issues/4594
We want to limit the number of checkout_payment_method_fields we allow on the credit_card, custom_credit_card, and custom_onsite extensions to allow the partners from abusing this.
Backend PR: https://github.com/Shopify/shopify/pull/503013
This PR is putting a max validation on the checkouy_payment_method_fields array in the relevant extension schemas.
1. Create a new spin instance using constellation `payment-apps:with-cli` e.g. `spin up payment-apps:with-cli –name cli-testing`
2. From cli directory on your spin instance, create a new directory one level up for cli app development (in the Shopify/ base directory). You should then run any `pnpm *` commands in the CLI directory using a path flag.
```
cd Shopify/cli
mkdir …
```
> Limit the number of field definitions allowed for credit_card, custom_credit_card, and custom_onsite extensions

- RELEASE_NOTES/3.60.md
CLI [3.60.0](https://github.com/Shopify/cli/releases/tag/3.60.0) release notes
> create CLI version 3.60.0 release notes

- .changeset/wet-paws-smoke.md
- packages/cli-kit/src/private/node/session.ts
- packages/cli-kit/src/private/node/session/identity-token-validation.ts
Running dev with TAE in Spin was failing when trying to refresh the tokens:
```
The currently available CLI credentials are invalid.  
The CLI is currently unable to prompt for reauthentication.
Restart the CLI process you were running. If in an interactive terminal, you will be prompted to reauthenticate. If in a non-interactive terminal, ensure the correct credentials are available in the program environment. 
```
Original thread: https://shopify.slack.com/archives/C030LHFCA5T/p1714414263061029
Skip the error message thrown when the credentials are invalid and we can't run the auth flow, as it doesn't make sense for 1p dev in Spin.
Try with `0.0.0-experimental-20240430140716` in Spin
> Fix auth for 1p development in Spin

- .changeset/real-ravens-camp.md
- package.json
- packages/app/package.json
- packages/cli/bin/bundle.js
- packages/theme/package.json
- packages/theme/src/cli/commands/theme/check.ts
- pnpm-lock.yaml
There is a bug in theme check where some expected assets can't be found. This is because on the bundled CLI we need to explicitly copy any asset folder.
- Copy the `data` folder from `theme-check-data-updater` into the final bundled `dist` folder.
> [stable] Include `theme-check-docs-updater` data folder in final bundled dist

- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook.test.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook_schemas/webhook_subscription_schema.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook_subscription.test.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook_subscription.ts
- packages/app/src/cli/models/extensions/specifications/types/app_config_webhook.ts
- packages/app/src/cli/models/extensions/specifications/validation/app_config_webhook.ts
We need to add filters to declarative webhooks for the [customizable filters project](https://vault.shopify.io/gsd/projects/38737).
The PR adds an optional filter value to the webhook subscription configuration.  The filter is treated as a uniqueness constraint on the subscription (i.e. you can't have two subscriptions with the same uri/topic/filter) and performs grouping on the field.  Used the existing includeFields/subTopics as reference for these changes.
- Tested against https://github.com/Shopify/shopify/pull/504278
- Created an app with the following webhooks configuration in the TOML file
```
[webhooks]
api_version = "2024-04"
[[webhooks.subscriptions]]
topics = [ "products/update" ]
uri = "https://shopify.com/7bf98a69-f616-49d9-a7b1-868d58deafbc"
filter = "field:value"
```
Ran …
> Add filter to webhooks app config

- packages/cli-kit/src/public/node/themes/types.ts
- packages/theme/src/cli/services/dev.test.ts
- packages/theme/src/cli/utilities/asset-ignore.test.ts
- packages/theme/src/cli/utilities/theme-downloader.test.ts
- packages/theme/src/cli/utilities/theme-downloader.ts
- packages/theme/src/cli/utilities/theme-fs.test.ts
- packages/theme/src/cli/utilities/theme-fs.ts
- packages/theme/src/cli/utilities/theme-fs/theme-fs-mock-factory.ts
**WHY are these changes introduced?**
- Mise en place for adding polling for theme editor changes in the `theme dev` command
- Part of https://github.com/Shopify/develop-advanced-edits/issues/203
**WHAT is this pull request doing?**
- Adds `delete` and `write` methods to the `ThemeFileSystem` interface
- replaces the `removeThemeFile` and `writeThemeFile` functions with these new methods
- creates a mockThemeFileSystem fixture function for testing
- updates the tests accordingly
**How to test your changes?**
This is a refactor so no behaviour should change
`pnpm test`
> [Refactor][Themes] Move local disk 'delete' and 'write' operations  behind the ThemeFileSystem interface

- packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client.ts
- packages/cli-kit/src/private/node/api.ts
- packages/cli-kit/src/private/node/session.ts
- packages/cli-kit/src/private/node/session/exchange.test.ts
- packages/cli-kit/src/private/node/session/exchange.ts
- packages/cli-kit/src/private/node/session/identity.ts
- packages/cli-kit/src/private/node/session/scopes.test.ts
- packages/cli-kit/src/private/node/session/scopes.ts
- packages/cli-kit/src/private/node/session/validate.ts
- packages/cli-kit/src/public/node/session.ts
Related to https://github.com/Shopify/develop-app-management/issues/1752
Authenticate against App Management API when `USE_SHOPIFY_DEVELOPERS_CLIENT` is enabled
With and without `USE_SHOPIFY_DEVELOPERS_CLIENT=1`:
- `bin/spin p shopify auth logout`
- `bin/spin p shopify app config link --verbose`
> App Management API authentication

- .changeset/young-lamps-explode.md
- packages/app/src/cli/utilities/developer-platform-client/partners-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
When you create a new `Only extension app` using the CLI, then you modify the `toml` to add some scopes and finally run the `dev` or `deploy` command to create a new remote app, then the `scopes` in the resulting `toml` are empty
- The scopes included in the `toml` are passed to the `CreateApp` mutation either for `launchable` apps or for `only extension apps`
- Create a new `only extension` app with the CLI
- Edit the `toml` to include `scopes = "write_products"`
- Run the `dev` or `deploy` command with `--reset` and create a new remote app
- Check the resulting `toml` and the `scopes = "write_products"` entry should be there
> Create new remote only extension app includes the access scopes

- .changeset/ninety-bottles-whisper.md
- packages/create-app/src/commands/init.ts
- packages/create-app/src/services/init.ts
Closes https://github.com/Shopify/develop-app-management/issues/1786
After cloning an app template, lock files are removed from .gitignore, provided one of our built-in templates was used. If you used a custom url we assume you know what you're doing.
`pnpm create-app --path="<somewhere>"` will exercise this
> Remove lock files from .gitignore after app init

- .changeset/tough-rings-dress.md
- packages/app/src/cli/api/graphql/convert_dev_to_transfer_disabled_store.ts
- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/prompts/dev.ts
- packages/app/src/cli/services/context.test.ts
- packages/app/src/cli/services/context.ts
- packages/app/src/cli/services/dev/select-store.test.ts
- packages/app/src/cli/services/dev/select-store.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
- packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client.ts
- packages/cli-kit/src/private/node/ui/utilities.ts
Closes https://github.com/Shopify/develop-app-management/issues/1785 
In the usual place where a dev store is selected, prompt prior to converting it to transfer-disabled (where that is required). The user can choose to select a different store if needed.
Internal video: https://share.descript.com/view/QtyPwXjPLEu (has a small snag which is corrected now)
- Create a dev store on partners. Choose the left-hand option, not the "I want to test apps" option. Give it a minute or so to become real, and follow the login prompt partners will send you to.
- Run `p shopify app dev --reset` and select that store.
- See the new warning
> Prompt to convert dev stores to transfer-disabled

- packages/app/src/cli/api/graphql/get_versions_list.ts
- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/services/context/breakdown-extensions.test.ts
- packages/app/src/cli/services/context/breakdown-extensions.ts
- packages/app/src/cli/services/release.test.ts
- packages/app/src/cli/services/release.ts
- packages/app/src/cli/services/release/version-diff.test.ts
- packages/app/src/cli/services/release/version-diff.ts
- packages/app/src/cli/services/versions-list.test.ts
- packages/app/src/cli/services/versions-list.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
- packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client.ts
- packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client/graphql/app-version-by-id.ts
- packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client/graphql/app-version-by-tag.ts
- packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client/graphql/app-versions.ts
- packages/app/src/cli/utilities/developer-platform-client/shopify-developers-client/graphql/release-version.ts
Filling out more commands
Adds ShopifyDevelopersClient support for `app versions list` and `app release`.
Note that, since a version diffing query is unavailable, we have implemented a simple local diffing strategy which is essentially the same as what's going on behind the scenes anyway.
Also note that some data (e.g. created at date) has been stubbed out for now, since it is not available in the prototype API but should be available in the production API.
These screenshots should give a general picture of the situation:
`app versions list`
`app release` (showing diffs of adding + removing)
On prototype, run `app versions list` and `app release`
> `app versions list` and `app release`

- packages/cli-kit/src/public/node/http.ts
- packages/theme/src/cli/services/dev.test.ts
- packages/theme/src/cli/services/dev.ts
- packages/theme/src/cli/utilities/theme-environment/cookies.test.ts
- packages/theme/src/cli/utilities/theme-environment/cookies.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-renderer.test.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-renderer.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-session.test.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-session.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-utils.test.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-utils.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.ts
- packages/theme/src/cli/utilities/theme-environment/types.ts
Fixes https://github.com/Shopify/develop-advanced-edits/issues/210
This PR introduces the module that remotely renders storefronts and will power part of the `shopify theme dev` logic.
The public API introduced by this PR is:
```ts
render(session, renderContext)
```
Internally, the way it works is:
- `theme-environment/storefront-renderer.ts` - handles the rendering logic. It ensures that the request to render is authenticated, the session is refreshed*, and the required headers are being passed
- `theme-environment/storefront-session.ts` - handles the session/cookies creation to make sure the renderer is rendering the proper development theme with replace-templates capabilities
\* This will be introduced in a following PR
This is an internal module and will be exposed by the proxy, so we …
> Introduce new remote renderer for `shopify theme dev`

- .changeset/dirty-weeks-end.md
- packages/app/src/cli/models/extensions/schemas.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.ts
Fixes https://github.com/Shopify/core-issues/issues/70722
Homogenizing the terminology to "placement" instead of "placement_reference" et al.
Just renames the key used by developers. This is an unreleased feature (not yet enabled in core), so we want to get the terminology correct before release. Does not rename the values passed on to core.
The process is to have a local copy of CLI point at an spin instance, and then to deploy a locally developed ui extension on that instance.
- use my instance "rename-default-placement-3"
```
SHOPIFY_CLI_1P_DEV=1 SPIN_INSTANCE=rename-default-placement-3 SHOPIFY_SERVICE_ENV=spin pnpm create @shopify/app 
```
In the new app directory:
```
SPIN_INSTANCE=rename-default-placement-3 SHOPIFY_SERVICE_ENV=spin pnpm shopify app generate extension 
```
Configure …
> Renames default_placement_reference extension toml property to default_placement

- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/extensions/specification.ts
- packages/app/src/cli/models/extensions/specifications/app_config_privacy_compliance_webhooks.test.ts
- packages/app/src/cli/models/extensions/specifications/app_config_privacy_compliance_webhooks.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook.test.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook_schemas/webhooks_schema.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook_subscription.test.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook_subscription.ts
- packages/app/src/cli/models/extensions/specifications/transform/app_config_webhook.test.ts
- packages/app/src/cli/models/extensions/specifications/transform/app_config_webhook.ts
- packages/app/src/cli/services/app/config/link.ts
- packages/app/src/cli/services/app/select-app.ts
Fixes https://github.com/Shopify/develop-app-management/issues/1792
There are two ways of defining webhooks in the toml:
- Condensed: multiple topics in the same subscription definition (sharing the same URI)
- Expanded: each subscription has only 1 topic
When linking to a new app we need to default to the condensed state, but right now we are doing expanded.
- Remove the `simplify` function from the specification
- Update the webhook reverse transform to transform from expanded to condensed.
- Add an additional transform to the `link` command to further condense webhooks
See the description in this [issue](https://github.com/Shopify/develop-app-management/issues/1792)
> Fix webhook link logic

- packages/app/src/cli/api/graphql/subscribe_to_app_logs.ts
- packages/app/src/cli/constants.ts
- packages/app/src/cli/services/app-logs/poll-app-logs.test.ts
- packages/app/src/cli/services/app-logs/poll-app-logs.ts
- packages/app/src/cli/services/app-logs/write-app-logs.test.ts
- packages/app/src/cli/services/app-logs/write-app-logs.ts
- packages/app/src/cli/services/dev/processes/app-logs-polling.ts
- packages/app/src/cli/services/dev/processes/setup-dev-processes.test.ts
- packages/app/src/cli/services/dev/processes/setup-dev-processes.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
- packages/cli-kit/src/private/node/constants.ts
- packages/cli-kit/src/public/node/logs.ts
For https://github.com/Shopify/shopify-functions/issues/118
Adds log polling to the app dev command.
This listens for functionRuns 
- Have a dev store with your app installed and function deployed
- enable log polling flag on partners org
- set local envVar to enable the log polling, `export SHOPIFY_CLI_ENABLE_APP_LOG_POLLING=1`
- From the cli directory, run app dev, i.e. `pnpm shopify app dev --path /Users/lopert/code/log-streaming/app/log-streamer`
> Add log polling to `dev` command

- packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx
Fixed a wrapping issue introduced in `ConcurrentOutput` in #3797
> add a root <Text> element to log files to fix wrapping

- .changeset/cuddly-starfishes-tickle.md
- packages/cli-kit/src/private/node/api/headers.ts
- packages/cli-kit/src/public/node/base-command.ts
Unhandled errors are shown twice:
- Sets the flag `skipOclifErrorHandling` to [prevent Oclif from printing the error](https://github.com/oclif/core/blob/63b6e59204718f8871f0d05e1a493777476886d0/src/errors/handle.ts#L35), which is already shown by the CLI
- Skips the stacktrace for API errors, which is not useful (it always points to the code where the request is made)
- Edit `packages/cli/src/cli/commands/version.ts` and add `throw new Error('Boom!')` at the beginning of `run()`
- `p shopify version`
> Fix the output for unhandled errors

- packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx
> add a root <Text> element to log files to fix wrapping (3.61 patch)

- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook.test.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook_schemas/webhook_subscription_schema.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook_subscription.test.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook_subscription.ts
- packages/app/src/cli/models/extensions/specifications/transform/app_config_webhook.ts
- packages/app/src/cli/models/extensions/specifications/types/app_config_webhook.ts
- packages/app/src/cli/models/extensions/specifications/validation/app_config_webhook.ts
Subtopics are being deprecated in favor of filters.
Removing subtopic references from the CLI.
Ran `SHOPIFY_SERVICE_ENV=spin NODE_TLS_REJECT_UNAUTHORIZED=0 pnpm shopify app deploy --path ./test-filter-app`
Confirmed subTopic isn't set in the distributed app module:
For TOML with these webhooks:
```
[webhooks]
api_version = "2024-04"
[[webhooks.subscriptions]]
topics = [ "products/update" ]
uri = "https://webhook.site/848d85d1-d86f-4d7e-b412-59465aa69d43"
sub_topic = "type:color-swatch"
filter = "type:color-swatch"
```
> Remove subtopic from webhooks app config

- packages/cli-kit/src/private/node/session/scopes.test.ts
- packages/cli-kit/src/private/node/session/scopes.ts
To avoid issues like:
- https://github.com/Shopify/cli/issues/3962
- https://github.com/Shopify/cli/issues/3963
Only request App Management scope when `USE_APP_MANAGEMENT_API` is present
- `p shopify auth logout`
- `p shopify app generate extension --path /your-app --verbose`
- `USE_APP_MANAGEMENT_API=1 p shopify app generate extension --path /your-app --verbose`
> Only request App Management scope when needed

- packages/app/src/cli/services/dev/ui/components/Dev.test.tsx
- packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.test.tsx
- packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx
- packages/cli-kit/src/public/node/ui.tsx
Implement some UX feedback to reduce required eye travel in CLI output.
> Right align 2nd column in ConcurrentOutput

- .changeset/metal-chefs-yell.md
- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/app/loader.ts
Fixes https://github.com/Shopify/app-ui/issues/1192
Updating the error message shown when dev'ing or deploying multiple print extensions with the same target. Also updated to use the handle rather than app name as it is unique.
Before: 
After:
1. Have an app with multiple print extensions for the same target ([wiki](https://github.com/Shopify/app-ui/wiki/print-extensions))
2. From this repo, run `cli-spin pnpm shopify app dev --path ../to-your-app`
3. Assert that you see the expected message.
> Update duplicate print action message

- packages/app/src/cli/services/app-logs/poll-app-logs.test.ts
- packages/app/src/cli/services/app-logs/poll-app-logs.ts
Fixes https://github.com/Shopify/shopify-functions/issues/222
Currently dev is set to ignore all non-function logs, which filters out the throttle event being sent.
Instead of ignoring those logs, it just prints out the log's payload as prettified JSON.
🎩 
- Ran [a chronograma tes](https://cronograma.shopify.io/tests/38351)t to spam a test shop with huge logs
- Ran a dev session in my terminal for that shop and app
- Received the throttle log once the throttle was hit, once for each request that occurred after the throttle was hit:
```
/Users/duncanuszkay/Library/Logs/shopify-cli-nodejs/38a85423c1f66c3123ed92fa74fea697/app_logs_2024-06-06T17:47:14.100110Z.json
13:47:15 │ app-logs   │ ❌ Function failed to execute with error: InputSizeLimitExceededError
13:47:15 │ app-logs   │ Log: …
```
> Print non-function log payloads directly to the terminal

- packages/app/src/cli/services/app-logs/poll-app-logs.test.ts
- packages/app/src/cli/services/app-logs/poll-app-logs.ts
Fixes https://github.com/Shopify/shopify-functions/issues/206
In the event of a 429 or 5XX error, enqueues another attempt at polling.
This prevents `dev` from crashing whenever there's a server error, and also allows the server time to recover instead of continuing to poll with the regular frequency.
Set the app logs controller in partners to always return an error during polling. You can even do this while polling to see different error messages / handling.
My 🎩 
> Retry app log polling after 429 or 5XX

- packages/app/src/cli/api/graphql/extension_specifications.ts
- packages/app/src/cli/services/generate/fetch-extension-specifications.ts
- packages/app/src/cli/utilities/json-schema.ts
- packages/cli-kit/package.json
- packages/cli-kit/src/public/node/json-schema.test.ts
- packages/cli-kit/src/public/node/json-schema.ts
- pnpm-lock.yaml
Connects the new JSON Schema contracts feature to the CLI
1. Updates specification loading to include pulling in and using JSON schema contracts
2. Normalises contracts: in particular, we would rather have less `$ref` usage in the schema, as it makes remapping errors harder. We dereference them here. There's zero functional or behavioural difference in the validation afterward (AJV was already dereferencing, just silently)
3. Added a layer of defence to error remapping
With flag enabled, add
```
[metaobjects.author.fields]
not_good = true
```
to an app and running deploy should do it.
> Connect JSON schema contracts to CLI

- packages/app/src/cli/services/app-logs/poll-app-logs.test.ts
- packages/app/src/cli/services/app-logs/poll-app-logs.ts
- packages/app/src/cli/services/app-logs/write-app-logs.test.ts
- packages/app/src/cli/services/app-logs/write-app-logs.ts
- packages/cli-kit/src/private/node/content-tokens.test.ts
- packages/cli-kit/src/private/node/content-tokens.ts
- packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.test.tsx
- packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx
- packages/cli-kit/src/public/node/output.ts
Multiple runs of the same function run together visually:
Additionally, the log file path is a bit long and frequently wraps, limiting its usefulness.
* Prefix function log output with box drawing characters, to better group related lines.
* Output function log file as a link instead of a file path, on terminals that support hyperlinks.
_VS Code_
_MacOS Terminal (no hyperlink support)_
_Windows Terminal (hyperlink disabled by default in `supports-hyperlink`_
_Windows Terminal w/ hyperlinks forced_
* Allow hyperlink tokens to provide an explicit fallback value.
* Added a `gray` coloring output token.
* Allow disabling of ansi stripping in `ConcurrentOutput` via `useConcurrentOutputContext`.
Run `app dev` in an app w/ functions and function log streaming enabled. Execute the function.
> Function log differentiation and file linking

- packages/app/src/cli/services/app-logs/poll-app-logs.test.ts
- packages/app/src/cli/services/app-logs/poll-app-logs.ts
Fixes https://github.com/Shopify/script-editor/issues/4145
Changes the behaviour when we encounter an unexpected error.
Previously, we would catch the error and stop the polling.
Now, we always enqueue another polling attempt regardless of the error.
- run dev targetting your spin instance
- change partners app logs controller to return various errors, i.e.
```ruby
return render json: { errors: ['some text'] }, status: 422
```
> Handle transient failures during app log polling

- .github/actions/run-and-save-test-coverage/action.yml
- .github/workflows/checks.yml
- .github/workflows/shopify-cli.yml
Fixes an issue where a failing CI run doesn't output the reason for the failure. What's happening is nx holds off from outputting what happens with a task for as long as it can -- then when the task completes (in failure in this case) it outputs a huge amount in one go and exits with a 1. Github actions ends the job before this huge output has flushed.
Uses nx's `--output-style=stream` option on CI jobs that are doing `run-many`. This output style means nx doesn't buffer any output.
The downside of this is that nx does try to pretend that the tasks being run happened sequentially -- app's test results all together, cli-kit's all together -- but the reality is messier as they are run interleaved. That's what's shown in the output.
It's a CI change, but you can look at the github actions …
> For github actions, prefer streamed NX output

- packages/app/src/cli/api/graphql/app_deploy.ts
- packages/app/src/cli/services/deploy/upload.test.ts
- packages/app/src/cli/services/deploy/upload.ts
Fixes https://github.com/Shopify/develop-app-inner-loop/issues/1819
Validation errors for webhook subscriptions include a useless ramdom ID (the remote title):
Show `Webhook Subscription` as the title for webhook subscription errros.
Add a webhook subscription with an invalid topic and deploy
> Fix the error title for invalid webhook subscriptions

- packages/app/src/cli/services/info.ts
- packages/cli-kit/src/private/node/conf-store.ts
- packages/cli-kit/src/public/node/node-package-manager.test.ts
- packages/cli-kit/src/public/node/node-package-manager.ts
- packages/cli/src/cli/services/commands/version.ts
`shopify version` should be fast. Checking for a new version makes it slower. We should do this a max of once daily.
Limits checks to once daily, otherwise we use the cached value.
`p shopify:run version` should become faster. No wait between displaying current local version and latest version on npm.
> Cache CLI package version

- packages/cli-kit/src/public/node/node-package-manager.test.ts
- packages/cli-kit/src/public/node/node-package-manager.ts
- packages/cli/src/cli/services/upgrade.test.ts
Fixes #4028 
This is necessary for handling monorepos correctly.
The existing mechanism finds the closest `package.json` file and determines the package manager for that directory.
With these changes, we use `npm prefix` to find the project root, then look for `package.json` and a lockfile in that directory.
If we fail to find a lockfile at any point, we still default to `npm`.
Create a monorepo with pnpm, and create a workspace inside it with a Shopify app.
Running commands inside the app, the package manager should be detected correctly.
> Search for lockfile in project root to identify package manager in workspaces

- packages/app/src/cli/models/extensions/specifications/app_config_privacy_compliance_webhooks.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook_subscription.test.ts
- packages/app/src/cli/models/extensions/specifications/validation/common.ts
- packages/app/src/cli/services/app/config/link.test.ts
- packages/app/src/cli/services/app/write-app-configuration-file.ts
This reverts commit 35b85e277c256239a08458867ab8504a3ed33715.
We are going with relative paths for the time being 🔁 😄 
More details in https://github.com/Shopify/develop-app-inner-loop/issues/1599
> relative path declarative webhooks

- packages/app/src/cli/services/dev/processes/setup-dev-processes.test.ts
- packages/app/src/cli/services/dev/processes/setup-dev-processes.ts
Fixes https://github.com/Shopify/shopify-functions/issues/253
We only send app logs for function related events at the moment, so to save resources we will only poll if the user has a function.
> Only poll when app has functions

- .vscode/settings.json
- packages/app/src/cli/models/app/app.ts
Related to https://github.com/Shopify/develop-app-inner-loop/issues/1504
We are adding declarative webhooks to the templates in https://github.com/Shopify/shopify-app-template-remix/pull/743 and https://github.com/Shopify/shopify-app-template-ruby/pull/131, but it's failing because not a valid schema in the CLI.
The templates include a very simple legacy app schema, and then the CLI transforms it to the new schema when linking. But the legacy schema doesn't support webhooks, so I'm adding it here to be able to load the app.
- `p shopify app init --template=https://github.com/Shopify/shopify-app-template-remix#declarative-webhooks`
- `p shopify app init --template=https://github.com/Shopify/shopify-app-template-ruby#declarative-webhooks`
How do we know this change was effective? Please …
> Allow declarative webhooks template

- packages/theme/src/cli/commands/theme/dev.ts
- packages/theme/src/cli/services/dev.test.ts
- packages/theme/src/cli/services/dev.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.ts
- packages/theme/src/cli/utilities/theme-environment/types.ts
- https://github.com/Shopify/develop-advanced-edits/issues/205
Plumbing work for starting the development server 
This doesn't do anything yet but you can `p test`
> Pass Development Server flags down to theme environment

- configurations/vite.config.ts
See also https://github.com/Shopify/cli/pull/4082
Extends the test timeout for MacOS on CI/CD
> Extend the test timeout for MacOS CI runs

- packages/app/src/cli/models/extensions/specifications/flow_template.ts
With the existing flow template extension schema we were just checking that the category was there and it's an array of strings. This leaves the validation of whether the categories in the array are valid up to the reviewer _after_ the template extension had been deployed. This is not great for bother the reviewer and the template author.
Adds another layer of validation to the schema to check if the categories in the array are in fact valid
Local test: https://screenshot.click/19-38-0xvyn-gvwpr.mp4
None
> feat: Add flow template category validation

- packages/app/src/cli/models/extensions/specifications/flow_template.ts
Follow up to https://github.com/Shopify/cli/pull/4093 just adding an additional category group that's used by the Flow team.
Adds secondary array of valid template categories. Error will print out categories minus the ones used by the flow team.
> fix: add flow team custom categories

- packages/app/src/cli/services/app-logs/dev/poll-app-logs.test.ts
- packages/app/src/cli/services/app-logs/dev/poll-app-logs.ts
- packages/app/src/cli/services/app-logs/utils.ts
This PR addresses [issue #133](https://github.com/Shopify/functions-externals-project/issues/133) by adding function network access events to the app logs within the dev command. Additionally, it includes export to the function run log message, which aids in understanding multi-target functions, particularly those using external calls.
- **Triggered:** When a response is retrieved from the cache.
- **Frequency:** This will be the most frequently emitted event.
- **Triggered:** When a request is being executed in the background.
- **Possible Reasons:**
- A cache miss within async calls (`reason = no_cached_response`).
- A cached response that is about to expire, necessitating a background refresh for future calls (`reason = cached_response_about_to_expire`).
- **Triggered:** When an actual …
> [App Logs] Function network access events

- packages/app/src/cli/services/context/breakdown-extensions.test.ts
- packages/app/src/cli/services/context/breakdown-extensions.ts
As we suspected, the relative URI shows up in the baseline config when doing the deploy diff. This prepends the app url before we do the diff check. This is all temporary until we move this logic to the server.
closes: https://github.com/Shopify/develop-app-inner-loop/issues/1837
> fix deploy diff for relative declarative webhooks

- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/base_payments_app_extension_schema.test.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/base_payments_app_extension_schema.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/credit_card_payments_app_extension_schema.test.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/custom_credit_card_payments_app_extension_schema.test.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/custom_onsite_payments_app_extension_schema.test.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/offsite_payments_app_extension_schema.test.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/redeemable_payments_app_extension_schema.test.ts
* Modified the `supported_buyer_context` schema to either allow an array of currency definitions, or an array of currency plus countries. A mixture of the two is no longer allowed.
* Use `refine` to give a user friendly error message.
```
pnpm shopify app init --name test --template none
pnpm shopify app generate extension --path test --name "Offsite Payment Extension" --template offsite_payments
```
Edit `test/extensions/offsite-payment-extension/shopify.extension.toml` with your test configuration, e.g.
```
[[extensions.supported_buyer_contexts]]
currency = "USD"
[[extensions.supported_buyer_contexts]]
currency = "CAD"
countries = ["CA"]
```
Then trigger the validation:
```
pnpm shopify app build --path test
```
<details>
<summary>✅ Validation passes when only using currency …
> supported buyer context: disallow mixed definition types

- packages/app/src/cli/services/context/identifiers-extensions.test.ts
- packages/app/src/cli/services/context/identifiers-extensions.ts
Fixes https://github.com/Shopify/cli/issues/4139
When running dev with declarative webhooks and relative paths, we are comparing the URLs with the server ones, which are absolute, so we are finally creating new extensions every time. They are only removed on deploy and there's a limit of 100 that can be reached if running dev multiple times. After reaching it, the server returns an error.
Related to changes in https://github.com/Shopify/cli/pull/3710 and https://github.com/Shopify/cli/pull/3846
Only deploy draftable extensions when running dev.
`p shopify app dev --verbose` and check if it's creating a  WEBHOOK_SUBSCRIPTION extension
> Avoid deploying draft webhook extensions on dev

- .changeset/warm-chicken-sin.md
- packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/file.rb
- packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/theme_test.rb
This PR updates the checksum calculation to avoid loops in when users run the `shopify theme dev --theme-editor-sync`, as before the values were never matching.
In the past, we introduced a visitor that was adding the `settings` key locally as the platform auto adds them ([context](https://github.com/Shopify/shopify-cli/commit/6d79724ca5a6516bf47e654feed98c61b668582f)):
That was a great, as we were avoiding unnecessary uploads when templates were only missing the `settings` key. However, now that we support themes blocks, that also have settings and may be deeply nested, that convenience is not longer ideal and keeping up locally may generate erratic behaviour.
Thus, this PR removes the visitor, and fixes the loop scenario that some users were facing with the `--theme-editor-sync` flag. …
> Avoid loop when users pass the `--theme-editor-sync` flag in the `shopify theme dev` command

- .changeset/metal-bikes-smell.md
- packages/app/src/cli/services/context/identifiers-extensions.test.ts
- packages/app/src/cli/services/context/identifiers-extensions.ts
The backend always returns an absolute path, but the CLI might only have relative ones.
Use `endsWith` to compare relative and absolute URIs
> [stable] Match webhooks by comparing relative and absolute paths

- bin/bundling/esbuild-plugin-dedup-cli-kit.js
- packages/cli/bin/bundle.js
Since `cli-hydrogen` is an external dependency that at the same time depends on `cli-kit` which exists in this repo, it creates a weird dependency tree that eventually causes esbuild to bundle 2 identical copies of `cli-kit`
Fixes #0000 
- Add a new ESBuild plugin to dedup `cli-kit` when bundling.
See the snapshot in the comments, if you install that and try any app and hydrogen command, everything should work.
> Dedup cli-kit when bundling hydrogen

- packages/ui-extensions-dev-console/src/sections/Extensions/components/ExtensionRow/ExtensionRow.tsx
- packages/ui-extensions-dev-console/src/sections/Extensions/components/ExtensionRow/components/PreviewLinks/PreviewLinks.tsx
- packages/ui-extensions-dev-console/src/sections/Extensions/components/PreviewLink/PreviewLink.module.scss
- packages/ui-extensions-dev-console/src/sections/Extensions/components/PreviewLink/PreviewLink.tsx
- packages/ui-extensions-dev-console/src/sections/Extensions/components/Row/Row.module.scss
- packages/ui-extensions-dev-console/src/sections/Extensions/hooks/useExtension.ts
See https://hackdays.shopify.io/projects/18849
See project and commits for details
[Remove broken links for pos-ui extensions](https://github.com/Shopify/cli/pull/4137/commits/55cc7a5e802bcf1b76b4d89f743e8019c57b4fe1)
1. Create a POS ui extension
2. Run `dev` and open the dev console. 
3. Assert that the POS UI extensions are displayed without links (other than the mobile QR code)
[Fix cursor and capitalization styles](https://github.com/Shopify/cli/pull/4137/commits/cabcb509e7bffffef36fa2666f53e8a75c6de970)
1. Create some extensions
2. Run `dev` and open the dev console. 
3. Assert that extension targets are not capitalized, and that only clickable links show the pointer cursor.
[Remove unused show/hide methods](https://github.com/Shopify/cli/pull/4137/commits/958ce5171058ae4bac3b97d3b348 …
> Hackdays dev console overhaul

- packages/app/src/cli/services/app-logs/logs-command/ui/components/Logs.test.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/Logs.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.test.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.ts
- packages/app/src/cli/services/app-logs/types.ts
- packages/app/src/cli/services/app-logs/utils.ts
This PR adds support of [function network access](https://shopify.dev/docs/apps/build/functions/input-output/network-access) within the app logs command:
- Add the export to the function run events description
- Add the function network access [events](https://github.com/Shopify/functions-externals-project/issues/133)
1. **Deploy a Function with Network Access:**
- Use the following command to add a pickup point function that has network access:
```sh
shopify app generate extension --template pickup_point_delivery_option_generator --name pickup-points-generator
```
- Follow the instructions in the extension README for enabling and testing pickup points.
2. **Verify Network Access Events:**
- Run the logs command  
```sh 
SHOPIFY_CLI_ENABLE_APP_LOG_POLLING=1  pnpm shopify app logs --path …
```
> [App logs streaming] Add function network access events to the app logs cmd

- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/services/deploy/bundle.test.ts
- packages/app/src/cli/services/deploy/bundle.ts
Fixes https://github.com/Shopify/develop-app-inner-loop/issues/1849
The deploy command generates a manifest with all the extensions content and includes it in the bundle to upload
Part of the work extracted from https://github.com/Shopify/cli/pull/4101
- Replace the `tmpDir` [here](https://github.com/Shopify/cli/compare/manifest-api?expand=1#diff-02c8891dbc51e66a73680b8d021fcfa80d34576835781908282434eaba6e9920R20) to `/tmp` to be able to check generated the bundle
- Generate some extensions and run `USE_APP_MANAGEMENT_API=1 bin/spin p shopify app deploy` 
- `cat /tmp/bundle/manifest.json`
> Deploy app manifest

- packages/app/src/cli/commands/app/config/use.ts
- When running `app config use`, the user wants to change the current active configuration
- For this, we were loading the current active configuration first, to validate that this is a valid app, and then do the switch
- This caused issues when the current configuration is not valid, but it shouldn't prevent you from changing to a new one!
- Don't load the current active configuration on `app config use`
- Just validate that the current path is an app folder.
From `main` or a released version:
- Create an app
- `app config link`
- Duplicate the toml with a different name `shopify.app.new-config.toml`
- Remote the `application_url` field from the first toml
- Run `app config use new-config`
- It should crash.
Now, from this branch, do the same, it should work.
How do we know this change …
> Don't load the old app config when running app config use

- packages/app/src/cli/services/function/common.test.ts
- packages/app/src/cli/services/function/common.ts
If a function command is run outside of a function directory, the command simply fails. As an improvement to the UX, we should prompt the user to choose which function they'd like to run the command on.
Closes https://github.com/Shopify/shopify-functions/issues/229
This PR adds a prompt if the CLI is in an interactive terminal so that the user can choose the function to run a function command on (if they're not in a function directory).
Run a function command (e.g. `function run`) outside of a function directory with an interactive terminal
> Show prompt when running function command outside of function directory

- docs-shopify.dev/commands/interfaces/theme-console.interface.ts
- docs-shopify.dev/generated/generated_docs_data.json
- packages/cli/README.md
- packages/cli/oclif.manifest.json
- packages/theme/src/cli/commands/theme/console.ts
- packages/theme/src/cli/services/console.test.ts
- packages/theme/src/cli/services/console.ts
- packages/theme/src/cli/utilities/prompts.test.ts
- packages/theme/src/cli/utilities/prompts.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-session.test.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-session.ts
- Part of https://github.com/Shopify/develop-advanced-edits/issues/257
```mermaid
graph LR
A[Start] --> B{Is the storefront password protected?}
B -- No --> I[End]
B -- Yes --> D{Is the --store-password flag provided?}
D -- No --> E[Prompt the user for a password]
D -- Yes --> F[Validate the provided --store-password flag]
E --> G[Validate the prompted password]
F --> H{Is the password valid?}
G --> H{Is the password valid?}
H -- Yes --> I[End]
H -- No --> E[Prompt the user for a password]
```
1. Ensure your storefront is password protected via the admin
2. `pnpm shopify theme console --dev-preview`
3. You should see a password prompt
a. Enter a couple of incorrect passwords, then the correct one
4. `pnpm shopify theme console --dev-preview --store-password=<PASSWORD>`
a. Try with some …
> [Themes] Theme Console - ensureReplEnv 1/2 - Storefront Password Prompting

- packages/cli-kit/src/public/node/themes/theme-manager.ts
- packages/theme/src/cli/commands/theme/console.ts
- packages/theme/src/cli/services/console.test.ts
- packages/theme/src/cli/services/console.ts
- packages/theme/src/cli/services/local-storage.ts
- packages/theme/src/cli/utilities/repl-theme-manager.test.ts
- packages/theme/src/cli/utilities/repl-theme-manager.ts
- Part 2/2 of https://github.com/Shopify/develop-advanced-edits/issues/257
- https://github.com/Shopify/develop-advanced-edits/issues/264
- Initializes a REPL theme when executing the `shopify theme console` command
<details><summary><h4>Test Theme Creation</h4></summary>
1) `shopify theme list` and verify that you don't have an existing `REPL theme`. If you do, delete it using `shopify theme delete -t <THEME_ID>`
2) `pnpm shopify theme console --dev-preview` and validate that a theme has been created
3) `shopify theme list` should now show a theme with the development role following the naming pattern `Liquid Console (<CLI_VERSION>)`
</details> 
<details><summary><h4>Test Theme Fetching</h4></summary>
1) Run `pnpm shopify theme console --dev-preview` again
2) `shopify theme list` should …
> [Themes] Theme Console - ensureReplEnv 2/2 - REPL Theme Creation

- packages/cli-kit/src/private/node/content-tokens.ts
- packages/cli-kit/src/private/node/session/device-authorization.test.ts
- packages/cli-kit/src/private/node/session/device-authorization.ts
- packages/cli-kit/src/public/node/output.ts
- packages/cli-kit/src/public/node/ui.tsx
Recently we switched to device auth by default, which has added some friction to login. This restores the simplicity of pressing any key to log in.
Before:
After:
We only use this flow in non-cloud TTY environments.
Logout and do anything that requires login, e.g. `config link`
> Add press-key-to-login to device auth flow

- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/services/app/config/link-service.test.ts
- packages/app/src/cli/services/app/config/link.test.ts
- packages/app/src/cli/services/app/config/link.ts
- packages/app/src/cli/services/app/fetch-app-from-config-or-select.ts
- packages/app/src/cli/services/app/write-app-configuration-file.test.ts
- packages/app/src/cli/services/app/write-app-configuration-file.ts
- packages/app/src/cli/services/context.test.ts
- packages/app/src/cli/services/context.ts
- packages/app/src/cli/services/deploy.test.ts
- packages/app/src/cli/services/deploy.ts
- packages/app/src/cli/services/deploy/upload.test.ts
- packages/app/src/cli/services/deploy/upload.ts
- packages/app/src/cli/services/local-storage.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client/graphql/active-app-release.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client/graphql/create-app.ts
Currently App Management is storing app ID in the place where API key should go, leading to a lot of general weirdness. It also breaks certain functional things.
Stores both the app ID and the API key in the app TOML. This is not ideal, and we should eventually replace it with API key only, especially given that we allow passing an API key as a flag for many commands.
1. `config link`-ing an app to App Management adds `app_id` to the app TOML
2. `config link`-ing an app to Partners doesn't change
3. `USE_APP_MANAGEMENT_API=1 bin/spin pnpm shopify app info --web-env --path /path/to/your/app` works and displays API key and secret
> Store API key and app ID

- .changeset/breezy-clouds-shave.md
- packages/app/src/cli/models/extensions/specifications/theme.ts
- packages/app/src/cli/services/dev/extension/server/middlewares.ts
- packages/cli-kit/assets/cli-ruby/lib/project_types/extension/models/specification_handlers/theme_app_extension.rb
Resolves #3893 
Adds `.wasm` asset support to theme app extensions. Another PR has already been shipped to enable this upstream
* Create a new app with a theme app extension
* Add a .wasm file in the assets folder
* Run the app dev command
* Notice the theme app extension is pushed as expected
None
> Add wasm asset support for theme app extensions

- packages/app/src/cli/models/extensions/specifications/custom_data.ts
- packages/cli-kit/src/public/node/json-schema.ts
Closes: https://github.com/Shopify/develop-app-inner-loop/issues/1940
We're getting warning messages from the AJV parser regarding union types. The union is considered valid and we want to  mute the warning messages.
Added `{allowUnionTypes: true}` to the AJV object to allow unions.
snuck in: Fixed pluralization on `products`, it should be singular.
Deploy an app and the union warning should be gone.
> Remove warning union messages from AJV parser 

- .changeset/big-donkeys-wink.md
- packages/app/src/cli/services/app/write-app-configuration-file.test.ts
- packages/app/src/cli/services/app/write-app-configuration-file.ts
Fixes https://shopify.zendesk.com/agent/tickets/49319741
Fixes https://github.com/Shopify/shopify-app-template-remix/issues/776#issuecomment-2259887290
The link process rewrites the TOML to transform webhook URIs like `https://example.com/webhooks` to `/webhooks` when the app URL is `https://example.com`.
But when the app URL ends with a slash, like `https://example.com/`, then we were wrongly updating the webhook URI to `webhooks`, causing the deploy validation to fail.
Remove the final slash from the app URL when doing that transformation, so the final result includes the required initial slash.
- Create an app and run link
- Update the `application_url` in the TOML to `https://whatever.com/`
- Add a subscription in the TOML:
```
[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ] …
```
> Fix relative webhooks TOML transformation

- packages/app/src/cli/commands/app/logs.ts
- packages/app/src/cli/services/app-logs/dev/poll-app-logs.test.ts
- packages/app/src/cli/services/app-logs/dev/poll-app-logs.ts
- packages/app/src/cli/services/app-logs/logs-command/render-json-logs.test.ts
- packages/app/src/cli/services/app-logs/logs-command/render-json-logs.ts
- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.test.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.ts
- packages/app/src/cli/services/app-logs/utils.ts
- packages/app/src/cli/services/context.test.ts
- packages/app/src/cli/services/context.ts
- packages/app/src/cli/services/dev/processes/app-logs-polling.ts
- packages/app/src/cli/services/logs.test.ts
- packages/app/src/cli/services/logs.ts
- packages/cli/README.md
- packages/cli/oclif.manifest.json
Fixes https://github.com/Shopify/shopify-functions/issues/297
We need to support a `--json` flag for clients looking to plug into logs programatically with `jq` or similar. At the same time, we were reaching a critical mass (3) of poll clients each with their own unique error handling behaviour, and it was time to simplify and refactor them together.
- Adds `--json` flag
- Refactors poll clients to use a shared error handler
- Adds missing tests
Tophatting is required for the three poll clients:
- `pnpm run shopify app dev`
- `pnpm run shopify app logs`
- `pnpm run shopify app logs --json`
For each, we'll need to test both with successful polling and errors returned from partners.
- Need to sync with product on this
> Add --json flag to app logs

- packages/app/src/cli/models/extensions/schemas.ts
closes https://github.com/Shopify/checkout-web/issues/36347
TL;DR - UiExtensions have the ability to parse fields marked as `required`  so long as they have a "default_value`. But only `required` exists on the schema. This would have gone unnoticed as the CheckoutUiExtension CLI settings schema allowed any key to be passed: https://github.com/Shopify/cli/blob/a3dd9e5eb2a91b7fdf255feb33deac777fb76ee0/packages/app/src/cli/models/extensions/extension-specifications/checkout_ui_extension.ts#L10-L14
However in core we validate this, so including `required` necessitates including `default_value`. These keys were not explicitly defined, and the feature has [not rolled out](https://app.shopify.com/services/internal/app_betas/checkout_ui_extensions_settings_expanded_definitions) , so my guess is …
> Add default_value to Settings FieldSchema

- .changeset/chilly-garlics-stare.md
- packages/cli-kit/assets/cli-ruby/lib/shopify_cli/theme/dev_server/proxy.rb
- packages/cli-kit/assets/cli-ruby/test/shopify-cli/theme/dev_server/proxy_test.rb
The `_shopify_essential` may be redefined in the backend with a new theme id. This change ensures the CLI don't use that theme ID and renews the session using the existing workflow defined by the `#secure_session_id` method.
This PR changes the logic in the CLI proxy that renews the `secure_session_id`.
- Run `shopify theme dev --verbose`
- Refresh the browser
- Notice the live theme is no longer rendered
N/A
> Avoid live theme from being set in the `shopify theme dev` session

- packages/app/src/cli/prompts/dev.test.ts
- packages/app/src/cli/prompts/dev.ts
- packages/app/src/cli/services/dev/select-store.test.ts
- packages/app/src/cli/services/dev/select-store.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
Closes https://github.com/Shopify/develop-app-inner-loop/issues/1984
Basically https://github.com/Shopify/develop-app-inner-loop/issues/1899#issuecomment-2249057719, but use this branch instead for step 1 + in the last step, you should see the domain of the stores instead of just the store names
> Show domain for stores list (app management client only)

- .changeset/selfish-turkeys-vanish.md
- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/app/validation/common.ts
- packages/app/src/cli/models/extensions/specifications/validation/common.ts
Fixes https://github.com/Shopify/develop-app-inner-loop/issues/1959
The [url() validation by Zod](https://github.com/colinhacks/zod/blob/821d45b9ed1f3376f3912de15933c92dc926ccbd/src/types.ts#L818) was adding an error message, and then another one was being added by our custom validation, basically to check for HTTPS.
Remove the Zod validation for URL and include that in our custom one, so that we only get one error message.
- Update the `application_url` in the TOML to `wrong`
> Fix URL validation in the app schema

- packages/theme/src/cli/commands/theme/console.ts
- packages/theme/src/cli/services/console.test.ts
- packages/theme/src/cli/services/console.ts
- packages/theme/src/cli/utilities/repl.test.ts
- packages/theme/src/cli/utilities/repl.ts
- packages/theme/src/cli/utilities/repl/evaluater.ts
- packages/theme/src/cli/utilities/repl/presenter.test.ts
- packages/theme/src/cli/utilities/repl/presenter.ts
- https://github.com/Shopify/develop-advanced-edits/issues/259
EDIT - _This has been modified to use `readline` to accept console inputs _
https://github.com/user-attachments/assets/0645b141-be79-4c82-aff9-84797e1fb9fb
1) Checkout the branch
2) `pnpm shopify theme console --dev-preview`
3) Play around with the console. Note that the error messages will change as the evaluator is implemented. (There are also different layers - the shutdown message, which stops the loop (hard to trigger) and the graceful message which catches the error and keeps the loop going.
Some ideas
- Delimiter - `{{ collections.first }}` or `{% x %}`
- Null value - `f`
- Something that will error out - `JSON(`
- Please feel free to suggest more cases!
> [Themes] Theme Console - Handle the REPL lifecycle

- .github/workflows/reviewers-reminder.yml
This reminder is still showing the old handle of the team (@shopify/app-management):
Update it to @Shopify/app-inner-loop 
See [below](https://github.com/Shopify/cli/pull/4286#issuecomment-2275149043)
> Fix App Inner Loop team handle

- .changeset/smart-mugs-love.md
- packages/app/src/cli/services/function/binaries.test.ts
- packages/app/src/cli/services/function/binaries.ts
Fixes bug on Windows where Javy and function-runner binaries are not executing because the file names do not end with `.exe`. Also adds installing and executing both binaries to the test suite.
Javy was not was not running on Windows because the executable did not end in `.exe`.
Adds `.exe` to the Javy and function-runner binary names on Windows.
If you're on Windows, using cmd:
1. Create a Shopify app containing at least one JS Function extension if you do not already have one.
2. `pnpm shopify app build --path <path_to_app>` will perform the initial download of Javy.
3. Verify there are no errors reported.
4. `pnpm shopify app build --path <path_to_app>` will test that it uses the downloaded version of Javy.
5. Verify there are no errors reported.
6. `echo {} | pnpm shopify app function …
> Fix running Javy and function-runner on Windows

- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.test.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.ts
Fixes https://github.com/Shopify/shopify-functions/issues/364
Because React re-renders when a state changes (by reference), every time we received a successful request, we were setting the errors array. We poll roughly twice a second, which meant that we are performing a ton of unnecessary re-renders, causing flickering.
1. Run `app logs`
2. Trigger enough function runs so that your terminal has to scroll
With this change, there should be no flickering and it should be easy to copy your function run output.
> Only reset errors if there are errors

- .changeset/metal-jobs-relax.md
- packages/app/src/cli/services/import-extensions.ts
- There is currently a limit for handles to be 30 chars long
- The process to import flow extensions (or other importable extensions) was using the name of the extension as identifier in the `.env`
- This is OK when the name is less than 30 chars, as the output would be identical to the handle value.
- If the title is longer, then the id in the `.env` file won't match the `handle` and the deploy will fail.
Adjust the value used to store the key in the `.env` file to match the handle.
> Fix handle being too long on flow import

- .changeset/khaki-shirts-taste.md
- packages/plugin-cloudflare/src/install-cloudflared.test.ts
- packages/plugin-cloudflare/src/install-cloudflared.ts
- packages/plugin-cloudflare/src/tunnel.ts
The [latest release from cloudflared](https://github.com/cloudflare/cloudflared/releases/tag/2024.8.2) finally includes the ARM64 version, so we can use it and not require Rosetta anymore.
- Upgrades cloudflared
- Uses the new release for the ARM64 platform
- Removes an error related to Rosetta
- `p shopify app dev`
- `./packages/plugin-cloudflare/bin/cloudflared version` => 2024.8.2
- [Ensure Rosetta is not used](https://thenextweb.com/news/how-to-check-app-running-m1-native-version-on-mac): 
- `./packages/plugin-cloudflare/bin/cloudflared tunnel --url localhost:8080`
- Open the Activity Monitor
- Filter by `cloudflared`
- Check that it shows `Apple` in the `Kind` column
Tested in Mac/Linux/Windows
> Upgrade Cloudflared and use the new release for ARM64

- packages/cli-kit/src/public/node/custom-oclif-loader.ts
Currently, the CLI doesn't detect Hydrogen monorepo on CI because the paths in GitHub actions does not use the organization name, but the repo name twice (`hydrogen/hydrogen`).
> Support Hydrogen monorepo on CI

- packages/app/src/cli/services/import-extensions.ts
- There is currently a limit for handles to be 30 chars long
- The process to import flow extensions (or other importable extensions) was using the name of the extension as identifier in the `.env`
- This is OK when the name is less than 30 chars, as the output would be identical to the handle value.
- If the title is longer, then the id in the `.env` file won't match the `handle` and the deploy will fail.
Adjust the value used to store the key in the `.env` file to match the handle.
> Fix handle being too long on flow import (main)

- .changeset/cuddly-yaks-laugh.md
- docs-shopify.dev/commands/interfaces/theme-console.interface.ts
- docs-shopify.dev/generated/generated_docs_data.json
- packages/cli-kit/src/public/node/http.ts
- packages/cli/README.md
- packages/cli/oclif.manifest.json
- packages/theme/src/cli/commands/theme/console.ts
- packages/theme/src/cli/services/console.test.ts
- packages/theme/src/cli/services/console.ts
- packages/theme/src/cli/services/local-storage.ts
- packages/theme/src/cli/utilities/repl/evaluator.test.ts
- packages/theme/src/cli/utilities/repl/evaluator.ts
- packages/theme/src/cli/utilities/repl/presenter.test.ts
- packages/theme/src/cli/utilities/repl/presenter.ts
- packages/theme/src/cli/utilities/repl/repl-theme-manager.test.ts
- packages/theme/src/cli/utilities/repl/repl-theme-manager.ts
- packages/theme/src/cli/utilities/repl/repl.test.ts
- packages/theme/src/cli/utilities/repl/repl.ts
- packages/theme/src/cli/utilities/repl/storefront-password-prompt.test.ts
- packages/theme/src/cli/utilities/repl/storefront-password-prompt.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-session.test.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-session.ts
- https://github.com/orgs/Shopify/projects/4613/views/62?pane=issue&itemId=69671709
Base branch for the `shopify theme console` TS implementation
- There are more detailed instructions in each of the feature branches that were merged in 
1) Execute the new feature `pnpm shopify theme console --dev-preview`
2) Open an instance of the ruby implementation `shopify theme console`
Evaluate some expressions and look for parity differences
Intentional Differences:
- We return `null` rather than `nil` in TS land  
> [Themes] - Shopify Theme Console

- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
Fixes https://github.com/Shopify/develop-app-inner-loop/issues/2005
Generates the right URL by extracting the version ID from the global ID returned by the backend
- `USE_APP_MANAGEMENT_API=1 p shopify app deploy` 
> Fix version URL shown after deploy for App Management API

- packages/app/src/cli/services/app-logs/logs-command/ui/components/Logs.test.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/Logs.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.test.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.ts
[Ticket](https://github.com/Shopify/shopify-functions/issues/368)
The CLI indentation and space formatting of app run logs for input and output of a function run did not tally up with [the specs](https://docs.google.com/document/d/1R_qB9-n0ahIiEkObNO7_aioWvqByNlJsKHj0_4UrxMA/edit?usp=sharing).
- Adding indentation for log file output. 
- Adding single line space between input and output
- Removing space between `"run" executed in 0.4190` and `M instructions`.
1. Checkout this branch in local, `dev up` and `pnpm install`.
2. Create a functions app in local, install it in your dev store. 
4. Run `pnpm run shopify app logs --path <path to functions app in your local system>` from the cli directory where you have checked out this branch. 
5.  Trigger functions run from your dev store. 
How do …
> Functions_368 Fixing indentation and spacing in app logs cli

- packages/app/src/cli/services/app-logs/logs-command/ui/components/Logs.tsx
Fixes https://github.com/Shopify/shopify-functions/issues/292
Text was being wrapped columnwise in the metadata line of the log, rather than as a unit. 
E.G. it was doing:
```
this is my fu your command ran in 
nction name 9 million instructions
```
Instead of:
```
this is my function name your com
mand ran in 9 million instructions
```
Following the pattern in [this PR](https://github.com/Shopify/cli/pull/3959/files), I added a root text element to instruct ink to wrap these as a single unit.
- Shrink your window, increase your function handle length, or increase text size until the metadata log line does not fit in one line in the terminal
- Run `shopify app logs` and run the function
- The metadata line should wrap as a row, e.g.
```
2024-08-12T18:31:16.747589Z cv Success export "run" …
```
> Add root test element to ensure proper word wrapping

- packages/theme/src/cli/services/local-storage.ts
- packages/theme/src/cli/utilities/repl/storefront-password-prompt.test.ts
- packages/theme/src/cli/utilities/repl/storefront-password-prompt.ts
- https://github.com/Shopify/develop-advanced-edits/issues/276
- Stores the storefront password in local storage so that users don't have to continually provide the password via a flag or text input
- Passwords are stored separately for **each store**
This includes
- Basic storage of valid passwords
- Ability to override the stored value with the `--store-password flag`
- Removal of incorrect or outdated passwords
https://github.com/user-attachments/assets/1ad8752a-a788-40b2-ab1a-de887a51cfdc
**Basic Usage:**
1) Run the command with a correct password
2) Run the command again without providing a password - it should work
**Override Capability:**
3) Override the stored password by using the  `--store-password` flag with an incorrect value
4) You should be prompted to input another password …
> [Themes] Console - Make storefront password storage sticky

- packages/app/src/cli/services/dev/processes/theme-app-extension-next.test.ts
- packages/app/src/cli/services/dev/processes/theme-app-extension-next.ts
- packages/app/src/cli/utilities/host-theme-manager.test.ts
- packages/app/src/cli/utilities/host-theme-manager.ts
- packages/app/src/cli/utilities/host-theme-watcher.test.ts
- packages/app/src/cli/utilities/host-theme-watcher.ts
- packages/cli-kit/src/public/node/themes/api.ts
- packages/cli-kit/src/public/node/themes/theme-manager.ts
- packages/cli-kit/src/public/node/themes/types.ts
- https://github.com/Shopify/develop-advanced-edits/issues/220
_note: This solution uses a placeholder URL rather than the public github URL. Further testing is required - will be tracked [here](https://github.com/Shopify/develop-advanced-edits/issues/261)_
```mermaid
flowchart LR
A[Start] --> B{Is theme provided?}
B -- Yes --> C[Fetch theme by ID]
C --> D{Theme found?}
D -- Yes --> E[Return theme ID]
D -- No --> F[Throw AbortError]
B -- No --> G[Look for a host theme]
G --> H{Host theme found?}
H -- No --> J[Create a host theme]
J --> K[Wait for theme to finish processing]
K --> E
H -- Yes --> E
E --> L[End]
```
https://github.com/Shopify/cli/assets/35415298/bfee87e9-b78c-4f62-85b0-620aee3e813b
> [Themes][app dev][TAE] Find or Create host theme when preparing theme app extension preview

- packages/cli-kit/src/public/node/themes/api.test.ts
- packages/cli-kit/src/public/node/themes/api.ts
- packages/theme/src/cli/services/push.test.ts
- packages/theme/src/cli/services/push.ts
- packages/theme/src/cli/utilities/theme-uploader.test.ts
- packages/theme/src/cli/utilities/theme-uploader.ts
The setup of the `shopify theme dev` command was not ignoring static assets, so this PR updates the logic to do that. So, we were facing this message with themes with static assets:
(this PR doesn't updates public facing behavior, so I'm not adding a changelog)
This PR moves the logic that ignores static assets to the uploader.
Additionally, this PR updates the API layer to show the error proper message. This way, if we face a similar regression in the future or the API will show a friendly message to users:
- Create a file called `assets/bla.css.liquid`
- Run `shopify theme push`
- Run `shopify theme dev --dev-preview`
- Notice we no longer face an error
N/A
> Update the new `shopify theme dev` command so that it does not delete generated assets

- packages/app/src/cli/services/app-logs/dev/write-app-logs.test.ts
- packages/app/src/cli/services/app-logs/logs-command/render-json-logs.test.ts
- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.test.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.ts
- packages/app/src/cli/services/app-logs/utils.ts
- packages/cli-kit/src/public/common/string.test.ts
- packages/cli-kit/src/public/common/string.ts
[Ticket](https://github.com/orgs/Shopify/projects/2117/views/75?pane=issue&itemId=73912552)
For ease of reading logs we want to have the function run logs in the developer's local timezone. 
1. Changing the log timezone in regular text app logs to be in local time.
2. Adding local timezone for JSON app logs. 
1. Checkout my branch in your local machine.
2. Have an app with a function ready. 
3. From cli repo run `pnpm run shopify app logs --path <path to functions app>`
4. Trigger function run. 
> Functions_370 Adding local time to cli logs

- .changeset/shy-moons-teach.md
- packages/app/src/cli/services/dev/processes/setup-dev-processes.ts
- packages/app/src/cli/services/dev/processes/web.ts
Fixes #4309 
We are currently proxying all webs, including background processes. But apparently we shouldn't be doing this.
Only proxies the frontend process. This way, requests will always be directed to the correct process.
Try the repro steps in the linked issue. The failure can easily be reproduced on `main` but doesn't happen when using this fixed CLI version.
> Only proxy frontend

- packages/app/src/cli/commands/app/logs.ts
- packages/cli/README.md
- packages/cli/oclif.manifest.json
Our current CSV formatting doesn't follow OCLIF standards, which instead has the user enter the flag multiple times.
Using the `multiple: true` setting in OCLIF to opt into OCLIF standard behaviour.
Run `shopify app logs --sources extensions.something --sources extensions.something-else`, replacing the sources with real functions from your app.
> Use oclif multiple flag on source

- packages/app/src/cli/services/dev/graphiql/server.ts
Fixes #4223
We aren't able to access GraphiQL on a remote environment because the localhost URL is hardcoded.
Pulls the URL from the request context, so even if it's behind a tunnel or proxy, the URLs will be correctly formed from the perspective of the browser.
1. Run an HTTPS tunnel to `localhost:3457`
2. `p shopify app dev --path /path/to/your/app --graphiql-key=abcdef`
3. Hit `g` to open up GraphiQL. It will give an error page. Add `?key=abcdef` to your URL and then it should work.
4. Replace `localhost:3457` with your tunnel URL on https. Everything should still work properly, including firing a GraphQL query.
5. Try uninstalling your app and going through the install flow from GraphiQL. Things should work as normal.
> Access GraphiQL on remote URL

- packages/app/src/cli/models/extensions/schemas.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.ts
Part 2 of https://github.com/Shopify/core-issues/issues/74004
Vault project: https://vault.shopify.io/gsd/projects/39317
Following the decision on the [tech design](https://docs.google.com/document/d/1DIDgtmb-JicQU9RCmzWfsVYDcV_MNE4KsdxytKRANAI/edit#heading=h.f0wr9ffq0l9g) to introduce a property called `allow_direct_linking` for an extension point's configurable capabilities. This allows app developers to configure whether the app extension can be used inside navigations (do they render a root url)
https://github.com/Shopify/shopify/pull/524406 is for the core side validations and updates the UiExtension API schema to incorporate target-level capabilities. This pull request allows `allow_direct_linking` to be configured for a ui_extension target. 
Add an optional capabilities hash which …
> Add allow_direct_linking to UIExtension schema

- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/services/deploy/bundle.test.ts
- packages/app/src/cli/services/deploy/upload.ts
As @pt2pham discovered, we were incorrectly setting the `assets` field in the deploy manifest file that we added in https://github.com/Shopify/cli/pull/4194. We were saving the `handle` there, but we actually use the `uid` as the folder name to store the extension stuff.
- Fixes the assets field in the manifest file
- Fixes an unrelated issue with error handling on deploy
- Replace the tmpDir [here](https://github.com/Shopify/cli/blob/eb5c103914a39f98625e9fe11bfd016c4bb85f32/packages/app/src/cli/services/deploy/bundle.ts#L20) to `/tmp` to be able to check generated the bundle
- Generate an extension and run `USE_APP_MANAGEMENT_API=1 bin/spin p shopify app deploy`
- `cat /tmp/bundle/manifest.json`
> Fix assets in deploy manifest

- packages/cli-kit/src/public/node/error-handler.ts
We are getting some errors in Bugnsag from environments like `test`: https://app.bugsnag.com/shopify/cli/errors?filters[error.status]=open&filters[event.since]=all&filters[app.release_stage]=test
It seems that [this check](https://github.com/Shopify/cli/blob/4a22d5b23429771d58c1a3b5748663e76064b938/packages/cli-kit/src/public/node/error-handler.ts#L66) is not working as expected in some cases.
Change the Bugsnag settings to only report in production.
Documentation: https://docs.bugsnag.com/platforms/javascript/configuration-options/#enabledreleasestages
One of the PRs that was raising errors from the CI is https://github.com/Shopify/cli/pull/4149. I've checked that [this error](https://app.bugsnag.com/shopify/cli/errors/66a7766ecb88867560472792), coming from that PR, didn't get more …
> Report to Bugsnag only in production

- .changeset/seven-starfishes-jump.md
- packages/app/src/cli/services/context.test.ts
- packages/app/src/cli/services/context.ts
Fixes https://github.com/Shopify/develop-app-inner-loop/issues/2048
Fixes https://github.com/Shopify/cli/issues/4264
In v3.65 we included [this refactor](https://github.com/Shopify/cli/pull/4233) that allowed to run link from the deploy command, but there are some situations where we are running link, but we shouldn't because we should use a current configuration. This is affecting especially in CI environments because the link process produces an error as it requires an input by the user.
Only run link on deploy when:
- There is no provided api_key or config
- There's no current configuration (cache or TOML) or is legacy
- Reset is passed
- `p shopify app deploy --client-id whatever`
- `p shopify app deploy -c production`
- `p shopify app config use production`
- …
> Avoid link on deploy when there is a current config

- .changeset/seven-starfishes-jump.md
I added a changeset by mistake in https://github.com/Shopify/cli/pull/4387, because it will be already included in the patch release: https://github.com/Shopify/cli/pull/4388
> Remove unneeded changeset

- packages/theme/src/cli/utilities/theme-environment/remote-theme-watcher.test.ts
- packages/theme/src/cli/utilities/theme-environment/remote-theme-watcher.ts
- https://github.com/Shopify/develop-advanced-edits/issues/298
- skips the JSON reconciliation step when the `theme-editor-sync` flag is passed with an empty development theme
- _The polling will still occur in this case_
1) `shopify theme delete -d`
2) `shopify-dev theme dev --dev-preview --theme-editor-sync`
Validate that you are NOT prompted for JSON reconciliation
https://github.com/user-attachments/assets/821c8761-5bdf-451b-8624-b3cb16ef3a65
> [Theme Dev] - Skip JSON reconciliation when development theme is empty

- packages/theme/src/cli/constants.ts
- packages/theme/src/cli/utilities/theme-environment/remote-theme-watcher.test.ts
- packages/theme/src/cli/utilities/theme-environment/remote-theme-watcher.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.ts
- packages/theme/src/cli/utilities/theme-environment/theme-polling.test.ts
- packages/theme/src/cli/utilities/theme-environment/theme-polling.ts
- packages/theme/src/cli/utilities/theme-environment/theme-reconciliation.test.ts
- packages/theme/src/cli/utilities/theme-environment/theme-reconciliation.ts
- packages/theme/src/cli/utilities/theme-fs.test.ts
- packages/theme/src/cli/utilities/theme-fs.ts
Closes
- https://github.com/Shopify/develop-advanced-edits/issues/292
- https://github.com/Shopify/develop-advanced-edits/issues/293
With the introduction of https://github.com/Shopify/cli/pull/4356, the `theme-editor-sync` flag needs to be updated to accommodate the new upload functionality
**Note: there is a known issue where `settings_schema.json` is always detected as a mismatching file. Fixing that is not within the scope of this PR.**
- Shares a single `ThemeFileSystem` instance between the `themeFileSystem watcher` (local FS)  and `remoteTheme watcher`, allowing them to work with a unified version of `files`
- When the `remoteThemeWatcher` downloads a file, it updates `localThemeFileSystem.files` with the new value **and checksum** via the `write` function …
> [Themes][Feature] Dev Server - Handle theme editor sync conflicts between local and remote themes

- packages/cli/oclif.manifest.json
- packages/theme/src/cli/commands/theme/console.ts
- packages/theme/src/cli/commands/theme/pull.test.ts
- packages/theme/src/cli/commands/theme/pull.ts
- packages/theme/src/cli/services/dev.ts
- packages/theme/src/cli/services/pull.ts
Use the `--dev-preview` beta flag in the `shopify theme pull` command instead of `--beta`.
Renames the `--beta` to  `--dev-preview`.
- Run `shopify theme pull --dev-preview`
N/A
> Use the `--dev-preview` beta flag in the `shopify theme pull` command

- .changeset/spicy-cheetahs-obey.md
- packages/app/src/cli/services/function/build.test.ts
- packages/app/src/cli/services/function/build.ts
If `shopify app function build` is run for a JS Function extension before `shopify app build` is executed, then Javy is not installed before trying to execute it. This used to work when using the `javy-cli` NPM package to execute Javy because that package would implicitly install Javy if it was not already installed. But now that the CLI doesn't use that package, installation needs to be explicitly performed. I've chosen to do it in the `runJavy` function to ensure a check is always performed to see if Javy is installed and install if it isn't.
Ensuring Javy is installed before trying to run it. The `installBinary` method performs a check to see if the binary is installed before attempting an install so this won't result in any attempts to redownload the binary if it's already present. …
> Ensure Javy is always installed before running it

- packages/theme/src/cli/services/dev.ts
- packages/theme/src/cli/utilities/theme-environment/remote-theme-watcher.test.ts
- packages/theme/src/cli/utilities/theme-environment/remote-theme-watcher.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.ts
- packages/theme/src/cli/utilities/theme-environment/theme-reconciliation.test.ts
- packages/theme/src/cli/utilities/theme-environment/theme-reconciliation.ts
- https://github.com/Shopify/develop-advanced-edits/issues/300
- Adds the `theme reconciliation` progress bar back 
- Fixes an issue where the progress bar would render before the user has a chance to provide input - rendering the CLI in a "stuck" state where input there is no way to provide the input needed to resolve the progress bar
- Fixes an async conflict with the `store-password` input which prevented users from selecting a `reconciliation option`
1) **Checkout the latest version of Dawn**
2) **Upload this version of Dawn** to your shop using `shopify theme push -d`.
This will trigger a job on core which adds `settings` keys in your `JSON` assets
3) **Run `shopify-dev theme dev --dev-preview --theme-editor-sync --store-password=<INCORRECT_PASSWORD>`**.
You should see a large number …
> [Themes] Theme Dev - Editor Sync - Fix Hanging Theme Reconciliation Progress Bar and User Inputs

- packages/app/src/cli/commands/app/function/run.ts
- packages/app/src/cli/services/function/binaries.ts
- packages/app/src/cli/services/function/build.test.ts
- packages/app/src/cli/services/function/build.ts
- packages/app/src/cli/services/function/replay.test.ts
- packages/app/src/cli/services/function/replay.ts
- packages/app/src/cli/services/function/runner.test.ts
- packages/app/src/cli/services/function/runner.ts
- packages/app/src/cli/services/function/ui/components/Replay/hooks/useFunctionWatcher.test.tsx
- packages/app/src/cli/services/function/ui/components/Replay/hooks/useFunctionWatcher.ts
The Function Runner binary to use when running functions was changed recently. However, the `replay` command was not updated, so it was using the old global binary.
This PR does two things (in two commits):
1. Updates the replay command to be consistent with how functions should be run.
2. Consolidates the logic for running a function so that it can be used everywhere.
Test:
- `function replay` without watch runs function
- `function replay` with watch runs function on change
- `function run` with piped input runs function
- `function run` with input path runs function
> Use function runner binary in replay

- packages/cli-kit/src/public/node/themes/types.ts
- packages/theme/src/cli/commands/theme/dev.ts
- packages/theme/src/cli/services/dev.ts
- packages/theme/src/cli/utilities/notifier.test.ts
- packages/theme/src/cli/utilities/notifier.ts
- packages/theme/src/cli/utilities/theme-fs.ts
- Closes https://github.com/Shopify/develop-advanced-edits/issues/297
Adds a `Notifier` module that accepts a URL or a filepath
- If a valid `URL` is provided, we will send a `POST` request with the shape `{"files":["<FILE_KEY>"]}
- Otherwise, we will attempt to write the `filename` to the file located at the path specified
- `notifyPath` can be a `relative` **or** `absolute` path
I considered adding support for specifying numerous `notifiers` - I want to gather alignment before building this, as I'm unsure of how much value lies in that change. I _believe_ it should be pretty straightforward to do so!
- Run `shopify-dev theme dev --dev-preview --notify <PATH>` with a couple of the following cases:
- a relative path e.g. (`./output` or `output`)
- absolute path e.g. …
> [Themes] Add support for the `--notify` flag in the theme dev command

- packages/app/src/cli/services/function/binaries.ts
I fixed the output in function-runner and released a new version.
Updates the binaries to use the latest function-runner.
Run a replay
```
pnpm shopify app function replay --path /Users/lopert/code/log-streaming/app/log-streamer/extensions/product-discount
```
Ensure that the output of the replay command no longer contains the wrapping `JsonOutput`.
cd to the binary's directory
```
cd /Users/lopert/src/github.com/Shopify/cli/packages/app/dist/cli/services/bin
```
check the version
```
./function-runner --version
function-runner 6.0.0
```
> update function-runner to v6.0.0

- packages/app/src/cli/api/graphql/business-platform-organizations/generated/types.d.ts
- packages/create-app/src/prompts/init.test.ts
- packages/create-app/src/prompts/init.ts
The shopify.dev docs use "[extension only app](https://shopify.dev/docs/apps/build/app-extensions/build-extension-only-app)" nomenclature. When creating a new app in the CLI we use "start by adding your first extension".  This inconsistency is confusing.
* "Start by adding your first extension" becomes "Build an extension only app".
* For consistency, "Start with Remix (recommended)" becomes "Build a Remix app (recommended)".
Run through the create a new app process.
None
> Use extension only verbage to match shopify.dev docs

- packages/cli-kit/src/public/node/themes/api.test.ts
- packages/cli-kit/src/public/node/themes/api.ts
- packages/cli/README.md
- packages/cli/oclif.manifest.json
- packages/theme/src/cli/commands/theme/console.ts
- packages/theme/src/cli/commands/theme/push.ts
- packages/theme/src/cli/services/dev.ts
- packages/theme/src/cli/utilities/asset-checksum.test.ts
- packages/theme/src/cli/utilities/asset-checksum.ts
- packages/theme/src/cli/utilities/theme-fs.test.ts
During my dev preview tests, I've applied some improvements to fix or polish specific workflows in the dev preview build — this PR syncs the `main` with the dev preview branch.
- Fixes the `shopify theme dev` command when a development theme doesn't exist — I've moved the creation of the mini theme to the API that creates a theme to centralize the theme creation. Without this, users can't run `shopify theme dev` because the CLI can't create the session and authenticate on password-protected stores (as the minimum amount of assets is required to conclude that authentication)
- Fixes the `http://localhost:undefined/password` message when users are running the `shopify theme console` without the dev preview flag
- Forces the usage of the new implementation of the `shopify theme push` command …
> Apply dev preview development preview improvements

- packages/app/src/cli/services/context.test.ts
- packages/app/src/cli/services/context.ts
Fixes https://github.com/Shopify/develop-app-inner-loop/issues/2072
Regression introduced in https://github.com/Shopify/cli/pull/4358
Ensure we use the right developer platform client before making any request
- `p shopify app init`
- `USE_DEVELOPER_PLATFORM_API=1 p shopify app deploy`
> Fix deploy after app creation with App Management API

- .changeset/sixty-mangos-beam.md
- packages/app/src/cli/commands/app/function/run.ts
- packages/app/src/cli/services/function/binaries.ts
- packages/app/src/cli/services/function/common.test.ts
- packages/app/src/cli/services/function/common.ts
- packages/app/src/cli/services/function/runner.test.ts
- packages/app/src/cli/services/function/runner.ts
#gsd:37875
Addresses:
- https://github.com/Shopify/script-service/issues/7502
Pre-requisite:
- https://github.com/Shopify/function-runner/pull/352
- Release new version ✅
Updates the function-runner version used by CLI. 
The new version will show an update benchmark results sections, including more information on the input and output size. Also, the color of the text in the `Benchmarks` section will be determined by the dynamic scaling limits. 
The new function runner requires two additional parameters to be provided (schema path and query path). 
Note: If incorrect arguments are provided to function for schema path and query path, then function runner will halt execution. If parameters are not passed, then it will use defaults for the limits. 
For Partners DX, there should not be an …
> [ShopifyVM] Update-function runner to use dynamic scaling

- .changeset/gold-berries-prove.md
- packages/app/src/cli/services/function/binaries.ts
Related issue: https://github.com/Shopify/shopify-functions/issues/394
We released a small update to the `function-runner`.
This PR bumps the `function-runner` version so that it is using the latest version.
1. Run a function with the `app function run --verbose` command. Verify that the debug log line states version 6.2.1.
2. Run the downloaded binary with the `--version` flag and verify it's 6.2.1.
> Bump function-runner to 6.2.1

- packages/cli-kit/src/private/node/conf-store.test.ts
- packages/cli-kit/src/private/node/conf-store.ts
- packages/cli-kit/src/private/node/constants.ts
- packages/cli-kit/src/public/node/analytics.ts
- packages/cli-kit/src/public/node/error-handler.ts
Some users are experiencing errors thousands of times daily, with minimal value added by analytics from those reports. We are throttling analytics (including bugsnag, monorail, and open analytics) to 300 events daily, to balance the need for continuous visibility into error conditions with the need to make those problems more visible by clearing out much of the noise from individual users with e.g. a background process retrying continuously thousands of times daily.
This isn't a perfect solution, we still are getting up to hundreds of reports daily from noisy users. But it's a quick and easy solution that gets us started down the path and eliminates the vast majority of noise immediately.
Adds a rate limiter around the reporting functions. At the moment, there is no granularity for …
> Throttle analytics to 300 daily events per dev machine

- packages/theme/src/cli/commands/theme/dev.ts
Ruby dependencies should only be invoked when the legacy flag is passed. However, users receive the following message when they try to invoke `shopify theme dev`.
When the `--legacy` flag is not passed, it defaults to `undefined`, and then the mechanism that refreshes the session is invoked. This regression was introduced after the dev preview when we [inverted](https://github.com/Shopify/cli/pull/4439) the logic from `--dev-preview` to `--legacy`.
N/A
> Ruby dependencies should only be invoked when the legacy flag is passed

- packages/theme/src/cli/utilities/theme-environment/hot-reload/server.test.ts
- packages/theme/src/cli/utilities/theme-environment/hot-reload/server.ts
Closes https://github.com/Shopify/develop-advanced-edits/issues/302
Grab the section names from the section group JSON file and sends them to the browser to request new versions of the sections.
Follow the video in the linked issue.
cc @Shopify/advanced-edits
> [Theme] Fix hot reload for section groups

- packages/theme/src/cli/utilities/theme-environment/proxy.ts
Closes https://github.com/Shopify/develop-advanced-edits/issues/328
Closes https://github.com/Shopify/develop-advanced-edits/issues/303 (already fixed in https://github.com/Shopify/cli/pull/4447)
The localization form/links are adding `return_to: /?_fd=0&pb=0` to its FormData.
This change removes these query params from the Location header before forwarding it to the browser.
cc @Shopify/advanced-edits
> [Theme] Fix querystring after localization redirect

- .changeset/nervous-sloths-wash.md
- packages/cli-kit/src/public/node/themes/factories.ts
Fixes https://github.com/Shopify/develop-advanced-edits/issues/339
Fixes https://github.com/Shopify/cli/issues/4470
- Add a fallback to calculate size when files are empty
- Add an empty file to your theme via admin
- Run `shopify theme pull -t <THEME>`
> [Themes] Account for empty assets when calculating theme asset size

- .changeset/nervous-sloths-wash.md
- packages/cli-kit/src/public/node/themes/factories.ts
Backport [[Themes] Account for empty assets when calculating theme asset size by jamesmengo · Pull Request #4475 · Shopify/cli](https://github.com/Shopify/cli/pull/4475/commits) which fixes #4470
> [3.67] - Account for empty assets when calculating theme asset size

- .changeset/metal-eggs-tap.md
- packages/theme/src/cli/services/local-storage.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-password-prompt.test.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-password-prompt.ts
Backport - [[Themes][Fix] - Ensure that theme store is initialized in local storage when validating storefront password](https://github.com/Shopify/cli/pull/4473) which fixes https://github.com/Shopify/cli/issues/4471
> [3.67] - Ensure that theme store is initialized in local storage when validating storefront password

- .changeset/hip-chefs-dance.md
- packages/theme/src/cli/utilities/theme-environment/dev-server-session.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-renderer.test.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-renderer.ts
Fixes https://github.com/Shopify/cli/issues/4477
The `shopify theme console` command was failing since [this change](https://github.com/Shopify/cli/pull/4376), because the Theme Access requests need the `Authorization` header.
This PR now just passes the `Authorization` header as we already have it at the moment the session is initialized.
This PR also avoids propagating the content-type of the SFR response, because when it's being proxied by the Theme Access app, that content-type is set to `application/json` (we're not introducing any branching code here, to protect the CLI from future changes, and in the end, the content-type should never be `application/json`).
Use the following command passing the Theme Access token:
- Install the Theme Access app in your store
- Generate a  Theme …
> Fix Theme Access authentication on `shopify theme dev` and `shopify theme console` commands

- .changeset/cuddly-months-switch.md
- packages/theme/src/cli/utilities/theme-fs.test.ts
- packages/theme/src/cli/utilities/theme-fs.ts
Fixes #4499  
Handles SVG files as text in MIME type detection
Serve a theme and add/update an SVG file
**Before**
**After**
cc @benjaminsehl 
> Fix content in SVG files

- .changeset/metal-plants-chew.md
- packages/app/src/cli/models/extensions/specifications/app_config_privacy_compliance_webhooks.test.ts
- packages/app/src/cli/models/extensions/specifications/app_config_privacy_compliance_webhooks.ts
Fixes https://github.com/Shopify/cli/issues/4511
When you deploy an app with:
- Application URL including a final slash (default value in the template), like `https://example.com/`
- Privacy compliance webhook with a relative URI, like `/webhooks`
Then the webhook is registered with a duplicated slash in Partners: https://example.com//webhooks
The same as https://github.com/Shopify/cli/pull/4357, but for privacy compliance webhooks.
Removes the ending slash from the application URL when generating the final URL to deploy.
- Create an app and set the application URL to `https://whatever.com/`
- Add a privacy compliance webhook with a relative URL: `/webhooks`
- Check in Partners that the webhook URL is `https://whatever.com/webhooks`
How do we know this change was …
> Fix duplicated slashes when deploying privacy compliance webhooks with relative URIs

- .changeset/short-hornets-compete.md
- packages/theme/src/cli/utilities/theme-environment/proxy.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts
Fixes #4479 again, after being reopened with a slightly different issue.
I'm unsure why, but it looks like SFR doesn't add the charset encoding when called from development. It seems to be adding it to production sites, however. The legacy CLI was also adding this (not sure if manually or by calling the API in a different way). cc @karreiro do you perhaps have more context on this?
Note: SFR and legacy CLI are not adding the charset encoding to JS / CSS assets so I've not changed that 🤔 
For themes that don't specify `<meta charset="utf-8">` in the layout, certain characters are not rendered correctly:
This PR adds the proper charset to the contet-type for HTML responses so things are rendered correctly:
1. Remove `<meta charset="utf-8">` from your layout.
1. Render `××hey××Пи好` in any …
> [Theme] Specify charset for HTML responses

- packages/cli-kit/src/private/node/analytics.ts
- packages/cli-kit/src/private/node/api/rest.ts
- packages/cli-kit/src/private/node/session.test.ts
- packages/cli-kit/src/private/node/session.ts
- packages/cli-kit/src/private/node/session/exchange.ts
- packages/cli-kit/src/public/node/analytics.test.ts
- packages/cli-kit/src/public/node/context/local.ts
- packages/cli-kit/src/public/node/monorail.ts
- packages/cli-kit/src/public/node/session.test.ts
- packages/cli-kit/src/public/node/session.ts
Related to https://github.com/Shopify/monorail/pull/19405
We need to differenciate different auth types.
Adds `env_auth_method` to monorail events, the possible values are `'partners_token' | 'device_auth' | 'theme_access_token' | 'custom_app_token' | 'none'`
Improves `user_id` detection when using custom tokens.
> Track env_auth_method

- .changeset/tiny-poems-tie.md
- packages/theme/src/cli/utilities/asset-checksum.test.ts
- packages/theme/src/cli/utilities/asset-checksum.ts
- packages/theme/src/cli/utilities/theme-ext-environment/theme-ext-fs.test.ts
- packages/theme/src/cli/utilities/theme-fs.test.ts
Fixes https://github.com/Shopify/cli/issues/4537
This PR updates the calculation of checksums to no longer minify assets before calculating the checksum.
- Run `shopify-dev theme init top-hat`
- Run `cd top-hat`
- Run `shopify-dev theme dev --theme-editor-sync` (select **Keep the local version**)
- Notice that translation files no longer keep refreshing (some initial sync does happen with template and section group files due to keys that get auto-added by the platform, but they no longer loop)
**Before**
**After**
N/A
> Update checksum calculation to no longer minify assets before calculating

- packages/cli/src/index.ts
- packages/theme/src/index.ts
Fixes https://github.com/Shopify/develop-advanced-edits/issues/346
- Exports the `push, `pull`, and `fetchStoreThemes` commands via the CLI package
1) Checkout and build this branch
2) Create a file in a package that includes `@shopify/theme`, such as `packages/app/src/cli/test.ts`
3) Import `push`, `pull`, and `fetchStoreThemes`
4) Hover over the function definition to see the JSDoc
5) Hover over the args inside of `push` and `pull` to see the JSDoc for the args inside flags
6) Test the autocomplete for flags args
https://github.com/user-attachments/assets/20e127fb-f411-4d34-93a9-95330254364a
<details><summary>Template</summary>
```ts
import {fetchStoreThemes, pull, push} from '@shopify/theme'
await pull({
development: true,
})
await push({
development: true,
only: ['asdf'],
})
await …
```
> [Themes] Add `push`, `pull`, and `fetchStoreThemes` to Themes Package Public Exports

- .changeset/fresh-mice-travel.md
- we need to manually trigger a minor release to stay with our cadence
- CLI version `3.68.0`
- there were no minor labelled changes, so we'll manually add one to trigger the automated changeset process
> force cli minor version 3.68.0

- .changeset/witty-insects-study.md
- packages/theme/src/cli/utilities/theme-downloader.test.ts
- packages/theme/src/cli/utilities/theme-downloader.ts
Fixes https://github.com/Shopify/cli/issues/4472
This updates the `shopify theme pull` command to ignore files as expected by applying the ignore filters in the local keys.
- Run `shopify theme init test`
- Run `cd test`
- Run `rm locales/es*`
- Run `shopify theme push -d`
- Run `git checkout locales/`
- Run `shopify theme pull -d --only config`
- Notice that `locales/es.json` and `locales/es.schema.json` are no longer deleted
N/A
> Fix `shopify theme pull --only <value>` so it does not delete ignored files

- packages/app/src/cli/services/dev.test.ts
- packages/app/src/cli/services/dev.ts
We show a warning if we think the developer may have forgotten to run deploy prior to dev, in particular if the developer has changed their app scopes in their local TOML file, but they're out of sync with what is found remotely. There are cases where this check is giving a false alarm.
Normalise the scope strings before comparing them.
Tricky one... there's an automated test. And we have an internal app that has one of these false alarms that I'm happy to share once we have a testable patch in place.
> Warn less often about scope mismatch

- packages/theme/src/cli/services/local-storage.test.ts
- packages/theme/src/cli/services/local-storage.ts
Adds tests for the changes introduced [Force dealing with config get returning undefined](https://github.com/Shopify/cli/pull/4517)
Closes https://github.com/Shopify/cli/issues/4528
- Test that the functions in `local-storage` throw an Error when `getThemeStore()` returns `undefined`
- Allow for a `LocalStorage<ThemeLocalStorageSchema>` instance to be injected into the functions in `local-storage`, which will be used to check in `requireThemeStore` (_this enables the testing, which was unfortunately not as straightforward as I would have liked_)
`pnpm test`
cc: @Shopify/advanced-edits
> [Themes] - Add tests to local storage functions that call `requireThemeStore`

- .changeset/rotten-worms-rush.md
- packages/theme/src/cli/utilities/theme-uploader.ts
I found that this promise rejection was causing process exit:
Turning it here into an error message instead:
(Note in the above image I was using `renderWarning` but I've changed it to `renderError` since that's more accurate, I think)
> [Theme] Avoid process exit when failing to delete a file from the remote theme

- packages/cli/oclif.manifest.json
- packages/theme/src/cli/commands/theme/console.ts
Fixes https://github.com/Shopify/develop-advanced-edits/issues/350
This pull request focuses on cleaning up and simplifying the `Console` class in the `theme` package by removing deprecated and unused code. The most important changes include removing unnecessary imports, flags, and methods related to legacy implementations and port handling.
- Removes Ruby CLI2 invocations from the `theme console` command
- Removes `legacy` and `port` flags
- Run the command with the `legacy` or `port` flags
cc: @Shopify/advanced-edits
> [Themes] Remove Ruby from `theme console` command

- .changeset/unlucky-years-look.md
- packages/cli-kit/src/public/node/fs.ts
- packages/theme/src/cli/utilities/asset-ignore.test.ts
- packages/theme/src/cli/utilities/asset-ignore.ts
Backport https://github.com/Shopify/cli/pull/4564
> [3.68] Update the ignore module (`--only`/`--ignore`/`.shopifyignore`) to be backward compatible with (Ruby) Shopify CLI 2

- .changeset/rotten-worms-rush.md
- packages/theme/src/cli/utilities/theme-uploader.ts
Backport https://github.com/Shopify/cli/pull/4581
> [3.68] Avoid process exit when failing to delete a file from the remote theme

- packages/app/src/cli/commands/app/build.ts
- packages/app/src/cli/commands/app/function/build.ts
- packages/app/src/cli/commands/app/function/replay.ts
- packages/app/src/cli/commands/app/function/run.ts
- packages/app/src/cli/commands/app/function/schema.ts
- packages/app/src/cli/commands/app/function/typegen.ts
- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/services/app-context.test.ts
- packages/app/src/cli/services/app-context.ts
- packages/app/src/cli/services/function/common.test.ts
- packages/app/src/cli/services/function/common.ts
- packages/app/src/cli/services/function/replay.test.ts
- packages/app/src/cli/services/function/replay.ts
- packages/app/src/cli/services/generate-schema.test.ts
- packages/app/src/cli/services/generate-schema.ts
- packages/app/src/cli/utilities/app-command.ts
- packages/eslint-plugin-cli/rules/required-fields-when-loading-app.js
Start using `linkedAppContext` in some commands.
- Modifies all function commands to use the generic `linkedAppContext` instead of `ensureConnectedAppFunctionContext`
- Create new type `AppLinkedInterface` for better DX
- Update some names and types
- Delete unnecessary tests and functions related to `ensureConnectedAppFunctionContext` 🚀 
- Run the function commands, here are some scenarios:
- Logged out
- In a new app
- With an old toml (just a toml with `client_id = 2222`)
Try to run the commands in those scenarios and then repeat, the second time everything should work automatically.
> Use app context in functions

- packages/app/src/cli/services/build/extension.ts
Fixes https://github.com/Shopify/shopify-functions/issues/445
Function developers have the option of specifying a custom build path for their Wasm file. This PR updates the CLI code to read from that path if it's specified, otherwise use the default path of `dist/index.wasm` (described [here](https://shopify.dev/docs/api/functions/configuration#properties)).
1. Create a Rust function with a specific build path (e.g. `target/wasm32-wasi/release/my-function.wasm`)
2. Run `shopify app deploy`
> Use TOML configuration for function build path

- packages/app/src/cli/services/app/config/link.ts
A bug was introduced the other day when, to support app-context, we made `link` return a config state.
Config state returned from link now returns the actual directory of the app, and not the one passed by the user (which might or might not be the app directory!)
- Have an app with an empty toml (just `scopes = ""`)
- Add a function
- Make sure that the toml is still empty, if it's not, force it.
- run 
```
pnpm shopify app function schema --stdout --path <path_to_function> --client-id <a_client_id>
```
> Config state after linking should include the real app directory

- .changeset/polite-suits-remain.md
- packages/theme/src/cli/utilities/errors.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.ts
- packages/theme/src/cli/utilities/theme-environment/theme-polling.ts
- packages/theme/src/cli/utilities/theme-fs.test.ts
- packages/theme/src/cli/utilities/theme-fs.ts
- packages/theme/src/cli/utilities/theme-uploader.ts
Related to #4576 and #4598
A proper request retry + token refresh is still needed but this PR tries to handle async errors more gracefully.
Ensure we print async errors properly with a red banner, and avoid process exit in some situations:
- On file delete / upload error in the remote theme, we show the error but the process continues. This is because the local development can continue working with local files in most cases, and is up to the developer to halt the process after seeing the error.
- On polling errors, wait for 5 errors before exiting the process. This is because it might recover from one or two failed attempts since it still compares local checksums with latest.
For example, when you lose your internet connection while polling:
During the initial sync, if there are too many …
> [Theme] Handle async errors

- .changeset/purple-games-collect.md
- packages/theme/src/cli/utilities/log-request-line.test.ts
- packages/theme/src/cli/utilities/log-request-line.ts
- packages/theme/src/cli/utilities/theme-environment/html.ts
- packages/theme/src/cli/utilities/theme-environment/proxy.ts
- packages/theme/src/cli/utilities/theme-fs.ts
Iterating on the last user logging improvements
Follow up to: https://github.com/Shopify/cli/pull/4536
Closes: https://github.com/Shopify/develop-advanced-edits/issues/359
This PR adds more functionality to user logging when using the Dev Server.
Highlights:
- Pulled the `logRequestLine` function into it's own util file for use in other areas
- Added logging to proxy requests allowing us to see `POST` requests (*not including /cdn routes*)
- Added some colour distinction to the output such as status codes and response time
Output example with changes:
Pull down the branch
Build the branch
run `theme dev`
click around and watch the logs
> [Themes] Add status codes and event methods to user logging

- .changeset/quiet-gorillas-tie.md
- packages/theme/src/cli/services/push.ts
Fixes https://github.com/Shopify/develop-advanced-edits/issues/357
When using the `--json` flag on `shopify theme push`, if there is an error, we are getting [object Object] as part of the output.
Making a small change to only output the `theme.name` since it's all that's required for the warning message.
Before:
After:
pull down the branch `fix-issue-357`
build the branch
break any `.json` file
run `theme push --json`
> remove [object Object] from theme push --json warning message

- .changeset/wicked-cycles-bake.md
- packages/theme/src/cli/utilities/theme-environment/local-assets.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts
Fixes #4607 
Makes the `/cdn/...` pathname prefix optional so that it serves local files from `localhost:1234/assets/...` directly. This is not used by the CLI itself but some users relied on this for custom integrations. I guess we can keep supporting it for backward compatibility? @karreiro @mgmanzella 
**Note:** this only work for local assets. We are not forwarding this type of request to the CDN for files that are only present in the remote version or that need to be rendered remotely (e.g. `assets/file.css.liquid`). Should we do that?
Check that your local theme files can be accesses in the browser from `localhost:1234/assets/...`
> [Theme] Fix local asset serve for backward compatibility

- .changeset/hungry-grapes-mate.md
- packages/theme/src/cli/utilities/asset-ignore.test.ts
- packages/theme/src/cli/utilities/asset-ignore.ts
- packages/theme/src/cli/utilities/theme-fs.test.ts
- packages/theme/src/cli/utilities/theme-fs.ts
Related to https://github.com/Shopify/cli/issues/4644
Remove the warning message from the ignore-module because some files can only be ignored using backward-compatible patterns otherwise users need to resort to regexes (you may double-check patterns in action and compare the recent version with the legacy one on [this gist](https://gist.github.com/karreiro/bc2ea3de24e8de577ef6bd54efb1cb21)).
Removes the warning message.
- Run `shopify theme dev --legacy --ignore "templates/*.json"`
- Notice the warning no longer appears
N/A
> Remove the warning message from the ignore-module because some files can only be ignored using backward-compatible patterns

- .changeset/thick-poets-brake.md
- docs-shopify.dev/commands/examples/theme-console.example.sh
- docs-shopify.dev/commands/examples/theme-init.example.sh
- docs-shopify.dev/commands/examples/theme-push.example.sh
- docs-shopify.dev/generated/generated_docs_data.json
- packages/cli/README.md
- packages/cli/oclif.manifest.json
- packages/theme/src/cli/commands/theme/console.ts
- packages/theme/src/cli/commands/theme/init.ts
- packages/theme/src/cli/commands/theme/push.ts
Fixes https://github.com/Shopify/develop-advanced-edits/issues/369
There are some leftover theme commands that show a different pattern on how to call them in our dev docs. They show up as `theme: command` where the majority of examples refer to the commands as `theme command`
Updated examples for `console`, `push` and `init` to use a space instead of `:`
You can see the updated auto-generated documents showing the changes, (`README.md`, `oclif.manifest.json`, and example scripts (`.sh`))
You can double check by pulling down the branch, and running `npm run refresh:manifests`. There should be no other changes to the generated docs.
> Fix syntax for theme command documentation

- packages/app/src/cli/services/init/template/cleanup.test.ts
- packages/app/src/cli/services/init/template/cleanup.ts
- packages/cli-kit/src/public/node/liquid.test.ts
- packages/cli-kit/src/public/node/liquid.ts
Template repos may come with liquid files in them, and currently the CLI will try to parse them all, which will most likely lead to errors when creating new apps.
Adding a file (name TBD) containing a list of files we want the CLI to leave alone when cloning a repo. That way, templates can determine what is off limits for the CLI. Ideally, this file's name should be generic enough that if we add any other sort of pre-processing, we can still use the same file.
Via unit tests, and creating apps with with a private template (slack me for the URL!).
None needed!
- We probably want to document this file somewhere?
> Allow ignoring liquid files using .cli-liquid-bypass

- packages/cli/oclif.manifest.json
- packages/theme/src/cli/commands/theme/push.test.ts
- packages/theme/src/cli/commands/theme/push.ts
Reverts Shopify/cli#4559
https://github.com/Shopify/develop-advanced-edits/issues/332
> Revert "[Themes] Remove Ruby from `theme push` command"

- bin/bundling/esbuild-plugin-graphiql-imports.js
- packages/app/assets/graphiql/style.css
- packages/app/src/cli/services/dev/graphiql/server.ts
We accidentally deleted the `style.css` file that was used for both legacy auth and graphiQL while removing the legacy auth flow.
Restore the `style.css` file, but add it to `app` this time since it is only used by GraphiQL.
> Restore style.css for GraphiQL

- packages/cli/oclif.manifest.json
- packages/theme/src/cli/commands/theme/push.test.ts
- packages/theme/src/cli/commands/theme/push.ts
https://github.com/Shopify/develop-advanced-edits/issues/374
1) Remove `password` flag as entrypoint to Legacy implementaiton
2)`legacy` renders a warning and direct users to open an issue
3) Introduces a fallback `legacy` altnerative
1) Run the command with the `legacy` flag 
- Should render a warning and run the TS implementation
2) Run the command with a `password` provided from the theme access app
- Should run the TS implementation
3) Run the command with `legacy-3.66`
- Should run the Ruby implementaiton
cc: @Shopify/advanced-edits
> [Themes] Replace legacy flag in `Push` command

- .changeset/little-ladybugs-fix.md
- packages/cli-kit/src/public/node/themes/api.test.ts
- packages/cli-kit/src/public/node/themes/api.ts
https://github.com/Shopify/develop-advanced-edits/issues/375
- Prevents unnecessary warning messages when a file is already absent from the remote theme. This can happen when deleting a file on the remote theme and the `--theme-editor-sync` flag is provided
1) Run `shopify-dev theme dev --theme-editor-sync`
2) Delete a file on the remote theme via the code editor
3) Observe that we don't report the failed deletion
https://github.com/user-attachments/assets/f8016a13-f562-4756-84c4-f19d9e69dfdb
> Prevent rendering remote file deletion error when file has already been removed 

- .changeset/silent-ghosts-hide.md
- packages/cli-kit/src/public/node/themes/api.test.ts
- packages/cli-kit/src/public/node/themes/api.ts
Related to https://github.com/Shopify/cli/issues/4576, https://github.com/Shopify/cli/issues/4598, and https://github.com/Shopify/cli/pull/4599
Retry requests for some HTTP errors. This PR doesn't propose to refresh the session because we're already refreshing it every [30 minutes](https://github.com/Shopify/cli/blob/main/packages/theme/src/cli/utilities/theme-environment/dev-server-session.ts#L8), the Admin session token expires in 2 hours, and we're getting a [fresh](https://github.com/Shopify/cli/blob/74fa66cfdb97b2d2e01c53be7f68409d7bb2710a/packages/theme/src/cli/services/dev.ts#L222) token when we start the session.
This PR updates the Admin REST API client to retry requests when they encounter certain HTTP errors. The Ruby CLI was more permissive regarding execution abortion, so …
> Make `shopify theme dev` more resilient to HTTP errors with the Admin API

- packages/app/src/cli/services/app-logs/logs-command/ui/components/Logs.test.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/Logs.tsx
- packages/app/src/cli/services/app-logs/types.ts
- packages/app/src/cli/services/app-logs/utils.ts
Part of: https://github.com/Shopify/script-service/issues/6233
We're enhancing the debugging experience for developers by providing visibility into the input query variables used during a function run.
This PR will add an input query variables section that will conditionally show based on if input query variables are used. Input query variables will be used when the values are specified in the `toml`.
Add input query variables section to the `app logs` command:
I also added some visual improvements to make the output and input sections more clear for partners to view. And updated the ouput and input sections to match.
Changes: **with improved styling**
<details><summary>With coloring (also will need to update other sections - alternate idea)</summary>
</details>
and when no metafield is …
> [ShopifyVM] 'app logs' Show input query variables in output for FunctionRunLog

- packages/cli-kit/src/public/node/error-handler.ts
- packages/cli-kit/src/public/node/error.test.ts
- packages/cli-kit/src/public/node/error.ts
…bugs
There are a category of errors that are not CLI bugs, and are environmental issues -- e.g. a disk becomes readonly in use. These come up a lot, as this is code that runs on a multitude of environments. Let's flag them as non-bugs as they make it hard to track real issues.
Adds an allow-list of "not bugs" messages.
> Allow specific error messages to be flagged as environmental and not bugs

- packages/app/src/cli/services/dev/update-extension.ts
A recent change introduced a regression in `app dev`
Remove an unnecessary call to `configWithoutFirstClassFields`, that's already done in the `deployConfig` function, no need to do it here.
Run dev in an app with a ui-extension, make a change in the extension while dev is running, everything should work.
> Fix crash on `dev` when making changes in an extension

- .changeset/giant-icons-exercise.md
- packages/theme/src/cli/services/push.test.ts
- packages/theme/src/cli/services/push.ts
Fixes https://github.com/shopify/cli/issues/4708
1) Fixes an issue for users of the `theme push` command where `allowLive` was not being picked up correctly
2) `ESlint` fixes
`pnpm shopify theme push --allow-live --live` should not prompt users
> [Themes] Connect `allowLive` flag to `theme push` execution

- .changeset/soft-melons-retire.md
- packages/cli/oclif.manifest.json
- packages/theme/src/cli/commands/theme/dev.ts
- packages/theme/src/cli/services/dev.test.ts
- packages/theme/src/cli/services/dev.ts
Fixes https://github.com/Shopify/develop-advanced-edits/issues/354
- Remove `legacy` and `legacy-3.66` flag from `theme dev` command
- Remove Ruby code path in `theme dev` command
- Remove call to `execCLI2`
- Remove `CLI2 flags` and related functionality
- Remove `refreshTokens` and related code
- Remove `deprecationWarnings` for `poll` and `-e` flags
- Run `shopify theme dev` with the follow options:
- `--legacy` and `--legacy-3.66` flag is not supported
- `--poll` and `-e` flag will no longer render warnings
> [Themes] Remove Ruby from `theme dev` command

- packages/cli-kit/src/private/node/api.ts
- packages/cli-kit/src/private/node/api/graphql.ts
- packages/cli-kit/src/private/node/api/headers.test.ts
- packages/cli-kit/src/private/node/api/headers.ts
- packages/cli-kit/src/private/node/api/rest.ts
- packages/cli-kit/src/private/node/constants.ts
- packages/cli-kit/src/public/node/api/admin.test.ts
- packages/cli-kit/src/public/node/api/admin.ts
- packages/cli-kit/src/public/node/api/graphql.test.ts
- packages/cli-kit/src/public/node/api/graphql.ts
Along with https://github.com/Shopify/themekit-access/pull/3703, add support for theme access tokens for GraphQL in the CLI. Will unblocking CLI GraphQL migration effort.
Add theme access logic for GraphQL requests (proxy to theme access app with appropriate headers).
In follow up, would like to clean up theme access logic by creating a file for it, rather than implementing it in REST and GraphQL 
See https://github.com/Shopify/themekit-access/pull/3703 for tophatting instructions
> Add GQL support for theme access tokens

- packages/theme/src/cli/services/dev.test.ts
- packages/theme/src/cli/services/dev.ts
It seems like we accidentally removed the gift card preview [here](https://github.com/Shopify/cli/pull/4560/files#diff-6aa5bcfd28a39726943182f60e3836a310541225dab8a218aa25bc9982488536L182-L189). This PR brings it back.
It brings the gift card link back and adds a test to avoid a similar scenario in the future.
I'm not adding a changeset because the PR that removed the gift card preview was merged recently, so this is not a user-facing thing.
N/A
> Restore gift card preview URL

- .changeset/small-goats-cough.md
- packages/theme/src/cli/services/package.test.ts
- packages/theme/src/cli/services/package.ts
When `config/settings_schema.json` has an error, the `shopify theme package` command was presenting an unactionable error message. Now, it shows a friendly error.
Updates the `shopify theme package` to handle that error and also to use `parseJSON` instead of `JSON.parse` to support comments.
- Run `shopify theme package`
Before:
After:
N/A
> Show an error when the `config/settings_schema.json` file can't be parsed

- .changeset/strong-guests-worry.md
- packages/cli-kit/src/public/node/themes/types.ts
- packages/theme/src/cli/services/dev.ts
- packages/theme/src/cli/utilities/theme-fs.test.ts
- packages/theme/src/cli/utilities/theme-fs.ts
Fixes: https://github.com/Shopify/develop-advanced-edits/issues/370
While fixing up some of the documentation relating to using the `--nodelete` flag, I noticed that files were still being deleted remotely when using `theme dev --nodelete`. 
The `mountThemeFileSystem` was not receiving the `--nodelete` flag if it was being used. I added it to the `ThemeFileSystemOptions` type and now we check if it present in the `handleFileDelete` method. If it is, we return early.
Run the current build and use the command `theme dev --nodelete`
Make a file.
Delete the file.
You should see it be deleted remotely.
-------------------------------------
Pull down this branch
Build this branch
Run `theme dev --nodelete`
Make a file
Delete the file
You will see it keeps the remote file.
How do we know this …
> Fix --nodelete behaviour on dev command

- .github/CODEOWNERS
Unblock auto-generated documentation change reviews
- Adds `@advanced-edits` and @`app-inner-loop` as code owners in the `docs-shopify.dev` directory
> Allow advanced-edits to review docs updates

- packages/app/src/cli/services/flow/serialize-fields.ts
- packages/app/src/cli/services/flow/serialize-partners-fields.test.ts
- packages/app/src/cli/services/flow/serialize-partners-fields.ts
- packages/app/src/cli/services/flow/types.ts
Flow action extension needs to support marketing activity config field.
https://github.com/Shopify/marketing-automations/issues/2118#issuecomment-2430000954
Adding the needed logic to support `shopify app import-extensions` for Flow action extensions with marketing activity config field.
* spin up `extensions`
* run `yarn create @shopify/app` in extensions terminal
* Start your app by running `dev cd your-app` and then `yarn shopify app dev`. It'll ask you to login, make sure you pick the partners account not regular dev account
* Go the partners dashboard and create a Flow action extension with multiple config fields including marketing activity config
* In CLI shell, run `pnpm shopify app import-extensions --path ../extensions/your-app`, choose `Flow Extensions` when asked "Extension …
> Fix Flow action extension CLI import

- .changeset/great-timers-explode.md
- packages/theme/src/cli/services/info.ts
Fixes https://github.com/Shopify/develop-advanced-edits/issues/377
Now that we are no longer keeping the legacy ruby commands, we can remove the need to check for a ruby version in `theme info`
Remove the ruby version check from the command.
Before:
After
Pull down the branch
Build the branch
Run `theme info`
> Remove ruby version from theme info command

- packages/app/src/cli/commands/app/import-extensions.ts
- packages/app/src/cli/services/context/identifiers-extensions.ts
Removing the `isShopify` check for marketing activity extensions as we are ready for rollout
> Remove isShopify checks for marketing activity extension

- graphql.config.ts
- packages/cli-kit/src/cli/api/graphql/admin/generated/theme_delete.ts
- packages/cli-kit/src/cli/api/graphql/admin/generated/theme_publish.ts
- packages/cli-kit/src/cli/api/graphql/admin/generated/theme_update.ts
- packages/cli-kit/src/cli/api/graphql/admin/generated/types.d.ts
- packages/cli-kit/src/cli/api/graphql/admin/mutations/theme_delete.graphql
- packages/cli-kit/src/cli/api/graphql/admin/mutations/theme_publish.graphql
- packages/cli-kit/src/cli/api/graphql/admin/mutations/theme_update.graphql
- packages/cli-kit/src/public/node/themes/api.test.ts
- packages/cli-kit/src/public/node/themes/api.ts
- packages/cli-kit/src/public/node/themes/utils.ts
- packages/theme/src/cli/commands/theme/delete.ts
- packages/theme/src/cli/services/delete.test.ts
- packages/theme/src/cli/services/delete.ts
- packages/theme/src/cli/services/publish.test.ts
- packages/theme/src/cli/services/publish.ts
- packages/theme/src/cli/services/push.test.ts
- packages/theme/src/cli/services/push.ts
- packages/theme/src/cli/services/rename.test.ts
- packages/theme/src/cli/services/rename.ts
Following the introduction of theme admin GraphQL endpoints, port the CLI to use GraphQL.
Extending what @catlee started here https://github.com/Shopify/cli/pull/4541
Migrate `themeDelete`, `themeUpdate`, and` themePublish` to use the admin graphql for both regular sessions and theme access sessions. Renamed uses of `delete/update/publishTheme` to `themeDelete/Update/Publish` for consistency.
Change themeDelete to return boolean (true on success, false on failure) instead of a theme.
To ship after Chris' code gen PR (shipped).
`shopify theme delete`
`shopify theme publish`
`shopify theme rename`
> Migrate theme delete/update/publish to GraphQL 

- .changeset/fresh-ears-search.md
- packages/theme/src/cli/utilities/theme-environment/proxy.test.ts
- packages/theme/src/cli/utilities/theme-environment/proxy.ts
Fixes https://github.com/shopify/cli/issues/4634
When the "Sign in with Shop" is activated, the `/account` endpoint behaves differently (returning the live theme ID in the body) impacting the proxy. However, following the redirect maintains the expected theme ID in the session.
It's important to note that stores without that feature were not being affected by this, and are not affected by this change as well.
This PR updates the proxy logic to proxy `/account` requests and avoid the remote-render of the `/account` endpoint.
This PR also refactors the logic in the proxy to rely on regular expressions to evaluate patterns to centralize the logic for each case on the regular expressions and prevent conditions from growing like `p.startsWith(..) && p.endsWith(..)`. …
> Fix the theme ID mismatch error, where the live theme ID is returned instead of the development theme ID

- packages/app/src/cli/models/extensions/schemas.ts
- packages/app/src/cli/services/flow/serialize-fields.ts
- packages/app/src/cli/services/flow/validation.ts
Flow action extension needs to support marketing activity config field.
https://github.com/Shopify/marketing-automations/issues/2118#issuecomment-2430000954
Adding the needed logic to support `shopify app deploy` for Flow action extensions with marketing activity config field. The marketing activity config field should get persisted in the `app_static_extension_configs` table in core with the right URL's.
* spin up `extensions`
* run `yarn create @shopify/app` in extensions terminal
* Start your app by running `dev cd your-app` and then `yarn shopify app dev`. It'll ask you to login, make sure you pick the partners account not regular dev account
* In CLI shell,  run `pnpm shopify app generate extension --path ../extensions/your-app` to generate a Flow action extension, modify the …
> fix Flow action extension CLI deploy to work with marketing activity config field

- .changeset/fresh-crabs-kick.md
- packages/theme/src/cli/utilities/asset-ignore.test.ts
- packages/theme/src/cli/utilities/asset-ignore.ts
- packages/theme/src/cli/utilities/theme-fs.test.ts
- packages/theme/src/cli/utilities/theme-fs/theme-fs-mock-factory.ts
Fixes https://github.com/Shopify/cli/issues/4710
When a user is using `!` in their `.shopifyignore` file to ensure that file is not ignored, it had unintended side effects such as ignoring other files and folders, and not actually negating the file(s) it is supposed to.
Add some additional logic around separating negated options and normal ignored options.
Essentially, we all regular ignored logic in the `.shopifyignore` file and then run any negated logic afterwards which undoes the ignore.
Ex:
We have these files
`assets/basic.css`
`assets/complex.css`
`assets/my_special.css`
We want to ignore all files in the assets folder **except** my_special.css
Our `.shopifyignore` will look like
```git
assets/*.css,
!assets/my_special.css
```
Even though we will initially ignore the entire assets …
> Fix bug related to using negated patterns in shopify ignore

- packages/cli-kit/src/cli/api/graphql/admin/generated/get_theme_file_bodies.ts
- packages/cli-kit/src/cli/api/graphql/admin/generated/get_theme_file_checksums.ts
- packages/cli-kit/src/cli/api/graphql/admin/generated/types.d.ts
- packages/cli-kit/src/cli/api/graphql/admin/queries/get_theme_file_bodies.graphql
- packages/cli-kit/src/cli/api/graphql/admin/queries/get_theme_file_checksums.graphql
- packages/cli-kit/src/public/node/api/admin.ts
- packages/cli-kit/src/public/node/themes/api.test.ts
- packages/cli-kit/src/public/node/themes/api.ts
- packages/theme/src/cli/constants.ts
- packages/theme/src/cli/utilities/batching.ts
- packages/theme/src/cli/utilities/theme-downloader.test.ts
- packages/theme/src/cli/utilities/theme-downloader.ts
- packages/theme/src/cli/utilities/theme-environment/theme-polling.test.ts
- packages/theme/src/cli/utilities/theme-environment/theme-polling.ts
- packages/theme/src/cli/utilities/theme-environment/theme-reconciliation.test.ts
- packages/theme/src/cli/utilities/theme-environment/theme-reconciliation.ts
- packages/theme/src/cli/utilities/theme-fs.test.ts
Migrate off the REST Assets API and use graphQL instead.
This PR adjusts the `fetchThemeAsset` and `fetchChecksums` method to use the [`OnlineStoreTheme.files` field](https://shopify.dev/docs/api/admin-graphql/unstable/objects/OnlineStoreTheme#connection-files).
Where appropriate I've also updated callers to fetch multiple assets at once with `fetchThemeAssets`.
`p shopify theme pull ...` should fetch all the files from your theme to a local directory.
> Port fetchThemeAssets / fetchChecksums to graphQL

- .changeset/two-laws-hammer.md
- packages/app/src/cli/models/extensions/extension-instance.test.ts
- packages/app/src/cli/models/extensions/extension-instance.ts
- packages/app/src/cli/models/extensions/specification.ts
- packages/app/src/cli/models/extensions/specifications/checkout_ui_extension.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.ts
- packages/app/src/cli/services/build/extension.ts
Fixes [UI extension source map generation issue](https://github.com/Shopify/shopify/issues/548438) 
Extension developers will be able to use generated source map files for e.g. troubleshooting a live extension in a production store by loading the file in Chrome dev tools while interacting with a checkout where their extension is present.
- Adds `generates_source_maps` ExtensionFeature value
- Adds `generates_source_maps` feature to `ui_extension` and `checkout_ui_extension` specifications
- For these extensions, generate the sourcemap on `shopify app deploy` and move it into a `/dist` subdirectory of the extension project that was used to produce it
- Output the source map file paths when in `--verbose` mode
Spin up `checkout-ui-extension-dev:developer-dashboard`
From the `CLI` project, …
> Generate local sourcemap files for UI extensions

- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
Fixes https://github.com/Shopify/develop-app-inner-loop/issues/2265 
Switches to Shopify CDN hosted templates JSON, so we're not relying directly on GitHub's CDN infrastructure for moment-to-moment CLI operations.
```sh
$ USE_APP_MANAGEMENT_API=1 pnpm app generate extension --path /path/to/your/app
```
You should see the prompt as usual.
> Use Shopify CDN URL instead of GitHub CDN

- packages/theme/src/cli/utilities/theme-environment/storefront-session.test.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-session.ts
https://github.com/Shopify/cli/issues/4737
Fixes a bug in the storefront password protection detection logic where redirects on the provided URL (e.g. `.com` -> `.se`) cause us to detect the storefront as password protected.
- Specifically check for redirects to the `/password` path, rather than assuming any `302` redirect indicates password protection
- Improving debug output for password protection status
**Replicate**
1. Disable password protection on your store
2. Add a domain to your store, and set that as your default domain
3. Provide the original (now secondary) domain in the `--store` flag value
4. Run `pnpm shopify theme dev` with this branch and verify the appropriate error message is shown
> [Themes] Improve storefront password protection redirect handling

- .changeset/great-zoos-punch.md
- packages/cli-kit/src/public/node/themes/api.test.ts
- packages/cli-kit/src/public/node/themes/api.ts
https://github.com/Shopify/cli/issues/4793
When using `app dev`, host themes were getting overwritten due to a race condition between the `minimum asset upload` and the core job that handles theme installation when the `src` param`, causing potential issues during development.
Prevents the upload of of minimum theme assets when a source URL is provided during theme creation. 
1. Run `app dev` with a theme extension
2. Verify that the host theme is created with proper content
3. Ensure no empty files are present in the theme
> [Themes] Fix empty files in host themes during `app dev`

- .changeset/brown-dots-clap.md
- packages/theme/src/cli/utilities/theme-environment/dev-server-session.test.ts
- packages/theme/src/cli/utilities/theme-environment/dev-server-session.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-session.test.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-session.ts
Adds validation to ensure required theme files exist before initializing the dev server session. This helps catch issues with incomplete or corrupted themes that could cause the dev server to fail when initializing the preview session.
- https://github.com/Shopify/cli/issues/4735
- https://github.com/Shopify/develop-advanced-edits/issues/406
- Adds a new `verifyRequiredFilesExist` function that checks for essential theme files (`layout/theme.liquid` and `config/settings_schema.json`)
1. Create a theme missing either `layout/theme.liquid` or `config/settings_schema.json` on your shop (more instructions below if needed)
2. Run the `theme dev` with the theme flag, and specify the `--theme` flag to point at the theme created above. Verify that it fails with appropriate error message …
> [Themes] Verify existence of required theme files before initializing storefront session

- .changeset/tough-eels-bow.md
- notifications.json
- packages/app/src/cli/models/app/loader.ts
- packages/cli-kit/package.json
- packages/cli-kit/src/private/node/conf-store.test.ts
- packages/cli-kit/src/private/node/conf-store.ts
- packages/cli-kit/src/public/node/base-command.ts
- packages/cli-kit/src/public/node/cli.ts
- packages/cli-kit/src/public/node/global-context.ts
- packages/cli-kit/src/public/node/node-package-manager.ts
- packages/cli-kit/src/public/node/notifications-system.test.ts
- packages/cli-kit/src/public/node/notifications-system.ts
- packages/cli/oclif.manifest.json
- packages/cli/src/cli/commands/cache/clear.ts
- packages/cli/src/cli/commands/notifications/generate.ts
- packages/cli/src/cli/commands/notifications/list.ts
- packages/cli/src/cli/services/commands/notifications.ts
- packages/cli/src/index.ts
- packages/eslint-plugin-cli/rules/specific-imports-in-bootstrap-code.js
This PR is adding back the [Notification system](https://github.com/Shopify/cli/pull/4149) that was reverted in https://github.com/Shopify/cli/pull/4818 because we were fetching the json from GitHub and it's rate-limited.
- Fetches the notifications from the Shopify CDN instead of GitHub (the asset is added to the CDN in https://github.com/Shopify/static-cdn-assets/pull/1129)
- Generate and list commands also get the file from the CDN, unless `SHOPIFY_CLI_NOTIFICATIONS_URL` is specified
Install the snapshot from this branch: `npm i -g @shopify/cli@0.0.0-snapshot-20241111105008`
I've uploaded a sample notifications.json to simplify testing:
- `SHOPIFY_CLI_NOTIFICATIONS_URL=https://shopify.link/MNbn shopify version`
- `SHOPIFY_CLI_NOTIFICATIONS_URL=https://shopify.link/MNbn shopify theme …
> Notification system with CDN

- packages/app/src/cli/services/dev/app-events/app-event-watcher-handler.ts
- packages/app/src/cli/services/dev/app-events/app-event-watcher.ts
- packages/app/src/cli/services/dev/extension/localization.test.ts
- packages/app/src/cli/services/dev/extension/localization.ts
- packages/app/src/cli/services/dev/processes/dev-session.ts
- packages/app/src/cli/services/dev/processes/setup-dev-processes.test.ts
- packages/app/src/cli/services/dev/ui/components/Dev.tsx
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/cli-kit/src/private/node/ui/components/ConcurrentOutput.tsx
We need to prepare the new dev experience for real use.
- Use new colors for the dev output
- Improve messages for dev session events
- Use `dev-session` as generic identifier for events in terminal
- Use colors in terminal only for relevant cases (Session updated, errors...)
- Show a message when scopes are changed.
- Other minor improvements.
(Note, this screenshot doesn't include the new color change, which were added later)
Run `dev` with the app management API.
> UX Improvements for `app dev` in app management

- packages/cli-kit/package.json
- packages/cli-kit/src/public/node/context/fqdn.test.ts
- packages/cli-kit/src/public/node/context/fqdn.ts
- packages/cli-kit/src/public/node/vendor/dev_server/DevServer.ts
- packages/cli-kit/src/public/node/vendor/dev_server/network-interfaces.d.ts
- pnpm-lock.yaml
Internal to Shopify, the CLI needs to support the new dev server infrastructure and hostnames for local development environments.
For any non-Shopifolk: there's no difference, it's an internal adjustment.
Adds a copy of the DevServer library (with permission) and use it for FQDNs during local dev.
Run ` SHOPIFY_SERVICE_ENV="local" p shopify app info --path=<path to an app> --verbose`
You'll see the CLI exit, because the first thing it wanted to connect locally to wasn't there (probably `identity`). Confirm the error message and the URL it was trying to connect to.
> Add vendored DevServer library

- .changeset/eight-dragons-grab.md
- packages/app/src/cli/services/function/binaries.ts
The function-runner version has an Javy QuickJS provider that matches what's being used in production. I'm already in here so may as well update Javy as well. This should also slightly de-risk future updates to Javy because there will be fewer changes (compared to updating across multiple versions at the same time).
Updates the versions the CLI will download to the latest versions of Javy and the function-runner.
- `rm -r packages/app/dist/cli/services/bin/` (clear out any cached downloaded binaries)
- `pnpm shopify app function build --path <path_to_function_extension>` (downloads and runs Javy)
- `echo "{}" | pnpm shopify app function run --path <path_to_function_extension>` (downloads and runs function-runner)
> Update Javy and function-runner versions

- configurations/vite.config.ts
Excludes vendor directories from code coverage reporting to ensure more accurate test coverage metrics that focus on our own codebase.
Adds an exclude pattern `**/src/**/vendor/**` to the code coverage configuration in Vite to prevent vendor code from being included in coverage reports.
> Coverage analysis shouldn't include vendored libraries

- packages/app/src/cli/services/dev/processes/dev-session.ts
There is a race condition that can prevent the dev-session to start.
- Fix the race condition: the dev create process shouldn't be cancelled in any case
- If a change is detected before the session is ready, show a warning.
- Add a 30s timeout, if the session hasn't started in 30 seconds, exit the process and inform the user. (this shouldn't be necessary, but probably useful in the early stages for testing)
Run `app dev` with the app management API
> Improve dev session start

- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/app/loader.ts
- packages/app/src/cli/services/init/init.ts
- pnpm-lock.yaml
To create during `app init`, we need to load what we call the "Creation Options" which include two key values: the default scopes and whether the app is launchable or not.
We did this by loading the local app first to check those values, but we can't do that if the template has custom extensiosn, because we don't have the specifications at this point (because there is no remote app yet!)
Instead of loading the app: just load the basic configuration from the toml and the `webs` configuration. That's all we need for the creation options.
The easiest way is to put a breakpoint in `services/init/init.ts` line 201.
Validate that the `creationOptions` object is valid in these three cases:
- An extensions-only app
- A default remix app
- A remix template with custom extensions and scopes (ask …
> Get creation options without loading the app during `app init`

- packages/app/src/cli/services/extensions/bundle.test.ts
- packages/app/src/cli/services/extensions/bundle.ts
AppWatcher should be the only one responsible for watching changes in extensions.
Removes unused `watch` options from the ui extension bundler.
Nothing to test, this is removing unused code.
> Remove watch options from bundle extension functions

- packages/cli-kit/src/public/node/notifications-system.test.ts
- packages/cli-kit/src/public/node/notifications-system.ts
The tests are broken on main because a new CLI notification was added and it's affecting some tests
Skip notifications check on CI and tests
CI
> Skip notifications check on CI and tests

- .changeset/swift-frogs-fail.md
- packages/theme/src/cli/services/dev.test.ts
- packages/theme/src/cli/services/dev.ts
Do you suffer from long logs? Do you accidentally close your browser window and have to scroll all the way up in your terminal to find the theme dev links? Look no further than the addition of shortcut keys!
Closes https://github.com/Shopify/cli/issues/4713
Closes https://github.com/Shopify/develop-advanced-edits/issues/427
With the amount of logs `theme dev` generates, it can be difficult to find the original store links such as previewing your theme, or opening the theme editor. Having shortcut keys is a simple way to open the links without needing to physically click on them in the terminal.
Add shortcut keys to the `theme dev` command
We look for keypresses, specifically:
`t` - opens the theme locally
`e` - opens the theme editor
`p` - opens the share preview
`g` - opens the gift …
> [Feature] Add shortcut keys to theme dev

- packages/app/src/cli/api/graphql/business-platform-organizations/generated/types.d.ts
- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/services/app/select-app.ts
- packages/app/src/cli/services/context/breakdown-extensions.test.ts
- packages/app/src/cli/services/context/breakdown-extensions.ts
- packages/app/src/cli/services/context/identifiers.ts
- packages/app/src/cli/services/release.ts
- packages/app/src/cli/services/release/version-diff.test.ts
- packages/app/src/cli/services/release/version-diff.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
Responding to comments by @shauns regarding code quality ([1](https://github.com/Shopify/cli/pull/4777/files#r1846175012), [2](https://github.com/Shopify/cli/pull/4777/files#r1846173629))
Removes an extra field being passed around but not used (`registrationUid`), and reorganizes types to be more logical (rather than Partners-centric) which also allows DRYing up some code in `AppManagementClient` around the shared logical types.
Most importantly, `config` is now passed around as an object rather than a JSON string.
In both Partners and App Management:
1. Create a new app
2. Generate some extensions (admin link work well)
3. Deploy a version, confirming that the diff appears correctly
4. Re-release the initial version before deploying extensions, confirming the diff appears correctly …
> Clean up app management client module interpretation quality concerns

- packages/app/src/cli/services/dev/app-events/app-event-watcher.ts
- packages/app/src/cli/services/function/ui/components/Replay/Replay.test.tsx
- packages/app/src/cli/services/function/ui/components/Replay/Replay.tsx
- packages/app/src/cli/services/function/ui/components/Replay/hooks/useFunctionWatcher.test.tsx
- packages/app/src/cli/services/function/ui/components/Replay/hooks/useFunctionWatcher.ts
Migrates the function replay functionality to use the new app event watcher system instead of the legacy extension watcher.
- Replaces `setupExtensionWatcher` with `AppEventWatcher` for function replay functionality
- Updates type requirements from `AppInterface` to `AppLinkedInterface`
- Simplifies error handling by leveraging the app event watcher's built-in error reporting
- Removes redundant test assertions related to the old watcher setup
1. Create a function extension
2. Run the function with `--replay`
3. Make changes to the function code
4. Verify that the function reruns automatically
5. Introduce a build error and verify error messages are displayed correctly
> Use AppWatcher for function replay

- packages/app/src/cli/services/dev/processes/draftable-extension.ts
Addresses potential race conditions when pushing updates for draftable extensions in parallel.
- Filters extension events to only process draftable extensions
- Implements concurrent processing of extension updates using `Promise.all`
1. Run dev with multiple draftable extensions (admin-action, theme)
2. Verify that we send initial drafts for every extension.
> Fix initial draft update

- .changeset/sixty-years-stare.md
- docs-shopify.dev/commands/interfaces/app-function-replay.interface.ts
- docs-shopify.dev/commands/interfaces/app-function-run.interface.ts
- docs-shopify.dev/commands/interfaces/app-info.interface.ts
- docs-shopify.dev/commands/interfaces/app-logs.interface.ts
- docs-shopify.dev/commands/interfaces/app-versions-list.interface.ts
- docs-shopify.dev/commands/interfaces/theme-info.interface.ts
- docs-shopify.dev/commands/interfaces/theme-list.interface.ts
- docs-shopify.dev/commands/interfaces/theme-push.interface.ts
- docs-shopify.dev/generated/generated_docs_data.json
- packages/app/src/cli/commands/app/function/replay.ts
- packages/app/src/cli/commands/app/function/run.ts
- packages/app/src/cli/commands/app/info.ts
- packages/app/src/cli/commands/app/logs.ts
- packages/app/src/cli/commands/app/versions/list.ts
- packages/app/src/cli/models/app/loader.ts
- packages/cli-kit/package.json
- packages/cli-kit/src/private/node/constants.ts
- packages/cli-kit/src/public/node/cli.ts
- packages/cli-kit/src/public/node/environment.ts
- packages/cli-kit/src/public/node/notifications-system.test.ts
- packages/cli-kit/src/public/node/notifications-system.ts
- packages/cli-kit/src/public/node/path.ts
- packages/cli/README.md
- packages/cli/oclif.manifest.json
- packages/theme/src/cli/commands/theme/info.ts
- packages/theme/src/cli/commands/theme/list.ts
- packages/theme/src/cli/commands/theme/push.ts
Fixes https://github.com/Shopify/cli/issues/4925
- Prevents notifications from being shown when the `--json` or `-j` flags are used, or the `SHOPIFY_FLAG_JSON` environment variable
- Unifies the usage of the `--json` flag across commands. Some where missing the shortcut `-j` and the descriptions were different.
- Applies the same logic to the `showMultipleCLIWarningIfNeeded`, where we were only checking for `--json`
- `pnpm i -g @shopify/cli@0.0.0-snapshot-20241127122146`
- `SHOPIFY_CLI_NOTIFICATIONS_URL=https://shopify.link/MNbn shopify theme list`
- `SHOPIFY_CLI_NOTIFICATIONS_URL=https://shopify.link/MNbn shopify theme list --json`
- `SHOPIFY_CLI_NOTIFICATIONS_URL=https://shopify.link/MNbn shopify theme list -j`
- `SHOPIFY_FLAG_JSON=1 …
> Skip notifications when using --json

- .github/CODEOWNERS
- Add subfolders to `docs-shopify.dev` 
- Update README.md
Motivation: Self serve for PR's like https://github.com/Shopify/cli/pull/4900/files where we add a new flag
> Update CODEOWNERS file patterns and add CLI README

- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/models/extensions/extension-instance.ts
- packages/app/src/cli/models/extensions/schemas.ts
- packages/app/src/cli/models/extensions/specification.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.ts
- packages/app/src/cli/services/build/extension.ts
- packages/app/src/cli/services/dev/app-events/app-event-watcher.test.ts
- packages/app/src/cli/services/dev/app-events/app-event-watcher.ts
- packages/app/src/cli/services/dev/app-events/app-watcher-esbuild.test.ts
- packages/app/src/cli/services/dev/app-events/app-watcher-esbuild.ts
- packages/app/src/cli/services/dev/extension/payload.test.ts
- packages/app/src/cli/services/dev/extension/payload.ts
- packages/app/src/cli/services/dev/extension/payload/models.ts
- packages/ui-extensions-server-kit/src/types.ts
Part of [conditional rendering project](https://docs.google.com/document/d/1X1NhQMxz6GnTU49rDplMd1yVmX3rsj2obIfHUFQ7WkM/edit?tab=t.0).
This PR enables the processing of a `should_render` asset, as well as other assets.
- Maps `should_render` field from TOML to extension config
- Bundles all `should_render` modules into one file (for both `dev` and `deploy` actions)
- Sends `buildManifest` to `shopify` in order centralize file path information in one place
[Testing instructions](https://gist.github.com/elanalynn/bff3bda620cb5d0284d0cf892e713e90)
> Enable multiple asset handling

- .github/dependabot.yml
Updates Dependabot configuration to better organize dependency updates by grouping all dev dependencies together
> Make a dependabot group for dev dependencies

- .github/ISSUE_TEMPLATE/bug-report.yml
The verbose output is usually too big and requires a lot of scrolling in the issues
Updates the bug report template to add a default value to the verbose output with some markdown to enable collapsing it.
It will look like this:
<details>
<summary>Verbose output</summary>
```
Paste the output here!
```
</details>
Merge and create an issue
> Collapse verbose output by default in bug template

- .github/ISSUE_TEMPLATE/bug-report.yml
Since the Shopify CLI is now installed globally by default, the instruction in the issue template to check `package.json` to find the version is outdated.
> Remove reference to package.json

- packages/app/src/cli/commands/app/init.ts
- packages/app/src/cli/services/init/init.ts
App init shows the success message and then it still takes 1-2s to finish. 
Load the app BEFORE showing the success message.
1. Run `shopify app init` to create a new app
2. Verify that after the success message, the command finishes immediately (it can still take up to 500ms to process analytics)
> Show `app init` success after loading the app

- packages/app/src/cli/services/deploy/bundle.test.ts
- packages/app/src/cli/services/deploy/bundle.ts
- packages/app/src/cli/services/dev/fetch.test.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/cli-kit/src/private/node/constants.ts
- packages/cli-kit/src/private/node/session.ts
- packages/cli-kit/src/private/node/session/exchange.ts
- packages/cli-kit/src/private/node/session/scopes.test.ts
- packages/cli-kit/src/private/node/session/scopes.ts
- packages/cli-kit/src/public/node/context/local.test.ts
- packages/cli-kit/src/public/node/context/local.ts
Kicks off https://github.com/Shopify/develop-app-inner-loop/issues/2343
Refactors how we check if App Management is enabled by introducing a dedicated function and constant. This means there will now only be 1 place to change if we want to edit the logic for enabling App Management.
- Introduces `isAppManagementEnabled()` helper function in `context/local.ts`
- Replaces direct environment variable checks with the new helper function
1. Set environment variable `USE_APP_MANAGEMENT_API=1`
2. Run CLI commands that interact with App Management
3. Verify the behavior remains the same
4. Test with `USE_APP_MANAGEMENT_API=0` to ensure disabled state works correctly
> Centralize gating of the App Management API

- packages/cli-kit/src/private/node/api.test.ts
- packages/cli-kit/src/private/node/api.ts
- packages/cli-kit/src/public/node/api/admin.ts
- packages/cli-kit/src/public/node/api/graphql.test.ts
- packages/cli-kit/src/public/node/api/graphql.ts
- packages/cli-kit/src/public/node/themes/api.test.ts
When running `shopify theme dev` for long periods of time, the session can timeout and needs to be refreshed. The client will receive 401 errors from the server until the session is refreshed.
We've fixed this for REST calls in https://github.com/Shopify/cli/pull/4790.
This PR does the same for graphQL calls.
Fixes #4897 
@karreiro and I decided the best way to approach this was to extend the functionality of `retryAwareRequest` so that when a 401 error occurs, and an `unauthorizedHandler` is provided, then we call the unauthorizedHandler and retry the request.
Further up the stack in the graphQL code, we use the session's refresh function as the unauthorizedHandler.
> Refresh session on 401 for graphQL requests

- .changeset/khaki-glasses-wave.md
- packages/app/src/cli/services/function/binaries.ts
If a Shopify Functions-related binary is downloaded in parallel, every download after the first one completes will fail with a `dest already exists` error because `move` by default throws this error if a file already exists.
Instructs the CLI to overwrite when downloading the binary. It's going to be the same binary anyway.
This is going to be difficult to test because it relies on parallelism which isn't deterministic.
> Fix dest already exists error by setting overwrite flag on stable branch

- .changeset/shiny-guests-give.md
- packages/app/src/cli/services/admin-link/extension-to-toml.test.ts
- packages/app/src/cli/services/admin-link/utils.test.ts
- packages/app/src/cli/services/admin-link/utils.ts
Updated mapping from context to target for legacy links. Previous mapping was not matching the convention for targets.
> Update context to target mappings

- .changeset/honest-cobras-invite.md
- .github/CODEOWNERS
- packages/cli-kit/src/public/node/themes/api.ts
- Fixes https://github.com/Shopify/cli/issues/5010
We recently migrated the CLI to use the new GraphQL endpoints to upload theme files. We had logic in the code that would throw a GraphQL error if the file/asset being uploaded did not have a value or attachment. Unfortunately this was falsely targeting newly created files that have a value of an empty string `''`.
This PR removes the GraphQL error raising entirely. The only scenario we check for now is if there is a valid `attachment` otherwise we'll always upload the file as a `TEXT` file with an empty string or the value itself.
1. Pull down this branch and run `pnpm run build`
2. In a local theme folder, create a new empty file `touch snippets/empty.liquid`
3. Run `shopify theme dev --path /your/theme/with/empty/file`
You should not …
> Allow empty theme files to be uploaded

- packages/app/src/cli/utilities/extensions/locales-configuration.test.ts
- packages/app/src/cli/utilities/extensions/locales-configuration.ts
The current file size limit of 16KB for extension localization files is too restrictive for some use cases.
Increases the extension localization file size limit from 16KB to 20KB while maintaining the overall bundle size limit of 256KB.
1. Create a localization file larger than 16KB but smaller than 20KB
2. Verify the extension can be deployed without size limit errors
3. Verify files over 20KB still trigger appropriate error messages
> Increase localization file size limit

- .changeset/wicked-singers-explode.md
- packages/app/src/cli/services/dev/update-extension.test.ts
- packages/app/src/cli/services/dev/update-extension.ts
Function drafts were not working correctly during development mode due to incorrect file path handling and encoding issues.
Fixes function drafts by using the correct `extension.outputPath` instead of `bundlePath` when reading WASM files. The WASM files in the bundle path were being encoded in base64, causing compatibility issues. 
1. Create a function extension in your app
2. Run `dev`
3. Verify that function drafts are now working correctly
> Fix function drafts

- bin/get-graphql-schemas.js
- graphql.config.ts
- packages/app/project.json
- packages/app/src/cli/api/graphql/functions/api_schema_definition.ts
- packages/app/src/cli/api/graphql/functions/generated/schema-definition-by-api-type.ts
- packages/app/src/cli/api/graphql/functions/generated/schema-definition-by-target.ts
- packages/app/src/cli/api/graphql/functions/generated/types.d.ts
- packages/app/src/cli/api/graphql/functions/queries/schema-definition-by-api-type.graphql
- packages/app/src/cli/api/graphql/functions/queries/schema-definition-by-target.graphql
- packages/app/src/cli/api/graphql/functions/target_schema_definition.ts
- packages/app/src/cli/commands/app/function/run.ts
- packages/app/src/cli/commands/app/function/schema.ts
- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/services/function/common.test.ts
- packages/app/src/cli/services/function/common.ts
- packages/app/src/cli/services/generate-schema.test.ts
- packages/app/src/cli/services/generate-schema.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
- packages/cli-kit/src/public/node/api/functions.ts
- packages/eslint-plugin-cli/rules/no-inline-graphql.js
Notes: See https://github.com/Shopify/shopify/pull/554957 for the Core branch and tophat instructions
https://github.com/Shopify/shopify-functions/issues/483
```
pnpm run shopify app function schema --path=./new-app
```
We added a new enpoint in core on the `dd` branch - 
This PR also updates the CLI interface for developer platform client to ensure compatibility with both the Partners Client and the App Management Client. Given the differences in their respective request structures and required parameters, this change aims to maintain a clean and functional API while adapting to the varied needs of both clients.
Notes on AMF vs Partners Flow:
**Partners Client - Flow**
- With the cli's partners-client request, the [query](https://github.com/Shopify/cli/blob/82b872fb4d9aff53031e0283366141e …
> [ShopifyVM] Use Functions App Management API for Dev Dash

- packages/theme/src/cli/utilities/theme-fs.test.ts
- packages/theme/src/cli/utilities/theme-fs.ts
- packages/theme/src/cli/utilities/theme-uploader.test.ts
- packages/theme/src/cli/utilities/theme-uploader.ts
Closes https://github.com/Shopify/develop-advanced-edits/issues/468
Adds support for theme block files when uploading theme
- Introduces explicit partitioning support for blocks folder
- Modifies theme uploads to upload blocks first
1. Try uploading `horizon` from the CLI on the `CLI 3.71`+
2. Run `shopify theme push -u`
3. Verify that `custom-section` has an error like this: `Failed to upload file sections/custom-section.liquid:
-Invalid preset "Featured collection": invalid block type "featured-collection": undefined block type.`
4. Check out this branch and build
5. Run `pnpm shopify theme push -u`
6. Confirm that theme is uploaded with no errors
BEFORE
AFTER
> [Themes] Add support for block liquid files in theme partitioning

- packages/cli-kit/package.json
- packages/cli-kit/src/public/node/cli.ts
- packages/cli/src/index.ts
- packages/create-app/src/index.ts
Makes the `launchCLI` parameter optional in `runCLI` and `runCreateCLI` functions. This reverts a change to the external contract of `@shopify/cli-kit` introduced in https://github.com/Shopify/cli/pull/4842
- Sets a default launcher param if one is not provided.
Run `shopify` CLI app & create app commands to verify they work without explicit launcher.
> Make launcher option for CLI optional

- .changeset/red-tips-mix.md
- packages/cli-kit/src/public/node/git.test.ts
- packages/cli-kit/src/public/node/git.ts
- packages/theme/src/cli/services/dev.ts
- packages/theme/src/cli/services/pull.test.ts
- packages/theme/src/cli/services/pull.ts
- packages/theme/src/cli/services/push.ts
- packages/theme/src/cli/utilities/theme-ui.ts
Another check to avoid a potentially destructive behaviour when running `theme pull`.
Checks that the current directory is a git directory, and that there are no uncommitted changes before pulling and overwriting new files.
1. `git clone https://github.com/Shopify/dawn` or `git init` in a new directory
2. Touch a file in the directory
3. Run `shopify theme pull` within that directory
4. Ensure that you are prompted
https://github.com/user-attachments/assets/1e3dfd78-be60-48e5-a8ff-317f6662aecc
> Ensure git directory is clean when running `theme pull`

- packages/cli-kit/src/private/node/ui/components/AutocompletePrompt.test.tsx
- packages/cli-kit/src/private/node/ui/components/SelectInput.tsx
The autocomplete prompt component fails when users enter search terms containing special regex characters, particularly backslashes. This causes the component to break instead of handling the invalid regex gracefully.
Adds error handling around regex creation in the SelectInput component to gracefully handle malformed regex patterns. When an invalid regex is encountered (such as an incomplete backslash), the component now falls back to displaying the unmodified label instead of throwing an error.
1. Use the autocomplete prompt component
2. Enter a search term containing backslashes or other special regex characters
3. Verify that the component continues to function and display results without breaking
> Fix an error when user enters '\' in an auto complete

- packages/app/src/cli/services/function/build.test.ts
- packages/app/src/cli/services/function/build.ts
Catches a runtime error when building JS Shopify Functions, by checking the required runtime module exists.
Adds validation to check for the existence of the `run.ts` module in the `@shopify/shopify_function` package during the function build process. Later in the build process we inject an explicit dependency on this module (`import __runFunction from "@shopify/shopify_function/run"`).
If the module is missing, it throws a clear error message prompting users to update their dependencies.
This doesn't occur often, and the library is stable, but it may be possible if dependencies have been corrupted or the developer is using a customised or very old dependency.
There were checks for the module being present, but these were only applied in the case where a function was a single default …
> Check that @shopify/shopify_function has a `run` module

- packages/app/src/cli/services/dev/select-app.ts
Fixes an unhandled error thrown when selectOrCreateApp fails to do either.
Instead of using `!`, handles the case where the app is `undefined`.
> Fix exception raised when selectOrCreateApp fails to find an app

- packages/app/src/cli/services/admin-link/utils.test.ts
- packages/app/src/cli/services/admin-link/utils.ts
Target subdomains are kebab cased and context controllers are snake case. There was a missing transformation to switch casing.
Add hyphenate method to switch from snake case to kebab case
> Fix undescores in subdomain target when importing legacy links

- packages/theme/src/cli/commands/theme/generate/block.ts
- packages/theme/src/cli/services/generate/blocks.test.ts
- packages/theme/src/cli/services/generate/blocks.ts
- packages/theme/src/cli/utilities/generator.ts
> Feat: Generate Liquid Blocks

- packages/cli/README.md
- packages/cli/oclif.manifest.json
- packages/theme/src/cli/commands/theme/generate/section.ts
- packages/theme/src/cli/services/generate/sections.test.ts
- packages/theme/src/cli/services/generate/sections.ts
- packages/theme/src/cli/utilities/generator.ts
Adds support for generating theme sections with both Liquid and JSON file types, providing developers with more flexibility when creating new theme sections.
- Introduces a new `generateSection` service to handle section file creation
- Adds support for both Liquid and JSON section file types
- Implements file existence checks to prevent overwriting existing sections
- Updates the section generator command to handle the new file type option
- Adds comprehensive tests for the section generation functionality
1. Run `theme generate section` and follow the prompts
2. Choose between Liquid or JSON file types
3. Verify the generated section file contains the correct structure
4. Try generating a section with a name that already exists to test error handling
> [Themes] Add support for generating liquid and JSON section files

- packages/cli/README.md
- packages/cli/oclif.manifest.json
- packages/theme/src/cli/commands/theme/generate/template.test.ts
- packages/theme/src/cli/commands/theme/generate/template.ts
- packages/theme/src/cli/services/generate/templates.test.ts
- packages/theme/src/cli/services/generate/templates.ts
- packages/theme/src/cli/utilities/generator.test.ts
- packages/theme/src/cli/utilities/generator.ts
> [Themes] Add template generation with liquid and json support

- .changeset/heavy-frogs-pretend.md
- packages/theme/src/cli/utilities/theme-uploader.ts
Part of https://github.com/Shopify/cli/issues/5031
A previous [PR](https://github.com/Shopify/cli/pull/4792/files#diff-c4edcc1629cc0813d96396f1661f9f69fcdbece0f346f9d53dc99b6233abd5f1R21) changed the endpoint to upload the themes files from REST API to GraphQL API
- The new endpoint did not cause the issue, but the PR also increased the theme upload batch size
- This is generally fine when using the CLI through regular user login, but fails when requests are being proxied through Theme Access App
- Instead Theme Access App on your store
- Set environment variables in terminal
```
export SHOPIFY_CLI_THEME_TOKEN=<password from app>
export SHOPIFY_FLAG_STORE=<store>
export SHOPIFY_FLAG_FORCE="1"
```
- Run this CLI branch against an existing theme
- `npx shopify theme push --theme="bug-dec16" …
> [Bug Fix] Reduce theme upload batch size to prevent timeout

- .changeset/heavy-frogs-pretend.md
- packages/theme/src/cli/utilities/theme-uploader.ts
Backport of https://github.com/Shopify/cli/pull/5113
> [3.72] Backport - Reduce theme upload batch size to prevent timeout

- .changeset/heavy-frogs-pretend.md
Changeset type should have been a patch in the original PR -  https://github.com/Shopify/cli/pull/5123
This applies to the main branch as well
Caused the version update to look like this: https://github.com/Shopify/cli/pull/5128
> Modify changeset type to patch

- .changeset/heavy-frogs-pretend.md
https://github.com/Shopify/cli/pull/5113
Should have been a patch bump instead.
> [Themes] Fix changeset type

- packages/app/src/cli/api/graphql/business-platform-organizations/generated/list_app_dev_stores.ts
- packages/app/src/cli/api/graphql/business-platform-organizations/queries/list_app_dev_stores.graphql
- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/prompts/dev.test.ts
- packages/app/src/cli/prompts/dev.ts
- packages/app/src/cli/services/dev/select-store.test.ts
- packages/app/src/cli/services/dev/select-store.ts
- packages/app/src/cli/services/store-context.test.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
Fixes https://github.com/Shopify/develop-app-inner-loop/issues/2455
Allows developers to find dev stores in the list even if they have > 50 stores.
Enables autocomplete search for dev stores, just as we have for apps.
Note this will only work for BP orgs, it's not implemented for Partner orgs.
Using an org with > 50 dev stores, run `app dev` and search for a store by name that is beyond the first 50.
> Enable search for dev stores

- packages/cli-kit/src/public/node/error-handler.ts
Adds support for tracking business platform IDs in error reporting metadata, enabling better error tracking and debugging capabilities for business platform related issues.
Adds `business_platform_id` to the list of app keys that are collected and included in error reporting metadata.
1. Trigger an error in an app that includes a business platform ID
2. Verify that the error report in bugsnag includes the business platform ID in the metadata
> Include business platform ID in bugsnag info

- packages/app/src/cli/services/app-context.test.ts
- packages/app/src/cli/services/app-context.ts
When we run `app info` on an app with an invalid extension TOML:
1. The TOML loading fails, but is in unsafe report mode so execution can continue
2. We replace the config with a default empty object [here](https://github.com/Shopify/cli/blob/3a87534b82e20b7ad9398a0fcc19673f2546dabe/packages/app/src/cli/models/app/loader.ts#L167)
3. Our code thinks there's no UID
4. It inserts a second UID into the file, making it invalid 🤦 
Skips the UID update when in unsafe report mode, as:
1. We haven't built sufficient confidence that it is correct to update
2. We probably shouldn't edit files on `app info` anyway!
1. Create an app with an extension and change a type (e.g. string to number) in the `shopify.extension.toml` file
2. Run `shopify app info` twice.
On the second time (on `main`), it will …
> [Fix] Skip UID update when in unsafe report mode

- packages/app/src/cli/models/app/app.test.ts
- packages/app/src/cli/models/app/app.ts
To improve the handling of custom extension directory paths in app configuration by ensuring proper glob pattern support for watching changes in subfolders.
Adds functionality to automatically convert single asterisk wildcards (`*`) to double asterisks (`**`) in extension directory paths. This ensures proper recursive watching of subdirectories when using chokidar for file watching during `dev`.
1. Create an app with and put some extensions in a folder called `custom_extensions`
2. Ensure your app.toml has `extension_directories = ['custom_extensions/*']`
2. Run `dev`
3. Verify that changes in extension files are properly detected and HMR works.
> Fix extension_directories wildcards to always be recursive

- package.json
- shipit.nightly.yml
- shipit.production.yml
- shipit.stable.yml.sample
- shipit.stable_3_71.yml
To prevent people from running `pnpm bundle` locally, which might break their CLI dev environment.
Renames the `bundle` script to `bundle-for-release` in package.json and updates all shipit configuration files to use the new script name. This change makes it more explicit that this bundling step is specifically for the release process and should not be used locally.
1. Run `pnpm bundle-for-release` to verify the renamed script works as expected
2. Verify that the nightly/snapshot build process completes successfully
> Rename bundle to bundle-for-release

- .changeset/small-guests-brake.md
- packages/app/src/cli/models/app/loader.ts
Fixes an issue where TOML configuration file errors were not being properly detected when error properties contained falsy values (such as occurring on the zero-th column).
Updates the error property check in the configuration file loader to explicitly verify if properties are undefined, rather than relying on truthy/falsy evaluation.
1. Create a TOML configuration file with an error at position 0
2. Run the CLI command that loads the configuration
3. Verify that the error is properly detected and reported
> Fix error handler for invalid TOML files

- .changeset/healthy-tips-raise.md
- packages/theme/src/cli/commands/theme/info.ts
- packages/theme/src/cli/services/info.ts
Applying the changes in #5170 to themes as well.
1. Uses standardized UI Kit components
2. Removes the version warning - since we warn daily and issue notifications, it doesn't add value here.
Before:
After:
```sh
shopify theme info
```
By the way, I noticed that this command doesn't take a `--path` variable, is that just an oversight? I definitely added one for local testing.
> Theme info rework

- packages/cli-kit/src/public/node/themes/api.ts
Adds debug logging to report that themeFetch failed on top of the changes introduced in #5200
This is likely inconsequential, but may come in handy for debugging something in the future (even more so because the client will handle failures silently otherwise)
@karreiro  **Do we want to do this? Would we be adding too much noise?**
> [Themes] Add debug logging for theme fetch errors

- packages/app/src/cli/services/dev.ts
- packages/app/src/cli/services/dev/ui.test.tsx
- packages/app/src/cli/services/dev/ui.tsx
- packages/app/src/cli/services/dev/urls.test.ts
- packages/app/src/cli/services/dev/urls.ts
Fixes https://github.com/Shopify/develop-app-inner-loop/issues/2348
Removes this app url change banner since it is no longer needed by Developer Dashboard apps or apps using consistent dev
Additionally, `isCurrentAppSchema` is always true now, so we remove some of the mentions of it from the files we are touching.
**From within the CLI folder:**
**Try not using the App Management API first and confirm partners dashboard app url update banner doesn't show**
- Create an app `p shopify app init`
- Choose **a remix app** 
- `p shopify app dev --path ./name-of-your-app --reset`
- You should **not** see the app url banner saying you can change App URL on Partners.
**Now try using the App Management API and confirm partners dashboard app url update banner doesn't show**
- …
> Hide all banners that tell you to change app URL 

- .github/workflows/shopify-cli.yml
- packages/app/src/cli/services/deploy/bundle.test.ts
- packages/app/src/cli/services/deploy/bundle.ts
- packages/app/src/cli/services/dev/fetch.test.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/cli-kit/src/private/node/api/headers.ts
- packages/cli-kit/src/private/node/constants.ts
- packages/cli-kit/src/private/node/session.ts
- packages/cli-kit/src/private/node/session/exchange.test.ts
- packages/cli-kit/src/private/node/session/exchange.ts
- packages/cli-kit/src/private/node/session/scopes.test.ts
- packages/cli-kit/src/private/node/session/scopes.ts
- packages/cli-kit/src/public/node/context/local.test.ts
- packages/cli-kit/src/public/node/context/local.ts
Completes https://github.com/Shopify/develop-app-inner-loop/issues/2343
Removes the App Management feature flag and makes it a default part of the CLI's functionality. This should be merged when App Management is ready to be rolled out to all eligible organizations.
- Removes the `USE_APP_MANAGEMENT_API` environment variable and related checks
- Removes most behavior implementing a special case where App Management is disabled
- ... with the exception of when using a Partners CLI token, in which case we need to access only Partners and not App Management
1. Deploy an app using `shopify app deploy --reset` (or you can start all the way back from `app init`)
2. Verify organizations are fetched from both Partners and App Management APIs
3. Test app creation and management workflows to ensure …
> Remove all conditional logic around App Management being disabled

- .changeset/mean-seas-hide.md
- packages/cli-kit/src/public/node/fs.test.ts
- packages/cli-kit/src/public/node/fs.ts
- packages/theme/src/cli/services/metafields-pull.test.ts
- packages/theme/src/cli/services/metafields-pull.ts
Fixes https://github.com/Shopify/cli/issues/5183
We've noticed a significant number of users discussing whether to ignore the `.shopify/metafields.json` file. While this decision ultimately rests with the developer, ignoring it by default seems like a sensible approach. This PR proposes implementing that default.
This PR updates the `.shopify/metafields.json` creation to also add it to `.gitignore`.
- Run `shopify theme metafields pull`
- Notice that, when the .shopify/metafields.json file is created, it's also added in the gitingore
N/A
> Add `.shopify/metafields.json` to `.gitignore` by default

- packages/app/src/cli/api/graphql/app-management/generated/create-app.ts
- packages/app/src/cli/api/graphql/app-management/queries/create-app.graphql
- packages/app/src/cli/services/app/config/link.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
There is an issue when using `--reset` and linking to a new app. The CLI wasn't properly configuring this new app and if done during `app dev`, it was obtaining the apiSecret.
Make sure that we properly build the `AppCreationDefaultOptions` object when linking to a new app during a `--reset` command.
Make sure that we fetch the api secret also on `createApp` mutations, not only on `getApp` queries.
1. export USE_APP_MANAGEMENT_API=1 
2. `shopify app init` and create a new app (api client) in a Plus org and choose the Remix template
3. `shopify app dev` and see the that app opens
4. stop the server and run `shopify app dev --reset` and create a new app (api client)
5. Verify that you don't see any vite error in the console and dev works
6. Verify that your new toml has `embedded = true` …
> Fix dev when resetting and creating a new app

- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/app/loader.ts
- packages/app/src/cli/services/app/config/link-service.test.ts
- packages/app/src/cli/services/app/config/link.ts
- packages/app/src/cli/services/context.ts
- packages/app/src/cli/services/dev/select-app.test.ts
- packages/app/src/cli/services/dev/select-app.ts
- packages/app/src/cli/services/init/init.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
We had two very similar objects: `CreateAppOptions` and `AppCreationDefaultOptions`
We are refactoring and unifying everything to just use `CreateAppOptions`.
- Consolidates app creation options into a single `CreateAppOptions` interface
- Removes redundant name parameter from `createApp` method signatures
- Updates all callers to use the new unified options interface
- Ensures directory is consistently passed through creation options
1. Create a new app using `shopify app init`
2. Link an existing app using `shopify app config link` 
3. Verify all app creation flows work as expected with proper options passed through
> Simplify CreateAppOptions and DefaultAppOptions into a single object

- packages/app/src/cli/services/build/extension.ts
We want ESBuild errors from functions to appear in the dev logs.
If a javascript function throws an ESBuild error, re-throw as it is and the dev-session will automatically parse and format it.
1. Create a javascript function extension
2. Run dev
3. Modify the function to have some syntax error. 
4. See that the error is properly shown in the dev log, with specific details on where it happened.
> Rethrow functions esbuild errors

- .changeset/strange-dodos-develop.md
- packages/app/src/cli/services/function/binaries.ts
Bump to latest version of `function-runner`
Bump the version that is downloaded
- `rm -r packages/app/dist/cli/services/bin/` (clear out any cached downloaded binaries)
- `pnpm shopify app function build --path <path_to_function_extension> `(downloads and runs Javy)
- `cat <path_to_function_input> | pnpm shopify app function run --path <path_to_function_extension>` (downloads and runs function-runner)
> Bump `function-runner` to v7.0.1

- .changeset/chatty-lies-rescue.md
- package.json
- packages/theme/src/cli/utilities/asset-path.ts
Originally reported [here](https://shopify.slack.com/archives/C05E3BDFDRB/p1737473033912099).
Under some unknown circumstances, NX might complain about circular dependencies:
Replace `require.resolve` with `findPathUp` to ensure Nx doesn't think `@shopify/cli` is a dependency.
`shopify theme profile --url /` should still work.
> [Theme] Change how assets are resolved

- .changeset/shiny-lions-marry.md
- packages/cli-kit/src/private/node/ui/components/Tasks.test.tsx
- packages/cli-kit/src/private/node/ui/components/Tasks.tsx
- packages/cli-kit/src/private/node/ui/components/TextAnimation.tsx
Fixes the poor display of the loading bar in no-color terminals.
https://github.com/user-attachments/assets/06e49f94-7982-4e32-b3bd-67a3275ecf78
```sh
$ p shopify kitchen-sink async
```
or any other command which uses a rainbow bar (e.g. creating a new app)
> Replace rainbow bar with moving hill for no-color mode

- packages/app/src/cli/api/graphql/app-management/generated/specifications.ts
- packages/app/src/cli/api/graphql/app-management/queries/specifications.graphql
- packages/app/src/cli/api/graphql/extension_specifications.ts
- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
- packages/eslint-plugin-cli/rules/no-inline-graphql.js
Adds support for client-provided UIDs in app specifications, enabling the CLI to distinguish between extension-style and config-style modules based on their UID management approach.
- Adds `isClientProvided` field to the UID strategy in app specifications GraphQL query
This is inert in isolation, as the option isn't used yet.
> RemoteSpecfication includes uidIsClientProvided

- packages/app/src/cli/services/dev/processes/dev-session.test.ts
- packages/app/src/cli/services/dev/processes/dev-session.ts
- packages/app/src/cli/services/dev/processes/previewable-extension.ts
- packages/app/src/cli/services/dev/processes/setup-dev-processes.test.ts
- packages/app/src/cli/services/dev/processes/setup-dev-processes.ts
- packages/app/src/cli/services/dev/ui/components/Dev.test.tsx
- packages/app/src/cli/services/dev/ui/components/Dev.tsx
- packages/app/src/cli/utilities/extensions/locales-configuration.ts
For dev-sessions, update the preview URL dynamically depending on whether the app has previewable extensions or not.
- Adds dynamic preview URL updates in dev sessions based on extension previewability
- Introduces a new `devSessionPreviewURL` state to track and update the preview URL
- Updates the UI to reflect preview URL changes in real-time
1. Start a dev session with no previewable extensions (no UI ext.)
- Verify the default app preview URL is displayed
2. Add a previewable extension (admin-action for example)
- Verify the preview URL updates to show the dev console URL
- Press 'p' to confirm the new URL opens correctly
3. Remove all previewable extensions
- Verify the preview URL reverts to the default app preview URL
> Update preview URL based on dev session status

- packages/app/src/cli/services/dev/extension.ts
- packages/app/src/cli/services/dev/extension/payload.ts
There was a bug where adding a non-previewable extensions during a dev-session would cause a crash, because we tried to add that extension to the dev-console process as well.
- For the previewable process (dev-console), ignore any change related to non-previewable extensions.
1. Run a dev-session with just an admin-action extension (or any ui-extension)
2. Add a new webhook to your toml file.
3. Verify the session is updated and it doesn't crash.
> Filter non-previewable extensions from the dev-console

- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/models/app/loader.ts
- packages/app/src/cli/models/extensions/load-specifications.ts
- packages/app/src/cli/models/extensions/specification.ts
- packages/app/src/cli/models/extensions/specifications/custom_data.ts
- packages/app/src/cli/services/generate/fetch-extension-specifications.test.ts
- packages/app/src/cli/services/generate/fetch-extension-specifications.ts
Closes https://github.com/Shopify/develop-app-storage/issues/18
Removes the custom data specification and improves handling of remote extension specifications with different UID strategies. As DCDD is an app.toml managed module, we need to be able to indicate that it's UID strategy is `single`
- Removes the custom data specification and its associated configuration
- Updates the UID strategy handling based on `uidIsClientProvided` flag
1. Run the test suite to verify the updated remote specification handling
2. Tophat: make an app, connect to DL org (has module enabled), all the following should work.
- Run dev, add `[metaobjects.author.fields]\nbirthday="date"` , no failure
- Deploy same config, no failure
- Do a link into a new file, see the above config preserved
> Drive DCDD from server specifications

- packages/app/src/cli/services/store-context.ts
Since the previous code was added, a new generic and shared function to add to gitignore was added to the code.
Use the shared function instead of a custom one.
1. Create a new Shopify app
2. Run any command that triggers store selection
3. Verify that the `.shopify` directory is added to `.gitignore`
4. Verify that running the command multiple times doesn't create duplicate entries
> Use the shared addToGitIgnore function

- packages/app/src/cli/services/dev/app-events/app-event-watcher.test.ts
- packages/app/src/cli/services/dev/app-events/app-event-watcher.ts
- packages/app/src/cli/services/dev/processes/dev-session.test.ts
- packages/app/src/cli/services/dev/processes/dev-session.ts
Improves error handling in the dev-session process by properly propagating and displaying errors that occur during the load, build and watch phases.
- Adds error event handling to the `AppEventWatcher` class
- Propagates build errors through the event system instead of writing directly to stderr
- Implements error handling for uncaught errors in the dev session
1. Start a dev-session
2. Make a change in a toml that would break validation (using a number were a string is expected)
3. Verify the error is corrrectly shown in the dev log in red.
> All validations errors should be handled by the dev-session

- .github/dependabot.yml
We are not grouping Dependabot PRs for some important dependencies, but then the separate PRs fail on CI because [we check that all the packages have the same version](https://github.com/Shopify/cli/blob/4aa84d12b46fe6af7530f9af9f62f2dca4f6f012/packages/features/steps/node-deps.steps.ts#L55) for them.
Example:
- https://github.com/Shopify/cli/pull/5141
- https://github.com/Shopify/cli/pull/5142
- https://github.com/Shopify/cli/pull/5143
- Create more groups for the important dependencies, so that we have a single PR for any of them
- Do not exclude them from `minor_versions`, because [if a dependency matches more than one rule, it's included in the first group that it matches](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#groups--) …
> Fix Dependabot groups

- packages/app/src/cli/services/dev/processes/dev-session-status-manager.ts
- packages/app/src/cli/services/dev/ui/components/DevSessionUI.test.tsx
- packages/app/src/cli/services/dev/ui/components/DevSessionUI.tsx
The current UI component was getting too complex to support both legacy and new dev, with many conditionals and adding more props.
This PR aims to solve that by creating a simpler UI component specific for dev-sessions. So that we can keep evolving this one without affecting the current dev behaviour.
- Creates a new `DevSessionUI` component
- Has the same shortcuts support as the old component
- Can receive status updates via an injected devSessionStatusManager.
Nothing to test, this component is not being used yet (will be in a following PR)
> Create a new UI component for DevSessions

- packages/app/src/cli/services/dev.ts
- packages/app/src/cli/services/dev/processes/dev-session-status-manager.test.ts
- packages/app/src/cli/services/dev/processes/dev-session-status-manager.ts
- packages/app/src/cli/services/dev/processes/dev-session.test.ts
- packages/app/src/cli/services/dev/processes/dev-session.ts
- packages/app/src/cli/services/dev/processes/setup-dev-processes.ts
- packages/app/src/cli/services/dev/ui.test.tsx
- packages/app/src/cli/services/dev/ui.tsx
Until now we've been using the `devSessionStatusManager` as a singleton instance.
We want to avoid singletons, so this PR converts it to a normal instance that is injected.
- Create a `devSessionStatusManager` instance before all dev processes
- Inject it to the `dev-session` process and the new `DevSessionUI` component.
- Start a dev session (start without any UI-extensions)
- Verify that the UI is valid
- Verify that adding a new ui-extension mid-dev, changes the previewURL in the terminal.
> Refactor devStatusManager from singleton to injected instance

- .changeset/giant-crews-act.md
- packages/theme/src/cli/utilities/theme-environment/proxy.test.ts
- packages/theme/src/cli/utilities/theme-environment/proxy.ts
Related to #5103
Fixes `/account/logout` route, and adds a temporary workaround for `/checkouts/...` to use the production domain while we figure out how to properly proxy checkout from localhost.
- Try adding items to the cart, then go to checkout. It should not show any 40x error. It should go to the .myshopify.com domain without the localhost proxy.
- Check that `/account/logout` doesn't show 40x error.
> [Theme] Fix local dev proxy for checkout and accounts/logout

- .changeset/curvy-kangaroos-flow.md
- packages/cli-kit/package.json
- packages/cli-kit/src/public/node/git.test.ts
- packages/cli-kit/src/public/node/git.ts
- pnpm-lock.yaml
Fixes https://github.com/Shopify/cli/issues/5286
Instead of manipulating raw strings, now `addToGitIgnore` uses the `ignore` module (already being used by [apps](https://github.com/Shopify/cli/blob/8b7f3b0b3e66a1d34498ff3026fc1b00363ee27b/packages/app/package.json#L71)), so we may prevent equivalent patterns from being added.
It's important to notice though, that not all patterns reported on Fixes https://github.com/Shopify/cli/issues/5286 are equivalent as we may notice in the screenshot below:
- Run `shopify theme metafields pull`
- Remove `.shopify/metafields.json`
- Remove any `.shopify` entry from `.gitignore`
- Notice that, when the `.shopify/metafields.json` file is created, an entry is also added in the `.gitignore`
N/A
> Improve mechanism that adds `.shopify` to `.gitignore` to avoid duplicate entries

- packages/cli-kit/src/private/node/session/validate.test.ts
- packages/cli-kit/src/private/node/session/validate.ts
Optimizes the token validation flow by deferring the identity token validation until after checking for token expiration, reducing unnecessary API calls.
- Moves the identity token validation check to occur after token expiration checks.
This one is hard to tophat:
1. Use the CLI with an expired token (wait two hours without using the CLI?)
2. Verify the token refresh flow is triggered without making unnecessary identity validation calls (running in verbose)
> Dont introspect token if already expired

- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/models/app/app.test.ts
- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/models/app/loader.ts
- packages/app/src/cli/services/dev.ts
Enables the CLI to patch app manifests with development URLs during local development, ensuring that app home, app proxy, and app access configurations use the correct development URLs instead of production URLs.
- Adds support for patching app manifests with development URLs during local development
- Introduces new test data helpers for app home and app proxy extensions
- Updates the app model to store and use development URLs when generating manifests
1. Create an app with app home, app proxy, and app access extensions
2. Run the dev command
3. Verify that the manifest (inside `./shopify/bundle`) includes the correct development URLs.
> Patch the app manifest with the development URLs, add tests

- configurations/vite.config.ts
- packages/app/vite.config.ts
Switches the default pool option for vitest to threads: https://vitest.dev/guide/improving-performance#test-isolation -- this should be quicker.
I tested this with hyperfine locally and found it improved performance. `--no-isolation` did not.
NB: I have left the apps package using the forked process approach: test clean-up isn't correct there at present.
> Improve vitest performance using thread pool

- packages/app/vite.config.ts
Running locally with benchmarking w/ hyperfine, the apps package appears to be stable with this change. It also seems to be a tad quicker. CI should confirm things more robustly.
> Switch packages/app to thread pooling for tests

- .vscode/settings.json
- packages/theme/src/cli/utilities/asset-checksum.test.ts
- packages/theme/src/cli/utilities/theme-ext-environment/theme-ext-fs.test.ts
- packages/theme/src/cli/utilities/theme-fs.test.ts
Cross-workspace vitest, as used by the vitest test explorer in the IDE, was broken due to file path issues. These are fixed.
> Fix cross-workspace vitest

- .github/workflows/codeql.yml
- .github/workflows/security-code-scanner.yml
The [default CodeQL setup](https://github.com/Shopify/cli/security/code-scanning/tools/CodeQL/status) is not working since April because of a [wrong configuration](https://github.com/Shopify/cli/security/code-scanning/tools/CodeQL/status/configurations/automatic/5e300aa741f4280a21b4dafff72a6b28743df548d4a6076cefecffe2bcbb76c1), but it doesn't show any error.
I tried to add the Security Code Scanner tool by Shopify in https://github.com/Shopify/cli/pull/5333, but it looks like [it's failing](https://github.com/Shopify/cli/actions/runs/13156133085/workflow) because it's not ready yet for public repos.
So I'm adding a custom CodeQL workflow, generated from GitHub with the default values. [It seems to work](https://github.com/Shopify/cli/actions/workflows/codeql.yml).
- Removes the Security …
> Add workflow for CodeQL Analysis

- packages/app/src/cli/api/graphql/app-management/generated/app-version-by-tag.ts
- packages/app/src/cli/api/graphql/app-management/queries/app-version-by-id.graphql
- packages/app/src/cli/api/graphql/app-management/queries/app-version-by-tag.graphql
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
Completes https://github.com/Shopify/develop-app-inner-loop/issues/1862
Depends on https://github.com/Shopify/shopify/pull/575881
We are fetching all the versions from app management, and then iterating through them to find the one we want, and then re-fetching that one with full details. But we should just fetch the one we want immediately.
Uses a new `versionByTag` field to query for just the version we want (also saves us a request).
* List versions of an app you've deployed with `p shopify app versions list` and choose a different version than is currently deployed. (Best if the app has some extensions.)
* `p shopify app release --version YOUR_VERSION_TAG`
* Ensure the version is found correctly
* Ensure the diff looks correct …
> Query app version directly by tag

- .changeset/stupid-starfishes-search.md
- packages/theme/src/cli/services/profile.test.ts
- packages/theme/src/cli/utilities/errors.test.ts
- packages/theme/src/cli/utilities/errors.ts
- packages/theme/src/cli/utilities/log-request-line.ts
- packages/theme/src/cli/utilities/repl/evaluator.ts
- packages/theme/src/cli/utilities/theme-environment/hot-reload/error-page.ts
- packages/theme/src/cli/utilities/theme-environment/hot-reload/server.test.ts
- packages/theme/src/cli/utilities/theme-environment/hot-reload/server.ts
- packages/theme/src/cli/utilities/theme-environment/html.ts
- packages/theme/src/cli/utilities/theme-environment/proxy.test.ts
- packages/theme/src/cli/utilities/theme-environment/proxy.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-renderer.test.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-renderer.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts
~[HOLD] -- This currently fails when the proxy logic gets a 401 or similar because H3 has already sent headers/status and we can't overwrite them.~
Fixes #5103 
Certain routes can't be rendered by SFR (e.g. app routes) and we must proxy them instead. We don't know before hand all of these routes, so this PR is adding a fallback: if a rendering fails with 4xx (the observed status errors for this situation), we try to proxy it. If the proxy doesn't work, we forward the original render error.
- Try going to `/account/logout` with `--verbose`. It should show that render failed and proxying worked.
- Then try `/not-found-path`. It should return the rendering error after trying the proxy (see logs).
> [Theme] Fix 401 and 405 for certain routes in local dev

- .changeset/khaki-snakes-stare.md
- packages/app/src/cli/utilities/extensions/theme/host-theme-manager.test.ts
- packages/app/src/cli/utilities/extensions/theme/host-theme-manager.ts
- packages/cli-kit/src/cli/api/graphql/admin/generated/theme_create.ts
- packages/cli-kit/src/cli/api/graphql/admin/mutations/theme_create.graphql
- packages/cli-kit/src/public/node/themes/api.test.ts
- packages/cli-kit/src/public/node/themes/api.ts
- packages/cli-kit/src/public/node/themes/theme-manager.ts
- packages/theme/src/cli/services/push.test.ts
- packages/theme/src/cli/services/push.ts
- packages/theme/src/cli/utilities/development-theme-manager.test.ts
- packages/theme/src/cli/utilities/repl/repl-theme-manager.test.ts
- packages/theme/src/cli/utilities/theme-selector.test.ts
- packages/theme/src/cli/utilities/theme-selector.ts
Migrate theme create to use GraphQL `themeCreate` mutation. Use [skeleton theme](https://github.com/Shopify/theme-skeleton) (minimal theme that contains only `theme.liquid`, `password.liquid`, and `settings_schema.json`) created my @jamesmengo 
`shopify theme dev` or `shopify theme push`
- running with theme directory creates a skeleton theme and pushes those file
- running without theme directory just creates a skeleton theme
> Migrate themeCreate to GraphQL 

- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.ts
- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/useSelfAdjustingInterval.test.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/useSelfAdjustingInterval.ts
We have had the occasional flakey test in usePollAppLogs. This affects our build process so is worth improving; I've taken a stab at it.
I broke out the self-adjusting interval element of the polling hook into its own hook and tests
I also adjusted the app log polling hook more generally:
- I pulled out the interesting/business logic part of the hook into a method. This leaves the hook a lot easier to reason about
- Within the hook, I used React references for any non-stateful instance variables
> Make usePollAppLogs tests more predictable

- nx.json
- packages/app/project.json
- packages/cli-kit/project.json
- packages/cli/project.json
- packages/create-app/project.json
- packages/plugin-cloudflare/project.json
- packages/plugin-did-you-mean/project.json
- packages/theme/project.json
- packages/ui-extensions-dev-console/project.json
- packages/ui-extensions-server-kit/project.json
This PR flattens the NX task graph for `lint`, `test` and their variations (e.g. `test:coverage`)
This makes running these tasks simpler and quicker -- there are no longer any pre-requisite activities. These activities may have been required at one time but as the project has evolved they have become redundant.
> Flatten nx graph

- packages/app/src/cli/services/init/init.ts
Fixes https://app.bugsnag.com/shopify/cli/errors/669725e0d6faad0008d97c40
Fixes a potential race condition where template files could be moved before the target app directory is properly prepared.
Adds a directory availability check before moving template scaffold files during app initialization. This ensures the output directory exists and is ready before file operations begin.
> Check if app directory exists just before moving temp copy

- packages/cli-kit/src/private/node/session/device-authorization.ts
- packages/cli-kit/src/public/node/system.ts
Fixes https://app.bugsnag.com/shopify/cli/errors/66ee2691df0c3356706e3473
Improves the authentication flow when the browser cannot be automatically opened by providing a fallback to display the authentication URL, as we would on an unsupported session.
Enhances the `openURL` function to return a boolean indicating success/failure of opening the URL. When the browser cannot be opened automatically, the CLI now displays a clickable link instead of propagating an exception.
> Handle if openUrl fails

- packages/cli-kit/src/public/node/cli.test.ts
- packages/cli-kit/src/public/node/cli.ts
The CLI currently only warns users when running on an unsupported Node.js version. This can lead to potential security risks and compatibility issues if users continue using outdated versions.
Changes the behavior when detecting an old Node.js version from showing a warning to displaying an error and exiting the process. This enforces the requirement to use supported Node.js versions.
Run `nvm use 16`. Run the CLI, confirm you see an error message and the CLI exits.
> Check for invalid node engine before running commands

- packages/app/src/cli/models/extensions/schemas.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.ts
Fixes: https://github.com/Shopify/bundles-app/issues/2953?issue=Shopify%7Cbundles-app%7C2995 according to https://vault.shopify.io/gsd/projects/42594
Adds an additional `urls` field on the schema related to the link extension object.
All tests pass. Sea of green 
Run tests in the `packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts` file.
> Modify Schema to Support Link Extension URL

- .github/workflows/release-manual.yaml
- bin/release
Updates the default release tag from "latest" to "nightly" and adds conditional logic for Homebrew and documentation updates.
- Changes the default release tag from "latest" to "nightly" in both the GitHub workflow and release script -> Safer to default to `nightly`
- Adds required permissions for contents and pull-requests in the GitHub workflow -> test to see if this is enough to open a PR in a private repo.
- Makes Homebrew and documentation PR creation conditional, only running when the tag is "latest"
1. Trigger a manual release without specifying a tag to verify it defaults to "nightly"
2. Trigger a release with "latest" tag to verify Homebrew and documentation PRs are created
3. Trigger a release with "nightly" or "experimental" tags to verify no additional PRs are created
> Improve manual release script

- packages/app/src/cli/commands/app/generate/extension.ts
- packages/app/src/cli/commands/app/versions/list.ts
- packages/cli/README.md
- packages/cli/oclif.manifest.json
A couple of commands have a `file` static argument, unused and undocumented: [app generate extension](https://github.com/Shopify/cli/blob/663aae197960a6848cb93a098906d83b69e5219e/packages/app/src/cli/commands/app/generate/extension.ts#L66), [app versions list](https://github.com/Shopify/cli/blob/663aae197960a6848cb93a098906d83b69e5219e/packages/app/src/cli/commands/app/versions/list.ts#L31)
Remove them
- `p shopify app generate extension`
- `p shopify app generate extension --help`
- `p shopify app versions list`
- `p shopify app versions list --help`
> Remove unused args

- packages/theme/src/cli/services/profile.ts
Improves logging / ability to debug issues with `theme profile`. This will help debug will `theme profile` is not working on WSL
Motivation: https://github.com/Shopify/cli/issues/5414
- Add debug logs to improve our visibility into the `theme profile` command
> [Themes] Improve instrumentation in theme profile service

- .changeset/violet-carrots-argue.md
- packages/cli-kit/src/public/node/hooks/postrun.ts
- packages/cli-kit/src/public/node/hooks/prerun.ts
- packages/cli-kit/src/public/node/notifications-system.test.ts
- packages/cli-kit/src/public/node/notifications-system.ts
- packages/cli-kit/src/public/node/system.ts
- packages/cli/src/cli/services/commands/notifications.ts
Fixes https://app.bugsnag.com/shopify/cli/errors/673374fe41bcaf15edcf8ac7
> [!NOTE]
> There was a first attempt (https://github.com/Shopify/cli/pull/5020) reverted in https://github.com/Shopify/cli/pull/5234
> 
> The difference from the previous PR:
> - The process is run in background only for Mac/Linux, because in Windows it opens a new terminal window
> - The process is run at the beginning of the command (prerun) instead of the end (postrun), so most of the times the fetch will finish before the command itself.
We were fetching the notifications at the beginning of each command and caching the result for 1 hour. That approach has two disadvantages:
- When the network operation hangs or takes too long (the timeout is 3 seconds), the command has to wait with no feedback for the user …
> Fetch notifications in background II

- .changeset/tender-flowers-mate.md
- packages/theme/src/cli/utilities/theme-environment/html.test.ts
- packages/theme/src/cli/utilities/theme-environment/html.ts
Fixes https://github.com/Shopify/cli/issues/5377
This PR updates the function that asserts the matching theme ID, introducing a mechanism to recover in those scenarios.
https://share.descript.com/view/Qcj4DzKFmfz
N/A
> Improve `shopify theme dev` to recover when theme ID mismatch errors happen

- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/app/loader.ts
- packages/app/src/cli/services/app/patch-app-configuration-file.test.ts
- packages/app/src/cli/services/app/patch-app-configuration-file.ts
- packages/app/src/cli/services/store-context.test.ts
The current implementation stores dev store URLs in a flat structure, which can lead to conflicts when developers work with multiple organizations. This change introduces app-specific storage of dev store URLs.
Updates the hidden configuration structure to store dev store URLs under app-specific keys, preventing conflicts when connecting to different organizations. The change includes:
- Modifying the `AppHiddenConfig` interface to use app names as keys
- Using deep merge for config updates
- Updating store context handling to reference app-specific store URLs
Example:
```
{
"testa8e113c942b95b54c1d0ffbc2": {
"dev_store_url": "test-store-3.myshopify.com"
},
"test6f7048e1a203d6ae64c601f1": {
"dev_store_url": "test-store-2.myshopify.com"
}
}
```
1. Create multiple app configurations in your …
> Store hidden config per client ID

- packages/app/src/cli/services/dev/app-events/app-event-watcher-handler.ts
- packages/app/src/cli/services/dev/app-events/app-event-watcher.test.ts
- packages/app/src/cli/services/dev/app-events/app-event-watcher.ts
- packages/app/src/cli/services/dev/processes/dev-session.test.ts
- packages/app/src/cli/services/dev/processes/dev-session.ts
Improve DevSession feedback by showing the current status in the dynamic section of the terminal log footer.
- Adds specific error cause for app validation errors
- Introduces new status message handlers for different dev session states (build errors, ready state, loading, etc.)
- Ensures proper status updates when extensions are affected by changes
1. Run `dev` command with dev-sessions enabled.
2. Verify status messages appear correctly for:
- Initial loading state
- Build errors (make a bad change in a extension code)
- Validation errors (make a bad change in a toml file)
- Successful updates
- Ready state
3. Confirm status message automatically resets to "Ready" 2 seconds after an update
> Emit status events from dev-session

- .changeset/famous-lemons-work.md
- packages/cli-kit/src/private/node/api.test.ts
- packages/cli-kit/src/private/node/api.ts
- packages/cli-kit/src/private/node/constants.ts
- packages/cli-kit/src/private/node/sleep-with-backoff.test.ts
- packages/cli-kit/src/private/node/sleep-with-backoff.ts
- packages/cli-kit/src/public/node/environment.ts
Network errors during API calls can be transient and should be automatically retried to improve reliability. Currently, the CLI only retries on explicit rate limit errors (code 429), but should also handle common network issues like DNS failures or connection timeouts, where we are confident this is the cause of the issue.
Network level retries are based on an elapsed time limit -- there are 10 seconds between starting the first attempt at the request and the retry loop being stopped. On each iteration of the retry loop, the delay is doubled. The first delay is 300ms, then 600 and so on.
The retry logic is implemented at a low level, and will affect all GraphQL and fetch requests made through CLI Kit. This includes non-GraphQL calls to `identity`.
Response-based retries -- using the HTTP …
> Network error request retries

- .changeset/two-bottles-dance.md
- packages/app/src/cli/services/app-logs/dev/poll-app-logs.test.ts
- packages/app/src/cli/services/app-logs/utils.ts
- packages/app/src/cli/services/deploy/upload.ts
- packages/app/src/cli/services/dev/processes/dev-session.ts
- packages/app/src/cli/services/function/binaries.ts
- packages/cli-kit/package.json
- packages/cli-kit/src/private/node/api.test.ts
- packages/cli-kit/src/private/node/api.ts
- packages/cli-kit/src/private/node/constants.ts
- packages/cli-kit/src/private/node/sleep-with-backoff.ts
- packages/cli-kit/src/public/node/api/admin.test.ts
- packages/cli-kit/src/public/node/api/admin.ts
- packages/cli-kit/src/public/node/api/graphql.test.ts
- packages/cli-kit/src/public/node/api/graphql.ts
- packages/cli-kit/src/public/node/environment.ts
- packages/cli-kit/src/public/node/http.test.ts
- packages/cli-kit/src/public/node/http.ts
- packages/cli-kit/src/public/node/monorail.test.ts
- packages/cli-kit/src/public/node/monorail.ts
- packages/cli-kit/src/public/node/notifications-system.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-session.test.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-session.ts
- pnpm-lock.yaml
Improves network request handling in the CLI by introducing configurable request behaviours, timeouts, and retries. This enhances reliability and responsiveness of network operations across the codebase.
These are available for fetch & shopifyFetch, and used by the GraphQL stack.
These changes are backward-compatible for public interfaces in CLI kit, and test coverage for network APIs is greatly increased.
- Introduces `requestMode` to configure network request behaviors with presets:
- `default`: Automatic retries and timeouts
- `non-blocking`: No retries, with timeouts
- `slow-request`: No retries or timeouts -- i.e. neutral
- Adds configurable abort signals and timeout controls for requests
- Enhances request retry logic with better error handling
- Updates network calls across the …
> Controllable request behaviour

- .github/workflows/release.yml
- bin/release
The release script will fail in the next release cycle if we don't change this.
Fixes permissions issues in the GitHub Actions release workflow. We need those to sign with provenance in the next release.
Nothing to test, just wait for the next release and see that the release script works.
> Add missing permissions to the release workflow

- packages/app/src/cli/api/graphql/app-management/generated/create-app-version.ts
- packages/app/src/cli/api/graphql/app-management/generated/types.d.ts
- packages/app/src/cli/api/graphql/app-management/queries/create-app-version.graphql
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
Following up to https://github.com/Shopify/cli/pull/5436 per [this issue](https://github.com/Shopify/develop-app-inner-loop/issues/2530). Per these issues, we've updated the API shape on the back-end and need to update the CLI to match.
This changes the `CreateAppVersion` GraphQL call to use the updated `AppVersionInput` data shape. I've also added an `AppVersionSourceWithUrl` interface to help to ensure that we're conforming to the API locally. See the [previous PR](https://github.com/Shopify/cli/pull/5436) for a brief discussion of that.
We also didn't have any tests for the `deploy` command, so I've added some.
- `p shopify app init`
- `p shopify app deploy` - which will exercise the non-source-url branch
- `p shopify app generate extension` and pick e.g. Admin Action or another …
> Update mutation variables for AppVersionCreate

- packages/app/src/cli/services/translate/utilities.ts
An empty manifest is (I think) `[{}]`, not `{}`. Otherwise it crashes when no translation files.
> fix empty manifest

- .changeset/cold-radios-applaud.md
- packages/theme/src/cli/services/metafields-pull.test.ts
- packages/theme/src/cli/services/metafields-pull.ts
Part of https://github.com/Shopify/theme-tools/issues/724
When CLI is run from language-server `ensureDirectoryConfirmed` will ALWAYS return `true` since the user can't input yes/no when dealing with non-theme directories.
- This means that `metafields.json` will always be fetched (even for non-theme projects)
Instead of changing the behavior of `ensureDirectoryConfirmed`, we (@karreiro and I) decided to add an env var that can be processed by CLI. This env var would only be set when run from the language-server.
- Ensures metafield definitions can't be force-fetched when running from language-server (VSCode extension)
- Build the CLI
- `pnpm run build`
- In theme-tools change `fetchMetafieldDefinitionsForURI` so that it points to a built version of this branch (i.e. …
> CLI can't force fetch metafields when run by language-server

- .changeset/few-islands-visit.md
- packages/app/package.json
- packages/theme/package.json
- pnpm-lock.yaml
Ideally the final piece of fixing the CLI for Windows platform
Part of https://github.com/Shopify/cli/issues/3497
Previous PR: https://github.com/Shopify/theme-tools/pull/835
- Bumping theme check packages so that it can theme check on windows
- n/a
- install the snapshot on a windows system (i.e. `npm i -g @shopify/cli@0.0.0-snapshot-20250312183234`)
- run `shopify theme check` on a theme on the windows system
- see theme check errors
BEFORE
AFTER (Powershell)
AFTER (cmd)
> Bump theme check packages

- .changeset/great-clocks-dress.md
- packages/theme/src/cli/utilities/theme-environment/html.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts
Requests using Section Rendering API and such don't need the proxy fallback since we are sure they are supposed to go to SFR. This is a quick fix to make logs easier for an issue that @jamesmengo is debugging.
> [Themes] Skip proxy fallback for known rendering requests

- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/extensions/load-specifications.ts
- packages/app/src/cli/models/extensions/specification.ts
- packages/app/src/cli/models/extensions/specifications/app_config_app_access.ts
- packages/app/src/cli/models/extensions/specifications/app_config_app_home.ts
- packages/app/src/cli/models/extensions/specifications/app_config_app_proxy.ts
- packages/app/src/cli/models/extensions/specifications/app_config_branding.ts
- packages/app/src/cli/models/extensions/specifications/app_config_point_of_sale.ts
- packages/app/src/cli/models/extensions/specifications/app_config_webhook_schemas/webhooks_schema.ts
- packages/app/src/cli/services/context/identifiers-extensions.test.ts
The WHY is explained in the previous PR in the stack, but basically:
ALL extensions schemas should inherit from the same BaseSchema so that we can properly use generics and access the typed configuration correctly.
TL;DR
Thanks to this we move from:
```ts
if ('application_url' in config) {
config.application_url = urls.applicationUrl
}
```
to just
```
config.application_url = urls.applicationUrl
```
- Adds proper type annotations to extension specification schemas
- Extends `BaseSchema` in all app config schemas for consistency
- Adds missing transformation configurations for app proxy and point of sale extensions (these are needed so that no additional properties are accidentally included)
1. Run the test suite to ensure all tests pass
2. Create a new app with various extension types to …
> Config modules schemas inherit from BaseSchema

- packages/app/src/cli/commands/app/dev.ts
Implemented feedback on the `--use-localhost` preview banner language.
> Localhost banner language feedback

- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
Fixes https://github.com/Shopify/develop-app-outer-loop/issues/1277
This PR should be merged first: https://github.com/shop/world/pull/14765
Caches the result of the query to retrieve the asset URL for 59 minutes (under 1h, which will be the expiration of the URLs), so that it can be re-used during a dev session, instead of making an extra request on every update (330ms to 1s).
`shopify app dev` with App Management API
To simplify, I've actually used `cacheTTL: {minutes: 2}`, so that I could wait for the expiration and it can be tested against production, where the URL only works for 5 min.
> Cache CreateAssetURL for 1h

- .changeset/hip-mayflies-film.md
- packages/app/src/cli/api/graphql/app-management/generated/app-logs-subscribe.ts
- packages/app/src/cli/api/graphql/app-management/queries/app-logs-subscribe.graphql
- packages/app/src/cli/api/graphql/subscribe_to_app_logs.ts
- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/services/app-logs/dev/poll-app-logs.test.ts
- packages/app/src/cli/services/app-logs/dev/poll-app-logs.ts
- packages/app/src/cli/services/app-logs/logs-command/poll-app-logs.test.ts
- packages/app/src/cli/services/app-logs/logs-command/poll-app-logs.ts
- packages/app/src/cli/services/app-logs/logs-command/render-json-logs.test.ts
- packages/app/src/cli/services/app-logs/logs-command/render-json-logs.ts
- packages/app/src/cli/services/app-logs/logs-command/ui.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/Logs.test.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/Logs.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.test.tsx
- packages/app/src/cli/services/app-logs/logs-command/ui/components/hooks/usePollAppLogs.ts
- packages/app/src/cli/services/app-logs/types.ts
- packages/app/src/cli/services/app-logs/utils.ts
- packages/app/src/cli/services/dev/processes/app-logs-polling.test.ts
- packages/app/src/cli/services/dev/processes/app-logs-polling.ts
- packages/app/src/cli/services/dev/processes/setup-dev-processes.test.ts
- packages/app/src/cli/services/dev/processes/setup-dev-processes.ts
- packages/app/src/cli/services/logs.test.ts
- packages/app/src/cli/services/logs.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
- packages/cli-kit/src/public/node/api/app-management.ts
- packages/cli-kit/src/public/node/api/partners.ts
- packages/cli-kit/src/public/node/api/utilities.ts
Requires: https://github.com/Shopify/cli/pull/5497
Requires: Partners - js.app-logs-prototype-2Request: Core - 03-07-expose_dev_dash_route_to_manage_app_logs
Part of: https://github.com/Shopify/temp-project-mover-Archetypically-20250320163947/issues/137
This PR adds app logs functionality to the `AppManagementClient`, allowing app logs to be fetched through the Developer Platform client interface. 
Key changes:
- Implemented `subscribeToAppLogs` and `appLogs` methods in `AppManagementClient`
- Updated the `DeveloperPlatformClient` interface to include `organizationId` and `appId` parameters
- `PartnersClient` will ignore them
- Added new `fetchAppLogsDevDashboard` in `utils`
- Updated all app logs related components to pass through organizationId and appId
All tests have been updated to …
> Integrates subscribe and fetchAppLogs with developer dashboard 

- packages/cli-kit/src/public/node/themes/api.ts
- packages/eslint-plugin-cli/config.js
- packages/plugin-cloudflare/src/install-cloudflared.test.ts
- packages/plugin-cloudflare/src/install-cloudflared.ts
- packages/theme/src/cli/utilities/notifier.ts
- packages/theme/src/cli/utilities/theme-environment/proxy.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-renderer.ts
To ensure that HTTP proxy support is maintained across the CLI by enforcing the use of our custom fetch implementation instead of Node.js built-in fetch.
Adds an ESLint rule to restrict the use of the global `fetch` function, requiring developers to use our custom implementation from `@shopify/cli-kit/node/http` instead. The built-in Node.js fetch doesn't support HTTP proxies, which can cause issues for users behind corporate proxies.
The PR:
- Adds a new ESLint rule `no-restricted-globals` to flag usage of the global fetch
- Adds appropriate `eslint-disable-next-line` comments to existing fetch usages that are exceptions
> Enforce in-house fetch function

- packages/app/src/cli/services/dev/app-events/app-watcher-esbuild.test.ts
- packages/app/src/cli/services/dev/app-events/app-watcher-esbuild.ts
When an app is reloaded, the ESBuild contexts need to be recreated for updated ui-extensions because the toml could have been updated with relevant changes.
Fixes https://github.com/Shopify/develop-app-outer-loop/issues/1282
Update the filter condition in `updateContexts()` to also handle updated extensions when `appWasReloaded` is true
1. Run a dev-session with an app that uses ui-extensions
2. Change the handle of the extension during dev
3. See that the session is updated correctly.
> Recrate ui-extension ESBuild contexts when updating the toml

- packages/app/src/cli/services/deploy.ts
- packages/app/src/cli/services/deploy/bundle.test.ts
- packages/app/src/cli/services/deploy/bundle.ts
- packages/app/src/cli/services/dev/app-events/app-event-watcher.ts
- packages/app/src/cli/services/dev/processes/dev-session/dev-session.ts
To improve visibility of the code that's actually being deployed.
Instead of creating the "bundle" in a temporary folder, store it under `.shopify` so if a user really wants to, they can access the deployed code.
Renames bundle files to be more descriptive of their purpose:
FOR DEPLOY:
- Changes `bundle.zip` to `deploy-bundle.zip`
- Changes the bundle directory path to use `.shopify/deploy-bundle` instead of a temporary directory
FOR DEV:
- Renames the dev bundle to `dev-bundle.zip` and its directory to `.shopify/dev-bundle`
These changes make it clearer which bundles are for deployment and which are for development, improving maintainability and debugging.
1. Run `shopify app deploy` and verify that the bundle is created with the new name `deploy-bundle.zip`
2. Run `shopify app dev` and …
> Store deploy artifacts in `.shopify`

- packages/app/src/cli/models/app/app.test.ts
- packages/app/src/cli/models/extensions/extension-instance.test.ts
- packages/app/src/cli/models/extensions/extension-instance.ts
- packages/app/src/cli/services/context/identifiers-extensions.test.ts
- packages/app/src/cli/services/deploy.test.ts
- packages/app/src/cli/services/dev/app-events/app-event-watcher.test.ts
We need to follow `uidStrategy` when building the `uid`. Specifically we need to fix it for the `single` case and use the spec identifier in that case.
Refactors the extension instance UID generation by:
- Creating a dedicated `buildUIDFromStrategy` method to handle UID generation based on the extension's strategy
1. This doesn't imply any change in functionality. You can try deploying an app with different types of extensions
> Build UID using uidStrategy

- packages/app/src/cli/services/dev/processes/app-watcher-process.ts
- packages/app/src/cli/services/dev/processes/dev-session/dev-session-logger.test.ts
- packages/app/src/cli/services/dev/processes/dev-session/dev-session-logger.ts
- packages/app/src/cli/services/dev/processes/dev-session/dev-session-process.test.ts
- packages/app/src/cli/services/dev/processes/dev-session/dev-session-process.ts
- packages/app/src/cli/services/dev/processes/dev-session/dev-session-status-manager.test.ts
- packages/app/src/cli/services/dev/processes/dev-session/dev-session-status-manager.ts
- packages/app/src/cli/services/dev/processes/dev-session/dev-session.ts
- packages/app/src/cli/services/dev/processes/setup-dev-processes.test.ts
We should better say `app preview` externally
Renames `dev session` references in logs and prompts to `app preview`
`p shopify app dev` against dev platform
> Rename dev session to app preview

- packages/cli/package.json
- pnpm-lock.yaml
Fix global-agent with a strict version
> Fix global-agent with a strict version

- packages/app/src/cli/services/bundle.test.ts
- packages/app/src/cli/services/bundle.ts
- packages/cli-kit/src/public/node/archiver.ts
Fixes https://github.com/Shopify/develop-app-outer-loop/issues/1453
Removes the unrequired *.js.map files from the zip bundle for both dev and deploy
Dev and deploy with UI extensions
> Exclude map files from the app bundle

- packages/app/src/cli/utilities/app/http-reverse-proxy.test.ts
In `http-reverse-proxy.test.ts`, the test setup acquires 3 ports: `proxyPort`, `targetPort1`, and `targetPort2` using `getAvailableTCPPort`. We were previously requesting these ports concurrently using `Promise.all`. This created a small possibility of a race condition where the same available port could be selected by multiple concurrent requests before being bound, potentially leading to test failures.
This PR modifies the port acquisition to use sequential `await` calls. Each port request now waits for the previous one to complete, ensuring distinct ports are highly likely to be assigned for the test setup.
- run `npx vitest run packages/app/src/cli/utilities/app/http-reverse-proxy.test.ts` to directly run the changed test.
How do we know this …
> Change http reverse proxy test to await TCP port test individually

- .changeset/orange-poems-give.md
- package.json
- packages/app/src/cli/models/app/app.test.ts
- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/app/loader.ts
- packages/app/src/cli/models/extensions/extension-instance.ts
- packages/app/src/cli/models/extensions/specification.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.ts
- packages/app/src/cli/services/dev/app-events/app-watcher-esbuild.ts
- packages/app/src/cli/services/generate.ts
- packages/app/src/cli/services/generate/extension.test.ts
- packages/app/src/cli/services/generate/extension.ts
- packages/app/src/cli/services/generate/fetch-template-specifications.test.ts
- packages/app/src/cli/services/generate/fetch-template-specifications.ts
- packages/cli-kit/src/public/node/is-polaris-unified-enabled.test.ts
- packages/cli-kit/src/public/node/is-polaris-unified-enabled.ts
Related to https://github.com/Shopify/app-ui/issues/2158
Enables support for Remote DOM UI extensions when using the `REMOTE_DOM_EXPERIMENT` environment variable.
1. Checkout this branch and set your `CLI_KIT_VERSION` to `3.78.0`
1. Grab the relative path to the directory for an existing app (or create one using `pnpm create-app` if you don't have one)
1. Create a remote ui extension by running `pnpm shopify app generate --path <app-directory>`
1. Select an Admin Block extension and chose the Typescript React template
1. Verify that it successfully creates the remote-ui block extension
1. Select a Checkout UI extension and chose the Typescript React template
1. Verify that it successfully creates the checkout-ui extension
1. Create a remote dom extension by running …
> Support Remote DOM ui extensions

- packages/theme/src/cli/utilities/theme-environment/storefront-renderer.test.ts
- packages/theme/src/cli/utilities/theme-environment/storefront-renderer.ts
This is just an internal fix but it shouldn't affect anything outside.
We were incorrectly replacing the method for every request to Section Rendering API with `POST`, even though we only need to do that when `replace_templates` is sent.
> [Theme] Stop replacing request method when calling Section Rendering API without `replace_templates`

- packages/app/src/cli/services/generate/fetch-template-specifications.ts
Address [issue](https://github.com/Shopify/cli/pull/5560#discussion_r2035299467) where the variable isn't named correctly
Rename variable to `polarisUnifiedEnabled`
Internal change - unit tests are sufficient.
> Rename internal polarisUnifiedEnabled variable for consistency

- .cursor/rules/base.mdc
- .cursor/rules/docs.mdc
Add a dedicated `.cursor` directory and point to original rule as `base` + point to existing documentation.
> add cursor directory

- packages/cli-kit/src/public/node/themes/api.test.ts
- packages/cli-kit/src/public/node/themes/api.ts
Removing the hard coded GraphQL version for the `themeCreate` mutation since the stable release is >= `2025-04` .
Didn't forget 😛 https://github.com/Shopify/cli/pull/5249#discussion_r1949997344
Tests pass and `shopify theme init` action work as is.
> Remove GQL version from themeCreate API

- .changeset/big-singers-pump.md
- packages/app/src/cli/models/app/app.test.ts
- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/models/extensions/extension-instance.ts
- packages/app/src/cli/models/extensions/specification.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.ts
Create a shopify.d.ts for each module that have a `tsconfig` to prevent JSX type collision between extensions.
1. Checkout this branch 
1. Grab the relative path to the directory for an existing app (or create one using `pnpm create-app` if you don't have one)
1. Create a remote dom extension by running `POLARIS_UNIFIED=true pnpm shopify app generate extension --path <your-app-directory>`
1. Select an Admin Block extension
1. Run `pnpm shopify app dev --path <your-app-directory>`
1. Verify that runs successfully.
NOTE: You will see errors relating to updating the drafts like "Error while updating drafts: "2025-07" is not a valid API version" - this is expected until `2025-07` is publicly available.
1. Open the remote-dom Block extension's TOML file and update the target
1. Verify that …
> Improve type definition support for POLARIS_UNIFIED extensions

- .changeset/funny-pots-visit.md
- packages/cli-kit/src/public/common/object.test.ts
- packages/cli-kit/src/public/common/object.ts
The current implementation of path-based operations (`getPathValue`, `setPathValue`, `unsetPathValue`) doesn't support property names that contain dots. When using string paths, lodash interprets dots as path separators for nested objects, making it impossible to directly access properties whose names contain dots.
For example, attempting to access a property named `"some.property"` would be interpreted as trying to access `property` inside the `some` object, rather than accessing the property literally named `"some.property"`.
This PR updates the parameter types for `getPathValue`, `setPathValue`, and `unsetPathValue` to use lodash's `PropertyPath` type instead of just `string`. This enables using array notation (`['some.property']`) to access properties with dots in their names.
The …
> Use `PropertyPath` in path value methods

- packages/app/src/cli/commands/app/dev/clean.ts
- packages/app/src/cli/index.ts
- packages/cli/README.md
- packages/cli/oclif.manifest.json
Add a new commend `app dev clean` to clean up app previews.
Adds a new hidden command `shopify app dev clean` that:
- Stops the app preview that was started with `shopify app dev`
- Restores the app active version to the selected development store
The command accepts the same flags as other app commands, including `--store` to specify which store to clean up from.
1. Start an app preview with `shopify app dev`
2. Run `shopify app dev clean` to stop the preview
3. Verify that the success message appears and the app active version is restored
> Add app:dev:clean command to stop app previews

- packages/cli-kit/src/public/node/tcp.test.ts
- packages/cli-kit/src/public/node/tcp.ts
To prevent port conflicts when multiple processes request random TCP ports in quick succession. If a caller doesn't use a port immediately, a duplicate random port can be chosen.
Enhances the `getAvailableTCPPort` function to track previously obtained random ports and ensure they aren't reused within the same process. This is accomplished by:
1. Adding a `obtainedRandomPorts` Set to keep track of ports that have been assigned
2. Adding logic to check if a random port has already been obtained and retry if necessary
3. Adding the obtained port to the tracking Set before returning it
Added a test case to verify that random ports are not reused.
> Remember randomly selected ports, and don't reuse them

- packages/cli-kit/src/private/node/ui/components/TextAnimation.tsx
The text animation component doesn't currently respond to terminal window resizing, and creates weird artifacts when resizing it.
Adds terminal resize handling to the TextAnimation component by:
- Dynamically calculating the width based on terminal size
- Updating the animation width when the terminal size changes
Run `pnpm shopify kitchen-sink:async` and resize your terminal.
> Improve loading bar resizes

- .changeset/tasty-terms-brake.md
- packages/app/src/cli/api/graphql/business-platform-destinations/generated/user-info.ts
- packages/app/src/cli/api/graphql/business-platform-destinations/queries/user-info.graphql
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/cli-kit/src/private/node/session/exchange.test.ts
- packages/cli-kit/src/private/node/session/exchange.ts
- packages/cli-kit/src/private/node/session/scopes.test.ts
- packages/cli-kit/src/private/node/session/scopes.ts
- packages/cli-kit/src/public/node/context/local.test.ts
- packages/cli-kit/src/public/node/context/local.ts
- packages/cli-kit/src/public/node/session.test.ts
- packages/cli-kit/src/public/node/session.ts
Closes 
- https://github.com/shop/issues-app-access/issues/689
Add support to use the CLI token for app management API
- Remove `isAppManagementDisabled()` function that disables App Management API if a CLI Token is provided
- Perform token exchange with **AppMangement API** and **BusinessPlatform API** if a CLI token is provided when creating a session for **AppManagmentClient**, and assign those access token as a `ServiceAccount` user
- Extend `UserInfo` query to get the first 2 organizations the user/CLI token service account belongs to
- This assumes the CLI Token will always only belong to a single organization and raise an exception if the CLI Token belong in multiple orgs
- ⚠️ With this change, CLI Tokens will be used to exchange for `Partners API`, `BP API` and `App Management …
> Add CLI token support for app management and BP API

- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
- Append `Partner Dashboard` to partner organizations
- Append `Dev Dashboard` to dev dash organizations
Examples:
> Identification for partner or dev dash orgs

- .changeset/thirty-kings-add.md
- packages/app/src/cli/services/app-context.test.ts
- packages/app/src/cli/services/app-context.ts
When forcing a relink of an app, the system was still using the cached configuration file name, which made the overwrite the existing config.
Fixes https://github.com/Shopify/cli/issues/5653
Modifies the `linkedAppContext` function to set the `configName` to `undefined` when `forceRelink` is true, allowing users to be prompted for a new configuration file name instead of using the cached one.
1. Run a command with `--reset`
2. Verify that you are prompted to select a configuration file name
3. Confirm that the new configuration file is used after relinking
> Don't use cached config name when using `--reset`

- .changeset/stale-melons-invent.md
- packages/app/package.json
- packages/theme/package.json
- pnpm-lock.yaml
- Bumping theme check and language libraries
- I created a static block and a snippet with LiquidDoc and created a bunch of errors to test if `shopify theme check` captures those warnings introduced in the updated libs
- Create a block or snippet with LiquidDoc
- Render the snippet using `render` tag
- Render the static block using `content_for` tag
- Get errors for missing arguments, mismatched arg type, unrecognized arg, and duplicate args
n/a
> Bump theme check & language libs

- packages/cli-kit/src/public/node/environment.ts
The default timeout for network calls is too short, causing unnecessary timeouts in some cases.
Increases the default timeout for network calls from 15 seconds to 30 seconds in the `maxRequestTimeForNetworkCallsMs` function.
1. Make a deploy with 50+ functions, see that it doesn't timeout
2. If it does, verify that requests now timeout after 30 seconds instead of 15 seconds with --verbose
> Increase default request timeout to 30s

- .changeset/quick-planes-try.md
- packages/app/src/cli/api/graphql/business-platform-organizations/generated/types.d.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
Merge fixes from this [PR](https://github.com/Shopify/cli/pull/5700)
Follow testing steps from this [PR](https://github.com/Shopify/cli/pull/5700)
We need to release a patch
> Merge main fixes

- .changeset/seven-jeans-run.md
- packages/app/package.json
- packages/app/src/cli/constants.ts
- packages/app/src/cli/services/app/patch-app-configuration-file.test.ts
- packages/app/src/cli/services/app/patch-app-configuration-file.ts
- packages/app/src/cli/services/app/toml-patch-wasm.test.ts
- packages/app/src/cli/services/app/toml-patch-wasm.ts
- packages/cli/bin/bundle.js
- pnpm-lock.yaml
To improve TOML file manipulation by adding a WASM-based implementation for patching app configuration files.
- Adds `@shopify/toml-patch` dependency (v0.2.0) to handle TOML file modifications
- Adds a feature flag `SHOPIFY_CLI_USE_WASM_TOML_PATCH` to toggle between implementations. Off by default.
1. Set the environment variable `SHOPIFY_CLI_USE_WASM_TOML_PATCH=true`
2. Make a new DP2 app
3. Edit the TOML file to put some formatting/comments in
4. Run `shopify app dev`
5. See that `automatically_update_urls_on_dev` is set -- i.e. the file is written to -- but your formatting is not broken
> Add dependency on @shopify/toml-patch

- packages/app/src/cli/services/dev/ui.tsx
- packages/app/src/cli/services/dev/ui/components/DevSessionUI.test.tsx
- packages/app/src/cli/services/dev/ui/components/DevSessionUI.tsx
- packages/cli-kit/src/public/node/ui/components.ts
Support persistent app previews.
- Adds a user-friendly message when a persistent dev session remains active.
1. Run `shopify app dev`
2. Wait for the app preview to be ready
3. Press Ctrl+C to terminate the CLI process
4. Verify that the message about the app preview still being active appears
5. Run `shopify app dev clean` to clean up the persistent session
> Add persistent dev mode support to DevSessionUI

- .changeset/twenty-lamps-behave.md
- packages/theme/src/cli/services/push.test.ts
- packages/theme/src/cli/services/push.ts
I need to show the errors from a theme preview GitHub Action that we have for Horizon.
Adds the upload `"errors"` to the JSON output from `shopify theme push --json`.
I added a unit test. If you want to test it manually, run `shopify theme push --json` with an invalid theme (but NOT theme check invalid! upload invalid.)
> Add actual "errors" to `shopify theme push --json` output

- .changeset/moody-chairs-divide.md
- packages/cli-kit/src/public/node/is-global.test.ts
- packages/cli-kit/src/public/node/is-global.ts
- packages/cli-kit/src/public/node/version.test.ts
- packages/cli-kit/src/public/node/version.ts
Related to https://github.com/Shopify/cli/issues/5600#issuecomment-2807041478
In some cases, the two installations warning is not working as expected, showing the message when there is no global version.
Until now, we basically ran the `shopify` command internally to see if there is a global version. But it turns out that execa, the library we use to run external binaries, is actually running the local dependency sometimes, giving false positives.
- Before running `shopify`, check the path of the `shopify` binaries found with the `which` library and discard the local ones (including`node_modules`)
- Unify the methods to check the global version: we were running `shopify version` in one place and `shopify app dev` in another, because it's faster. Now we just use `shopify` in both, which is …
> Improve global CLI detection

- .changeset/nice-ducks-shop.md
- packages/app/src/cli/models/extensions/extension-instance.ts
- packages/app/src/cli/models/extensions/specification.ts
- packages/app/src/cli/models/extensions/specifications/app_config_app_access.test.ts
- packages/app/src/cli/models/extensions/specifications/app_config_app_access.ts
- packages/app/src/cli/services/dev/processes/dev-session/dev-session-logger.test.ts
- packages/app/src/cli/services/dev/processes/dev-session/dev-session-logger.ts
- packages/app/src/cli/services/dev/processes/dev-session/dev-session-process.test.ts
- packages/app/src/cli/services/dev/processes/dev-session/dev-session.ts
For:
- https://github.com/shop/issues-app-access/issues/715
Depends on PR:
- https://app.graphite.dev/github/pr/shop/world/41406/Support-dev-session-auto-update-ApiPermission-scopes
| Before | After |
| -- | -- |
|![action-required-for-scope-update.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/0ulauwH3MAngKQbIjk2w/4fdf641b-fedf-4b21-9529-148e64332b44.png)|![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/0ulauwH3MAngKQbIjk2w/58d2ddd8-39fc-4eb9-afea-f2cb1ea3998d.png)|
Removes the "Action required" message and link that appears when app scopes are updated during development. 
1. Start a dev session for an app
2. Update the app's scopes in the app TOML in include new scopes
3. See the `action required` message no longer exists
[See video demo in this …
> No action required for scope update

- .changeset/sweet-colts-film.md
- packages/theme/src/cli/utilities/theme-fs.test.ts
- packages/theme/src/cli/utilities/theme-fs.ts
Fixes #5640
- On deletion or renaming of a theme file, clear any associated asset upload errors to prevent this overlay from persisting for the whole session
https://github.com/user-attachments/assets/90e7681c-b7ec-4f97-9988-8b1613aa3470
1) Run `shopify-dev theme dev`
2) Rename template to something invalid (i.e.`404.json` -> `404 copy.json`)
3) Verify that the asset upload errors page is rendered
4) Rename the template to a valid name (i.e.`404 copy.json` -> `404.json`)
5) Verify that the asset upload error page disappears
> [Fix][Themes] Remove asset upload errors for files that are renamed / deleted

- .changeset/moody-chairs-divide.md
- packages/cli-kit/src/public/node/is-global.test.ts
- packages/cli-kit/src/public/node/is-global.ts
Partially reverts https://github.com/Shopify/cli/pull/5704
The default PNPM folder for global packages in Mac is `/pnpm/global/5/node_modules/`, but the previous PR was expecting global installations to not contain `node_modules`.
Also, it's possible to customize the folder, so it's better to avoid this approach.
This is causing `shopify app init` to use NPM when the CLI is installed globally with PNPM.
Keeps the logic to detect the global installation based on the project path.
- `pnpm i -g @shopify/cli@0.0.0-snapshot-20250502142317`
- `shopify app init` => it should use pnpm
Global version:
- `npm i -g @shopify/cli/0.0.0-snapshot-20250502142317 --@shopify:registry=https://registry.npmjs.org`
- `shopify cache clear`
- `shopify app info` => nothing
- `npm add @shopify/cli`
- `shopify …
> Revert global CLI detection change

- bin/release
There needs to be at least one changeset for a release to work.
Create an empty changeset for nightly/experimental releases to ensure they succeed. 
Nightly should work again
> Fix nightly releases when there are no changesets yet

- .changeset/metal-worms-check.md
- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/app/loader.ts
Fixes bugsnag error 678f6e234714603e798bf36a
Instead of using `parse`, which can throw, use `safeParse` and the existing `abortOrReport` mechanism when loading extension config.
> Fix error handling for misconfigured multi-extension config

- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
To allow nightly CLI versions to access newer templates that would otherwise be restricted by minimum CLI version requirements, while still respecting deprecation rules.
Modifies the `allowedTemplates` function to:
- Inject a version parameter (defaulting to CLI_KIT_VERSION)
- Add special handling for nightly versions (those starting with "0.0.0")
- Allow nightly versions to access templates regardless of minimum CLI version requirements
- Still respect deprecation rules even for nightly versions
1. Run the CLI with a nightly version
2. Verify that templates with minimum CLI version requirements higher than the current stable release are accessible
3. Confirm that deprecated templates remain inaccessible even with nightly versions …
> Fix template filter for nightly versions

- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/cli-kit/src/public/node/hooks/prerun.ts
- packages/cli-kit/src/public/node/version.test.ts
- packages/cli-kit/src/public/node/version.ts
To improve the handling of pre-release versions in the CLI by creating a dedicated utility function that centralizes the logic for identifying pre-release versions.
- Introduces a new `isPreReleaseVersion()` utility function in the version module that checks if a version is a pre-release version (starts with '0.0.0')
- Replaces direct string checks (`version.startsWith('0.0.0')`) with the new utility function across multiple files
- Updates the logic in `allowedTemplates()` to use the new function, renaming variables for better clarity (`isDevelopmentVersion` → `satisfiesPreReleaseVersion`)
- Adds tests for the new utility function
1. Run the test suite to verify the new function works as expected
2. Test the CLI with both regular and pre-release versions to ensure version checks behave …
> Extract logic to detect pre-release versions

- packages/app/src/cli/commands/app/dev/clean.ts
- packages/app/src/cli/services/dev-clean.test.ts
- packages/app/src/cli/services/dev-clean.ts
To improve error handling when stopping app previews and to refactor the dev clean functionality into a service.
- Extracts the app preview cleanup logic from the `DevClean` command into a new service function `devClean`
- Adds proper error handling for the `devSessionDelete` API call
- Improves the success message formatting with proper command styling
1. Create an app preview with `shopify app dev`
2. Run `shopify app dev clean` to stop the preview
3. Verify that the success message is properly formatted
4. Try to reproduce an error scenario (if possible) to verify the error handling works correctly
> Extract `dev clean` logic to a service file

- packages/app/src/cli/services/function/binaries.ts
With function-runner v8.0.0, we removed the `codec` flag, and added support for the Shopify function WASM API. The CLI did not use the codec flag so no changes were needed.  Now CLI can run functions that are using the shopify functions wasm api. 
> [ShopifyVM] update to function runner v8.0.1 for WASM API support

- .changeset/orange-bugs-retire.md
- packages/theme/package.json
- packages/theme/src/cli/utilities/theme-environment/hot-reload/server.test.ts
- packages/theme/src/cli/utilities/theme-environment/hot-reload/server.ts
- pnpm-lock.yaml
This PR fixes an issue related to hot-reloading compiled assets (such as scripts.js, block-scripts.js, etc).
This PR enriches the hot-reload event's payload by including details indicating whether the `javascript` or `stylesheet` tags were modified. This approach triggers a full-reload event the first time users update a section file with a `javascript` tag, but it caches this information, and subsequent updates will only trigger a full reload if the content of the `javascript` tag has changed.
- Update your local `theme-hot-reload` package to use [this branch](https://github.com/Shopify/theme-hot-reload/pull/41)
- Run `SHOPIFY_CLI_LOCAL_HOT_RELOAD=true shopify-dev theme dev`
- Change the {% javavascript %} content within a section file
- Verify that the browser correctly performs a full …
> Fix an issue with hot-reloading the compiled assets (scripts.js, block-scripts.js, etc)

- packages/app/src/cli/services/dev/app-events/app-event-watcher.ts
UI extensions currently don't output any logging for successful builds, unlike Functions.
Adds logging for esbuild-managed builds to the app watcher.
Add a UI extension and `pnpm shopify app dev --path <your app>`
> Add build logging to app watcher for esbuild-based extensions

- packages/cli-kit/src/public/node/tcp.test.ts
- packages/cli-kit/src/public/node/tcp.ts
Continuation of https://github.com/Shopify/cli/pull/5794
@isaacroldan realized that the CLI does not allow multiple dev sessions anymore after the previous PR, and that it works with `0.0.0.0` instead of `localhost` as the port.
- Use `0.0.0.0` as the host only when HOST env var is defined
- Use the same logic for `checkPortAvailability` and `getAvailableTCPPort`
Tested on Mac, Linux and Windows.
- Multiple dev sessions
- `HOST=wrong pnpm shopify app dev`
> Fix port detection

- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/app/loader.ts
Fixes https://github.com/Shopify/develop-app-inner-loop/issues/2237
Prior to this PR, we assumed that if we are missing the `client_id` attribute in the TOML, that means that we are loading a TOML that is shaped like the `LegacyAppSchema`. `client_id` is required in `AppSchema`, however we should be able to validate the TOML as an `AppSchema` with a `client_id` missing. 
We determine if the schema is `LegacyAppSchema` _first_ and after we have determined that the TOML is not `LegacyAppSchema`, we can evaluate the TOML more accurately against `AppSchema` and return a correct zod validation error. (The TOML is likely not a `LegacyAppSchema` and we should rarely ever be using this zod schema since we only use it when developers are loading an app they cloned from a template or a very very …
> Detect shopify.app.toml is using correct schema when client_id is missing 

- packages/app/src/cli/prompts/dev.test.ts
- packages/app/src/cli/prompts/dev.ts
Because sometimes the updated URL isn't a tunnel
> don't mention tunnels in URL override message

- packages/app/src/cli/prompts/dev.ts
Since we’re not publishing the manually instructions, should we change the second option
Update this message:
```
?  --use-localhost requires a certificate for `localhost`. Generate it now?
>  (y) Yes, use mkcert to generate it
(n) No, I'll provide it manually
```
to:
```
(n) No, I'll run `app dev` again without `--use-localhost`
```
Using an app that doesn't have mkcert files in `./shopify`
```
pnpm build && pnpm shopify app dev --path='[PATH]' --use-localhost
```
None
> Update no message when generating a certificate

- packages/cli-kit/src/public/node/node-package-manager.test.ts
- packages/cli-kit/src/public/node/node-package-manager.ts
Fixes [this Bugsnag issue](https://app.bugsnag.com/shopify/cli/errors/6683f85fde91d40008a444ca?filters[event.unhandled]=true&filters[metaData.Command.cmd_all_plugin][][type]=ne&filters[metaData.Command.cmd_all_plugin][][value]=%40shopify%2Fcli-hydrogen&filters[metaData.Command.cmd_all_plugin][][type]=ne&filters[metaData.Command.cmd_all_plugin][][value]=%40shopify%2Ftheme&filters[release.seen_in]=3.80.0&filters[error.status]=open&filters[event.since]=7d&event_id=682985a201261ecb923a0000). 
The current implementation of `getPackageManager` doesn't handle failures when trying to determine the package manager directory using `npm prefix`. This can lead to uncaught exceptions when the command fails.
Adds error handling to the `getPackageManager` function to gracefully fall back to using the …
> npm prefix fails should not leak out

- packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.ts
Fixes [this Bugnsag issue](https://app.bugsnag.com/shopify/cli/errors/680272e3176d741c89527395?filters[event.unhandled]=true&filters[metaData.Command.cmd_all_plugin][][type]=ne&filters[metaData.Command.cmd_all_plugin][][value]=%40shopify%2Fcli-hydrogen&filters[metaData.Command.cmd_all_plugin][][type]=ne&filters[metaData.Command.cmd_all_plugin][][value]=%40shopify%2Ftheme&filters[release.seen_in]=3.80.0&filters[error.status]=open&filters[event.since]=7d).
Improves error handling for UI extension type reference issues.
Enhances error messaging when a type reference for UI extensions cannot be found:
- Replaces standard `Error` with `AbortError` for better error handling
- Splits the error message into a main message and a solution hint
- Removes the version-specific guidance from the test …
> UI extension shared type implemention should throw AbortError with actionable issue

- .github/actions/run-and-save-test-coverage/action.yml
- .github/workflows/shopify-cli.yml
- bin/save-coverage-file.js
- package.json
- packages/app/src/cli/utilities/app/http-reverse-proxy.test.ts
- packages/theme/src/cli/services/pull.test.ts
Simplify debugging unit test failures in CI by using vitest's monorepo support instead of going via nx.
When we run tests via nx, the logged output/failures/successes from each package's test run end up interleaved. It can be difficult to work out the cause of an issue. Vitest ensures output is clearly attributable back to a test/package.
1. Run `pnpm test:unit` to verify that all unit tests pass with Vitest
2. Run `pnpm test` to verify both unit and feature tests work correctly
3. Check that the coverage reports are generated correctly in CI
> Use vitest monorepo suppo for unit testst

- packages/app/src/cli/services/dev/processes/dev-session/dev-session.ts
Fixes a bug where the dev bundle would not be created when there are no assets but a manifest is required.
Modifies the condition in the `DevSession` class to create a dev bundle when `includeManifest` is true, even if there are no assets. Previously, the function would return early if there were no assets, regardless of whether a manifest was needed.
1. Run a dev session with no extensions
2. Verify that the app preview is started
> Fix app preview not starting correctly for apps without extensions

- .changeset/gorgeous-parents-impress.md
- packages/app/src/cli/services/function/binaries.ts
Cherry-pick commits from https://github.com/Shopify/cli/pull/5823
> [stable] Update function-runner to v9.0.0

- packages/app/src/cli/services/dev/processes/theme-app-extension.test.ts
- packages/app/src/cli/services/dev/processes/theme-app-extension.ts
- packages/cli-kit/src/public/node/context/fqdn.test.ts
- packages/cli-kit/src/public/node/context/fqdn.ts
Cherrypick commits from https://github.com/Shopify/cli/pull/5824
> [stable] Fix theme preview installation link for Management API apps

- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
Closes https://github.com/Shopify/develop-app-inner-loop/issues/2789
Currently, all Organization owned extension-only apps are being created without a `handle`. We theorize (but have not validated yet) that having a null handle will create issues with public distribution for Organization owned apps that handle their distribution in the Partners dashboard. This is meant to unblock that before Editions. 
We may have to create a migration to backfill `handle` for Organization only apps, but this PR will avoid adding any more ApiClients without a `handle`.
The ApiClient requires an app to be embedded for the persistence model to[ generate a `handle` on save](https://github.com/shop/world/blob/05-14-add_uniqueness_check_on_name_for_eventbus_integration/areas/core/shopify/components/apps/app/mod …
> Hardcode extension only apps to be embedded = true to make the behaviour consistent with Partners ext-only apps

- .changeset/fast-pigs-tickle.md
- packages/app/src/cli/prompts/init/init.ts
The Polaris release is being grouped as a "Release Candidate" and not being called "Early Access" any more.
> Update phrasing from Early Access to Release Candidate

- .changeset/fast-pigs-tickle.md
- packages/app/src/cli/prompts/init/init.ts
The Polaris release is being grouped as a "Release Candidate" and not being called "Early Access" any more.
Cherry-picked from https://github.com/Shopify/cli/pull/5850
> [stable] Update phrasing 

- packages/app/src/cli/services/dev/processes/dev-session/dev-session-process.test.ts
- packages/app/src/cli/services/dev/processes/dev-session/dev-session.ts
- packages/cli-kit/src/public/node/serial-batch-processor.test.ts
- packages/cli-kit/src/public/node/serial-batch-processor.ts
To improve the handling of rapid file changes during development by implementing a queue system for app events, preventing race conditions and ensuring all changes are properly processed.
Implements a more robust event handling system in the DevSession class:
1. Adds a queue system for app events to handle rapid changes
2. Introduces a consolidation mechanism that merges multiple events into a single update
3. Replaces the abort controller approach with a more reliable state tracking system
4. Ensures events are processed sequentially, preventing race conditions
5. Optimizes the update process by combining related changes
1. Run `dev` on a project with multiple extensions
2. Make rapid changes to multiple extension files
3. Verify that all changes are properly processed and reflected in …
> [stable] Queue and consolidate app events during dev session updates

- .changeset/tasty-peas-learn.md
- packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.ts
Cherry picked from https://github.com/Shopify/cli/pull/5859
The error message when types for a target cannot be found in the installed `@shopify/ui-extensions` version was not clear enough for users to understand how to fix the issue.
Fix https://github.com/shop/issues-appui/issues/203
Improves the error message when UI extension types cannot be found by:
1. Adding a more helpful error message that includes a specific example version format (e.g., 2025.10.0)
2. Creating a utility function `convertApiVersionToSemver` to properly format the API version in the error message
3. Updating the test to match the new error format
Unit tests should be sufficient
> [Stable] Update error message when types for the target cannot be found in the installed @shopify/ui-extensions version

- .changeset/tasty-peas-learn.md
- packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.ts
The error message when types for a target cannot be found in the installed `@shopify/ui-extensions` version was not clear enough for users to understand how to fix the issue.
Fix https://github.com/shop/issues-appui/issues/203
Improves the error message when UI extension types cannot be found by:
1. Adding a more helpful error message that includes a specific example version format (e.g., 2025.10.0)
2. Creating a utility function `convertApiVersionToSemver` to properly format the API version in the error message
3. Updating the test to match the new error format
Unit tests should be sufficient
> Update error message when types for the target cannot be found in the installed @shopify/ui-extensions version

- .changeset/shy-emus-jump.md
- packages/theme/src/cli/utilities/theme-downloader.ts
Fixes https://github.com/Shopify/developer-tools-team/issues/457
Renders a `%` rather than `1..50/200` in the progress bar when executing `theme pull`
- Instead of following the much more complicated approach with promises in `theme-uploader`, I didn't touch the way we batch files / jobs. I just updated the way we render progress to keep things simple. I **did** try that approach earlier - [link](https://github.com/Shopify/cli/pull/5809)
This brings things in line with `theme push`
https://github.com/user-attachments/assets/8281f441-be51-4264-8085-cb6dbea9cc5b
1) Build this branch
2) Execute `shopify-dev theme pull` in an empty directory or by passing the `--path`flag
3) Verify that the progress is a `%`
> Render `%` in progress bar when executing `theme-download`

- packages/app/src/cli/services/function/binaries.ts
Fixes an issue where a second invocation of `shopify app function build` to a Rust Function using the new Wasm API would result in an error as the trampoline binary errored in the case that a module used more than one memory. This is fixed in `1.0.2` to only error in the case when there is more than one non-imported memory.
Bump the binary version to 1.0.2
Run `shopify app function build` against any new Rust Function (uses the Wasm API, so `shopify_function` crate version >= 1.0.0) multiple times, see that it succeeds.
> Bump trampoline version to 1.0.2

- .changeset/happy-points-cover.md
- .changeset/silent-years-smash.md
- packages/app/src/cli/constants.ts
- packages/app/src/cli/services/dev/app-events/app-watcher-esbuild.test.ts
- packages/app/src/cli/services/dev/app-events/app-watcher-esbuild.ts
Fixes https://github.com/Shopify/cli/issues/5825
Fixes https://github.com/Shopify/develop-app-outer-loop/issues/1533
Enables minification by default on JS extensions while running `app dev`.
This is basically the same as @keiraarts suggested in https://github.com/Shopify/cli/pull/5831 (thanks!), but adding a flag to ensure we can keep the current behavior, so that users can debug more easily if needed.
- `npm i -g @shopify/cli@0.0.0-snapshot-20250521104958 --@shopify:registry=https://registry.npmjs.org`
- `shopify app init --template none --name minify-app`
- `cd minify-app`
- `shopify app generate extension --template admin_action --name admin-action --flavor typescript`
- `shopify app dev` => wait until it's ready and quit
- `cat …
> Minify JS extensions by default on app dev

- packages/app/src/cli/api/graphql/business-platform-organizations/generated/provision_shop_access.ts
- packages/app/src/cli/api/graphql/business-platform-organizations/generated/types.d.ts
- packages/app/src/cli/api/graphql/business-platform-organizations/queries/provision_shop_access.graphql
- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/services/store-context.test.ts
- packages/app/src/cli/services/store-context.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
- packages/cli-kit/src/private/node/session/scopes.test.ts
- packages/cli-kit/src/private/node/session/scopes.ts
This also contains the following PR which was merged into this one:
- https://github.com/Shopify/cli/pull/5531
Merging that one into this one wasn't the plan but I think we can roll with it to avoid having to recreate and re-review PRs. - @rmcnews
Support the provisioning of user access to stores through fbusiness platform. 
Adds the graphql and generated code for the BP `organizationUserProvisionShopAccess` mutation. 
Because it requires the new scope (`organization.on-demand-user-access`) that scope is added to the the list of requested scopes for BP API calls.
Before merging, we'll need to add the new scope to the allowed scopes for the `shopify-cli` oauth app in identity. 
- For [release](https://accounts.shopify.com/services/applications)
- For …
> Add BP mutation to ensure access to a dev store + Ensure user access to selected dev stores

- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/services/dev/fetch.test.ts
- packages/app/src/cli/services/dev/fetch.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
Refactors store fetching code and removes dead code to simplify future changes. 
`fetchStoreByDomain` is no longer used and is removed in this PR. 
This also allows the developer platform client interface to be simplified. Its `storeByDomain` method can then return an `OrganizationStore` instead of a GraphQL result. 
This change paves the way for changes to `OrganizationStore` that are not coupled to underlying GraphQL. 
Unit tests are sufficient here. The entire PR stack can be tophatted using the instructions [here](https://github.com/Shopify/cli/pull/5596). 
> Refactor store fetch, remove dead code

- packages/app/src/cli/api/graphql/business-platform-organizations/generated/fetch_dev_store_by_domain.ts
- packages/app/src/cli/api/graphql/business-platform-organizations/generated/list_app_dev_stores.ts
- packages/app/src/cli/api/graphql/business-platform-organizations/queries/fetch_dev_store_by_domain.graphql
- packages/app/src/cli/api/graphql/business-platform-organizations/queries/list_app_dev_stores.graphql
- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/models/organization.ts
- packages/app/src/cli/prompts/dev.test.ts
- packages/app/src/cli/services/context.test.ts
- packages/app/src/cli/services/dev/fetch.test.ts
- packages/app/src/cli/services/dev/select-store.test.ts
- packages/app/src/cli/services/store-context.test.ts
- packages/app/src/cli/services/store-context.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
Modifies the fix for https://github.com/Shopify/core-issues/issues/88829 to limit calls the BP provisioning mutation to organization owners and administrators.
The mutation is available only to holders of the `ondemand_access_to_stores` permission.  Other users should always be provisioned for access to a store and do not need the mutation called. 
To avoid a separate GraphQL query to fetch user permissions, they are instead added to existing to store fetch calls by including 
```
currentUser {
organizationPermissions
}
```
in the existing query.
The additional information is added to `OrganizationStore` class so that is available when needed. 
Ideally we would not be storing user-level information in a store object, but to avoid that, we'd need to
- Add yet another GraphQL call to the …
> Provision user access to stores only when permitted

- nx.json
To enable automatic exit of the TUI (Terminal User Interface) after task completion. See https://nx.dev/recipes/running-tasks/terminal-ui
It's pretty close to zero value to us. If this option isn't applied, every interactive run of nx stays open for 3 extra seconds in case the user wants to inspect the task log.
---
Adds a new `tui` configuration section to `nx.json` with `autoExit` set to `true`. This will make the TUI automatically exit after tasks are completed rather than requiring manual exit.
1. Run any Nx command that uses the TUI
2. Verify that the TUI automatically exits after the task completes
3. Try reverting the change and confirm that the TUI stays open until manually exited
> NX TUI should auto-exit

- configurations/vitest/setup.js
- package.json
- pnpm-lock.yaml
See for details:
- https://github.com/vitest-dev/vitest/issues/7315
- https://github.com/colinhacks/zod/issues/3950
TL;DR Zod does weird things with errors, which breaks Vitest's stricter error equality checks in v3. This workaround was suggested by the good folks behind Vitest, and avoids making our checks more lenient as was suggested in #5804
Adds a custom equality check for Zod errors that doesn't break when using Vitest 3
Update to Vitest 3 and see that the tests mentioned in #5804 don't fail as expected
> Add workaround for zod/vitest incompatibility

- packages/app/src/cli/utilities/developer-platform-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
- packages/cli-kit/src/public/node/api/admin.ts
- packages/cli-kit/src/public/node/api/app-management.ts
- packages/cli-kit/src/public/node/api/graphql.test.ts
- packages/cli-kit/src/public/node/api/graphql.ts
- packages/cli-kit/src/public/node/api/partners.ts
> Refresh session and retry on 401

- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/cli-kit/src/public/node/api/admin.ts
- packages/cli-kit/src/public/node/api/app-dev.test.ts
- packages/cli-kit/src/public/node/api/app-dev.ts
- packages/cli-kit/src/public/node/api/app-management.test.ts
- packages/cli-kit/src/public/node/api/app-management.ts
- packages/cli-kit/src/public/node/api/business-platform.ts
- packages/cli-kit/src/public/node/api/functions.ts
- packages/cli-kit/src/public/node/api/webhooks.ts
This PR refactors the API request functions to use a more consistent object parameter pattern instead of positional parameters.
Refactors API request functions across multiple client implementations to use a single object parameter pattern instead of multiple positional parameters. This change:
- Converts functions like `appManagementRequestDoc`, `businessPlatformRequest`, and others to accept a single options object
- Adds proper TypeScript interfaces for these request options
- Centralizes the creation of unauthorized handlers
- Makes parameter passing more explicit and less error-prone
- Improves code readability by making it clear which parameters are being passed
Just use the CLI, no behavior change in this PR.
> Force all requests in app management to have an unauthorizedHandler

- packages/ui-extensions-server-kit/package.json
The nightly release of `ui-extensions-server-kit` [is broken](https://github.com/Shopify/cli/actions/runs/15464803550/job/43534307190):
```
ui-extensions-server-kit - Error verifying sigstore provenance bundle: Failed to validate repository information: package.json: "repository.url" is "", expected to match "https://github.com/Shopify/cli" from provenance
```
Add required repository info to package.json: https://docs.npmjs.com/generating-provenance-statements#prerequisites
Merge and release
> Fix release for ui-extensions-server-kit

- .changeset/chatty-rats-pull.md
- packages/app/src/cli/services/dev/extension/websocket/handlers.test.ts
- packages/app/src/cli/services/dev/extension/websocket/handlers.ts
- packages/ui-extensions-server-kit/src/context/ExtensionServerProvider.tsx
- packages/ui-extensions-server-kit/src/state/actions/actions.ts
- packages/ui-extensions-server-kit/src/state/actions/types.ts
- packages/ui-extensions-server-kit/src/state/reducers/extensionServerReducer.test.ts
- packages/ui-extensions-server-kit/src/types.ts
Reverts Shopify/cli#5932
I accidentally jumped the gun in merging this PR as I didn't realize the [AppUI](https://vault.shopify.io/teams/3013-AppUI) team also needed to review these changes and it turns out they have some [good suggests](https://shopify.slack.com/archives/C04K7BZDH3N/p1749140890903219?thread_ts=1748871348.228269&cid=C04K7BZDH3N) for improvements.
For the same reason, https://github.com/Shopify/cli/pull/5947 will also be closed as it is fixing a bug that I caught in this code when testing the nightly release.
> Revert "[Feature] Display POS Extension logs within the CLI output"

- packages/create-app/bin/bundle.js
Create-app bundle should include the WASM from the toml-patch library.
> Include TOML patch in create-app bundle

- .changeset/smart-pears-camp.md
- packages/theme/src/cli/commands/theme/init.ts
- packages/theme/src/cli/services/init.test.ts
- packages/theme/src/cli/services/init.ts
Fixes https://github.com/Shopify/developer-tools-team/issues/732
This PR updates the `shopify theme init` command to prompt users about creating an AI file in their new theme.
- Run `shopify theme init` or `pnpm shopify theme init /tmp/test` (if you haven't configured the CLI dev environment locally)
https://github.com/user-attachments/assets/19bf983b-63c9-43dc-95dc-778a80d85999
N/A
> Prompt users who run `shopify theme init` to create their AI file

- .changeset/force-snapshot-build.md.ignore
This file was accidentally removed in https://github.com/Shopify/cli/pull/5965/commits/bd2e5a83d18332884c998079b5871707a7733f0a and is required for the `/snapit` command to work. Here's an example of the failure: https://github.com/Shopify/cli/actions/runs/15617379317/job/43993886342
> Add back changeset file required for snapit

- .changeset/force-snapshot-build.md.ignore
Oddly there was a typo in my copy/paste to bring this file back which is causing `/snapit` to continue to fail. This fixes the file to be what it was originally.
> Fix typo in force-snapshot-build

- .changeset/remove-git-remote-theme-init.md
- packages/cli-kit/src/public/node/git.test.ts
- packages/cli-kit/src/public/node/git.ts
- packages/theme/src/cli/services/init.test.ts
- packages/theme/src/cli/services/init.ts
Fixes https://github.com/Shopify/cli/issues/5957
This PR fixes an issue where `shopify theme init` was leaving the git remote pointing to the skeleton theme repository (`https://github.com/Shopify/skeleton-theme.git`).
Under the hood,  we are running `simple-git`'s `removeRemote` method. Before that, we check to see if any remote exists, if it doesn't we skip running `removeRemote`
Before:
After:
- Run `shopify theme init`
- CD into the new theme folder and run `git remote -v` (you should have nothing be returned)
> Remove git remote on theme init

- packages/app/src/cli/services/dev/graphiql/server.ts
Fixes:
- https://github.com/shop/issues-app-access/issues/745
- When getting access tokens from client credentials, send data in request body instead of URL params
I start `shopify app dev` and debugged to see client credentials body query, and checked GraphiQL still works
> [Main] Fix client credential request

- .changeset/itchy-houses-kick.md
- packages/theme/src/cli/utilities/theme-command.test.ts
- packages/theme/src/cli/utilities/theme-command.ts
Fixes https://github.com/Shopify/developer-tools-team/issues/735
We have some issues with the way we handle multiple environments which is done in `theme-command`. 
**Environment Detection Fix:**
- Changed from `if (!flags.environment)` to `if (!flags.environment?.length)` to properly distinguish between no environments ([]) and actual environment values (["dev"])
- Added proper handling for single vs multiple environment scenarios
**Improved Multi-Environment Execution:**
- Replaced Promise.all with renderConcurrent for multiple environments to prevent terminal output conflicts
- Each environment process gets its own isolated stdout/stderr streams
- Added `CommandContext` interface to pass stream references to commands
- Integrated `AbortController` for proper cancellation handling
- …
> Update behaviour for theme command calls

- .changeset/young-rocks-watch.md
- packages/cli-kit/src/private/node/session/device-authorization.test.ts
- packages/cli-kit/src/private/node/session/device-authorization.ts
Fixes https://github.com/Shopify/developer-tools-team/issues/740
When a backend service went down last week, we started returning `Unexpected end of JSON input`. The appearance of the error made it look like a CLI bug.
Adding extra error handling when the backend service is down or having issues.
There are associated tests to see what happens when returns are not proper JSON.
> added error handling for authorization when backend server may not be reachable

- .changeset/cuddly-rocks-push.md
- packages/cli-kit/src/public/node/base-command.ts
Fixes https://github.com/Shopify/cli/issues/5594
When using the environment variable `SHOPIFY_FLAG_ENVIRONMENT`, you would get inconsistent behaviour. Sometimes it would read use the environment and sometimes it would ignore it and use a default or cached value.
In `base-command` at `const environments = flags.environment ?? []` if `flags.environment` = `myshop` then `environments.length` would end up as 6 and skip additional processing.
Ensure, `environments` ends up as an array.
**Setup**
- Make sure you have a `shopify.theme.toml` file with a few environments.
- In your terminal or bash profile, add `export SHOPIFY_FLAG_ENVIRONMENT=<yourenvironment>
- run `echo $SHOPIFY_FLAG_ENVIRONMENT` and make sure you see the environment output
**Testing** …
> Handle SHOPIFY_FLAG_ENVIRONMENT correctly when passed as an environment variable

- .changeset/famous-humans-repair.md
- packages/app/src/cli/constants.ts
- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/app/loader.ts
To improve validation of app configuration files by enforcing stricter checks on unsupported sections in app.toml files. See #5816
Makes this improved validation the default for all. Opt-out supported via `SHOPIFY_CLI_DISABLE_UNSUPPORTED_CONFIG_PROPERTY_CHECKS`.
> Use improved config module loading by default

- .changeset/fifty-pigs-care.md
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/credit_card_payments_app_extension_schema.test.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/credit_card_payments_app_extension_schema.ts
Fixes the issue where the cc app extension creation systematically failed when using the templates due to the fact that :
- The template includes a blank `fingerprint` field. [Code reference](https://github.com/Shopify/extensions-templates/blob/main/payments-app-extension-credit-card/shopify.extension.toml.liquid#L27)
- The CLI schema enforces that the `fingerprint` field contains a string of at LEAST 1 character. [Code reference](https://github.com/Shopify/cli/blob/main/packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/credit_card_payments_app_extension_schema.ts#L36)
Reason # 1 : This app extension creation failure is a bug/blocker for partners because the CLI systematically fails generating a credit card payment extension, and the developer cannot …
> Remove the encryption certificate content validation from the CLI Schema 

- .github/workflows/release-manual.yaml
- .github/workflows/release.yml
- .github/workflows/snapit.yml
- .gitignore
- packages/cli-kit/src/private/node/analytics.ts
- packages/cli-kit/src/public/node/monorail.ts
- packages/cli/bin/bundle.js
To track which repository is being used to build the CLI, which helps with analytics and debugging.
- Adds a new environment variable `SHOPIFY_CLI_BUILD_REPO` to track the repository used for building the CLI
- Passes this variable in all GitHub workflow files that handle building and releasing
- Includes this information in analytics data via the new `env_build_repository` field
1. Run a build locally with `SHOPIFY_CLI_BUILD_REPO=your-repo/cli` set
2. Verify that analytics data includes the repository information
ALTERNATIVELY
1. Run the `release-manual` GH workflow pointing to this branch and select `experimental`
2. In the experimental release, run any command with verbose, see that  `env_build_repository` is included 
> Track if current build is fork

- packages/cli-kit/src/private/node/ui/components/TextAnimation.test.tsx
- packages/cli-kit/src/private/node/ui/components/TextAnimation.tsx
The current implementation of the TextAnimation component has a memory leak issue where event listeners for the 'resize' event are not properly cleaned up when the component unmounts.
- Fixes a memory leak in the TextAnimation component by properly cleaning up the resize event listener
- Adds comprehensive tests for the TextAnimation component to ensure proper functionality
- Wraps the resize handler in a useLayoutEffect hook to properly manage the lifecycle of the event listener
- Ensures the resize handler is properly removed when the component unmounts
1. Run the test suite to verify the TextAnimation component behaves as expected
2. Manually test the component in a UI that gets mounted and unmounted to ensure no memory leaks occur
3. Verify the component still properly resizes when …
> fix MaxListenersExceededWarning

- packages/store/src/prompts/confirm_export.test.ts
- packages/store/src/prompts/confirm_export.ts
- packages/store/src/prompts/export_results.test.ts
- packages/store/src/prompts/export_results.ts
- packages/store/src/services/store/operations/store-export.test.ts
- packages/store/src/services/store/operations/store-export.ts
To improve the user experience during store export operations by adding a confirmation prompt and enhancing the export results display.
- Adds a confirmation prompt before exporting data from a store
- `--no-prompt` flag to skip confirmation for automated workflows
- export results display by adding a download link when available
- Adds tests for the new confirmation prompt functionality
1. Run a store export operation: `shopify store export source.myshopify.com export.sqlite`
2. Verify the confirmation prompt appears and works correctly
3. Test with `--no-prompt` flag to ensure it skips the confirmation
4. Complete an export and verify the download link appears in the success message
> add confirmation step to exports

- packages/store/src/prompts/copy_info.test.ts
- packages/store/src/prompts/copy_info.ts
Updates spacing to align to/from values for copy info banner:
**Before**
**After**
> update copy from/to spacing

- packages/store/src/services/store/errors/errors.test.ts
- packages/store/src/services/store/errors/errors.ts
- packages/store/src/services/store/utils/file-uploader.test.ts
- packages/store/src/services/store/utils/file-uploader.ts
Updates structure of error messages to follow a consistent pattern, and displays user entered information in `"`s
**Before** / **After**
> Update error message structure

- packages/store/src/prompts/copy_result.test.ts
- packages/store/src/prompts/copy_result.ts
- packages/store/src/prompts/export_results.test.ts
- packages/store/src/prompts/import_result.test.ts
- packages/store/src/prompts/import_result.ts
- packages/store/src/prompts/operation_result.test.ts
- packages/store/src/prompts/operation_result.ts
- packages/store/src/services/store/mock/mock-api-client.ts
- packages/store/src/services/store/mock/mock-data.ts
- packages/store/src/services/store/operations/store-import.test.ts
- packages/store/src/services/store/operations/store-import.ts
Improves UI by cleaning up visual structure of results for copy and import operations (success/warning)
- Redesigns the operation result output format with a clearer structure including headline, body, and next steps
- Adds "From:" and "To:" labels to make source and destination more obvious
- Adds a direct link to the target shop in the next steps for import and copy operations
- Updates operation type constants to use the correct prefixed versions (STORE_EXPORT, STORE_IMPORT)
- Improves the download link text to be more concise
- Passes the target shop to the renderOperationResult function to enable shop-specific links
1. Run a store copy operation: `shopify store copy source-shop target-shop`
2. Run a store import operation: `shopify store import input.sqlite target-shop`
3. Verify the …
> Update results UI for copy + import

- packages/store/src/apis/admin/index.ts
- packages/store/src/apis/admin/types.ts
- packages/store/src/cli/api/graphql/admin/generated/types.d.ts
- packages/store/src/services/store/utils/file-uploader.test.ts
- packages/store/src/services/store/utils/file-uploader.ts
Fixes https://github.com/Shopify/workflows-operations/issues/3359
This PR updates the SQLite file upload functionality to:
1. Use the `SQLITE_DATABASE` resource type instead of `FILE` for staged uploads
2. Increase the maximum file size limit from 20MB to 300MB
3. Add API version parameter to the staged upload request (using 'unstable')
4. Fix the resource URL construction by appending the key parameter value
5. TEMPORARILY Add SQLite-specific types until SQLITE_DATBASE resource type visibility changes are in place
`npm shopify store copy --from-file file_bigger_than_20_mb_smaller_than_300mb.sqlite --to-store target_store`
with an sqlite file
> use `SQLITE_DATABASE` resource type, to permit larger file uploads

- .changeset/grumpy-doors-march.md
- packages/app/src/cli/constants.ts
- packages/app/src/cli/services/app/patch-app-configuration-file.test.ts
- packages/app/src/cli/services/app/patch-app-configuration-file.ts
- packages/app/src/cli/services/app/write-app-configuration-file.ts
- packages/app/src/cli/services/context.test.ts
- packages/app/src/cli/services/context.ts
- packages/app/src/cli/services/dev.ts
- packages/app/src/cli/services/dev/urls.test.ts
- packages/app/src/cli/services/dev/urls.ts
🚨 BLOCKED: downstack PR must be released first and have a period to run and shake out any issues.
This PR removes the ability to opt-out of WASM TOML patching by removing the `SHOPIFY_CLI_DISABLE_WASM_TOML_PATCH` environment variable. This completes the migration to format-preserving TOML updates.
> Remove SHOPIFY_CLI_DISABLE_WASM_TOML_PATCH opt-out

- .changeset/funny-pumpkins-smash.md
- packages/app/src/cli/constants.ts
- packages/app/src/cli/models/app/loader.test.ts
- packages/app/src/cli/models/app/loader.ts
To improve validation of app configuration files by enforcing stricter checks on unsupported sections in app.toml files. See #5816
Removes the `SHOPIFY_CLI_DISABLE_UNSUPPORTED_CONFIG_PROPERTY_CHECKS` opt-out.
> Remove opt-out for improve config module loading

- packages/app/src/cli/commands/app/function/replay.ts
- packages/app/src/cli/commands/app/function/run.ts
- packages/app/src/cli/commands/app/function/schema.ts
- packages/app/src/cli/commands/app/function/typegen.ts
- packages/app/src/cli/services/function/common.test.ts
- packages/app/src/cli/services/function/common.ts
- packages/app/src/cli/services/generate-schema.test.ts
- packages/app/src/cli/services/generate-schema.ts
- Fixes shop/issues-develop#1311
- Updates `function typegen` to not require authentication to run
- Updates `function run` to _conditionally_ require authentication. It does this by embedding conditional app linking inside the `getOrGenerateSchemaPath` function - if the schema is already there, the linked app is not required, otherwise it is (which forces auth).
- In addition to the changes above, this PR removes the `inFunctionContext` function. This function was previously performing some boilerplate around app loading and function selecting, but it was constraining when we had commands that wanted to mix authenticated and non-authenticated environment. I realized that the only line of code `inFunctionContext` was actually saving us was the `chooseFunction` step. This seemed like not …
> Update authentication requirements for CLI commands (typegen + run)

- dev.yml
- package.json
- packages/app/package.json
- packages/app/project.json
- packages/cli-kit/package.json
- packages/cli-kit/project.json
- packages/cli/package.json
- packages/cli/project.json
- packages/create-app/package.json
- packages/create-app/project.json
- packages/plugin-cloudflare/package.json
- packages/plugin-cloudflare/project.json
- packages/plugin-did-you-mean/package.json
- packages/plugin-did-you-mean/project.json
- packages/theme/package.json
- packages/theme/project.json
- packages/ui-extensions-dev-console/package.json
- packages/ui-extensions-dev-console/project.json
- packages/ui-extensions-server-kit/package.json
- packages/ui-extensions-server-kit/project.json
Now we use vitest directly for unit tests in CI, drop the nx tasks used for unit tests.
🚨 We lose `test:affected` with this change. That said, through plain vitest our entire test suite takes ~40s so there's not much to gain.
- Changes the `test` command in `dev.yml` to use `pnpm run test:unit` instead of `pnpm run test:affected`
- Removes the `test:affected` script from the root `package.json`
- Replaces package-specific test commands (`test`, `test:coverage`, `test:watch`) with a single `vitest` command in all packages
- Removes all NX test executor configurations from project.json files
1. Run `pnpm run test:unit` to verify all tests still run correctly
2. Try running vitest directly in individual packages using `cd packages/<package-name> && pnpm vitest`
How do we know this change was …
> Delete nx test tasks

- .changeset/poor-hornets-compete.md
- packages/theme/src/cli/utilities/theme-command.ts
Follow up to https://github.com/Shopify/cli/pull/5954#discussion_r2154407460
We can further simplify the codepaths that a theme command can go through. 
In both no environment and single environment scenarios, they both make a session and then run the command. They are now lumped together based on what the `environments` variable has.
- Run a series of commands
- `shopify theme list`
- `shopify theme list -e mystore`
- `shopify theme list -e mystore -e myotherstore`
- Ensure commands output the proper store(s)
> Simplify theme command environment paths

- packages/store/src/prompts/confirm_export.test.ts
- packages/store/src/prompts/confirm_export.ts
- packages/store/src/services/store/operations/store-export.test.ts
- packages/store/src/services/store/operations/store-export.ts
Fixes https://github.com/Shopify/workflows-operations/issues/3364
Adds a confirmation prompt when attempting to export store data to a file that already exists. This prevents accidental overwriting of existing files by:
1. Update `confirmExportPrompt` function so that it asks users if they want to overwrite an existing file if the file exists
2. Showing the appropriate confirmation prompt based on whether the file exists or not
run this command twice, the first time you will see the normal flow, the second time you will see the overwrite flow
`pnpm shopify store copy --from-store=source --to-file=file --mock`
> Add overwrite prompt for store export if file exists

- packages/store/src/lib/base-command.ts
closes https://github.com/Shopify/workflows-operations/issues/3390
Replaces the manual error rendering and process exit with a proper AbortError throw in the BaseBDCommand's error handling. This ensures that we still get proper monorail reporting. This change:
- Throws an AbortError with the error message instead of rendering the error and calling process.exit(1)
- Maintains the same error message for Early Access commands
Run a command you know will error (ex importing a file into a non dev store) with the `--verbose` flag
Ensure you see something like
and that success is false.
Also ensure the failure renders as expected
- [] I've considered possible cross-platform impacts (Mac, Linux, Windows)
- [] I've considered possible …
> To ensure we get failure metrics we need to throw the error instead of exiting with code 1

- packages/store/src/services/store/errors/errors.test.ts
- packages/store/src/services/store/errors/errors.ts
- packages/store/src/services/store/utils/file-uploader.test.ts
- packages/store/src/services/store/utils/file-uploader.ts
Closes https://github.com/Shopify/workflows-operations/issues/3398
Adds error handling for `file_uploader` to handle `ACCESS_DENIED` errors for stagedUploadCreate. What the error looks like in prod:
Instead of the above, we'll now show this:
This [PR](https://github.com/shop/world/pull/113293) makes it so that adding `bulk_data` permissions from admin will allow access of stagedUploadCreate for sqlite files for staff members of a shop that aren't shop owners.
Get added to an EA shop but not as owner, make sure you don't have `bulk_data_import` or `bulk_data_export` permissions. Then try running an import e.g. ` pnpm shopify store copy --from-file=test.sqlite --to-store=rusty-development-dev-3`
> Handle access denied file upload error

- packages/store/src/services/store/operations/store-copy.test.ts
- packages/store/src/services/store/operations/store-copy.ts
To ensure consistent capitalization in the copy operation message. Closes https://github.com/Shopify/workflows-operations/issues/3413#issue-3263903501
Changes the capitalization of "Copy Operation" to "Copy operation" in the `renderCopyInfo` function call to maintain consistent styling in user-facing messages.
1. Run a store copy operation
2. Verify that the message displays "Copy operation" with lowercase "o"
3. Ensure the functionality of the copy operation remains unchanged
| Before | After |
|----------|----------|
|  ![Screenshot 2025-07-25 at 1.13.51 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/VqqHovG3hmKnoZC4I5sl/3011dcd9-dfb2-49e1-a237-fd321cffd673.png) | ![Screenshot 2025-07-25 at 1.18.46 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/V …
> Update casing on 'operation' during copy operation banner

- packages/app/src/cli/services/context/id-matching.ts
This PR removes the legacy function migration code that is no longer needed.
Removes the `migrateLegacyFunctions` function and its usage in the `automaticMatchmaking` function. This code was previously used to handle the migration of legacy functions by matching them with their new counterparts, but is no longer necessary.
1. Run the CLI with a project that contains functions
2. Verify that function identification and matching still works correctly
> Remove migrateLegacyFunctions

- .changeset/compliance-webhooks-legacy-flow.md
- packages/app/src/cli/models/app/app.test.ts
- packages/app/src/cli/models/app/app.ts
Patch version of https://github.com/Shopify/cli/pull/6108
> Fix: Allow compliance webhooks with legacy install flow

- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/services/deploy.test.ts
- packages/app/src/cli/services/deploy.ts
- packages/app/src/cli/services/fetch-extensions.ts
- packages/app/src/cli/services/import-extensions.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
Fixes https://github.com/shop/issues-develop/issues/469
- When running deploy with Partners API, it suggests to optionally migrate dashboard extensions:
- When running deploy with App Management API, it requires to migrate/remove dashboard extensions to continue:
- `shopify app deploy`
To add a dashboard managed extension in production, [this flag](https://partners.shopify.com/internal/betas/enable_dashboard_subscription_link_extension_creation) can be enabled.
> Add import extensions functionality on deploy

- packages/app/src/cli/services/fetch-extensions.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
To ensure that module configuration data is properly included when registering extensions with the developer platform.
Adds the `activeVersion` field with the module's configuration data when registering extensions through the AppManagementClient. This ensures that any configuration associated with a module is properly serialized and sent to the platform.
1. Create an app with extensions that have configuration
2. Deploy the app using `shopify app deploy`
3. Verify that the configuration is properly saved and accessible in the deployed app
> Fix import-extensions post migration

- .changeset/great-dragons-float.md
- .changeset/wet-lions-cross.md
- packages/cli/oclif.manifest.json
- packages/theme/src/cli/commands/theme/rename.ts
- packages/theme/src/cli/services/rename.test.ts
- packages/theme/src/cli/services/rename.ts
- packages/theme/src/cli/utilities/theme-command.test.ts
- packages/theme/src/cli/utilities/theme-command.ts
Previously `theme rename` command could only be run with a single `--environment` flag. This PR allows `rename` to be used in multiple environments in a single command run. 
Since multi environment commands must run without interactions we need to define which flags are required to run the command. In some cases a command will provide a few different flags that all meet the same requirement, so this PR also updates validation logic to accept "one of" required flags. 
For example: `rename` requires `store`, `password`, `name`, and one of: `live`, `theme`, or `development` (since `rename` can use any of the three to understand what to rename)
- Updates environment validation logic to understand "one of" flag requirements
- Removes flag parsing and auth from `Rename` in favour of …
> Allow theme rename command to be called with multiple environments

- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/models/extensions/extension-instance.test.ts
- packages/app/src/cli/models/extensions/extension-instance.ts
- packages/app/src/cli/services/deploy/bundle.ts
- packages/app/src/cli/services/dev/app-events/app-event-watcher.ts
Fixes the inconsistency in how extension assets are referenced in the bundling process.
This PR changes how extension assets are referenced during the bundling process:
1. Updates manifest generation to use the more explicit `module.outputFolderId` instead of `module.uid` for assets folder.
2. Adds a new `outputFolderId` getter to the ExtensionInstance class that returns the extension's uid
3. Refactors the `keepBuiltSourcemapsLocally`, `buildForBundle`, and `copyIntoBundle` methods to use the extension's `outputFolderId` directly
4. Removes the now-redundant `getOutputFolderId` method and simplifies related code
1. Create an app with multiple extensions
2. Run `shopify app deploy` to verify extensions are deployed correctly
3. Verify that sourcemaps are correctly preserved in the …
> Use UID for the assets folder and manifest

- .changeset/stable-update-hydrogen-cli-11.1.3.md
- packages/cli/package.json
- pnpm-lock.yaml
Updates @shopify/cli-hydrogen from 11.1.2 to 11.1.3
- Fix issue so that Hydrogen build command will work with Remix ([#3056](https://github.com/Shopify/hydrogen/pull/3056)) by [@juanpprieto](https://github.com/juanpprieto)
This is the stable branch PR with changeset for an urgent release. The corresponding main branch PR (without changeset): https://github.com/Shopify/cli/pull/6213
> hydrogen/Bump cli-hydrogen to 11.1.3

- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/models/app/app.ts
- packages/app/src/cli/models/extensions/extension-instance.test.ts
- packages/app/src/cli/models/extensions/extension-instance.ts
- packages/app/src/cli/services/deploy/bundle.ts
- packages/app/src/cli/services/dev/app-events/app-event-watcher.ts
- packages/app/src/cli/services/dev/app-events/app-watcher-esbuild.test.ts
- packages/app/src/cli/services/dev/update-extension.test.ts
Related to https://github.com/Shopify/cli/pull/6183
Fixes an issue where extension assets were being incorrectly referenced by `outputFolderId` instead of using the extension's unique identifier.
Refactors how extension output folders are identified and referenced:
1. Removes the `outputFolderId` getter and replaces it with a more flexible `getOutputFolderId()` method that can accept a registration UUID
2. Updates the asset reference in the app model to use the extension's `uid` instead of `outputFolderId`
3. Modifies the bundle process to pass the extension UUID to the relevant methods
4. Updates the path handling in the app event watcher to use the new method
This change ensures that extension assets are consistently referenced by their unique identifiers throughout the codebase.
1. …
> Fix partners platform deploy using uid in path for extensions instead of uuid

- .changeset/modern-sloths-act.md
- packages/cli-kit/src/private/node/api.ts
There was a small typo in the list of `isARetryableNetworkError` and it may have caused any `network socket disconnected` errors to be skipped over and not retried.
Fixed the typo
> fix spelling for network socket retry error

- .changeset/hip-pots-allow.md
- packages/theme/src/cli/services/init.test.ts
- packages/theme/src/cli/services/init.ts
- Deleting `.git` dir after a new theme is created from `shopify theme init`
- removing `git` dir same as we do with `github` dir
- `shopify theme init`
- `cd <theme>`
- `ls -la`
- ensure `.git` and `.github` directories dont exist
n/a
> Remove git dir after initializing new theme

- packages/app/src/cli/commands/app/init.ts
- packages/app/src/cli/models/app/app.test-data.ts
- packages/app/src/cli/models/organization.ts
- packages/app/src/cli/services/app/config/link-service.test.ts
- packages/app/src/cli/services/app/config/link.test.ts
- packages/app/src/cli/services/context.test.ts
- packages/app/src/cli/services/context.ts
- packages/app/src/cli/services/dev/select-app.test.ts
- packages/app/src/cli/services/dev/select-app.ts
- packages/app/src/cli/services/info.test.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/app/src/cli/utilities/developer-platform-client/partners-client.ts
- packages/cli-kit/src/public/node/api/app-management.test.ts
- packages/cli-kit/src/public/node/api/app-management.ts
⚠️ Requires https://github.com/shop/world/pull/27672 to be released
Support removing the org_id from the app tomls.
- Remove ORG_ID from app managament API URLs.
Refactor all calls to the app management API to not include the organization ID. 
Add `organizationId` to the requested fields when fetching an app detail.
- Add ORG_ID as a variable for some queries/mutations
And update some to include it as part of the variables when the query/mutation is at the org level (like CreateApp),
1. Just use the CLI, check that the flow of creating an app, adding extensions and deploying all works.
> Remove org_id from app management URL

- packages/app/src/cli/services/dev.test.ts
- packages/app/src/cli/services/dev.ts
The new dev command may behave incorrectly if the app has extensions pending to migrate to the new dev platform (missing UIDs).
Raise an error when running dev before finishing the migration with deploy
- Migrate an org
- Run `p shopify app dev`
> Block dev when there are pending extensions to migrate

- packages/app/src/cli/services/context/breakdown-extensions.ts
- packages/app/src/cli/services/deploy.test.ts
- packages/app/src/cli/services/deploy.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
Prevents forced deployments when Partner Dashboard managed extensions need migration, ensuring a smoother migration process.
Adds a validation check that prevents users from running a forced deploy when using the App Management client with extensions that need migration. Instead, it shows a helpful error message instructing users to run a manual deploy first to import and migrate the extensions locally.
1. Create an app with Partner Dashboard managed extensions
2. Try to run a forced deploy using the App Management client
3. Verify that the error message appears with the list of extensions that need migration
4. Run a manual deploy to import the extensions
5. Verify that the forced deploy now works after migration
> Add in dev platform flow a --force check to block deploy before migrating partner-managed extensions

- .changeset/twelve-tools-exercise.md
- packages/theme/src/cli/services/dev.test.ts
- packages/theme/src/cli/services/dev.ts
- packages/theme/src/cli/utilities/theme-environment/hot-reload/server.test.ts
- packages/theme/src/cli/utilities/theme-environment/local-assets.ts
- packages/theme/src/cli/utilities/theme-environment/theme-environment.test.ts
- packages/theme/src/cli/utilities/theme-environment/types.ts
- packages/theme/src/cli/utilities/theme-ext-environment/theme-ext-server.ts
Fixes https://github.com/Shopify/cli/issues/6224
Previously, when running the theme proxy in the context of theme app extension development, it attempted to serve compiled assets locally. However, these assets couldn't be generated or served because the host theme doesn't exist in the local file system.
This PR updates the `DevServerSession` to identify the context in which it is running and avoid asset generation when the proxy is running in the context of theme app extension development.
- Run `shopify app dev -t <horizon_theme_id>` in an app.
- Verify that Horizon loads as expected.
**Before:**
https://github.com/user-attachments/assets/b0d9f2b7-0876-4dd9-854c-fead3ab0c72e
**After:**
https://github.com/user-attachments/assets/2f6b69a0-4f45-47c5-8e82-47c4fc07f248
N/A
How will we know if …
> Fix `shopify app dev` to serve local assets as expected

- packages/app/src/cli/models/extensions/extension-instance.ts
- packages/app/src/cli/services/deploy.ts
- packages/app/src/cli/services/deploy/bundle.test.ts
- packages/app/src/cli/services/deploy/bundle.ts
Supporting both APIs and different kind of identifiers is tricky. This solves an edge case when un-migrating an app.
- Rename `registrationUuid` to `outputId` inside `getFolderOuputId`, this value is not always a registrationUuid (only for partners), so this name reflects better the actual value.
- Return `outputId` if provided, otherwise, return `this.uid`
- For the future: we should just return `this.uid`
1. Run the bundling process for an extension with both AppManagement and Partners API
2. Verify that the output folder structure is correctly generated with the appropriate IDs
3. Ensure that existing functionality continues to work as expected
> Fix deploys in partners after an un-migration

- packages/app/src/cli/api/graphql/app-management/generated/active-app-release-from-api-key.ts
- packages/app/src/cli/api/graphql/app-management/generated/active-app-release.ts
- packages/app/src/cli/api/graphql/app-management/generated/app-version-by-id.ts
- packages/app/src/cli/api/graphql/app-management/generated/app-version-by-tag.ts
- packages/app/src/cli/api/graphql/app-management/generated/create-app-version.ts
- packages/app/src/cli/api/graphql/app-management/queries/active-app-release.graphql
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
Fixes https://github.com/shop/issues-develop/issues/17833
Added support for the `target` field in app module versions to enhance extension configuration capabilities.
- Added the `target` field to the GraphQL query for released app modules
- Updated the `AppModuleVersion` interface to include the optional `target` property
- Modified the `appExtensionRegistrations` method to include the context field in the `activeVersion` object when both config and target are present
- Added comprehensive tests to verify the behavior with various combinations of config and context values
1. Run the test suite to verify the new functionality:
```
npm test packages/app/src/cli/utilities/developer-platform-client/app-management-client.test.ts
```
2. Test the CLI with an app that uses extensions with …
> Pass app module context through to registration's activeVersion if it exists

- packages/app/src/cli/models/extensions/extension-instance.ts
Fixes bug found [here](https://shopify.slack.com/archives/C07JNNJT273/p1755022319130109)
Simplifies the logic for determining the `uid` value in the extension instance response.
Removes unnecessary variable assignment by directly using `this.uid` in the return object instead of conditionally assigning it to a temporary variable.
1. Run extension commands that use the extension instance response
2. Verify that extensions are properly identified with the correct uid
3. Ensure that both UUID strategy extensions and non-UUID managed extensions work as expected
> Send correct uid in manifest during deploy

- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
In https://github.com/Shopify/cli/pull/6137 we refactored the way we pass organization ID to some queries, but we missed one.
Fix the `ensureUserAccessToStore` query to pass the `organization_id` in the right format
- `p shopify app dev` with App Management and a non-migrated Plus account
> Fix wrong parameter in ensureUserAccessToStore query

- packages/app/src/cli/api/graphql/extension_migrate_app_module.ts
- packages/app/src/cli/api/graphql/extension_migrate_flow_extension.ts
- packages/app/src/cli/api/graphql/extension_migrate_to_ui_extension.ts
- packages/app/src/cli/services/context/identifiers-extensions.test.ts
- packages/app/src/cli/services/context/identifiers-extensions.ts
- packages/app/src/cli/services/dev/migrate-app-module.test.ts
- packages/app/src/cli/services/dev/migrate-app-module.ts
- packages/app/src/cli/services/dev/migrate-flow-extension.test.ts
- packages/app/src/cli/services/dev/migrate-flow-extension.ts
- packages/app/src/cli/services/dev/migrate-to-ui-extension.test.ts
- packages/app/src/cli/services/dev/migrate-to-ui-extension.ts
Note: Do not merge until changes to [Core](https://app.graphite.dev/github/pr/shop/world/133641) and [Partners](https://app.graphite.dev/github/pr/Shopify/partners/60107) have been merged
To support extension migration using both registration ID and UUID, allowing compatibility with the App Management API.
Updates GraphQL mutations for extension migration to accept either `registrationId` or `registrationUuid` as parameters:
- Modifies `MigrateAppModuleMutation`, `MigrateFlowExtensionMutation`, and `MigrateToUiExtensionQuery` to support both ID types
- Makes `registrationId` and `registrationUuid` optional in the respective variable interfaces
- Updates migration service functions to conditionally use UUID when working with the App Management API client
1. Test extension migration using …
> Update migration mutations to accept registration id or registration uuid based on which client we are using

- packages/app/src/cli/services/app-logs/dev/poll-app-logs.test.ts
- packages/app/src/cli/services/app-logs/dev/poll-app-logs.ts
- packages/app/src/cli/services/app-logs/utils.ts
- packages/app/src/cli/services/dev/processes/app-logs-polling.test.ts
- packages/app/src/cli/services/dev/processes/app-logs-polling.ts
Also fixed a negated condition linting issue.
Polling error:
Subscription error:
Confirming `app logs` output on subscription error:
> Ensure errors in app logging render in regular dev log stream

- packages/app/src/cli/services/bundle.test.ts
- packages/app/src/cli/services/bundle.ts
- packages/app/src/cli/services/deploy.ts
- packages/app/src/cli/services/deploy/bundle.test.ts
- packages/app/src/cli/services/deploy/bundle.ts
- packages/app/src/cli/services/dev/processes/dev-session/dev-session.ts
No need to re-create the manifest multiple times, we can create it once and pass it as needed.
Modifies the `writeManifestToBundle` function to accept an `AppManifest` directly instead of an `AppInterface` and identifiers. This change:
1. Simplifies the function signature by removing the need to generate the manifest inside the function
2. Moves the manifest generation responsibility to the caller
3. Updates all relevant tests and calling code to accommodate this change
4. Ensures the app manifest is only generated once and then passed to the bundle functions
1. Run the test suite to verify all tests pass
2. Test app deployment to ensure the bundle process works correctly
3. Verify that the dev session functionality continues to work as expected
How do we know this change was effective? …
> Simplify writeManifestToBundle by not re-creating the manifest

- packages/app/src/cli/services/dev.test.ts
- packages/app/src/cli/services/dev.ts
Fixes an issue where webhook subscriptions were incorrectly blocking the dev command due to missing UIDs.
Modifies the `blockIfMigrationIncomplete` function to ignore webhook subscriptions when checking if extensions have assigned UIDs. Webhook subscriptions do need UIDs but shouldn't block the dev command from proceeding.
1. Create an app with webhook subscriptions
2. Run the dev command
3. Verify that the dev command doesn't block due to webhook subscriptions missing UIDs
> Webhook subscriptions shouldnt block dev

- packages/cli-kit/src/public/node/archiver.integration.test.ts
- packages/cli-kit/src/public/node/archiver.ts
- packages/theme/src/cli/services/package.test.ts
Closes: https://github.com/Shopify/cli/issues/6205
Uploading a zip created by `theme package` could fail validation when uploading to a shopify store. Some validators expect folders to be present as explicit entries in the zip, not just implied by the files inside them.
Right now, theme package zips the files it finds, but doesn’t add the folders themselves as entries. This can trigger validation errors.
This PR updates the process to:
- Collect the folder paths for the files we’re zipping
- Add those folders to the zip first (as metadata)
- Add the files
This makes the zip include the folder info validators look for. In the reported case, unzipping and re-zipping with the macOS archiver worked because it preserved that folder structure metadata.
- Build the main branch or use a recent …
> Fix theme package folder structure

- packages/app/src/cli/api/graphql/business-platform-destinations/generated/organizations.ts
- packages/app/src/cli/api/graphql/business-platform-destinations/queries/organizations.graphql
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
Requires: 
1. https://github.com/shop/world/pull/147625 to ship to production.
2. Downstack PR: https://github.com/Shopify/cli/pull/6284
Once (1) ships, this PR can the updated GraphQL schema to access Dev Platform organizations to which the user has access.
Just updating a single GraphQL call with new syntax.
1. Check out https://github.com/shop/world/pull/147625 locally + dev up all the servers.
2. `dev cd organizations` / `dev c`
3. You may want to `Access::UserPermission.create(organization_id: 1, organization_user_id: 1, namespace: "organization", handle: "develop_apps
", organization_access: true, store_access_type: "all_stores")` to make the testing work more obviously (shows multiple orgs when you run `app init`). This is necessary because database seeds are still pre-RBAC for …
> Use updated destinations API for ListOrganizations

- packages/app/src/cli/models/app/identifiers.ts
- packages/app/src/cli/services/deploy.test.ts
- packages/app/src/cli/services/deploy.ts
- packages/app/src/cli/services/import-extensions.test.ts
- packages/app/src/cli/services/import-extensions.ts
This PR adds functionality to filter out extensions that have already been imported into the local environment, preventing crashes and improving the extension import process.
- Implements `filterOutImportedExtensions` function to check if extensions are already imported
- Updates the `importExtensionsIfNeeded` function to only import extensions that aren't already in the local environment
- Ensures the `.env` file is updated when importing extensions
- Adds tests for the new filtering functionality
1. Create an app with Dashboard extensions
2. manually run `import-extensions`​
3. Try to import extensions again -> should see “no extensions to migrate”
4. Run deploy against dev-dash -> should ask to migrate, but not to import.
> Fix issue when trying to import an already imported extension

- packages/app/src/cli/prompts/uid-mapping-error.ts
- packages/app/src/cli/services/context/breakdown-extensions.ts
- packages/app/src/cli/services/deploy.test.ts
- packages/app/src/cli/services/deploy.ts
- packages/app/src/cli/services/dev.ts
Migration-related banners lack context on the migration and required steps.
Adds documentation links to the banners.
Either use this branch to complete a migration (including error states with `app dev` and `app deploy --force`), or temporarily modify conditions around the banner code to force their display.
> Add documentation links to migration-related banners

- .changeset/bright-lobsters-grow.md
- packages/theme/src/cli/utilities/log-request-line.ts
- packages/theme/src/cli/utilities/theme-environment/html.ts
- packages/theme/src/cli/utilities/theme-environment/proxy.ts
Request logs are helpful during theme development for raising awareness about TTFB. However, in theme app extensions, these logs aren't useful and end up cluttering the logs.
This PR deactivates request logs for theme app extensions based on the development server context.
- Run `shopify app dev`
- Notice that request logs are no longer displayed
N/A
> Remove request logs from theme app extensions development server

- .changeset/calm-ears-add.md
- .changeset/many-ties-check.md
- packages/theme/src/cli/services/local-storage.test.ts
- packages/theme/src/cli/services/local-storage.ts
- packages/theme/src/cli/utilities/theme-command.test.ts
- packages/theme/src/cli/utilities/theme-command.ts
Commands with multiple environment flags are run concurrently. This allows for quick multi env command runs (_`push` with 10 environments takes 2.5s run concurrently vs 12s sequentially!_) but introduces race conditions in commands that rely on local storage read/writes. Theme commands use local storage to keep track of the current store URL as well as each store's current development theme.
Examples:
- `shopify theme delete -e store1 -e store2 --development` An environment would sometimes try to lookup the current dev theme using the other env's store as key if the store file was overwritten before the dev theme read
- `shopify theme push -e store1-env -e another-store1-env --development` Two new dev themes were being created since both environment's local storage reads occurred before …
> Prevent race conditions during multi environment execution

- docs/cli/architecture.md
Hydrogen packages were still in the CLI docs
Remove the two entries from the table in the architecture page
> Remove hydrogen packages from CLI docs

- packages/theme/src/cli/services/info.ts
This PR adds events to improve o11y in the `shopify theme info` commands.
Building on the component from https://github.com/Shopify/cli/pull/6184, this PR introduces event tracking for the `shopify theme info` command.
- Add a `console.log(compileData())` at the end of the command of the `info` command
- Verify that the expected events are being stored
> Add events for `shopify theme info`

- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
Fixes an issue with the app deep link generation where the organization ID was not being properly converted to a string, potentially causing incorrect URL formation.
Modifies the `appDeepLink` function to explicitly convert the organization ID to a string after extracting the number from the GID, ensuring the URL is correctly formatted.
1. Generate an app deep link using the `appDeepLink` function
2. Verify that the URL contains the correct organization ID in string format
3. Confirm the link properly navigates to the expected app in the developer dashboard
> Fix URL generation for release message

- .changeset/dull-cycles-brush.md
- packages/theme/src/cli/commands/theme/console.ts
- packages/theme/src/cli/commands/theme/dev.ts
- packages/theme/src/cli/commands/theme/profile.ts
- packages/theme/src/cli/flags.ts
- packages/theme/src/cli/services/flags-validation.test.ts
- packages/theme/src/cli/services/flags-validation.ts
Backport of https://github.com/Shopify/cli/pull/6319
We no longer raise password errors when users use custom app passwords with the `shopify theme pull` or `push` commands.
This change moves logic from `packages/theme/src/cli/flags.ts` to the specific commands that do not support custom app password authentication. The legacy method is only supported on certain commands.
- Run `shopify theme dev --password <custom_app_password>`
- You should see an error.
- Run `shopify theme push --password <custom_app_password>`
- The command should work as expected.
N/A
How will we know this change was effective? Please choose one:
> No longer raise password errors when users use custom app passwords on shopify theme pull/push commands

- .changeset/kind-wasps-rush.md
- packages/app/src/cli/services/context/id-matching.test.ts
- packages/app/src/cli/services/context/id-matching.ts
WHY are these changes introduced?
Fixes an issue with extension type matching in the context service.
WHAT is this pull request doing?
Match extensions with both identifier​ and external_identifier​ to support the case for both Partners and Dev Dash.
How to test your changes?
Try to deploy a web-pixel extension after migration without UUIDs in the env file.
n/a - this doesn't need measurement, e.g. a linting rule or a bug-fix
Existing analytics will cater for this addition
PR includes analytics changes to measure impact
Checklist
I've considered possible cross-platform impacts (Mac, Linux, Windows)
I've considered possible [documentation](https://shopify.dev/)changes
> [Stable] Match by both type and externalType 

- .changeset/chilly-seahorses-call.md
- packages/app/src/cli/commands/app/config/use.ts
Related to https://github.com/shop/issues-develop/issues/412
Related to https://shopify.slack.com/archives/C030LHFCA5T/p1756321896429259
We require authentication for `shopify auth config use`, but we don't really use it
Removes the requirement
- `shopify auth logout`
- `shopify app config use`
> Do not require auth for `app config use`

- .changeset/shy-islands-guess.md
- packages/cli-kit/src/public/node/base-command.ts
- packages/theme/src/cli/utilities/theme-command.test.ts
- packages/theme/src/cli/utilities/theme-command.ts
Previously, default flag values were treated by multi environment command mapping as CLI values, which take precedence over shopify.theme.toml values. This PR ensures that flag values are selected in order:
1. User provided CLI args
2. User provided shopify.theme.toml values
3. Default flag values
- Creates each environment's flags obj by combining: CLI flags with defaults, shopify.theme.toml flags, and CLI flags without defaults in that order
- Displays a warning if `--path` flag is provided to the CLI during multi env runs (path defaults to `cwd` and should be set per environment in `shopify.theme.toml`)
<details><summary>shopify.theme.toml is respected over default values</summary>
https://github.com/user-attachments/assets/357dc2c5-59f8-48f4-bcbc-4b76eb684603
</details> …
> Ensure user provided flag values override defaults in multi env commands

- .changeset/large-otters-dream.md
- packages/theme/src/cli/utilities/theme-command.test.ts
- packages/theme/src/cli/utilities/theme-command.ts
- Blocked by https://github.com/Shopify/cli/pull/6301 
Previously, all commands run with multiple environments attempted to create a session object with store URL and password. This PR ensures that commands that do no accept a password and don't need to be authenticated (like `check`, `init`, `package`, and `language-server`) will not try to create a session
- Makes session creation conditional on whether a command accepts a password
- Adds `requiresAuth` boolean to valid environment type and DRYs it up by creating an `ValidEnvironment` interface
- Install the snap build that contains these changes as well as `check` multi env logic
```
npm i -g @shopify/cli@0.0.0-snapshot-20250827192106 --@shopify:registry=https://registry.npmjs.org
```
- Add a `shopify.theme.toml` file …
> Only create sessions for multi env commands that require authentication

- .changeset/nervous-oranges-travel.md
- packages/theme/src/cli/utilities/theme-command.ts
We were not getting certain theme event data reporting in monorail due to when we fired off the event. I swear it actually works this time.
Moved logging data after a command is run within the `theme-command` layer.
> Theme monorail event reporting

- .changeset/pretty-clocks-develop.md
- packages/theme/src/cli/utilities/theme-command.ts
Follow up from https://github.com/Shopify/cli/pull/5874#issuecomment-3238374866
When parsing `shopify.theme.toml`'s in multi environment mode we skip normalizing stores that happens [here](https://github.com/Shopify/cli/blob/3a2f619ddd070597ce4b944b58a4c9c9f2d5b8cc/packages/theme/src/cli/flags.ts#L27)
It should take a store like `mystore` and append `myshopify.com` to it. 
Add `normalizeStoreFqdn` to the `loadEnvironments` method in the theme command layer. It will append the right domain to the store.
_Replicate the bug_
In the current version of the CLI (4.84.1) or on main
- Create or update your `shopify.theme.toml` by only referencing the store name
```bash
[environments.store1]
store = "first-store.myshopify.com" 
password = "shptka_*"
theme = "123456"
[environments.store2]
store = …
```
> Fixed store names not parsing correctly in multi-env theme commands

- .changeset/healthy-coins-walk.md
- packages/app/src/cli/services/function/binaries.test.ts
- packages/app/src/cli/services/function/binaries.ts
There is an issue some Function developers are seeing when running `shopify app build` where trying to execute trampoline binary resulted in an `ENOENT` error message when trying to spawn `shopify-function-trampoline-v1.0.2`. While investigating, I discovered that [the `moveFile` operation we perform while downloading a binary](shopify-function-trampoline-v1.0.2) is *not* atomic. If the destination file exists, the underlying library will delete the destination file before performing the move. This _could_ result in an `ENOENT` when trying to spawn that executable file if the timing is just right.
This introduces a check to ensure only one JS task at a time tries to download a specific binary and waits if there is a download in progress for that library. I've added a lot of code comments …
> Fix concurrency issue in downloadBinary

- .changeset/hot-fishes-develop.md
- packages/cli/oclif.manifest.json
- packages/theme/src/cli/commands/theme/publish.ts
- packages/theme/src/cli/services/publish.test.ts
- packages/theme/src/cli/services/publish.ts
We are changing the publish command to allow multiple environments to be specified in a single command to allow developers with multiple stores to work more efficiently.
Changing the publish command to use our multi environment infrastructure.
- If you don't already have one, create a `shopify.theme.toml` file
*Note*: You will need to create an access token through your shop(s) to bypass the need to login during theme commands.
The most basic example of the structure needed would be this:
```
[environments.env1]
store = "myfirstshop.myshopify.com"
password = "access_token"
theme = "your-theme-to-publish"
force = "true"
[environments.env2]
store = "mysecondshop.myshopify.com"
password = "access_token"
theme = "your-theme-to-publish"
force= "true" …
```
> Allow publish command to work with multiple environments

- packages/app/src/cli/models/extensions/extension-instance.ts
- packages/app/src/cli/models/extensions/specification.ts
- packages/app/src/cli/services/extensions/bundle.test.ts
- packages/app/src/cli/services/extensions/bundle.ts
To support a new build mode for extensions that allows copying specific files to the output directory based on configurable patterns.
Adds a new `copy_files` build mode for extensions that:
- Allows specifying file patterns to include in the build output
- Supports ignoring specific file patterns
- Maintains the directory structure when copying files
- Provides appropriate build output messages
The implementation includes:
- Updated type definitions for `BuildConfig` to support the new mode
- New `copyFilesForExtension` function to handle the file copying logic
- Comprehensive tests for the new functionality
- Integration with the existing extension build system
1. Create an extension with the following build configuration in its specification:
```
"buildConfig": {
"mode": "copy_files", …
```
> Add new copy_files build mode

- .changeset/khaki-crews-help.md
- packages/app/src/cli/services/dev/app-events/app-event-watcher.ts
- packages/app/src/cli/services/dev/extension.ts
- packages/app/src/cli/services/dev/extension/payload/models.ts
- packages/ui-extensions-server-kit/src/types.ts
Part of https://github.com/shop/issues-retail/issues/17789
[POS counterpart PR](https://app.graphite.dev/github/pr/Shopify/pos-next-react-native/68178/Add-build-error-handling-for-UI-extensions-in-development-mode)
Expands the `ExtensionPayload`​ interface to include more detailed errors for local extension builds.
```
development: {
// ... other properties
error?: {
message: string
file?: string
}
}
message: A string describing the error (e.g., "Unexpected \"}\"")
file: The file path where the error occurred (e.g., "../pos-e2e-ui-extension/extensions/remote-dom-sandbox/src/Tile.tsx")
```
- Enhances the `ExtensionBuildResult` type to include an optional `file` property that indicates which file contains the error
- Extracts more detailed error information from esbuild errors, including …
> Add error message and file to ExtensionPayload interface

- packages/cli-kit/src/private/node/ui/components/LoadingBar.test.tsx
- packages/cli-kit/src/private/node/ui/components/LoadingBar.tsx
- packages/cli-kit/src/private/node/ui/components/Tasks.test.tsx
- packages/cli-kit/src/private/node/ui/components/Tasks.tsx
To improve the loading/rainbow bar component in the CLI by extracting it into a reusable component that can be used across different parts of the application.
- Creates a new `LoadingBar` component that can be used to display loading states
- Extracts loading bar functionality from the `Tasks` component into this new reusable component
- Adds comprehensive tests for the `LoadingBar` component to ensure it works correctly in different scenarios:
- With and without colors
- With different terminal widths
- With different titles
- Updates the `Tasks` component to use the new `LoadingBar` component
- Refactors some of the `Tasks` tests to be more reliable and less dependent on timing
1. Run any CLI command that shows a loading state (e.g., `deploy`)
2. Verify that the loading bar appears …
> Add LoadingBar UI component

- packages/cli-kit/src/private/node/ui/components/Tasks.tsx
- packages/cli-kit/src/private/node/ui/hooks/use-exit-on-ctrl-c.test.ts
- packages/cli-kit/src/private/node/ui/hooks/use-exit-on-ctrl-c.ts
To improve code organization and maintainability by extracting the Ctrl+C handling logic into a reusable hook.
Creates a new `useExitOnCtrlC` hook that encapsulates the logic for handling Ctrl+C keyboard input to exit the process. This hook:
- Extracts the Ctrl+C handling logic from the Tasks component
- Provides a reusable implementation that can be used across different components
- Includes comprehensive test coverage for the new hook
The Tasks component has been updated to use this new hook, simplifying its implementation.
1. Run any CLI command that uses the Tasks component
2. Press Ctrl+C during execution
3. Verify that the process exits correctly
> Add useExitOnCtrlC hook

- packages/cli-kit/bin/documentation/examples.ts
- packages/cli-kit/src/private/node/ui/components/SingleTask.test.tsx
- packages/cli-kit/src/private/node/ui/components/SingleTask.tsx
- packages/cli-kit/src/public/node/ui.test.ts
- packages/cli-kit/src/public/node/ui.tsx
This PR introduces a new UI component to simplify displaying loading indicators while awaiting promise resolution. See example usage below.
By using this component when "slow" asynchronous functions are run, we can present a more responsive experience: rather than being greeted by a blank screen or a pause in feedback, the loading bar reassures the developer that something is happening.
- Adds a new `SingleTask` React component that shows a loading bar while a promise is in progress
- Implements `renderSingleTask` public API function that wraps the component for easy use
- Includes comprehensive test coverage for both the component and public API
The `renderSingleTask` function provides a simple way to display a loading indicator while awaiting a promise, and returns the promise's result …
> Introduce SingleTask component

- .changeset/polite-coats-pay.md
- docs-shopify.dev/commands/interfaces/app-init.interface.ts
- docs-shopify.dev/generated/generated_docs_data.json
- packages/app/src/cli/prompts/init/init.test.ts
- packages/app/src/cli/prompts/init/init.ts
- packages/cli/README.md
- packages/cli/oclif.manifest.json
- packages/create-app/oclif.manifest.json
The React Router template will become the recommended template
Swap Remix for React Router
`p shopify app init`
> Release the React Router template

- .changeset/big-ducks-joke.md
- packages/theme/src/cli/flags.test.ts
- packages/theme/src/cli/flags.ts
- packages/theme/src/cli/index.test.ts
- packages/theme/src/cli/utilities/theme-command.test.ts
- packages/theme/src/cli/utilities/theme-command.ts
We're seeing quite a few unhandled errors due to the command being run on a path that doesn't exist. Instead of blowing up let's catch the missing path early and let the user know.
Modifies `ThemeCommand` to check the path and to see if it exists. We throw two different errors depending on whether the user explicitly provided the path or not.
> [!NOTE]
> Right now this only works for commands that have been migrated to multi-environment support but soon that will be all of them!
```sh
npm i -g --@shopify:registry=https://registry.npmjs.org @shopify/cli@0.0.0-snapshot-20250916000226
shopify theme info --path foobarbaz
```
You should see an error:
```
➜  <theme> git:(main) shopify theme info --path foooooo
╭─ error ───────────────────────────────────────────────────────────────────────────── …
```
> Abort theme command if path doesn't exist

- packages/app/src/cli/models/app/loader.test.ts
To fix an issue with the test environment where `npm prefix` was being executed during tests, which could lead to inconsistent test behavior.
Mocks the `captureOutput` function from `@shopify/cli-kit/node/system` to prevent the execution of `npm prefix` inside the `getPackageManager` function during tests. This ensures that the tests run in a controlled environment without making actual system calls.
The changes include:
- Adding a mock for `captureOutput` at the top of the test file
- Adding mock implementations in specific tests to return the expected temporary directory
1. Run the test suite to ensure all tests pass
2. Verify that the tests no longer make actual system calls to `npm prefix`
3. Confirm that package manager detection still works correctly in the tests
How do we know this …
> Attempt at fixing loader flaky tests

- .changeset/short-owls-drop.md
- packages/theme/src/cli/utilities/theme-uploader.test.ts
- packages/theme/src/cli/utilities/theme-uploader.ts
Our theme uploader could create asset batches that were larger than the 1MB limit we set. This was caused by inaccurate calculation of the files containing multi-byte UTF-8 characters such as emojis or accented letters (e.g `é`, `ü`, `ñ`). We may see this more often with internationalized content
EX: `🍕🍕🍕🍕🍕` under the current calculation is measured as `10` characters but is actually 20 bytes.
- For all text based assets (.liquid, .json, .js) we use `Buffer.byteLength` to get the true byte size of the content.
- For binary assets (.png, .jpg) we continue the way it was before - calculating the size based on the length of the Base64-encoded string.
The changes should allow us to pack batches more reliably.
> Improve upload reliability with accurate bytesize calculation

- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
- packages/cli-kit/src/public/node/api/app-dev.ts
Avoid timeouts when starting a new dev session with many extensions.
This PR adds the ability to specify a `requestMode` option when creating a dev session. Specifically:
1. Sets the `requestMode` to `'slow-request'` for dev session creation
Easy way to test:
1. Run `app dev` with this env var: `SHOPIFY_CLI_MAX_REQUEST_TIME_FOR_NETWORK_CALLS=3000`
(You'd need around 10 ui_extensions)
2. See that if you run from `main`, this always crashes with "user aborted the request". Add more extensions if it doesn't.
3. See that it never crashes from this branch no matter the number of extensions.
> Modify request behaviour of devSessionCreate to slow-request

- .changeset/clean-squids-report.md
- packages/app/src/cli/models/extensions/specifications/type-generation.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.ts
Backports https://github.com/Shopify/cli/pull/6385
> Enable traversal of ui-extension files during type generation 

- .changeset/clean-squids-report.md
- packages/app/src/cli/models/extensions/specifications/type-generation.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.test.ts
- packages/app/src/cli/models/extensions/specifications/ui_extension.ts
Backport https://github.com/Shopify/cli/pull/6439
> [3.85] Enable traversal of ui-extension files during type generation

- .changeset/clean-squids-report.md
https://github.com/Shopify/cli/pull/6439 was accidentally targeted at main
> Remove changeset again

- packages/theme/src/cli/utilities/theme-command.ts
We are not collecting analytics when a theme command fails. This is because we put our logging after our `await command` and on failure, the promise stops and we never get to our logging method.
Wrap theme commands in `try/finally` blocks to ensure analytics are logged regardless of command success or failure. 
You can throw an error in a theme command on main and try to console log the analytics event in `theme-command`
Build this branch and do the same, you should see our logs.
> Fix theme analytics logging even when a command fails

- packages/cli-kit/src/private/node/otel-metrics.ts
Our monitors for latency are too chunky and the `50,000` upper limit is too low  (browse data [here](https://observe.shopify.io/d/deh11oe5v26f4d/shopify-apps-cli?orgId=1&from=now-3h&to=now&timezone=browser&var-cli_version=$__all)). An attempt to improve it - we should be able to increase the # of buckets a bit
> Increase quantity and amooth out histogram boundaries

- .changeset/silly-impalas-unite.md
- packages/app/src/cli/services/function/binaries.test.ts
- packages/app/src/cli/services/function/binaries.ts
Right now users trying to use Shopify Functions on Windows using ARM CPUs get error messages when downloading any of the Functions binaries. 
Updates the preferred binaries to versions that have Windows on ARM release artifacts and adds it as a supported platform if the requested version of a binary is new enough.
1. `dev clean`
2. `pnpm shopify app build --path <path_to_app>` to build all the Functions in the app. It'd be best to test with an app has the following extensions:
* uses the Wasm API
* a JS extension that uses the latest version of `shopify_function`
* a JS extension that uses version 0 or version 1 of `shopify_function`
3. `echo "{}" | pnpm shopify app function run --path <path_to_function>` to test the function-runner download works.
How do we know this change was …
> Add support for Windows on ARM for Functions binaries

- packages/app/src/cli/models/extensions/extension-instance.test.ts
- packages/app/src/cli/models/extensions/extension-instance.ts
- packages/app/src/cli/models/extensions/specifications/function.test.ts
- packages/app/src/cli/models/extensions/specifications/function.ts
- packages/app/src/cli/services/build/extension.test.ts
- packages/app/src/cli/services/build/extension.ts
Fixes https://observe.shopify.io/a/observe/errors/16559201434669527144
According to the [documentation](https://shopify.dev/docs/api/functions/latest#properties), the `[extensions.build]` property in `shopify.extension.toml` is optional, but the CLI throws an error when missing.
Ensures the field is optional in the schema and default values are properly used
- `npm i -g --@shopify:registry=https://registry.npmjs.org @shopify/cli@0.0.0-snapshot-20251006091027`
- `shopify app generate extension --template discount --flavor vanilla-js`
- Remove the `[extensions.build]` section from the `shopify.extension.toml`
- `shopify app function build`
- `shopify app generate extension`
> Fix default output build path for functions

- .changeset/tasty-boxes-hunt.md
- packages/cli-kit/src/private/node/session/exchange.test.ts
- packages/cli-kit/src/private/node/session/exchange.ts
When a session is refreshed and something changes (like a new scope/app), the stored alias is replaced by the user ID
Preserves the alias stored after login when refreshing the session
| Before | After |
|--------|--------|
| <img width="647" height="452" alt="before" src="https://github.com/user-attachments/assets/092a3449-bc10-4798-a164-53ad8401e763" /> | <img width="628" height="492" alt="after" src="https://github.com/user-attachments/assets/798aa2a4-43bb-4e20-815a-3e1fd4c8fe7d" /> | 
- `npm i -g --@shopify:registry=https://registry.npmjs.org @shopify/cli@0.0.0-snapshot-20251003131338`
- `shopify auth login`
- `shopify theme list`
- `shopify auth login`
> Preserve session alias on refresh

- .changeset/big-radios-wash.md
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/custom_onsite_payments_app_extension_schema.test.ts
- packages/app/src/cli/models/extensions/specifications/payments_app_extension_schemas/custom_onsite_payments_app_extension_schema.ts
Backport https://github.com/Shopify/cli/pull/6489 to 3.85.
> [3.85] Add start_verification_session_url field to custom onsite payments schema

- packages/app/src/cli/services/dev/extension/payload/store.ts
- packages/app/src/cli/services/dev/processes/previewable-extension.ts
- packages/app/src/cli/services/dev/processes/setup-dev-processes.ts
- packages/app/src/cli/services/store-context.ts
- packages/app/src/cli/utilities/app/app-url.ts
- packages/app/src/cli/utilities/extensions/fetch-product-variant.ts
- packages/cli-kit/src/private/node/session.ts
- packages/cli-kit/src/public/node/api/app-dev.ts
- packages/theme/src/cli/utilities/theme-command.ts
Clean up unnecessary awaits
- Removes all `await` keywords when calling `normalizeStoreFqdn`
1. Nothing to test, just that CI passes
> Remove unnecessary awaits

- .changeset/tall-olives-tie.md
- packages/app/src/cli/utilities/developer-platform-client.test.ts
- packages/app/src/cli/utilities/developer-platform-client.ts
- packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts
Fixes https://github.com/shop/issues-develop/issues/21223
We keep seeing some [unhandled 401 errors like this](https://observe.shopify.io/goto/CctwZi6NR?orgId=1), that shouldn't be happening.
When the CLI gets a 401, it tries to get a new token (by refreshing or starting the full authentication flow) and then retries the request.
The problem is that the retry after the refresh process was always using the App Management API token, but if the query was against Business Platform API, then it was obviously getting another 401, that was reported.
Pass the API type to the refresh function, so that it returns the proper token for each one.
The token must become invalid right before a Business Platform request, so it's not easy to reproduce. I faked it this way:
- Add a breakpoint …
> Fix token refresh for Business Platform API
